! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE MODGRINML(YDGEM,YDMCC,YDEPHY,KFIELDS2D,KFIELDS3D,KPAR2D,KPAR3D,&
                    & KLEVSM, PFPDGG2D, PFPDGG3D)

!**** *MODGRINML*  - Modify the gridpoint fields retrieved from MARS grib1 and grib2 
!                    this is based on modgrin, but it allows 3D surface fields.

!     Purpose.
!     --------
!          To apply some modifications to the grid-point fields
!          retrieved from MARS to adapt to IFS conventions.
!**   Interface.
!     ----------
!        *CALL* *MODGRIN(...)*

!        Explicit arguments : KFIELDS2D - number of fields 2D
!        -------------------- KFIELDS3D - number of fields 3D
!                             KPAR2D    - GRIB1 codes for fields 2D
!                             KPAR3D    - GRIB2 codes for fields 3D
!                             PFPDGG2D  - array containing fields 2D
!                             PFPDGG3D  - array containing fields 2D

!        Implicit arguments :
!        --------------------

!     Method.
!     -------
!        See documentation

!     Externals.     None
!     ----------

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     Author.
!     -------
!      Gabriele Arduini  *ECMWF*
!      Original : 01-09-21 (Adapted from modgrin.F90)
!     ------------------------------------------------------------------

USE YOMGEM   , ONLY : TGEM
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMCT0   , ONLY : LECMWF
USE YOMCST   , ONLY : RG, RTT
USE YOMLUN   , ONLY : NULOUT
USE YOM_GRIB_CODES  , ONLY : NGRBSTL1, NGRBSWVL1, NGRBSD, NGRBSDSL, NGRBSDOR ,&
 & NGRBSTL2, NGRBSWVL2, NGRBLSM, NGRBSR, NGRBSTL3 ,&
 & NGRBSWVL3, NGRBSRC, NGRBSKT, NGRBSTL4, NGRBSWVL4,&
 & NGRBTSN, NGRBWSN, NGRBSSTK, NGRBTVL, NGRBTVH, NGRBCVL,&
 & NGRBCVH, NGRBSLT, NGRBCI, NGRBUCUR, NGRBVCUR, NGRBFSR,NGRBLMLD,NGRBDL,NGRBLBLT
USE YOETHF   , ONLY : RHOH2O
USE YOEPHY   , ONLY : TEPHY
USE YOMMCC   , ONLY : TMCC

IMPLICIT NONE

#include "surf_inq.h"

#include "abor1.intfb.h"

TYPE(TGEM)        ,INTENT(IN)    :: YDGEM
TYPE(TEPHY)       ,INTENT(INOUT) :: YDEPHY
TYPE(TMCC)        ,INTENT(INOUT) :: YDMCC

INTEGER(KIND=JPIM),INTENT(IN)             :: KFIELDS2D 
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)    :: KFIELDS3D 
INTEGER(KIND=JPIM),INTENT(IN)             :: KPAR2D(:) 
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)    :: KPAR3D(:) 
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)    :: KLEVSM 
REAL(KIND=JPRB)   ,INTENT(OUT)            :: PFPDGG2D(:,:)
REAL(KIND=JPRB)   ,OPTIONAL,INTENT(OUT)   :: PFPDGG3D(:,:,:)

INTEGER(KIND=JPIM), EXTERNAL :: ISRCHEQ
REAL(KIND=JPRB) :: ZSCALE2D(KFIELDS2D+1)
REAL(KIND=JPRB), ALLOCATABLE :: ZSCALE3D(:)

INTEGER(KIND=JPIM) :: ICI, ICVH, ICVL, IITVH, IITVL, ILSM, IPARAM, ISD,&
 & ISST, ITSA1, ITSA2, ITSA3, ITSA4, ITSK, ITSN,IWSN,&
 & ITVH, ITVL, IWSA1, IWSA2, IWSA3, IWSA4, IWSK,IVTYPES,&
 & ISOTY,JFLD, JROF , IUCUR, IVCUR,ILMLD, IDL, ILBLT

INTEGER(KIND=JPIM) :: JLEV

LOGICAL         :: LLCURRENT

REAL(KIND=JPRB) :: ZCVH, ZCVL, ZWLMX
REAL(KIND=JPRB) :: ZRWLMAX,ZRCIMIN
REAL(KIND=JPRB) :: ZWSNTOT, ZSDTOT
REAL(KIND=JPRB),ALLOCATABLE :: ZRVCOV(:),ZRVLAI(:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

!*       1.    MODIFICATIONS TO FIELDS
!              -----------------------

IF (LHOOK) CALL DR_HOOK('MODGRINML',0,ZHOOK_HANDLE)
ASSOCIATE(LECURR=>YDEPHY%LECURR, LEOCCO=>YDEPHY%LEOCCO, LEOCWA=>YDEPHY%LEOCWA, &
 & YSURF=>YDEPHY%YSURF, &
 & NGPTOT=>YDGEM%NGPTOT, &
 & LNEMOLIMCUR =>YDMCC%LNEMOLIMCUR, &
 & LMCC04=>YDMCC%LMCC04)
CALL SURF_INQ(YSURF,KNVTYPES=IVTYPES)
ALLOCATE(ZRVCOV(0:IVTYPES))
ALLOCATE(ZRVLAI(0:IVTYPES))

IF (PRESENT(KFIELDS3D)) THEN
  ALLOCATE(ZSCALE3D(KFIELDS3D+1))
ENDIF
CALL SURF_INQ(YSURF,PRWLMAX=ZRWLMAX,PRCIMIN=ZRCIMIN,PRVCOV=ZRVCOV,PRVLAI=ZRVLAI)

!*    1.2   SETUP LOCAL SWITCHES
LLCURRENT= LECMWF .AND. LECURR .AND. (.NOT. LMCC04) .AND. (.NOT. LNEMOLIMCUR)

!*    1.3.1   ODD SCALINGS for 2D fields
DO JFLD=1,KFIELDS2D
  IPARAM=KPAR2D(JFLD)
  IF    (IPARAM == NGRBSDSL  ) THEN
    ZSCALE2D(JFLD)=1._JPRB
  ELSEIF(IPARAM == NGRBSR .OR. IPARAM == NGRBFSR ) THEN
    ZSCALE2D(JFLD)=RG
  ELSEIF(IPARAM == NGRBSRC ) THEN
    ZSCALE2D(JFLD)=RHOH2O
  ELSEIF(IPARAM == NGRBSDOR) THEN
    ZSCALE2D(JFLD)=RG
  ELSE
    ZSCALE2D(JFLD)=1.0_JPRB
  ENDIF
ENDDO

!*    1.3.2   ODD SCALINGS for 3D fields
IF (PRESENT(KFIELDS3D)) THEN
  DO JFLD=1,KFIELDS3D
    IPARAM=KPAR3D(JFLD)
    IF    (IPARAM == NGRBSDSL  ) THEN
      ZSCALE3D(JFLD)=RHOH2O
    ELSEIF(IPARAM == NGRBSR .OR. IPARAM == NGRBFSR ) THEN
      ZSCALE3D(JFLD)=RG
    ELSEIF(IPARAM == NGRBSRC ) THEN
      ZSCALE3D(JFLD)=RHOH2O
    ELSEIF(IPARAM == NGRBSDOR) THEN
      ZSCALE3D(JFLD)=RG
    ELSE
      ZSCALE3D(JFLD)=1.0_JPRB
    ENDIF
  ENDDO
ENDIF

CALL GSTATS(1403,0)
!$OMP PARALLEL DO SCHEDULE(STATIC,1) PRIVATE(JROF,JFLD)
DO JFLD=1,KFIELDS2D
  DO JROF=1,NGPTOT
    PFPDGG2D(JROF,JFLD)=ZSCALE2D(JFLD)*PFPDGG2D(JROF,JFLD)
  ENDDO
ENDDO
!$OMP END PARALLEL DO
IF (PRESENT(KFIELDS3D)) THEN
!$OMP PARALLEL DO SCHEDULE(STATIC,1) PRIVATE(JROF,JFLD)
  DO JFLD=1,KFIELDS3D
    DO JROF=1,NGPTOT
      PFPDGG3D(JROF,:,JFLD)=ZSCALE3D(JFLD)*PFPDGG3D(JROF,:,JFLD)
    ENDDO
  ENDDO
!$OMP END PARALLEL DO
ENDIF
CALL GSTATS(1403,1)

!*    1.4   MODIFICATIONS DEPENDENT ON LAND SEA MASK
ILSM=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBLSM)
IF(ILSM > KFIELDS2D) THEN
  WRITE(NULOUT,*) ' LAND-SEA MASK NOT FOUND ON FILE '
  CALL ABOR1(' ERROR in MODGRIN')
ENDIF
ITSK=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBSKT)
IF(ITSK > KFIELDS2D.AND.LECMWF) THEN
  WRITE(NULOUT,*) ' SKIN TEMPERATURE NOT FOUND ON FILE '
  CALL ABOR1(' ERROR in MODGRIN')
ENDIF
ITSA1=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBSTL1)
IF(ITSA1 > KFIELDS2D) THEN
  WRITE(NULOUT,*) ' SOIL TEMPERATURE 1 NOT FOUND ON FILE '
  CALL ABOR1(' ERROR in MODGRIN')
ENDIF
ITSA2=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBSTL2)
IF(ITSA2 > KFIELDS2D) THEN
  WRITE(NULOUT,*) ' SOIL TEMPERATURE 2 NOT FOUND ON FILE '
  CALL ABOR1(' ERROR in MODGRIN')
ENDIF
ITSA3=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBSTL3)
IF(ITSA3 > KFIELDS2D.AND.LECMWF) THEN
  WRITE(NULOUT,*) ' SOIL TEMPERATURE 3 NOT FOUND ON FILE '
  CALL ABOR1(' ERROR in MODGRIN')
ENDIF
ITSA4=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBSTL4)
IF(ITSA4 > KFIELDS2D.AND.LECMWF) THEN
  WRITE(NULOUT,*) ' SOIL TEMPERATURE 4 NOT FOUND ON FILE '
  CALL ABOR1(' ERROR in MODGRIN')
ENDIF
IWSK=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBSRC)
IF(IWSK > KFIELDS2D.AND.LECMWF) THEN
  WRITE(NULOUT,*) ' SKIN WETNESS NOT FOUND ON FILE '
  CALL ABOR1(' ERROR in MODGRIN')
ENDIF
IWSA1=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBSWVL1)
IF(IWSA1 > KFIELDS2D) THEN
  WRITE(NULOUT,*) ' SOIL WETNESS 1 NOT FOUND ON FILE '
  CALL ABOR1(' ERROR in MODGRIN')
ENDIF
IWSA2=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBSWVL2)
IF(IWSA2 > KFIELDS2D) THEN
  WRITE(NULOUT,*) ' SOIL WETNESS 2 NOT FOUND ON FILE '
  CALL ABOR1(' ERROR in MODGRIN')
ENDIF
IWSA3=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBSWVL3)
IF(IWSA3 > KFIELDS2D.AND.LECMWF) THEN
  WRITE(NULOUT,*) ' SOIL WETNESS 3 NOT FOUND ON FILE '
  CALL ABOR1(' ERROR in MODGRIN')
ENDIF
IWSA4=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBSWVL4)
IF(IWSA4 > KFIELDS2D.AND.LECMWF) THEN
  WRITE(NULOUT,*) ' SOIL WETNESS 4 NOT FOUND ON FILE '
  CALL ABOR1(' ERROR in MODGRIN')
ENDIF
!*Flake
ILMLD=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBLMLD)
IF(ILMLD > KFIELDS2D.AND.LECMWF) THEN
  WRITE(NULOUT,*) ' LAKE MIXED LAYER DEPTH NOT FOUND ON FILE '
  CALL ABOR1(' ERROR in MODGRIN')
ENDIF
ILBLT=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBLBLT)
IF(ILBLT > KFIELDS2D.AND.LECMWF) THEN
  WRITE(NULOUT,*) ' LAKE BOTTOM LAYER TEMPERATURE NOT FOUND ON FILE '
  CALL ABOR1(' ERROR in MODGRIN')
ENDIF
IDL=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBDL)
IF(IDL > KFIELDS2D.AND.LECMWF) THEN
  WRITE(NULOUT,*) ' LAKE MEAN DEPTH NOT FOUND ON FILE '
  CALL ABOR1(' ERROR in MODGRIN')
ENDIF

! Grib1 - grib2 selection
IF (.NOT.PRESENT(KFIELDS3D)) THEN
  ISD=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBSD)
  IF(ISD > KFIELDS2D.AND.LECMWF) THEN
    WRITE(NULOUT,*) ' SNOW DEPTH NOT FOUND ON FILE '
    CALL ABOR1(' ERROR in MODGRIN')
  ENDIF
  ITSN=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBTSN)
  IF(ITSN > KFIELDS2D.AND.LECMWF) THEN
    WRITE(NULOUT,*) ' SNOW TEMPERATURE NOT FOUND ON FILE '
    CALL ABOR1(' ERROR in MODGRIN')
  ENDIF
ELSE
  ISD=ISRCHEQ(KFIELDS3D,KPAR3D,1,NGRBSD)
  IF(ISD > KFIELDS3D.AND.LECMWF) THEN
    WRITE(NULOUT,*) ' SNOW DEPTH ML NOT FOUND ON FILE '
    CALL ABOR1(' ERROR in MODGRINML')
  ENDIF
  ITSN=ISRCHEQ(KFIELDS3D,KPAR3D,1,NGRBTSN)
  IF(ITSN > KFIELDS3D.AND.LECMWF) THEN
    WRITE(NULOUT,*) ' SNOW TEMPERATURE ML NOT FOUND ON FILE '
    CALL ABOR1(' ERROR in MODGRINML')
  ENDIF
  IWSN=ISRCHEQ(KFIELDS3D,KPAR3D,1,NGRBWSN)
  IF(IWSN > KFIELDS3D.AND.LECMWF) THEN
    WRITE(NULOUT,*) ' SNOW LIQ.WATER ML NOT FOUND ON FILE '
    CALL ABOR1(' ERROR in MODGRINML')
  ENDIF

ENDIF
ISST=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBSSTK)
IF(ISST > KFIELDS2D.AND.LECMWF) THEN
  WRITE(NULOUT,*) ' SST NOT FOUND ON FILE '
  CALL ABOR1(' ERROR in MODGRIN')
ENDIF
ITVL=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBTVL)
IF(ITVL > KFIELDS2D.AND.LECMWF) THEN
  WRITE(NULOUT,*) ' TVL NOT FOUND ON FILE '
  CALL ABOR1(' ERROR in MODGRIN')
ENDIF
ITVH=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBTVH)
IF(ITVH > KFIELDS2D.AND.LECMWF) THEN
  WRITE(NULOUT,*) ' TVH NOT FOUND ON FILE '
  CALL ABOR1(' ERROR in MODGRIN')
ENDIF
ICVL=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBCVL)
IF(ICVL > KFIELDS2D.AND.LECMWF) THEN
  WRITE(NULOUT,*) ' CVL NOT FOUND ON FILE '
  CALL ABOR1(' ERROR in MODGRIN')
ENDIF
ICVH=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBCVH)
IF(ICVH > KFIELDS2D.AND.LECMWF) THEN
  WRITE(NULOUT,*) ' CVH NOT FOUND ON FILE '
  CALL ABOR1(' ERROR in MODGRIN')
ENDIF
ISOTY=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBSLT)
IF(ISOTY > KFIELDS2D.AND.LECMWF) THEN
  WRITE(NULOUT,*) ' SOTY NOT FOUND ON FILE '
  CALL ABOR1(' ERROR in MODGRIN')
ENDIF
ICI=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBCI)
IF(ICI > KFIELDS2D.AND.LECMWF) THEN
  WRITE(NULOUT,*) ' CI NOT FOUND ON FILE '
  CALL ABOR1(' ERROR in MODGRIN')
ENDIF
IUCUR=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBUCUR)
IF(IUCUR > KFIELDS2D.AND.LECMWF.AND.LLCURRENT) THEN
  WRITE(NULOUT,*) ' U-COMP OF OCEAN CURRENT NOT FOUND ON FILE '
  CALL ABOR1(' ERROR in MODGRIN')
ENDIF
IVCUR=ISRCHEQ(KFIELDS2D,KPAR2D,1,NGRBVCUR)
IF(IVCUR > KFIELDS2D.AND.LECMWF.AND.LLCURRENT) THEN
  WRITE(NULOUT,*) ' V-COMP OF OCEAN CURRENT NOT FOUND ON FILE '
  CALL ABOR1(' ERROR in MODGRIN')
ENDIF
CALL GSTATS(1404,0)
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JROF,JLEV,IITVL,IITVH,ZCVL,ZCVH,ZWLMX,ZSDTOT,ZWSNTOT)
DO JROF=1,NGPTOT
  IF (LECMWF .AND. PFPDGG2D(JROF,ISST) == -9999.) THEN
    PFPDGG2D(JROF,ISST)=RTT
  ENDIF
  IF (LECMWF .AND. PFPDGG2D(JROF,ICI) == -9999.) THEN
    PFPDGG2D(JROF,ICI)=0.0_JPRB
  ENDIF
  IF(PFPDGG2D(JROF,ILSM) <= 0.5_JPRB) THEN
    IF(LECMWF) THEN
!      Ocean skin is kept from initial data and not copied from SST field
      IF (.NOT. LEOCWA .AND. .NOT. LEOCCO) THEN
        PFPDGG2D(JROF,ITSK) =PFPDGG2D(JROF,ITSA1)
      ENDIF
      PFPDGG2D(JROF,ITSA3)=PFPDGG2D(JROF,ITSA1)  !PV Delete ASAP; This line is WRONG, as from the 4-layer ice model
      PFPDGG2D(JROF,ITSA4)=PFPDGG2D(JROF,ITSA1)  !PV Delete ASAP; This line is WRONG, as from the 4-layer ice model
      PFPDGG2D(JROF,IWSK) =0.0_JPRB
      PFPDGG2D(JROF,IWSA3)=0.0_JPRB
      PFPDGG2D(JROF,IWSA4)=0.0_JPRB
      IF (.NOT.PRESENT(KFIELDS3D)) THEN
        PFPDGG2D(JROF,ISD)  =0.0_JPRB
      ELSE
        DO JLEV=1,KLEVSM
          PFPDGG3D(JROF,JLEV,ISD)  =0.0_JPRB
        ENDDO
      ENDIF
    ENDIF
    PFPDGG2D(JROF,ITSA2)=PFPDGG2D(JROF,ITSA1)
    PFPDGG2D(JROF,IWSA1)=0.0_JPRB
    PFPDGG2D(JROF,IWSA2)=0.0_JPRB
  ENDIF
  IF (LECMWF) THEN
    IF (.NOT.PRESENT(KFIELDS3D)) THEN
      PFPDGG2D(JROF,ISD)  = MAX(0.0_JPRB,  PFPDGG2D(JROF,ISD))
    ELSE
      ZSDTOT=0._JPRB
      DO JLEV=1,KLEVSM
        PFPDGG3D(JROF,JLEV,ISD) = MAX(0.0_JPRB, PFPDGG3D(JROF,JLEV,ISD)) 
        ZSDTOT=ZSDTOT + PFPDGG3D(JROF,JLEV,ISD)
      ENDDO
      ZWSNTOT=0._JPRB
      DO JLEV=1,KLEVSM
        PFPDGG3D(JROF,JLEV,IWSN) = MAX(0.0_JPRB, PFPDGG3D(JROF,JLEV,IWSN)) 
        ZWSNTOT=ZWSNTOT+PFPDGG3D(JROF,JLEV,IWSN)
      ENDDO
      ! Avoid points with only snow liq water but no ice snow 
      IF ((ZSDTOT-ZWSNTOT) <= 0._JPRB) THEN
         PFPDGG3D(JROF,1:KLEVSM,ISD) = 0._JPRB
         PFPDGG3D(JROF,1:KLEVSM,IWSN)= 0._JPRB
      ENDIF
    ENDIF
    IF (.NOT.PRESENT(KFIELDS3D)) THEN
      PFPDGG2D(JROF,ITSN)=MIN(PFPDGG2D(JROF,ITSN),RTT)
    ELSE
      DO JLEV=1,KLEVSM
        PFPDGG3D(JROF,JLEV,ITSN)=MIN(PFPDGG3D(JROF,JLEV,ITSN),RTT)
      ENDDO
    ENDIF
    IITVL=NINT(PFPDGG2D(JROF,ITVL))
    IITVH=NINT(PFPDGG2D(JROF,ITVH))
    ZCVL=PFPDGG2D(JROF,ICVL)*ZRVCOV(IITVL)
    ZCVH=PFPDGG2D(JROF,ICVH)*ZRVCOV(IITVH)
    ZWLMX=ZRWLMAX*(1.0_JPRB-ZCVL-ZCVH+ZCVL*ZRVLAI(IITVL)+ZCVH*ZRVLAI(IITVH))
    PFPDGG2D(JROF,IWSK)=MAX(0.0_JPRB,MIN(ZWLMX,PFPDGG2D(JROF,IWSK)))
    IF (PFPDGG2D(JROF,ICI) <= ZRCIMIN) PFPDGG2D(JROF,ICI)=0.
    PFPDGG2D(JROF,ILMLD)=MAX( 0.0_JPRB, &
                        &     MIN( MAX(2.0_JPRB, PFPDGG2D(JROF,IDL)) ,PFPDGG2D(JROF,ILMLD)) )
    PFPDGG2D(JROF,ILBLT)=MAX(273.15_JPRB,PFPDGG2D(JROF,ILBLT))
  ENDIF
  IF (LLCURRENT) THEN
!    Reset missing values (product land, ice) to zero
     IF (PFPDGG2D(JROF,IUCUR) == -9999.) THEN
       PFPDGG2D(JROF,IUCUR)=0.0_JPRB
     ENDIF
     IF (PFPDGG2D(JROF,IVCUR) == -9999.) THEN
       PFPDGG2D(JROF,IVCUR)=0.0_JPRB
     ENDIF
!    Reset to zero over model land
     IF(PFPDGG2D(JROF,ILSM) > 0.5_JPRB) THEN
       PFPDGG2D(JROF,IUCUR)=0.0_JPRB
       PFPDGG2D(JROF,IVCUR)=0.0_JPRB
     ENDIF
  ENDIF
ENDDO
!$OMP END PARALLEL DO
CALL GSTATS(1404,1)
! 
!     ------------------------------------------------------------------

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('MODGRINML',1,ZHOOK_HANDLE)
END SUBROUTINE MODGRINML
