! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE SUMCC(YDMCC,YDEPHY,KULOUT)

!**** *SUMCC* * - ROUTINE TO INITIALIZE SWITCHES FOR THE CLIMATE VERSION

!     PURPOSE.
!     --------
!        SET DEFAULT VALUES, THEN READS NAMELIST NAMMCC

!**   INTERFACE.
!     ----------
!        *CALL* *SUMCC(...)*

!     EXPLICIT ARGUMENTS :  KULOUT
!     --------------------

!     IMPLICIT ARGUMENTS :
!     --------------------
!        COMMON  YOMMCC

!     METHOD.
!     -------
!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------

!     AUTHOR.
!     -------
!      Michel Deque *CNRM*
!      ORIGINAL : 92-09-15

!     MODIFICATIONS.
!     --------------
!      Modified by M.Hamrud     : 04-10-01 CY28 Cleaning
!      Modified by D. Giard     : 04-09-15 new 923 configurations allowed
!      Modified by A.Alias      : GMEGEC/EAC list of modifications
!      JPh. Piedelievre : coupled model in distributed memory mode.
!                                 coupled model in UPDCPL mode (LMCC05,NFRCPL)
!      JJMorcrette, 20060605 MODIS albedo
!      JJMorcrette, 20061026 DU, BC, OM, SU, VOL, SOA climatological fields
!      S. Boussetta/G.Balsamo      May 2009   (Add switch for variable LAI: LLELAIV)
!      A.Alias    ,20091014 new keys LCURR and LGELAT added
!                           MPI1 + ocean currents (J-F. Gueremy)
!                           Print of NOACOMM added (E.Maisonnave)
!      K. Yessad (Jan 2012): remove old 923
!      K. Yessad (July 2014): NSTOP dependent calculations moved from SUMCC to SUMCCLAG.
!      J. Flemming (Jan 2014) Climate runs for MACC/Composition (LMCC_COMPO, LMCCIEC_COMPO
!      ----------------------------------------------------------------

USE PARKIND1 , ONLY : JPIM     ,JPRB
USE YOMHOOK  , ONLY : LHOOK,   DR_HOOK, JPHOOK
USE YOMLUN   , ONLY : NULNAM   ,NULOUT
USE YOMMCC   , ONLY : TMCC
USE YOMCT0   , ONLY : NFRCO
USE YOEPHY   , ONLY : TEPHY
USE YOMGRIB  , ONLY : NBITSEXPR

!      ----------------------------------------------------------------

IMPLICIT NONE

TYPE(TEPHY),TARGET,INTENT(INOUT) :: YDEPHY
TYPE(TMCC) ,TARGET,INTENT(INOUT) :: YDMCC
INTEGER(KIND=JPIM),INTENT(IN)    :: KULOUT 
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!      ----------------------------------------------------------------

LOGICAL, POINTER :: LCURR, LGELATO, LMCC01_MSE, LMCC01, LMCC02, LMCC03, LMCC04, &
 & LMCC05, LMCCEC, LMCCIEC, LMCCICEIC, LNEMOCOUP, LNEMOFLUXNC, LNEMO1WAY, &
 & LMCCDYNSEAICE, LNEMOLIMGET, LNEMOLIMPUT, LNEMOLIMALB, LNEMOLIMTEMP, &
 & LNEMOLIMTHK, LMULTIYR, LMCC_COMPO, LNEMOATMFLDS, LNEMOIFSLOG, LNEMOSSTFREEZ,&
 & LNEMOLIMTLVL, LESICE, LNEMOOCEICEMIX,LNEMOQNSICEFILT, LNEMOSICOUP, LNEMOGRIBFLDS,&
 & LNEMOPARTCOUP,LNEMOPARTMASK,LNEMOPARTMASKFILE,LNEMOGRIB3D,LNEMOGRIBMASK, L2DECV2NEMO,&
 & LNEMOOUTGRB,LCOUPINFOUT
INTEGER(KIND=JPIM), POINTER :: N923, NOACOMM, NFRCPL, NSSTICEOP, NNEMO3DLEVS
REAL(KIND=JPRB), POINTER :: RNPARTRAMPSTART,RNPARTRAMPLEN,&
 & RNPARTLAT,RNPARTLATSPREAD
CHARACTER(LEN=128), POINTER :: CDNPARTMASKFILE
#include "nammcc.nam.h"
#include "posnam.intfb.h"
#include "abor1.intfb.h"

!      ----------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('SUMCC',0,ZHOOK_HANDLE)
ASSOCIATE(LMCCIEC_COMPO=>YDMCC%LMCCIEC_COMPO)
! Associate pointers for variables in namelist
LCURR         => YDMCC%LCURR
LGELATO       => YDMCC%LGELATO
LMCC01_MSE    => YDMCC%LMCC01_MSE
LMCC01        => YDMCC%LMCC01
LMCC02        => YDMCC%LMCC02
LMCC03        => YDMCC%LMCC03
LMCC04        => YDMCC%LMCC04
LMCC05        => YDMCC%LMCC05
LMCCEC        => YDMCC%LMCCEC
LMCCIEC       => YDMCC%LMCCIEC
LMCCICEIC     => YDMCC%LMCCICEIC
N923          => YDMCC%N923
NOACOMM       => YDMCC%NOACOMM
NFRCPL        => YDMCC%NFRCPL
LNEMOCOUP     => YDMCC%LNEMOCOUP
LNEMOSSTFREEZ => YDMCC%LNEMOSSTFREEZ
LNEMOFLUXNC   => YDMCC%LNEMOFLUXNC
LNEMOOUTGRB   => YDMCC%LNEMOOUTGRB
LCOUPINFOUT   => YDMCC%LCOUPINFOUT
LNEMO1WAY     => YDMCC%LNEMO1WAY
LMCCDYNSEAICE => YDMCC%LMCCDYNSEAICE
LNEMOLIMGET   => YDMCC%LNEMOLIMGET
LNEMOLIMPUT   => YDMCC%LNEMOLIMPUT
LNEMOLIMALB   => YDMCC%LNEMOLIMALB
LNEMOLIMTEMP  => YDMCC%LNEMOLIMTEMP
LNEMOLIMTLVL  => YDMCC%LNEMOLIMTLVL
LNEMOLIMTHK   => YDMCC%LNEMOLIMTHK
LNEMOOCEICEMIX=> YDMCC%LNEMOOCEICEMIX
LNEMOQNSICEFILT=>YDMCC%LNEMOQNSICEFILT
LMULTIYR      => YDMCC%LMULTIYR
LMCC_COMPO    => YDMCC%LMCC_COMPO
LNEMOATMFLDS  => YDMCC%LNEMOATMFLDS 
LNEMOIFSLOG   => YDMCC%LNEMOIFSLOG  
NSSTICEOP     => YDMCC%NSSTICEOP
LESICE        => YDEPHY%LESICE
LNEMOSICOUP   => YDMCC%LNEMOSICOUP
LNEMOGRIBFLDS => YDMCC%LNEMOGRIBFLDS
LNEMOPARTCOUP => YDMCC%LNEMOPARTCOUP
LNEMOPARTMASK => YDMCC%LNEMOPARTMASK
LNEMOPARTMASKFILE => YDMCC%LNEMOPARTMASKFILE
RNPARTRAMPSTART => YDMCC%RNPARTRAMPSTART
RNPARTRAMPLEN => YDMCC%RNPARTRAMPLEN
RNPARTLAT     => YDMCC%RNPARTLAT
RNPARTLATSPREAD => YDMCC%RNPARTLATSPREAD
CDNPARTMASKFILE => YDMCC%CDNPARTMASKFILE
LNEMOGRIB3D   => YDMCC%LNEMOGRIB3D
NNEMO3DLEVS   => YDMCC%NNEMO3DLEVS
LNEMOGRIBMASK => YDMCC%LNEMOGRIBMASK
L2DECV2NEMO   => YDMCC%L2DECV2NEMO

!      ----------------------------------------------------------------

!*       1.    SET DEFAULT VALUES.
!              -------------------

!        1.1 Set implicit default values

LMCC01 = .FALSE.
LMCC02 = .FALSE.
LMCC03 = .FALSE.
LMCC04 = .FALSE.
LMCC05 = .FALSE.
LMCCEC = .FALSE.
LMCCIEC= .TRUE.
LMCCICEIC = .FALSE.
N923 = 0
NOACOMM=2
NFRCPL=HUGE(NFRCPL)
LCURR=.FALSE.
LGELATO=.FALSE.
LMCC01_MSE = .FALSE.
LNEMOCOUP=.FALSE.
LNEMOSSTFREEZ=.FALSE.
LNEMO1WAY=.FALSE.
LNEMOFLUXNC=.FALSE.
LNEMOOUTGRB=.FALSE.
LCOUPINFOUT=.FALSE.
LNEMOIFSLOG=.FALSE.
LMCCDYNSEAICE= .FALSE.
LNEMOGRIBFLDS=.FALSE.
LMULTIYR=.FALSE.
LMCCIEC_COMPO= .FALSE.
LMCC_COMPO=.FALSE.
NSSTICEOP=9
LNEMOGRIB3D=.FALSE.
NNEMO3DLEVS=20
LNEMOGRIBMASK=.FALSE.
L2DECV2NEMO=.FALSE.

!      ----------------------------------------------------------------

!*       2.    MODIFIES DEFAULT VALUES.
!              ------------------------

CALL POSNAM(NULNAM,'NAMMCC')
READ(NULNAM,NAMMCC)

N923 = MAX(0,MIN(11,N923))
IF (LMCCEC) THEN
  NFRCPL=NFRCO
  WRITE(KULOUT,*) ' IN SUMCC, NFRCPL UPDATED BY ECMWF ROUTINES: ',NFRCPL
ENDIF

IF (.NOT.LNEMOCOUP) THEN
   LNEMO1WAY=.FALSE.
   LNEMOFLUXNC=.FALSE.
   LNEMOOUTGRB=.FALSE.
   LNEMOGRIBFLDS=.FALSE.
   LNEMOGRIB3D=.FALSE.
   LNEMOGRIBMASK=.FALSE.
ENDIF

IF (.NOT.LMCC04) THEN
   WRITE(NULOUT,*) 'Uncoupled run so resetting LMCCDYNSEAICE'
   LMCCDYNSEAICE=.FALSE.
ENDIF

IF (.NOT.LMCCDYNSEAICE) THEN !Use of dynamic sea-ice model
   LNEMOLIMGET = .FALSE. 
   LNEMOLIMPUT = .FALSE.
   LNEMOLIMALB = .FALSE. 
   LNEMOLIMTEMP = .FALSE. 
   LNEMOLIMTLVL = .FALSE. 
   LNEMOLIMTHK = .FALSE.
   WRITE(NULOUT,*) 'LIM switches reset since LMCCDYNSEAICE is false'
ENDIF

IF (LMCCDYNSEAICE.AND.LNEMO1WAY) THEN
   LNEMOLIMGET = .FALSE. 
   LNEMOLIMALB = .FALSE. 
   LNEMOLIMTEMP = .FALSE. 
   LNEMOLIMTLVL = .FALSE. 
   LNEMOLIMTHK = .FALSE.
   WRITE(NULOUT,*) 'LIM switches reset since LNEMO1WAY is true'
ENDIF

IF(.NOT.LNEMOLIMTEMP.AND.LNEMOSICOUP) THEN
   WRITE(NULOUT,*)'LNEMOSICOUP without LNEMOLIMTEMP does not make sense!'
   CALL ABOR1('SUMCC: ABOR1 CALLED')
ENDIF

IF(LNEMOLIMTLVL.AND.LESICE) THEN
   WRITE(NULOUT,*)'LESICE together with LNEMOLIMTLVL does not make sense!'
   CALL ABOR1('SUMCC: ABOR1 CALLED')
ENDIF
 
!      -----------------------------------------------------------

!*       3.    PRINTS FINAL VALUES.
!              --------------------

WRITE(UNIT=KULOUT,FMT='('' Printings for module YOMMCC done in SUMCC '')')
WRITE(UNIT=KULOUT,FMT='(&
 & '' NSSTICEOP = '',I2,'' LCURR = '',L2,'' LGELATO = '',L2,&
 & '' LMCC01 = '',L2,'' LMCC02 = '',L2,'' LMCC03 = '',L2,&
 & '' LMCC04 = '',L2,'' LMCCEC = '',L2,'' LMCCIEC= '',L2/&
 & '' LMCCICEIC= '',L2/&
 & '' N923 ='',I2,'' LMCC05 = '',L2,&
 & '' NOACOMM ='',I1,'' LMCC01_MSE ='',L2, &
 & '' LMCC_COMPO = '',L2,'' LMCCIEC_COMPO = '',L2, '' LMULTIYR = '',L2)')&
 & NSSTICEOP,LCURR,LGELATO,&
 & LMCC01,LMCC02,LMCC03,LMCC04,LMCCEC,LMCCIEC,LMCCICEIC,&
 & N923,LMCC05, NOACOMM, LMCC01_MSE, LMCC_COMPO, LMCCIEC_COMPO,LMULTIYR 
WRITE(UNIT=KULOUT,FMT='('' * Module YOMMCC NEMO PART'')')
WRITE(UNIT=KULOUT,FMT='(&
 & '' LNEMOCOUP = '',L2, '' LNEMOSSTFREEZ = '',L2,&
 & '' LNEMO1WAY = '',L2,'' LNEMOFLUXNC = '',L2,&
 & '' LNEMOOUTGRB = '',L2,'' LNEMOIFSLOG = '',L2,&
 & '' LMCCDYNSEAICE = '',L2,'' LNEMOGRIBFLDS = '',L2,&
 & '' LNEMOLIMGET = '',L2,'' LNEMOLIMPUT = '',L2,&
 & '' LNEMOLIMALB = '',L2,'' LNEMOLIMTEMP = '',L2,'' LNEMOLIMTLVL = '',L2,&
 & '' LNEMOLIMTHK = '',L2, '' LNEMOOCEICEMIX = '',L2,&
 & '' LNEMOQNSICEFILT = '',L2, '' LNEMOSICOUP = '',L2)')&
 & LNEMOCOUP, LNEMOSSTFREEZ, LNEMO1WAY, LNEMOFLUXNC, LNEMOOUTGRB, &
 & LNEMOIFSLOG, LMCCDYNSEAICE, LNEMOGRIBFLDS, &
 & LNEMOLIMGET, LNEMOLIMPUT, LNEMOLIMALB, LNEMOLIMTEMP, LNEMOLIMTLVL,&
 & LNEMOLIMTHK, LNEMOOCEICEMIX, LNEMOQNSICEFILT, LNEMOSICOUP
WRITE(UNIT=KULOUT,FMT='(&
 & '' LNEMOGRIB3D = '',L2, '' NNEMO3DLEVS = '',I5)') &
 & LNEMOGRIB3D,NNEMO3DLEVS
WRITE(UNIT=KULOUT,FMT='(&
 & '' L2DECV2NEMO = '',L2)') &
 & L2DECV2NEMO
WRITE(UNIT=KULOUT,FMT='(&
 & '' LNEMOPARTCOUP = '',L2, '' LNEMOPARTMASK = '',L2, &
 & '' LNEMOPARTMASKFILE = '',L2,'' CDNPARTMASKFILE = '',A, &
 & '' RNPARTRAMPSTART = '',F8.2, '' RNPARTRAMPLEN = '',F8.2, &
 & '' RNPARTLAT = '',F8.2, '' RNPARTLATSPREAD = '',F8.2)')&
 & LNEMOPARTCOUP,LNEMOPARTMASK, &
 & LNEMOPARTMASKFILE, TRIM(CDNPARTMASKFILE), &
 & RNPARTRAMPSTART,RNPARTRAMPLEN, &
 & RNPARTLAT,RNPARTLATSPREAD
WRITE(UNIT=KULOUT,FMT='(&
 & '' LNEMOOUTGRB = '',L2, '' LCOUPINFOUT = '',L2)')&
 & LNEMOOUTGRB,LCOUPINFOUT
! For LCOUPINFOUT we need the experimental parameters to
! be in 24 bits
IF (LCOUPINFOUT) THEN
  NBITSEXPR=24
ENDIF
!      ----------------------------------------------------------------

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUMCC',1,ZHOOK_HANDLE)
END SUBROUTINE SUMCC
