MODULE CPLNG2

    USE CPLNG2_TYPES_MOD
    USE CPLNG2_DATA_MOD
    USE CPLNG2_INIT_MOD
    USE CPLNG2_EXCHANGE_MOD
    USE CPLNG2_FINALIZE_MOD

    IMPLICIT NONE

    PRIVATE

    PUBLIC CPLNG2_FLD_TYPE
    PUBLIC CPLNG2_FLD

    PUBLIC CPLNG2_ADD_FLD
    PUBLIC CPLNG2_ADD_FLD_COMPLETED
    PUBLIC CPLNG2_IDX

    PUBLIC CPLNG2_FLD_TYPE_GRIDPOINT
    PUBLIC CPLNG2_FLD_TYPE_SPECTRAL
    PUBLIC CPLNG2_FLD_TYPE_SINGLEPOINT ! for single column coupled model

    PUBLIC CPLNG2_FLD_IN
    PUBLIC CPLNG2_FLD_OUT

    PUBLIC CPLNG2_INIT
    PUBLIC CPLNG2_EXCHANGE
    PUBLIC CPLNG2_FINALIZE

END MODULE CPLNG2
