MODULE CPLNG2_TYPES_MOD

    USE PARKIND1, ONLY: JPIM, JPRB

    IMPLICIT NONE

    PRIVATE

    PUBLIC CPLNG2_FLD_TYPE

    TYPE CPLNG2_FLD_TYPE
        INTEGER(KIND=JPIM), ALLOCATABLE :: id(:, :)
        CHARACTER(LEN=128) :: name
        INTEGER(KIND=JPIM) :: TYPE
        INTEGER(KIND=JPIM) :: inout
        INTEGER(KIND=JPIM) :: stage
        INTEGER(KIND=JPIM) :: num_lvl
        INTEGER(KIND=JPIM) :: num_cat
        REAL(KIND=JPRB), ALLOCATABLE :: d(:, :, :)
    END TYPE CPLNG2_FLD_TYPE

END MODULE CPLNG2_TYPES_MOD
