! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE RADDRV(YDGEOMETRY,YDFIELDS,YDMODEL,KGPTOT,KFLDS,KBLOCKS,PGPIN)

!**** *RADDRV* - Radiation driver routine

!     Purpose.
!     --------
!           The motivation for this routine is primarily to call RADINTG.
!        RADINTG has been transplanted from CPGLAG/CALLPAR, so as to be 
!        able to resolve the conflict of latitudinal dependency implicit
!        in the interpolation scheme in RADINTG and support of any value
!        for NPROMA in CPGLAG.

!**   Interface.
!     ----------
!        *CALL* *RADDRV*

!        Explicit arguments :
!        --------------------
!        PGPIN     : input grid point array

!        Implicit arguments :
!        --------------------

!     Method.
!     -------
!        See documentation

!     Externals.
!     ----------
!        Called by SCAN2M and SCAN2M.

!     Reference.
!     ----------
!        see documentation for CPGLAG and CALLPAR

!     Author.
!     -------
!      George Mozdzynski  *ECMWF*
!      Original : 94-12-5

!     Modifications.
!     --------------
!      01-06-29 JJMorcrette : reordering aerosols
!      01-10-10 JJMorcrette : CCNs
!      01-11    GMozdzynski : support new radiation grid
!      02-09-20 JJMorcrette : P/P UV, PAR
!      03-08-01 M.Hamrud    : GFL introduction
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      JJMorcrette 20060721 PP of clear-sky OAR and TOA incident solar radiation
!      M.Hamrud      01-Jul-2006 Revised surface fields
!      N. Wedi and K. Yessad (Jan 2008): different dev for NH model and PC scheme
!      JJMorcrette 20081230 : Prognostic aerosols in rad and clouds
!      JJMorcrette 20091201 : Total and clear-sky downward direct SW flux at surface
!      GMozdzynski 20100226 : Remove old radiation interpolation interface (RADINT)
!      K. Yessad (Jan 2011): remove useless overdimension.
!      G.Mozdzynski (Feb 2011): OOPS cleaning, use of derived type TGSGEOM
!      HHersbach   20110401 : Auxiliary diagnostic radiation fields
!      M Ahlgrimm 31 Oct 2011 Surface Downward clear-sky LW and SW fluxes
!      G Balsamo  13 Jun 2013 lake prognostic buffer passed to radiation
!      T. Wilhelmsson (Sept 2013) Geometry and setup refactoring.
!      ABozzo 2014/2015: extra variables from RADINTG for aerosol and 
!                        GHG diagnostics 
!      R J Hogan 14 May 2014 : Partial derivatives of LW fluxes
!      M Leutbecher & S-J Lock (Jan 2016) Introduced SPP scheme (LSPP)
!      M Ahlgrimm 2017-11-11 cloud heterogeneity FSD
!      E. Dutra/G.Arduini, Jan 2018: change SP_SG dimensions, snow multi-layer
!      R J  Hogan 2019-01-23 : Spectral longwave emissivity in NLWEMISS intervals
!      R J  Hogan 2019-02-04 : Spectral longwave flux in NLWOUT intervals
!      F. Vana   11-Sep-2020 : Updated input state (t+dt rather then t)
!      M Leutbecher 2020-10-12 SPP abstraction
!     ------------------------------------------------------------------

USE TYPE_MODEL         , ONLY : MODEL
USE FIELDS_MOD         , ONLY : FIELDS
USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE PARKIND1           , ONLY : JPIM, JPRB
USE YOMHOOK            , ONLY : LHOOK, DR_HOOK, JPHOOK

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(FIELDS)      ,INTENT(INOUT) :: YDFIELDS
TYPE(MODEL)       ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN)    :: KGPTOT 
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLDS 
INTEGER(KIND=JPIM),INTENT(IN)    :: KBLOCKS 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGPIN(YDGEOMETRY%YRDIM%NPROMA,KFLDS,KBLOCKS) 
!     ------------------------------------------------------------------
! ZPRE9  : (NPROMA,0:NFLEVG)     ; HALF LEVEL PRESSURE
! ZPRE9F : (NPROMA,  NFLEVG)     ; FULL LEVEL PRESSURE
! ZDELP9 : (NPROMA,  NFLEVG)     ; PRESSURE DIFFERENCE ACROSS LAYERS
REAL(KIND=JPRB), ALLOCATABLE :: ZPRE9  (:,:),ZPRE9F (:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZDELP9 (:,:)

LOGICAL :: LLLAND (YDGEOMETRY%YRDIM%NPROMA)
LOGICAL :: LLLANDT(KGPTOT)

! ZMU0M : (NPROMA)            ; SOLAR ANGLE (between radiation steps)

REAL(KIND=JPRB) :: ZMU0M (YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) :: ZMU0MT(KGPTOT)

! - 1D (GEOGRAPHICAL DISTRIBUTION) .

! ZALBD      : DIFFUSE ALBEDO IN THE NTSW SW INTERVALS
! ZALBP      : PARALLEL ALBEDO IN THE NTSW SW INTERVALS

REAL(KIND=JPRB) :: ZALBD (YDGEOMETRY%YRDIM%NPROMA,YDMODEL%YRML_PHY_RAD%YRERAD%NTSW)
REAL(KIND=JPRB) :: ZALBP (YDGEOMETRY%YRDIM%NPROMA,YDMODEL%YRML_PHY_RAD%YRERAD%NTSW)
REAL(KIND=JPRB) :: ZALBDT(KGPTOT,YDMODEL%YRML_PHY_RAD%YRERAD%NTSW)
REAL(KIND=JPRB) :: ZALBPT(KGPTOT,YDMODEL%YRML_PHY_RAD%YRERAD%NTSW)

! ZCCNL      : CCN CONCENTRATION OVER LAND
! ZCCNO      : CCN CONCENTRATION OVER OCEAN 

REAL(KIND=JPRB) :: ZCCNL (YDGEOMETRY%YRDIM%NPROMA), ZCCNO (YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) :: ZCCNLT(KGPTOT), ZCCNOT(KGPTOT)

! - 2D (1:KLEV) .

! ZNEB       : FRACTIONAL CLOUDINESS FOR RADIATION.
! ZQICE      : SPECIFIC HUMIDITY OF SOLID WATER FOR RADIATION.
! ZQLI       : SPECIFIC HUMIDITY OF LIQUID WATER FOR RADIATION.
! ZQRAI      : SPECIFIC HUMIDITY OF RAIN WATER FOR RADIATION.
! ZRAIT      : RAIN RATE FOR RADIATION.
! ZQSAT      : SPECIFIC HUMIDITY AT SATURATION.
! ZAERO      : PROGNOSTIC AEROSOLS

REAL(KIND=JPRB) :: ZNEB  (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG),&
 & ZQLI  (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)&
 & ,  ZQSAT (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG),ZQICE (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)&
 & ,  ZQRAI (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG),ZRAIT (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)  
REAL(KIND=JPRB) :: ZAERO(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NAERO)

! - 1D (DIAGNOSTIC) .

! ZSPECTRALEMISS : MODEL SURFACE LONGWAVE EMISSIVITY IN SELECTED SPECTRAL INTERVALS
! ZEMIT      : DIAGNOSED SURFACE LONGWAVE TOTAL EMISSIVITY.
! ZCCC       : CONVECTIVE CLOUD COVER
! ZLCC       : LOW CLOUD COVER
! ZMCC       : MEDIUM CLOUD COVER
! ZHCC       : HIGH CLOUD COVER
! ZTCC       : TOTAL CLOUD COVER

REAL(KIND=JPRB) :: ZSPECTRALEMISS(YDGEOMETRY%YRDIM%NPROMA,YDMODEL%YRML_PHY_RAD%YRERAD%NLWEMISS)
REAL(KIND=JPRB) :: ZEMIT (YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) :: ZSPECTRALEMISST(KGPTOT,YDMODEL%YRML_PHY_RAD%YRERAD%NLWEMISS)
REAL(KIND=JPRB) :: ZEMITT(KGPTOT)

REAL(KIND=JPRB) :: ZTCC (YDGEOMETRY%YRDIM%NPROMA), ZCCC (YDGEOMETRY%YRDIM%NPROMA), ZLCC (YDGEOMETRY%YRDIM%NPROMA),&
 & ZMCC (YDGEOMETRY%YRDIM%NPROMA), ZHCC (YDGEOMETRY%YRDIM%NPROMA)  
REAL(KIND=JPRB) :: ZTCCT(KGPTOT), ZCCCT(KGPTOT), ZLCCT(KGPTOT),&
 & ZMCCT(KGPTOT), ZHCCT(KGPTOT)  

! - 2D (0:KLEV) FLUXES .

! - 2D (0:1)

REAL(KIND=JPRB) :: ZFRSOCT(KGPTOT,0:1),ZFRTHCT(KGPTOT,0:1)

! Arrays passed between RADINT and RADDIAG

! ZCTRSO     : CLEAR-SKY SHORTWAVE TRANSMISSIVITY
! ZCEMTR     : CLEAR-SKY NET LONGWAVE EMISSIVITY

! ZTRENU9T   : SURFACE TEMPERATURE (PTS)
! ZVFLSMT    : LAND-SEA MASK (PSLM)

! ZAEROT     : MIXING RATIO OF PROGNOSTIC AEROSOLS

!-- clear-sky radiation
! ZVRTRSCT   : CLEAR-SKY SHORTWAVE TRANSMISSIVITY (PTRSC)
! ZVREMTCT   : CLEAR-SKY NET LONGWAVE EMISSIVITY  (EMTC)

! Z2Q9       : SPECIFIC HUMIDITY PA/PA (PQ)
! Z2T9       : FULL LEVEL TEMPERATURE (PT)
! Z2O39      : FULL LEVEL PROGNOSTIC OZONE MIXING RATIO (ECMWF)

! ZFRTED     : Surface total-sky downward LW flux in each emissivity spectral interval
! ZTRSODT    : SURFACE DOWNWARD SW RADIATION
! ZTRSODCT   : CLEAR SKY SURFACE DOWNWARD SW RADIATION 
! ZTRTEDCT   : CLEAR SKY SURFACE DOWNWARD LW RADIATION 
! ZVNTOPT    : INDEX FOR TOP OF CONVECTIVE LAYER
! ZVNBAST    : INDEX FOR BOTTOM OF CONVECTIVE LAYER

REAL(KIND=JPRB) :: ZTRENU9T(KGPTOT)
REAL(KIND=JPRB) :: ZVFLSMT (KGPTOT)

!--      
REAL(KIND=JPRB) :: ZFRTED (KGPTOT,YDMODEL%YRML_PHY_RAD%YRERAD%NLWOUT)
REAL(KIND=JPRB) :: ZTRSODT (KGPTOT)
REAL(KIND=JPRB) :: ZTRSODCT(KGPTOT)
REAL(KIND=JPRB) :: ZTRTEDCT(KGPTOT)
REAL(KIND=JPRB) :: ZSUDUT  (KGPTOT)
REAL(KIND=JPRB) :: ZUVDFT  (KGPTOT)
REAL(KIND=JPRB) :: ZPARFT  (KGPTOT)
REAL(KIND=JPRB) :: ZPARCFT (KGPTOT)
REAL(KIND=JPRB) :: ZTINCFT (KGPTOT)
REAL(KIND=JPRB) :: ZFDIRT  (KGPTOT), ZCDIRT(KGPTOT)

REAL(KIND=JPRB) :: ZVNTOPT (KGPTOT)
REAL(KIND=JPRB) :: ZVNBAST (KGPTOT)
REAL(KIND=JPRB) :: ZPERTT  (KGPTOT, YDMODEL%YRML_GCONF%YRSPP_CONFIG%SM%NRFTOTAL_RADGRID) ! SPP: 2D random patterns


!                 LOCAL ARRAYS FROM METEO-FRANCE PHYSICS PACKAGE
!                 ----------------------------------------------

! ZQO3   ; OZONE MIXING RATIO (MASS)
! ZAER   ; AEROSOLS DISTRIBUTIONS
REAL(KIND=JPRB), ALLOCATABLE :: ZQO3(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZAER(:,:,:)

!extra variables for grib output GHG and aerosols fields
!active only for LDIAGFORCING=True
REAL(KIND=JPRB), ALLOCATABLE :: ZAERMACCS(:,:),ZAERMACCL(:,:),ZAERTGS(:,:,:),ZAERTGL(:,:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZAERMACCSJ(:,:),ZAERMACCLJ(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZGHG(:,:,:)
!extra variables for grib output GHG and aerosols fields
!active only for LDIAGFORCING=True

REAL(KIND=JPRB), ALLOCATABLE :: ZPRE9T (:,:),ZPRE9FT(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZDELP9T(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZNEBT (:,:),ZQLIT(:,:)&
 & ,  ZQSATT(:,:),ZQICET(:,:),ZQSNOWT(:,:)&
 & ,  ZQRAIT(:,:),ZRAITT(:,:),ZFSDT(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZFRSOT(:,:) ,ZFRTHT(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZTHT(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZVREMTDT(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZVREMTUT(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZVRTRSWT(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZVREMTCT(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZVRTRSCT(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: Z2Q9T   (:,:)
REAL(KIND=JPRB), ALLOCATABLE :: Z2T9T   (:,:)
REAL(KIND=JPRB), ALLOCATABLE :: Z2O39T  (:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZAEROT(:,:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZLWDERIVATIVE(:,:)

INTEGER(KIND=JPIM) :: IBL, IEND, IFDIA, IGL1,&
 & IGL2, IIDIA,&
 & IST, JAER, JCHA, JK, JL, JLEV,&
 & JLON, JSTGLO, JSW, JLW, IO3_CHEM
INTEGER(KIND=JPIM) :: IMP, IMPRG, IRGRID, IMGRID
INTEGER(KIND=JPIM) :: JPERT, JRF
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

#include "abor1.intfb.h"
#include "radcfg.intfb.h"
#include "raddiag.intfb.h"
#include "radintg.intfb.h"

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('RADDRV',0,ZHOOK_HANDLE)
ASSOCIATE(YDGFL=>YDFIELDS%YRGFL,YDGMV=>YDFIELDS%YRGMV, YDSURF=>YDFIELDS%YRSURF, &
 & YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV, YDGEM=>YDGEOMETRY%YRGEM, &
 & YDGSGEOM=>YDGEOMETRY%YRGSGEOM, YDOROG=>YDGEOMETRY%YROROG, YDEPHY=>YDMODEL%YRML_PHY_EC%YREPHY, &
 & YDPHY=>YDMODEL%YRML_PHY_MF%YRPHY,YDRADF=>YDMODEL%YRML_PHY_RAD%YRRADF, &
 & YDERAD=>YDMODEL%YRML_PHY_RAD%YRERAD,YGFL=>YDMODEL%YRML_GCONF%YGFL,YDERDI=>YDMODEL%YRML_PHY_RAD%YRERDI, &
 & YDCHEM=>YDMODEL%YRML_CHEM%YRCHEM, YDSPP_CONFIG=>YDMODEL%YRML_GCONF%YRSPP_CONFIG, YDSPP=>YDMODEL%YRML_SPP)

ASSOCIATE(NACTAERO=>YGFL%NACTAERO, NAERO=>YGFL%NAERO, NDIM=>YGFL%NDIM, &
 & YAERO=>YGFL%YAERO, YI=>YGFL%YI, YL=>YGFL%YL, YO3=>YGFL%YO3, YQ=>YGFL%YQ, &
 & YR=>YGFL%YR, YS=>YGFL%YS,NFSD=>YGFL%NFSD, &
 & GFL=>YDGFL%GFL,GMVT1=>YDGMV%GMVT1,GMVT1S=>YDGMV%GMVT1S, &
 & GMV=>YDGMV%GMV,GMVS=>YDGMV%GMVS,YT1=>YDGMV%YT1,YPH9=>YDGMV%YPH9, &
 & NDGENL=>YDDIM%NDGENL, NPROMA=>YDDIM%NPROMA, &
 & NFLEVG=>YDDIMV%NFLEVG, LERADIMPL=>YDEPHY%LERADIMPL, &
 & LAPPROXLWUPDATE=>YDERAD%LAPPROXLWUPDATE, LDIAGFORCING=>YDERAD%LDIAGFORCING, &
 & LEPO3RA=>YDERAD%LEPO3RA, NMODE=>YDERAD%NMODE, NRPROMA=>YDERAD%NRPROMA, &
 & NTSW=>YDERAD%NTSW, NLWEMISS=>YDERAD%NLWEMISS, NLWOUT=>YDERAD%NLWOUT, &
 & RCARDI=>YDERDI%RCARDI, &
 & NGPTOT=>YDGEM%NGPTOT, &
 & NDIMGMV=>YDGMV%NDIMGMV, NDIMGMVS=>YDGMV%NDIMGMVS, &
 & DERIVATIVELW=>YDRADF%DERIVATIVELW, EMTC=>YDRADF%EMTC, EMTD=>YDRADF%EMTD, &
 & SRCDIR=>YDRADF%SRCDIR, SRFDIR=>YDRADF%SRFDIR, SRLWD=>YDRADF%SRLWD, &
 & SRLWDC=>YDRADF%SRLWDC, SRSWD=>YDRADF%SRSWD, SRSWDC=>YDRADF%SRSWDC, &
 & SRSWDCS=>YDRADF%SRSWDCS, SRSWPAR=>YDRADF%SRSWPAR, SRSWPARC=>YDRADF%SRSWPARC, &
 & SRSWTINC=>YDRADF%SRSWTINC, SRSWUVB=>YDRADF%SRSWUVB, TRSC=>YDRADF%TRSC, &
 & TRSW=>YDRADF%TRSW, &
 & SD_VD=>YDSURF%SD_VD, SD_VF=>YDSURF%SD_VF, SD_VN=>YDSURF%SD_VN, &
 & SD_XR=>YDSURF%SD_XR, SP_RR=>YDSURF%SP_RR, SP_SB=>YDSURF%SP_SB, &
 & SP_SG=>YDSURF%SP_SG, SP_SL=>YDSURF%SP_SL, YSD_VF=>YDSURF%YSD_VF, &
 & YSD_VN=>YDSURF%YSD_VN, YSP_RR=>YDSURF%YSP_RR, &
 & LRAYFM=>YDPHY%LRAYFM,YFSD=>YGFL%YFSD)
!     ------------------------------------------------------------------

!  Initialisation

ALLOCATE(ZPRE9T (KGPTOT,0:NFLEVG))
ALLOCATE(ZPRE9FT(KGPTOT,NFLEVG))
ALLOCATE(ZDELP9T(KGPTOT,NFLEVG))
ALLOCATE(ZNEBT(KGPTOT,NFLEVG))
ALLOCATE(ZQLIT(KGPTOT,NFLEVG))
ALLOCATE(ZQSATT(KGPTOT,NFLEVG))
ALLOCATE(ZQICET(KGPTOT,NFLEVG))
ALLOCATE(ZQSNOWT(KGPTOT,NFLEVG))
ALLOCATE(ZQRAIT(KGPTOT,NFLEVG))
ALLOCATE(ZRAITT(KGPTOT,NFLEVG))
ALLOCATE(ZFRSOT(KGPTOT,0:NFLEVG))
ALLOCATE(ZFRTHT(KGPTOT,0:NFLEVG))
ALLOCATE(ZTHT(KGPTOT,NFLEVG+1))
ALLOCATE(ZVREMTDT(KGPTOT,NFLEVG+1))
ALLOCATE(ZVREMTUT(KGPTOT,NFLEVG+1))
ALLOCATE(ZVRTRSWT(KGPTOT,NFLEVG+1))
ALLOCATE(ZVREMTCT(KGPTOT,NFLEVG+1))
ALLOCATE(ZVRTRSCT(KGPTOT,NFLEVG+1))
ALLOCATE(Z2Q9T(KGPTOT,NFLEVG))
ALLOCATE(Z2T9T(KGPTOT,NFLEVG))

IF (LAPPROXLWUPDATE) THEN
   ALLOCATE(ZLWDERIVATIVE(KGPTOT,NFLEVG+1))
ENDIF

IF( ((YGFL%NCHEM>0 .AND. YDCHEM%LCHEM_O3RAD) .OR.  YO3%LGP) .AND.LEPO3RA) THEN
  ALLOCATE(Z2O39T(KGPTOT,NFLEVG))
ELSE
  ALLOCATE(Z2O39T(1,1))
ENDIF
IF (NFSD > 0) THEN
  ALLOCATE(ZFSDT(KGPTOT,NFLEVG))
ELSE
  ALLOCATE(ZFSDT(1,1))
ENDIF 
IF(NACTAERO > 0) THEN
  ALLOCATE(ZAEROT(KGPTOT,NFLEVG,NAERO))
ELSE
  ALLOCATE(ZAEROT(1,1,1))
ENDIF

IF( LRAYFM )THEN
  CALL GSTATS(1201,0)
! METEO FRANCE REQUIRE THESE ARRAYS
  ALLOCATE(ZQO3(NPROMA,NFLEVG))
  ALLOCATE(ZAER(NPROMA,6,NFLEVG))
  ALLOCATE(ZAERMACCS(1,1))
  ALLOCATE(ZAERMACCL(1,1))
  ALLOCATE(ZAERMACCSJ(1,1))
  ALLOCATE(ZAERMACCLJ(1,1))
  ALLOCATE(ZAERTGS(1,1,1))
  ALLOCATE(ZAERTGL(1,1,1))
  ALLOCATE(ZGHG(1,1,1))
!$OMP PARALLEL PRIVATE(JLEV,JLON,JCHA)
!$OMP DO SCHEDULE(STATIC)
  DO JLEV=1,NFLEVG
    DO JLON=1,NPROMA
      ZQO3(JLON,JLEV) = 0.0_JPRB
    ENDDO
  ENDDO
!$OMP ENDDO NOWAIT
!$OMP DO SCHEDULE(STATIC)
  DO JLEV=1,NFLEVG
    DO JCHA=1,6
      DO JLON=1,NPROMA
        ZAER(JLON,JCHA,JLEV)=0.0_JPRB
      ENDDO
    ENDDO
  ENDDO
!$OMP ENDDO
!$OMP END PARALLEL
  CALL GSTATS(1201,1)
ELSE
  IF (LDIAGFORCING) THEN
     ALLOCATE(ZQO3(NGPTOT,  NFLEVG))
     ALLOCATE(ZAER(NGPTOT,6,NFLEVG))
     ALLOCATE(ZGHG(NGPTOT,8,NFLEVG))
     ALLOCATE(ZAERMACCS(NGPTOT,14))
     ALLOCATE(ZAERMACCL(NGPTOT,16))
     ALLOCATE(ZAERMACCSJ(NGPTOT,12))
     ALLOCATE(ZAERMACCLJ(NGPTOT,12))
     ALLOCATE(ZAERTGS(NGPTOT,NFLEVG,14))
     ALLOCATE(ZAERTGL(NGPTOT,NFLEVG,16))
  ELSE
!    FOR ECMWF RADIATION WE MAKE THEM AS SMALL AS POSSIBLE
!    (WITHOUT VIOLATING RUNTIME SUBSCRIPT CHECKING ON CALLS)
     ALLOCATE(ZQO3(1,1))
     ALLOCATE(ZAER(1,1,1))
     ALLOCATE(ZGHG(1,1,1))
     ALLOCATE(ZAERMACCS(1,1))
     ALLOCATE(ZAERMACCL(1,1))
     ALLOCATE(ZAERMACCSJ(1,1))
     ALLOCATE(ZAERMACCLJ(1,1))
     ALLOCATE(ZAERTGS(1,1,1))
     ALLOCATE(ZAERTGL(1,1,1))
  ENDIF
ENDIF


!  Perform Computations on Fine Grid

CALL GSTATS(1202,0)

! find prognostic ozozne in chemistry array
IO3_CHEM=-999
IF (LEPO3RA) THEN
  IF (YGFL%NCHEM > 0 .AND. YDCHEM%LCHEM_O3RAD) THEN  
    DO JAER=1,YGFL%NCHEM
      IF (TRIM(YGFL%YCHEM(JAER)%CNAME) == 'O3' )  IO3_CHEM = JAER
    ENDDO
    IF (IO3_CHEM <= 0) THEN
      CALL ABOR1('RADDRV: LEPO3RA with LCHEM_O3RAD, but no chemistry O3 found')
    ENDIF
  ELSEIF (.NOT. YGFL%YO3%LGP) THEN
    CALL ABOR1('RADDRV: LEPO3RA without LCHEM_O3RAD, but no standalone gridpoint O3 found')
  ENDIF
ENDIF

!$OMP PARALLEL &
!$OMP&PRIVATE(JSTGLO,IST,IEND,IBL,JAER,JL,JSW,JK,JPERT,JRF,IMP,IMPRG,IRGRID,IMGRID,&
!$OMP&        LLLAND,ZALBD,ZALBP,ZCCNL,ZCCNO,ZPRE9,ZPRE9F,ZNEB,ZCCC,ZHCC,ZLCC,&
!$OMP&        ZMCC,ZTCC,ZDELP9,ZSPECTRALEMISS,ZEMIT,ZMU0M,ZQSAT,ZQICE,ZQLI,&
!$OMP&        ZQRAI,ZRAIT,ZAERO)

IF(.NOT.ALLOCATED(ZPRE9 )) ALLOCATE(ZPRE9(NPROMA,0:NFLEVG))
IF(.NOT.ALLOCATED(ZPRE9F)) ALLOCATE(ZPRE9F(NPROMA,NFLEVG))
IF(.NOT.ALLOCATED(ZDELP9)) ALLOCATE(ZDELP9(NPROMA,NFLEVG))

!$OMP DO SCHEDULE(DYNAMIC,1)
DO JSTGLO=1,NGPTOT,NPROMA
  IST =1
  IEND=MIN(NPROMA,NGPTOT-JSTGLO+1)
  IBL=(JSTGLO-1)/NPROMA+1

  IF (LERADIMPL) THEN
  CALL RADCFG(YDGEOMETRY,YDSURF,YDMODEL, IST    ,IEND   ,&
   & JSTGLO ,KFLDS,&
   & LLLAND,&
   & YDOROG(IBL)%OROG,&
   & PGPIN(1,1,IBL),GFL(1,1,1,IBL),&
   & GMVT1(1,1,YT1%MU,IBL),GMVT1(1,1,YT1%MV,IBL),&
   & GMVT1(1,1,YT1%MT,IBL),GMVT1S(1,YT1%MSP,IBL),&
   & SP_SB(:,:,:,IBL),SP_SG(:,:,:,IBL),&
   & SP_SL(:,:,IBL),SP_RR(:,:,IBL),&
   & SD_VF(:,:,IBL),SD_VN(:,:,IBL),SD_VD(:,:,IBL),&
   & ZALBD  ,ZALBP  ,ZCCNL  ,ZCCNO  ,ZPRE9  ,ZPRE9F ,ZNEB,&
   & ZCCC   ,ZHCC   ,ZLCC   ,ZMCC   ,ZTCC,&
   & YDGSGEOM(IBL)%GELAM,&
   & ZDELP9 ,ZSPECTRALEMISS,ZEMIT,&
   & YDGSGEOM(IBL)%GEMU ,ZMU0M ,ZQSAT,&
   & ZQICE  ,ZQLI   ,ZQRAI ,ZRAIT,&
   & ZAERO )
  ELSE
  CALL RADCFG(YDGEOMETRY,YDSURF,YDMODEL, IST    ,IEND   ,&
   & JSTGLO ,KFLDS,&
   & LLLAND,&
   & YDOROG(IBL)%OROG,&
   & PGPIN(1,1,IBL),GFL(1,1,1,IBL),&
   & GMV(1,1,YPH9%MU,IBL),GMV(1,1,YPH9%MV,IBL),&
   & GMV(1,1,YPH9%MT,IBL),GMVS(1,YPH9%MSP,IBL),&
   & SP_SB(:,:,:,IBL),SP_SG(:,:,:,IBL),&
   & SP_SL(:,:,IBL),SP_RR(:,:,IBL),&
   & SD_VF(:,:,IBL),SD_VN(:,:,IBL),SD_VD(:,:,IBL),&
   & ZALBD  ,ZALBP  ,ZCCNL  ,ZCCNO  ,ZPRE9  ,ZPRE9F ,ZNEB,&
   & ZCCC   ,ZHCC   ,ZLCC   ,ZMCC   ,ZTCC,&
   & YDGSGEOM(IBL)%GELAM,&
   & ZDELP9 ,ZSPECTRALEMISS,ZEMIT,&
   & YDGSGEOM(IBL)%GEMU ,ZMU0M ,ZQSAT,&
   & ZQICE  ,ZQLI   ,ZQRAI ,ZRAIT,&
   & ZAERO )
  ENDIF
       
  DO JL=IST,IEND
    LLLANDT (JSTGLO+JL-1)  =LLLAND(JL)
    ZCCCT   (JSTGLO+JL-1)  =ZCCC  (JL)
    ZHCCT   (JSTGLO+JL-1)  =ZHCC  (JL)
    ZLCCT   (JSTGLO+JL-1)  =ZLCC  (JL)
    ZMCCT   (JSTGLO+JL-1)  =ZMCC  (JL)
    ZTCCT   (JSTGLO+JL-1)  =ZTCC  (JL)
    ZEMITT  (JSTGLO+JL-1)  =ZEMIT (JL)
    ZMU0MT  (JSTGLO+JL-1)  =ZMU0M (JL)
    ZTRENU9T(JSTGLO+JL-1)  =SP_RR (JL,YSP_RR%YT%MP9,IBL )
    ZVFLSMT (JSTGLO+JL-1)  =SD_VF (JL,YSD_VF%YLSM%MP,IBL)
    
    ZVNTOPT (JSTGLO+JL-1)  =SD_VN (JL,YSD_VN%YTOP%MP,IBL)
    ZVNBAST (JSTGLO+JL-1)  =SD_VN (JL,YSD_VN%YBAS%MP,IBL)
    ZCCNLT  (JSTGLO+JL-1)  =ZCCNL (JL)
    ZCCNOT  (JSTGLO+JL-1)  =ZCCNO (JL)
  ENDDO
  DO JLW=1,NLWEMISS
    DO JL=IST,IEND
      ZSPECTRALEMISST(JSTGLO+JL-1,JLW)  =ZSPECTRALEMISS(JL,JLW)
    ENDDO
  ENDDO
  !SPP: pick up grid-point random patterns for use on radiation grid
  IF(YDSPP_CONFIG%LSPP) THEN
    DO JPERT=1,YDSPP_CONFIG%SM%NACT
      IF (YDSPP_CONFIG%SM%PN(JPERT)%RADGRID) THEN
        IMP   = YDSPP_CONFIG%SM%PN(JPERT)%MP - 1 ! points before random field for this perturbation
        IMPRG = YDSPP_CONFIG%SM%PN(JPERT)%MP_RADGRID - 1 ! points before random field for this perturbation
        DO JRF=1, YDSPP_CONFIG%SM%PN(JPERT)%NRF
          IRGRID = IMPRG +JRF ! random field index on radiation grid
          IMGRID = IMP + JRF  ! random field index on model grid
          DO JL=IST,IEND
            ZPERTT(JSTGLO+JL-1,IRGRID)  =  YDSPP%GP_ARP(IMGRID)%GP2D(JL,1,IBL)
          ENDDO
        ENDDO
      ENDIF
    ENDDO
  ENDIF
  DO JSW=1,NTSW
    DO JL=IST,IEND
      ZALBDT  (JSTGLO+JL-1,JSW)  =ZALBD (JL,JSW)
      ZALBPT  (JSTGLO+JL-1,JSW)  =ZALBP (JL,JSW)
    ENDDO
  ENDDO
  DO JK=0,NFLEVG
    DO JL=IST,IEND
      ZPRE9T  (JSTGLO+JL-1,JK)=ZPRE9 (JL,JK)
    ENDDO
  ENDDO
  DO JK=1,NFLEVG
!DIR$ IVDEP
     DO JL=IST,IEND
        ZPRE9FT (JSTGLO+JL-1,JK)=ZPRE9F(JL,JK)
     ENDDO
  ENDDO
  DO JK=1,NFLEVG
!DIR$ IVDEP
     DO JL=IST,IEND
        ZNEBT   (JSTGLO+JL-1,JK)=ZNEB  (JL,JK)
     ENDDO
  ENDDO
  DO JK=1,NFLEVG
!DIR$ IVDEP
     DO JL=IST,IEND
        ZQSATT  (JSTGLO+JL-1,JK)=ZQSAT (JL,JK)
     ENDDO
  ENDDO
!      ZQICET  (JSTGLO+JL-1,JK)=ZQICE (JL,JK)
!      ZQSNOWT (JSTGLO+JL-1,JK)=ZQSNOW (JL,JK)
!      ZQLIT   (JSTGLO+JL-1,JK)=ZQLI  (JL,JK)
  DO JK=1,NFLEVG
!DIR$ IVDEP
     DO JL=IST,IEND
        ZQICET  (JSTGLO+JL-1,JK)=GFL(JL,JK,YI%MP9_PH,IBL)
     ENDDO
  ENDDO
  DO JK=1,NFLEVG
!DIR$ IVDEP
     DO JL=IST,IEND
        ZQSNOWT (JSTGLO+JL-1,JK)=GFL(JL,JK,YS%MP9_PH,IBL)
     ENDDO
  ENDDO
  DO JK=1,NFLEVG
!DIR$ IVDEP
     DO JL=IST,IEND
        ZQLIT   (JSTGLO+JL-1,JK)=GFL(JL,JK,YL%MP9_PH,IBL)
     ENDDO
  ENDDO
!      ZQRAIT  (JSTGLO+JL-1,JK)=ZQRAI (JL,JK)
  DO JK=1,NFLEVG
!DIR$ IVDEP
     DO JL=IST,IEND
        ZQRAIT  (JSTGLO+JL-1,JK)=GFL(JL,JK,YR%MP9_PH,IBL)
     ENDDO
  ENDDO
  DO JK=1,NFLEVG
!DIR$ IVDEP
     DO JL=IST,IEND
        ZRAITT  (JSTGLO+JL-1,JK)=ZRAIT (JL,JK)
     ENDDO
  ENDDO
  DO JK=1,NFLEVG
!DIR$ IVDEP
     DO JL=IST,IEND
        Z2Q9T   (JSTGLO+JL-1,JK)=GFL(JL,JK,YQ%MP9_PH,IBL)
     ENDDO
  ENDDO
  DO JK=1,NFLEVG
     if(LERADIMPL)THEN
!DIR$ IVDEP
     DO JL=IST,IEND
        Z2T9T   (JSTGLO+JL-1,JK)=GMVT1(JL,JK,YT1%MT,IBL)
     ENDDO
     else
!DIR$ IVDEP
     DO JL=IST,IEND
        Z2T9T   (JSTGLO+JL-1,JK)=GMV(JL,JK,YPH9%MT,IBL)
     ENDDO
     endif
  ENDDO
  IF(LEPO3RA) THEN
     IF(YO3%LGP .AND. .NOT. (YGFL%NCHEM>0 .AND. YDCHEM%LCHEM_O3RAD) ) THEN
        DO JK=1,NFLEVG
!DIR$ IVDEP
           DO JL=IST,IEND
              Z2O39T  (JSTGLO+JL-1,JK)=GFL(JL,JK,YO3%MP9_PH,IBL)
           ENDDO
        ENDDO
     ENDIF
     IF ((YGFL%NCHEM>0 .AND. YDCHEM%LCHEM_O3RAD) .AND. IO3_CHEM > 0 ) THEN 
        DO JK=1,NFLEVG
!DIR$ IVDEP
           DO JL=IST,IEND
              Z2O39T(JSTGLO+JL-1,JK)=GFL(JL,JK,YGFL%YCHEM(IO3_CHEM)%MP9_PH,IBL)
           ENDDO
        ENDDO
     ENDIF
  ENDIF
 IF (NFSD > 0) THEN
    DO JK=1,NFLEVG
!DIR$ IVDEP
      DO JL=IST,IEND
        ZFSDT(JSTGLO+JL-1,JK)=GFL(JL,JK,YFSD%MP9_PH,IBL)
      ENDDO
    ENDDO
  ENDIF 
  IF (NACTAERO > 0) THEN
    DO JAER=1,NAERO
      DO JK=1,NFLEVG
!DIR$ IVDEP
        DO JL=IST,IEND
          ZAEROT(JSTGLO+JL-1,JK,JAER)=GFL(JL,JK,YAERO(JAER)%MP9_PH,IBL)
        ENDDO
      ENDDO
    ENDDO 
  ENDIF
  DO JK=1,NFLEVG
    DO JL=IST,IEND
      ZDELP9T (JSTGLO+JL-1,JK)=ZDELP9(JL,JK)
    ENDDO
  ENDDO
  DO JK=1,NFLEVG+1
!DIR$ IVDEP
     DO JL=IST,IEND
        ZVREMTDT(JSTGLO+JL-1,JK)=EMTD(JL,JK,IBL)
     ENDDO
  ENDDO
  DO JK=1,NFLEVG+1
!DIR$ IVDEP
     DO JL=IST,IEND
        ZVREMTUT(JSTGLO+JL-1,JK)=0.0
     ENDDO
  ENDDO
  DO JK=1,NFLEVG+1
!DIR$ IVDEP
     DO JL=IST,IEND
        ZVRTRSWT(JSTGLO+JL-1,JK)=TRSW(JL,JK,IBL)
     ENDDO
  ENDDO
!--clear-sky
  DO JK=1,NFLEVG+1
!DIR$ IVDEP
     DO JL=IST,IEND
        ZVREMTCT(JSTGLO+JL-1,JK)=EMTC(JL,JK,IBL)
     ENDDO
  ENDDO
  DO JK=1,NFLEVG+1
!DIR$ IVDEP
     DO JL=IST,IEND
        ZVRTRSCT(JSTGLO+JL-1,JK)=TRSC(JL,JK,IBL)
     ENDDO
  ENDDO
! Partial derivatives
    IF (LAPPROXLWUPDATE) THEN
       DO JK=1,NFLEVG+1
!DIR$ IVDEP
          DO JL=IST,IEND
             ZLWDERIVATIVE(JSTGLO+JL-1,JK)=DERIVATIVELW(JL,JK,IBL)
          ENDDO
       ENDDO
    ENDIF

ENDDO
!$OMP ENDDO

IF(ALLOCATED(ZPRE9 )) DEALLOCATE(ZPRE9)
IF(ALLOCATED(ZPRE9F)) DEALLOCATE(ZPRE9F)
IF(ALLOCATED(ZDELP9)) DEALLOCATE(ZDELP9)

!$OMP END PARALLEL
CALL GSTATS(1202,1)

!  FULL RADIATION COMPUTATIONS

CALL RADINTG(YDGEOMETRY,YDMODEL, &
 & NFLEVG  ,NMODE,&
 & ZALBDT  ,ZALBPT  ,ZCCNLT  ,ZCCNOT  ,ZPRE9T  ,ZPRE9FT ,RCARDI ,ZNEBT,&
 & ZQO3    ,ZAER    ,ZAERMACCS,ZAERMACCL,ZAERMACCSJ,ZAERMACCLJ,&
 & ZAERTGS,ZAERTGL,ZAEROT  ,ZGHG,&
 & ZDELP9T ,ZSPECTRALEMISST,&
 & ZMU0MT  ,Z2Q9T,&
 & ZQSATT  ,ZQICET  ,ZQSNOWT ,ZQLIT   ,ZFSDT   ,ZQRAIT  ,ZRAITT,&
 & ZVFLSMT ,Z2T9T   ,Z2O39T  ,ZTRENU9T,&
! FLUX OUTPUTS
 & ZVREMTDT,ZVREMTUT,ZVRTRSWT,ZVRTRSCT,ZVREMTCT,ZVNTOPT ,ZVNBAST,&
! ML: move zpertt before flux outputs
 & ZPERTT,&  
 & ZEMITT ,ZTHT    ,ZFRTED, ZTRSODT ,ZTRSODCT,ZTRTEDCT,ZSUDUT  ,ZUVDFT  ,ZPARFT  ,ZPARCFT, ZTINCFT,&
 & ZFDIRT  ,ZCDIRT  , ZLWDERIVATIVE )

!  PERFORM RADIATION DIAGNOSTICS

IIDIA=0
IFDIA=0

IGL1=1
IGL2=NDGENL
CALL GSTATS(1906,0)
CALL RADDIAG(YDGEOMETRY,YDMODEL%YRML_PHY_RAD,YDMODEL%YRML_PHY_EC%YRECLD,YDMODEL%YRML_PHY_MF%YRPHY3, &
 & IGL1    ,IGL2    ,NGPTOT  ,NFLEVG,&
 & LLLANDT,&
 & ZALBDT  ,ZALBPT  ,ZPRE9T  ,ZNEBT,&
 & ZCCCT   ,ZHCCT   ,ZLCCT   ,ZMCCT   ,ZTCCT,&
 & ZSPECTRALEMISST(:,1),ZSPECTRALEMISST(:,2),ZEMITT,&
 & ZMU0MT  ,ZVFLSMT,&
 & Z2T9T   ,ZTRENU9T,&
 & ZVREMTDT,ZVRTRSWT,&
 & ZFRTHCT ,ZFRTHT  ,ZFRSOCT ,ZFRSOT  ,ZTHT  , ZVRTRSCT, ZVREMTCT&
 & )  
CALL GSTATS(1906,1)

!  WRITE OUT GRIDPOINT ARRAY TO WORK FILE

CALL GSTATS(1203,0)
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JSTGLO,IST,IEND,JK,JL,IBL)
DO JSTGLO=1,NGPTOT,NPROMA
  IST =1
  IEND=MIN(NPROMA,NGPTOT-JSTGLO+1)
  IBL=(JSTGLO-1)/NPROMA+1

  DO JK=1,NFLEVG+1
!DIR$ IVDEP
     DO JL=IST,IEND
        EMTD(JL,JK,IBL) = ZVREMTDT(JSTGLO+JL-1,JK)
     ENDDO
  ENDDO
  DO JK=1,NFLEVG+1
!DIR$ IVDEP
     DO JL=IST,IEND
        TRSW(JL,JK,IBL) = ZVRTRSWT(JSTGLO+JL-1,JK)
     ENDDO
  ENDDO
!-- clear-sky      
  DO JK=1,NFLEVG+1
!DIR$ IVDEP
     DO JL=IST,IEND        
        EMTC(JL,JK,IBL) = ZVREMTCT(JSTGLO+JL-1,JK)
     ENDDO
  ENDDO
  DO JK=1,NFLEVG+1
!DIR$ IVDEP
     DO JL=IST,IEND
        TRSC(JL,JK,IBL) = ZVRTRSCT(JSTGLO+JL-1,JK)
     ENDDO
  ENDDO
  IF (LAPPROXLWUPDATE) THEN
     DO JK=1,NFLEVG+1
!DIR$ IVDEP
        DO JL=IST,IEND
           DERIVATIVELW(JL,JK,IBL) = ZLWDERIVATIVE(JSTGLO+JL-1,JK)
        ENDDO
     ENDDO
  ENDIF

!-- ozone, ghg, aerosols, if required
  IF (LDIAGFORCING) THEN
     DO JK=1,NFLEVG
!DIR$ IVDEP
        DO JL=IST,IEND
!           SD_XR(JL,JK, 1:8 ,IBL) = ZGHG(JSTGLO+JL-1,1:8,JK)
!           SD_XR(JL,JK, 9   ,IBL) = ZAERMACC(JSTGLO+JL-1,JK) !ZQO3(JSTGLO+JL-1,    JK)
!           SD_XR(JL,JK,10:15,IBL) = ZAER(JSTGLO+JL-1,1:6,JK)
           IF (JK==1) THEN  
!MACC total AOD (sum over species) for all SW spectral bands
           SD_XR(JL,JK, 1:14,IBL) = ZAERMACCS(JSTGLO+JL-1,1:14)
           ELSEIF (JK==2) THEN
!MACC total AOD (sum over species) for all LW spectral bands
           SD_XR(JL,JK, 1:15,IBL) = ZAERMACCL(JSTGLO+JL-1,1:15)
           ELSEIF (JK==3) THEN
!TEGEN total AOD (sum over species) for all SW spectral bands
           SD_XR(JL,JK,1:14,IBL) = SUM(ZAERTGS(JSTGLO+JL-1,:,1:14),1)
           ELSEIF (JK==4) THEN
!TEGEN total AOD (sum over species) for all LW spectral bands
           SD_XR(JL,JK,1:15,IBL) = SUM(ZAERTGL(JSTGLO+JL-1,:,1:15),1)
           ELSEIF (JK==5) THEN
!total TEGEN OD@550nm for each specie
           SD_XR(JL,JK,1:6,IBL) = SUM(ZAER(JSTGLO+JL-1,1:6,:),2)
           ELSEIF (JK==6) THEN
!total OD@550nm for all species
           SD_XR(JL,JK, 1:12,IBL) = ZAERMACCSJ(JSTGLO+JL-1,1:12)
           ELSEIF (JK==7) THEN
!total OD@11um for all species
           SD_XR(JL,JK, 1:12,IBL) = ZAERMACCLJ(JSTGLO+JL-1,1:12)
           ELSE
           SD_XR(JL,JK,:,IBL) = 0.0_JPRB
           ENDIF
        ENDDO
     ENDDO
  ENDIF

!DIR$ IVDEP
  DO JL=IST,IEND
    SRSWDCS(JL,IBL) = ZSUDUT (JSTGLO+JL-1)
    SRSWD  (JL,IBL) = ZTRSODT(JSTGLO+JL-1)
    SRSWDC (JL,IBL) = ZTRSODCT(JSTGLO+JL-1)
    SRLWDC (JL,IBL) = ZTRTEDCT(JSTGLO+JL-1)
    SRSWUVB(JL,IBL) = ZUVDFT (JSTGLO+JL-1)
    SRSWPAR(JL,IBL) = ZPARFT (JSTGLO+JL-1)
    SRSWPARC(JL,IBL)= ZPARCFT(JSTGLO+JL-1)
    SRSWTINC(JL,IBL)= ZTINCFT(JSTGLO+JL-1)
    SRFDIR (JL,IBL) = ZFDIRT (JSTGLO+JL-1)
    SRCDIR (JL,IBL) = ZCDIRT (JSTGLO+JL-1)
  ENDDO

  DO JK=1,NLWOUT
    DO JL=IST,IEND
      SRLWD(JL,JK,IBL) = ZFRTED(JSTGLO+JL-1,JK)
    ENDDO
  ENDDO

ENDDO
!$OMP END PARALLEL DO
CALL GSTATS(1203,1)


DEALLOCATE(ZPRE9T, ZPRE9FT, ZDELP9T, ZNEBT, ZQLIT, ZQSATT, ZQICET, ZQSNOWT)
DEALLOCATE(ZQRAIT, ZRAITT, ZFRSOT, ZFRTHT, ZTHT, ZVREMTDT, ZVREMTUT)
DEALLOCATE(ZVRTRSWT, ZVREMTCT, ZVRTRSCT, Z2Q9T, Z2T9T, Z2O39T)
DEALLOCATE(ZQO3, ZAER)
DEALLOCATE(ZAEROT,ZFSDT)
IF(ALLOCATED(ZGHG))DEALLOCATE(ZGHG)
IF(ALLOCATED(ZAERMACCS))DEALLOCATE(ZAERMACCS)
IF(ALLOCATED(ZAERMACCL))DEALLOCATE(ZAERMACCL)
IF(ALLOCATED(ZAERMACCSJ))DEALLOCATE(ZAERMACCSJ)
IF(ALLOCATED(ZAERMACCLJ))DEALLOCATE(ZAERMACCLJ)
IF(ALLOCATED(ZAERTGS))DEALLOCATE(ZAERTGS)
IF(ALLOCATED(ZAERTGL))DEALLOCATE(ZAERTGL)
IF(ALLOCATED(ZLWDERIVATIVE)) DEALLOCATE(ZLWDERIVATIVE)
!     ------------------------------------------------------------------

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('RADDRV',1,ZHOOK_HANDLE)
END SUBROUTINE RADDRV
