! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE ALLFPOS(YDRQDYN,YDFPDATA,YDRQPHY,LDFPLAG,LDOCE,LDCFU,LDXFU,YDGEOMETRY,YDGMV,YDGFL,YDSURF,YDCFU,YDXFU,YDMODEL, &
 & PCFUBUF,PXFUBUF,KCUFNR,PMCUFGP,KDATEF,KITER,LDINC,KPPSTEP,PTSTEP)

!**** *ALLFPOS*  - A complete step of post-processing

!     Purpose.
!     --------
!           performs a complete step of post-processing :
!            - physical fields post-processing
!            - dynamical fields post-processing
!            + post event in the case of Arpege/Arome

!**   Interface.
!     ----------
!        *CALL* *ALLFPOS

!        Explicit arguments :
!        --------------------
!           LDFPLAG : True if lagged post-proc. for physics (dyn pp already done)
!           LDOCE   : Post-processing ocean fields if called in ocean mode
!           LDCFU   : True if post-processing of cumulated fluxes
!           LDXFU   : True if post-processing of instantaneous fluxes
!           YDGEOMETRY : input model geometry
!           YDGMV   : input GMV fields
!           YDGFL   : input GFL fields
!           YDSURF  : input surface fields
!           PCFUBUF : input cumulated fluxes
!           PXFUBUF : input instantaneous fluxes
!           PMCUFGP : monitoring of coupling update frequency
!           KDATEF  : Date to be written to output files for the current step
!           KITER   : current iteration of post-processing (for opdis) 
!           LDINC   : .TRUE. if output filenames with time increment in hours ; otherwise in steps.
!           KPPSTEP : post-processing step number
!           PTSTEP  : model time step

!        Implicit arguments :
!        --------------------
!        None

!     Method.
!     -------
!        See documentation

!     Externals.
!     ----------

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     Author.
!     -------
!      R. El Khatib *METEO-FRANCE*
!      Original : 31-Jan-2017

!     Modifications.
!     R. El Khatib 15-Jun-2018 option NFPWRITE=-1 to disable norms
!     R. El Khatib 27-Nov-2018 fix handling of 2D fields, with a possible extra scan of pp.
!     R. El Khatib : 31-Jan-2019 fix for single precision compilation
!     R. El Khatib : 06-Jun-2019 split stepo_fpos to avoid multiple horizontal interpolation of model fields
!     ------------------------------------------------------------------

USE PARKIND1      , ONLY : JPIM,    JPRB, JPRD
USE YOMHOOK       , ONLY : LHOOK,   DR_HOOK, JPHOOK
USE YOMLUN        , ONLY : NULOUT
USE YOMCT0        , ONLY : LARPEGEF ,LOPDIS
USE GEOMETRY_MOD  , ONLY : GEOMETRY
USE YOMGMV        , ONLY : TGMV
USE YOMGFL        , ONLY : TGFL
USE YOMCFU        , ONLY : TCFU
USE YOMXFU        , ONLY : TXFU
USE TYPE_MODEL    , ONLY : MODEL
USE PARFPOS       , ONLY : JPOSDYN
USE FULLPOS       , ONLY : TFPDATA
USE TYPE_FPOFN    , ONLY : TFPOFN
USE YOMVERT       , ONLY : TVAB
USE YOMOPH0       , ONLY : CFPEXTSFX
USE YOMFPC        , ONLY : LALLOFP, LTRACEFP, NFPCHKDAT, NFPSFXWRT, RWIDOM, LWIDER_DOM
USE YOM4FPOS      , ONLY : TRQFPDYN
USE YOMFPGEOMETRY , ONLY : LFPOSBUF
USE YOMFP4L       , ONLY : TRQFP, IFPSEARCH
USE YOMTIM        , ONLY : RSTART   ,RVSTART  ,RTIMEF
USE TYPE_FPRQDYNS , ONLY : TYPE_FPRQDYN, ALLOCATE_FPRQDYN, INQUIRE_FPRQDYN, DEALLOCATE_FPRQDYN
USE MFIOOPTS_MOD  , ONLY : MFIOOPTS, MFIOOPTS_GETOPTS
USE YOMIO_SERV    , ONLY : IO_SERV_C001
USE FACTX_MOD     , ONLY : FACTX, NEWFACTX, FREEFACTX
USE YOMAFN        , ONLY : TAFN
USE IOFLDDESC_MOD , ONLY : IOFLDDESC
USE TYPE_FPOSBUF  , ONLY : FPOSBUF
USE TYPE_FPRQPHYS , ONLY : ALLOCATE_FPRQPHY
USE SURFACE_FIELDS_MIX , ONLY : TSURF

IMPLICIT NONE

TYPE(TRQFPDYN)    , INTENT(IN) :: YDRQDYN
TYPE(TFPDATA)     , INTENT(IN) :: YDFPDATA
TYPE(TRQFP)       , INTENT(IN) :: YDRQPHY
LOGICAL           , INTENT(IN) :: LDFPLAG
LOGICAL           , INTENT(IN) :: LDOCE
LOGICAL           , INTENT(IN) :: LDCFU
LOGICAL           , INTENT(IN) :: LDXFU
TYPE(GEOMETRY)    , INTENT(IN) :: YDGEOMETRY
TYPE(TGMV)        , INTENT(IN) :: YDGMV
TYPE(TGFL)        , INTENT(IN) :: YDGFL
TYPE(TSURF)       , INTENT(IN) :: YDSURF
TYPE(TCFU)        , INTENT(IN) :: YDCFU
TYPE(TXFU)        , INTENT(IN) :: YDXFU
TYPE(MODEL)       , INTENT(IN) :: YDMODEL
REAL(KIND=JPRB),INTENT(IN), TARGET :: PCFUBUF(YDGEOMETRY%YRDIM%NPROMA,YDCFU%NFDCFU,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB),INTENT(IN), TARGET :: PXFUBUF(YDGEOMETRY%YRDIM%NPROMA,YDXFU%NFDXFU,YDGEOMETRY%YRDIM%NGPBLKS)
INTEGER(KIND=JPIM), INTENT(IN)   :: KCUFNR
REAL(KIND=JPRB), INTENT(IN)      :: PMCUFGP(YDGEOMETRY%YRDIM%NPROMA,KCUFNR,YDGEOMETRY%YRDIM%NGPBLKS)
INTEGER(KIND=JPIM), INTENT(IN)    :: KDATEF(:)
INTEGER(KIND=JPIM), INTENT(IN)    :: KITER
LOGICAL,            INTENT(IN), OPTIONAL :: LDINC
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KPPSTEP
REAL(KIND=JPRB),    INTENT(IN), OPTIONAL :: PTSTEP

TYPE(TYPE_FPRQDYN) :: YLQTYPE
TYPE(FPOSBUF)     :: YLAUX
TYPE(TFPOFN)      :: YLOFN(SIZE(YDFPDATA%YFPOS%YFPGEOMETRY%YFPUSERGEO))
TYPE(TRQFP) :: YLRQSFX
TYPE(TRQFP) :: YLRQSP
TYPE(TRQFP) :: YLRQGP
TYPE(MFIOOPTS)    :: YLIOOPTS
TYPE(FACTX)       :: YLFACTX(SIZE(YLOFN))
TYPE(IOFLDDESC), ALLOCATABLE :: YLFIODSC(:)

!     CLVER : Configuration for vertical post-processing
!     CLHOR : Configuration for horizontal post-processing
!     CLWFP : Configuration for I/Os

CHARACTER(LEN=1)  :: CLVER,CLHOR,CLWFP,CLSCAN,CLEVTYPE,CLIOCONF
CHARACTER(LEN=9)  :: CLOPDIS ! config displayed for opdis
CHARACTER(LEN=33) :: CLFMT0='(1X,''ARRAY '',A10,'' DEALLOCATED '')'

INTEGER(KIND=JPIM) :: IFIRST(0:1), ILAST(0:1), JKIND_OF_PP, ILMOD(JPOSDYN), IGPX(JPOSDYN)
INTEGER(KIND=JPIM) :: JSCAN, J, IFPDOM, IPPLEV, JOVERSCAN
INTEGER(KIND=JPIM) :: IPTRCFU, IPTRXFU, IXFIS
INTEGER(KIND=JPIM) :: IFLDPTRCFU(YDCFU%NFDCFU), IFLDPTRXFU(YDXFU%NFDXFU)
INTEGER(KIND=JPIM), ALLOCATABLE :: ICOD(:)
LOGICAL :: LLAG, LLOWPASS, LLPHYS, LLHPOS, LLEZO, LLPADDING, LLSURF, LLINC, LLSURFVER, LLSURFHOR, LLNHDYN
REAL(KIND=JPRD) :: ZCT, ZVT, ZWT
REAL(KIND=JPRB) :: ZWSXI, ZWDXI
REAL(KIND=JPRB), POINTER :: ZCFUBUF(:,:,:), ZXFUBUF(:,:,:), ZFPBUF(:,:,:), ZAUXBUF (:,:,:), ZABUF(:,:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPEC(:,:), ZPPLEV(:)

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "user_clock.intfb.h"

#include "sufpofname.intfb.h"
#include "maxgpfv.intfb.h"
#include "sufptr2.intfb.h"
#include "gridfpos.intfb.h"
#include "fpgpnorm.intfb.h"
#include "sufporog.intfb.h"
#include "fpmodcfu.intfb.h"
#include "fpmodxfu.intfb.h"
#include "fpmodprec.intfb.h"
#include "stepo_fpos_hv.intfb.h"
#include "stepo_fpos_hvlag.intfb.h"
#include "stepo_fpos_vh.intfb.h"
#include "lcheck4nhfields.intfb.h"
#include "suvpos.intfb.h"
#include "cpvpospr.intfb.h"
#include "opdis.intfb.h"
#include "espfp.intfb.h"
#include "fpspnorms.intfb.h"
#include "suvfposl.intfb.h"
#include "wrhfp.intfb.h"
#include "wrsfp.intfb.h"
#include "wrmlfp.intfb.h"
#include "wrplfp.intfb.h"
#include "ini2wrfp.intfb.h"
#include "abor1.intfb.h"

#include "fp2sx1.h"
#include "fp2sx2.h"
!      -----------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('ALLFPOS',0,ZHOOK_HANDLE)
ASSOCIATE(YDFPOS=>YDFPDATA%YFPOS)
ASSOCIATE(YDFPGEOMETRY=>YDFPOS%YFPGEOMETRY, YDFPFILTERS=>YDFPOS%YFPFILTERS, YDFPIOH=>YDFPOS%YFPIOH, YDAFN=>YDFPOS%YAFN, &
 & YDFPVAB=>YDFPOS%YFPVAB, YDFPSTRUCT=>YDFPOS%YFPSTRUCT, YDFPWSTD=>YDFPOS%YFPWSTD,YDFPCNT=>YDFPOS%YFPCNT, &
 & YDNAMFPSCI=>YDFPOS%YNAMFPSCI, YDNAMFPINT=>YDFPOS%YNAMFPINT, NFLEVG=>YDGEOMETRY%YRDIMV%NFLEVG)
ASSOCIATE(TFP=>YDAFN%TFP, TFP_DYNDS=>YDAFN%TFP_DYNDS, GFP_PHYDS=>YDAFN%GFP_PHYDS, GFP=>YDAFN%GFP, &
 & NSFXPRE_CNT=>YDAFN%NSFXPRE_CNT, NFPSURFEX=>YDNAMFPSCI%NFPSURFEX, NFPCLI=>YDNAMFPSCI%NFPCLI, LPUTZS=>YDNAMFPSCI%LPUTZS, &
 & YDFPGEO_DEP=>YDFPGEOMETRY%YFPGEO_DEP, YDFPGEO=>YDFPGEOMETRY%YFPGEO, YDFPGIND=>YDFPGEOMETRY%YFPGIND, &
 & YDFPUSERGEO=>YDFPGEOMETRY%YFPUSERGEO,YDFPOFN=>YDFPIOH%YFPOFN(:), YDFPOPH=>YDFPIOH%YFPOPH(:), &
 & YDNAMFPIOS=>YDFPIOH%YNAMFPIOS, NFPCONF=>YDFPCNT%NFPCONF, NFPINPHY=>YDNAMFPINT%NFPINPHY)
ASSOCIATE(NFPROMA=>YDFPGEO%NFPROMA, NFPBLOCS=>YDFPGEO%NFPBLOCS, NFPRGPL=>YDFPGEO%NFPRGPL, &
 & LFPOSHOR=>YDFPGEOMETRY%LFPOSHOR, LMPHYS=>YDMODEL%YRML_PHY_MF%YRPHY%LMPHYS, &
 & LEPHYS=>YDMODEL%YRML_PHY_EC%YREPHY%LEPHYS, NFPRESOL=>YDFPUSERGEO(:)%NFPRESOL,LFPCOORD=>YDFPUSERGEO(:)%LFPCOORD, &
 & LFPMAPF=>YDFPUSERGEO(:)%LFPMAPF, NFPRGPG=>YDFPGEO%NFPRGPG, NSPEC2=>YDFPUSERGEO(:)%NSPEC2, &
 & LFPMODELSPEC=>YDFPUSERGEO(:)%LFPMODELSPEC, LFPMODELGRID=>YDFPUSERGEO(:)%LFPMODELGRID, &
 & LFPMODELCORE=>YDFPUSERGEO(:)%LFPMODELCORE,NFPSIZEG=>YDFPUSERGEO(:)%NFPSIZEG,CFPDOM=>YDFPUSERGEO(:)%CFPDOM, &
 & NGPSIZPK=>YDFPOPH(:)%NGPSIZPK, NSPSIZPK=>YDFPOPH%NSPSIZPK, YDCLIMO=>YDFPDATA%YFPCLIMO, &
 & NFPDIGITS=>YDNAMFPIOS%NFPDIGITS, LFPPGDFWR=>YDNAMFPIOS%LFPPGDFWR, YDDYNA=>YDMODEL%YRML_DYN%YRDYNA,&
 & LFPHISFWR=>YDNAMFPIOS%LFPHISFWR, NSPEC2G=>YDFPUSERGEO(:)%NSPEC2G, &
 & NFPXFLD=>YDNAMFPIOS%NFPXFLD, NFPWRITE=>YDNAMFPIOS%NFPWRITE, NFPGRIB=>YDNAMFPIOS%NFPGRIB)

IFPDOM=SIZE(YLOFN)

IF (PRESENT(LDINC)) THEN
  LLINC=LDINC
ELSE
  LLINC=PRESENT(PTSTEP)
ENDIF
! Physical outputs
IF (NFPWRITE == 1) THEN
  IF (LLINC) THEN
    CALL SUFPOFNAME(YDFPOFN%CSH,CDFPFN=YLOFN%CSH,KSTEP=KPPSTEP,KDIGITS=NFPDIGITS,PTSTEP=PTSTEP)
    CALL SUFPOFNAME(YDFPOFN%CGG,CDFPFN=YLOFN%CGG,KSTEP=KPPSTEP,KDIGITS=NFPDIGITS,PTSTEP=PTSTEP)
    CALL SUFPOFNAME(YDFPOFN%CUA,CDFPFN=YLOFN%CUA,KSTEP=KPPSTEP,KDIGITS=NFPDIGITS,PTSTEP=PTSTEP)
  ELSE
    CALL SUFPOFNAME(YDFPOFN%CSH,CDFPFN=YLOFN%CSH,KSTEP=KPPSTEP,KDIGITS=NFPDIGITS)
    CALL SUFPOFNAME(YDFPOFN%CGG,CDFPFN=YLOFN%CGG,KSTEP=KPPSTEP,KDIGITS=NFPDIGITS)
    CALL SUFPOFNAME(YDFPOFN%CUA,CDFPFN=YLOFN%CUA,KSTEP=KPPSTEP,KDIGITS=NFPDIGITS)
  ENDIF
  IF (LARPEGEF) THEN
    CALL MFIOOPTS_GETOPTS (YLIOOPTS, IO_SERV_C001)
    DO J=1,IFPDOM 
      CALL NEWFACTX(YLFACTX(J),YLIOOPTS,KDOM=J)
      YLFACTX(J)%IDATEF(:)=KDATEF(:)
    ENDDO
  ENDIF
ENDIF
IF (NFPSURFEX /= 0) THEN
  ! output surfex filename. Should be made possible if nfpwrite=0
  IF (LLINC) THEN
    CALL SUFPOFNAME(YDFPOFN%CSX,CDFPFN=YLOFN%CSX,KSTEP=KPPSTEP,CDEXT=CFPEXTSFX,KDIGITS=NFPDIGITS,PTSTEP=PTSTEP)
  ELSE
    CALL SUFPOFNAME(YDFPOFN%CSX,CDFPFN=YLOFN%CSX,KSTEP=KPPSTEP,CDEXT=CFPEXTSFX,KDIGITS=NFPDIGITS)
  ENDIF
ENDIF

! LLHPOS tells if any horizontal post-processing is active(core or E-zone).
! (otherwise model-shaped buffer are used, meaning for LAM the E-zone is included)
! Somehow this is a hack :-(
LLHPOS=LFPOSBUF(YDFPGEOMETRY)
! Unfortunately, for now climatology is supported only through the horizontal
! interpolations mechanizm, so we should extend the activation of LLHPOS :
LLHPOS=LLHPOS.OR.(NFPCLI>0)
! Should only the truncation change, then LLHPOS could remain .false. But this
! mean going to apache via pos which is not yet re-coded. For now therefore we force LLHPOS=true
!(though the mechanism already works for surface-independent post-processing) :
LLHPOS=LLHPOS.OR.((.NOT.(ALL(LFPMODELSPEC(:)))).AND.NFPCONF==2)
! Alas again, if NFPCONF=1 there is no mechanism yet to transfer the output arrays from
! pos (gpp, hfpbuf) directly to the input arrays for fullpos I/Os (hfpbuf)
! so we should extend again the activation of LLHPOS :
LLHPOS=LLHPOS.OR.(NFPCONF==1)
! (However it would work exceptionally if no spectral fit).

! LLEZO : .TRUE. if an extension zone computation is active
LLEZO = ANY(YDFPUSERGEO(:)%LFPBIPER)

! Padding output fields in file to mask an output domain wider than the model domain
LLPADDING=LWIDER_DOM.AND..NOT.LLEZO

IF(LTRACEFP) THEN
  WRITE(UNIT=NULOUT,FMT='('' LLEZO = '',L2,'' LLHPOS = '',L2, '' LLPADDING = '',L2)') LLEZO, LLHPOS, LLPADDING
ENDIF


! Pre-processing : setup auxilary data post-processing
WRITE(NULOUT,'('' == Full-Pos : setup auxilary data == '')')
LLPHYS=LEPHYS.OR.LMPHYS
CALL SUFPTR2(YDRQPHY,YLAUX%YRQPHY,NFPINPHY,YDNAMFPSCI,YDAFN,LLPHYS,LLHPOS,LFPOSHOR,YDRQDYN)

IPTRCFU=0
IPTRXFU=0
ZCFUBUF=>PCFUBUF(:,:,:)
ZXFUBUF=>PXFUBUF(:,:,:)

IF (YDRQPHY%NFIELDG > 0 .OR. YLAUX%YRQPHY%NFIELDG > 0) THEN

!*  MODIFY PRECIPITATIONS FIELDS (a second copy may be avoided if we know if cfu/xfu are already copies)
!                                (case of packing) => inout allowed)

  IF (LFPOSHOR.AND.(LDCFU.OR.LDXFU)) THEN
    ALLOCATE(ICOD(YLAUX%YRQPHY%NFIELDG+YDRQPHY%NFIELDG))
    ICOD(1:YLAUX%YRQPHY%NFIELDG)=YLAUX%YRQPHY%ICOD(1:YLAUX%YRQPHY%NFIELDG)
    ICOD(YLAUX%YRQPHY%NFIELDG+1:YLAUX%YRQPHY%NFIELDG+YDRQPHY%NFIELDG)=YDRQPHY%ICOD(1:YDRQPHY%NFIELDG)
    IF (LDCFU) THEN
      CALL FPMODCFU(GFP,YDCFU,ICOD,NFLEVG,IPTRCFU,IFLDPTRCFU)
      IF (IPTRCFU > 0) THEN
        NULLIFY(ZCFUBUF)
        ALLOCATE(ZCFUBUF(YDGEOMETRY%YRDIM%NPROMA,YDCFU%NFDCFU,YDGEOMETRY%YRDIM%NGPBLKS))
        ZCFUBUF(:,:,:)=PCFUBUF(:,:,:)
        CALL FPMODPREC(YDFPSTRUCT,YDGEOMETRY,IPTRCFU,ZCFUBUF,IFLDPTRCFU)
      ENDIF
    ENDIF
    IF (LDXFU) THEN
      CALL FPMODXFU(GFP,YDXFU,ICOD,IPTRXFU,IFLDPTRXFU)
      IF (IPTRXFU > 0) THEN
        NULLIFY(ZXFUBUF)
        ALLOCATE(ZXFUBUF(YDGEOMETRY%YRDIM%NPROMA,YDXFU%NFDXFU,YDGEOMETRY%YRDIM%NGPBLKS))
        ZXFUBUF(:,:,:)=PXFUBUF(:,:,:)
        CALL FPMODPREC(YDFPSTRUCT,YDGEOMETRY,IPTRXFU,ZXFUBUF,IFLDPTRXFU)
      ENDIF
    ENDIF
  ENDIF

!*       3.1 COMPUTE INPUT MAX. VALUES RELATED TO SOIL MOISTURE

  IF (LMPHYS) THEN
    CALL MAXGPFV(YDGEOMETRY,YDSURF,ZWSXI,ZWDXI)
  ENDIF

ENDIF

!*       5. PERFORM POST-PROCESSING ON AUXILARY SURFACE FIELDS
!           --------------------------------------------------

ALLOCATE(YLAUX%FPBUF(NFPROMA,YLAUX%YRQPHY%NFIELDG,NFPBLOCS))

IF (YLAUX%YRQPHY%NFIELDG > 0) THEN

  ! Physical fields post-processing
  CALL GRIDFPOS(YLAUX%YRQPHY,YDNAMFPINT,YDNAMFPSCI,YDAFN,NFPXFLD,YDFPGEOMETRY,YDFPDATA,ZWSXI,ZWDXI,YDFPWSTD,YDFPSTRUCT,'G',LLEZO, &
   & IFPDOM,YDGEOMETRY,YDSURF,YDCFU,YDXFU,YDMODEL,ZCFUBUF,ZXFUBUF,ZAUXBUF,P2DFIELDS=YLAUX%FPBUF,KP3LEVS=0,KP3FIELDS=0)
  NULLIFY(ZAUXBUF)

!*       5.4 Spectral fit of interpolated orography

  IF (NFPCONF == 2 .AND. NFPCLI == 0) THEN
    IXFIS=IFPSEARCH(YLAUX%YRQPHY,GFP%SFIS%ICOD)
    IF (IXFIS > 0) THEN
      CALL SUFPOROG(YLAUX%YRQPHY%NFIELDG,IXFIS,YDFPGEO,IFPDOM,NFPRESOL,NSPEC2,YLAUX%FPBUF)
    ENDIF
  ENDIF

ENDIF


!*       6. PERFORM POST-PROCESSING ON MAIN SURFACE FIELDS
!           ----------------------------------------------


IF (NFPSURFEX == 1) THEN

  IF (NFPWRITE >= 0) THEN
    ! Norms of auxilary fields can be of some help for bug tracking
    IF (LARPEGEF) THEN
      CALL FPGPNORM(NFPXFLD,YDFPGEO,IFPDOM,CFPDOM,NFPRESOL,NFPSIZEG,PGP=YLAUX%FPBUF,LDSURF=YLAUX%YRQPHY%LLSURF, &
       & CDPREF=YLAUX%YRQPHY%CLPREF,KDOM=YLAUX%YRQPHY%IDOM,KDOMPTR=YLAUX%YRQPHY%IDMP,CDNAME=YLAUX%YRQPHY%CLNAME)
    ELSE
      CALL FPGPNORM(NFPXFLD,YDFPGEO,IFPDOM,CFPDOM,NFPRESOL,NFPSIZEG,PGP=YLAUX%FPBUF,LDSURF=YLAUX%YRQPHY%LLSURF, &
       & CDPREF=YLAUX%YRQPHY%CLPREF,KDOM=YLAUX%YRQPHY%IDOM,KDOMPTR=YLAUX%YRQPHY%IDMP,CDNAME=YLAUX%YRQPHY%CLNAME, &
       & KGRIB=YLAUX%YRQPHY%IGRIB)
    ENDIF
  ENDIF

  ! Subcontract some surface fields
  CALL FP2SX1(YLAUX%YRQPHY%NFIELDG,YLAUX%YRQPHY%ICOD,YDFPGEO,YLAUX%FPBUF,YDAFN,LFPPGDFWR,LFPHISFWR,NFPXFLD,IFPDOM, &
   & YDFPOPH,YDFPVAB,YDFPUSERGEO,YLOFN%CSX,KDATEF,YDFPOFN%CSU,YLFACTX,NFPCHKDAT,LPUTZS)

ELSEIF (NFPSURFEX == 2) THEN

  ! Specific pp step
  CALL ALLOCATE_FPRQPHY(GFP_PHYDS,YLRQSFX,IFPDOM,NSFXPRE_CNT,GFP%SFXPRE(1:NSFXPRE_CNT)%ICOD,NULOUT,LALLOFP)

  NULLIFY(ZFPBUF)

  CALL GRIDFPOS(YLRQSFX,YDNAMFPINT,YDNAMFPSCI,YDAFN,NFPXFLD,YDFPGEOMETRY,YDFPDATA,ZWSXI,ZWDXI,YDFPWSTD,YDFPSTRUCT,'S',LLEZO, &
   & IFPDOM,YDGEOMETRY,YDSURF,YDCFU,YDXFU,YDMODEL,ZCFUBUF,ZXFUBUF,ZFPBUF,KP3LEVS=0,KP3FIELDS=0)

  IF (NFPWRITE == 1) THEN
    CLIOCONF='I'
    ! Setup fields I/O descriptors
    ALLOCATE(YLFIODSC(YLRQSFX%NFIELDG))
    CALL INI2WRFP(YLRQSP,YLRQGP,YLRQSFX,CLIOCONF,LLPADDING,RWIDOM,.FALSE.,.FALSE.,YLRQSFX%NFIELDG,IFPDOM,NFPGRIB, &
     & TFP_DYNDS,GFP_PHYDS,YLFIODSC)
    YLFIODSC(:)%NSIZPK = SUM(NGPSIZPK(:))
    YLFIODSC(:)%NFLSZ  = SUM(NFPSIZEG(:))
    IF (NFPSFXWRT == 0) THEN
      CALL FP2SX2(YDFPGEO,IFPDOM,YDFPOPH,YDFPVAB,YDFPUSERGEO,NSFXPRE_CNT,YLOFN%CSX,KDATEF,YDFPOFN%CSU,NFPCHKDAT,ZFPBUF,YLFIODSC)
    ELSE
      CALL WRHFP(NFPXFLD,YDFPGEO,IFPDOM,YDFPOPH,YDFPVAB,YDFPUSERGEO,YLRQSFX%NFIELDG,CLIOCONF,YLOFN%CGG, &
       & NFPCHKDAT,LLPADDING,YLFIODSC,ZFPBUF,YLFACTX,PTSTEP)
    ENDIF
    DEALLOCATE(YLFIODSC)
  ENDIF

  IF (NFPWRITE >= 0) THEN
    CALL FPGPNORM(NFPXFLD,YDFPGEO,IFPDOM,CFPDOM,NFPRESOL,NFPSIZEG,PGP=ZFPBUF,LDSURF=YLRQSFX%LLSURF,&
     & CDPREF=YLRQSFX%CLPREF,KDOM=YLRQSFX%IDOM,KDOMPTR=YLRQSFX%IDMP,CDNAME=YLRQSFX%CLNAME)
  ENDIF

  IF (ASSOCIATED(ZFPBUF)) THEN
    DEALLOCATE(ZFPBUF)
    NULLIFY(ZFPBUF)
  ENDIF

ENDIF

! The test of NFPSURFEX below is WRONG shortcut : one can perform ISBA->Surfex conversion simultaneously with other physical pp.
! The test is kept for a while or it would create useless fields with the traditional namelists of "couplingsurf". REK
IF (NFPSURFEX /= 1 .AND. YDRQPHY%NFIELDG > 0) THEN

  NULLIFY(ZFPBUF)

  CALL GRIDFPOS(YDRQPHY,YDNAMFPINT,YDNAMFPSCI,YDAFN,NFPXFLD,YDFPGEOMETRY,YDFPDATA,ZWSXI,ZWDXI,YDFPWSTD,YDFPSTRUCT,'P',LLEZO, &
   & IFPDOM,YDGEOMETRY,YDSURF,YDCFU,YDXFU,YDMODEL,ZCFUBUF,ZXFUBUF,ZFPBUF, &
   & YDAUX=YLAUX,KP3LEVS=0,KP3FIELDS=0)

  ! Write out
  IF (NFPWRITE == 1) THEN
    CLIOCONF='I'
    IF (LARPEGEF) THEN
      ! Setup fields I/O descriptors
      ALLOCATE(YLFIODSC(YDRQPHY%NFIELDG))
      CALL INI2WRFP(YLRQSP,YLRQGP,YDRQPHY,CLIOCONF,LLPADDING,RWIDOM,.FALSE.,.FALSE.,YDRQPHY%NFIELDG,IFPDOM,NFPGRIB, &
       & TFP_DYNDS,GFP_PHYDS,YLFIODSC)
      YLFIODSC(:)%NSIZPK = SUM(NGPSIZPK(:))
      YLFIODSC(:)%NFLSZ  = SUM(NFPSIZEG(:))
      CALL WRHFP(NFPXFLD,YDFPGEO,IFPDOM,YDFPOPH,YDFPVAB,YDFPUSERGEO,YDRQPHY%NFIELDG,CLIOCONF,YLOFN%CGG, &
       & NFPCHKDAT,LLPADDING,YLFIODSC,ZFPBUF,YLFACTX,PTSTEP)
      DEALLOCATE(YLFIODSC)
    ELSE
      DO J=1,IFPDOM
        CALL WRMLFP(YLRQSP,YLRQGP,NFPRESOL(J),NSPEC2(J),NSPEC2G(J),NFPRGPL,NFPRGPG,NFPROMA,YDGEOMETRY,YDMODEL,YDSURF, &
         & YDMODEL%YRML_PHY_EC%YRECLDP,YDMODEL%YRML_PHY_EC%YREPHY, &
         & YDRQPHY,CLIOCONF,LDFPLAG,LDOCE,YLOFN(J),KPPSTEP,ZFPBUF,PTSTEP=PTSTEP)
      ENDDO
    ENDIF
  ENDIF

  IF (NFPWRITE >= 0) THEN
    ! Norms
    IF (LARPEGEF) THEN
      CALL FPGPNORM(NFPXFLD,YDFPGEO,IFPDOM,CFPDOM,NFPRESOL,NFPSIZEG,PGP=ZFPBUF,LDSURF=YDRQPHY%LLSURF, &
       & CDPREF=YDRQPHY%CLPREF,KDOM=YDRQPHY%IDOM,KDOMPTR=YDRQPHY%IDMP,CDNAME=YDRQPHY%CLNAME)
    ELSE
      CALL FPGPNORM(NFPXFLD,YDFPGEO,IFPDOM,CFPDOM,NFPRESOL,NFPSIZEG,PGP=ZFPBUF,LDSURF=YDRQPHY%LLSURF, &
       & CDPREF=YDRQPHY%CLPREF,KDOM=YDRQPHY%IDOM,KDOMPTR=YDRQPHY%IDMP,CDNAME=YDRQPHY%CLNAME, &
       & KGRIB=YDRQPHY%IGRIB)
    ENDIF
  ENDIF

  IF (ASSOCIATED(ZFPBUF)) THEN
    DEALLOCATE(ZFPBUF)
    NULLIFY(ZFPBUF)
  ENDIF

ENDIF

IF (IPTRCFU > 0) THEN
  DEALLOCATE(ZCFUBUF)
ELSE
  NULLIFY(ZCFUBUF)
ENDIF
IF (IPTRXFU > 0) THEN
  DEALLOCATE(ZXFUBUF)
ELSE
  NULLIFY(ZXFUBUF)
ENDIF

IF (.NOT.(LDFPLAG.OR.LDOCE)) THEN

!*       2. LOOP ON SCANS
!           -------------

  NULLIFY(ZABUF)

  ! A second may be needed if certain 2D fields have been missed.
  ! It should not be the case for a change of resolution (though ...)

  LLSURFVER=(NFPCONF /= 2)
  LLSURFHOR=.TRUE.

  ! Post-processing on surface-independent levels (P, PV, Theta)
  IFIRST(0)=1
  ILAST (0)=3
  ! Post-processing on surface-dependent levels (H, eta, T, F)
  IFIRST(1)=4
  ILAST (1)=7

  DO JOVERSCAN=1,2

  DO JKIND_OF_PP=0,1 

  IF (JOVERSCAN==2) THEN
    IF (.NOT.LLSURFVER.AND..NOT.LLSURFHOR) EXIT
  ENDIF

  DO JSCAN=IFIRST(JKIND_OF_PP),ILAST(JKIND_OF_PP)

  !*     2.1 INITIALIZE CONFIGURATION

    SELECT CASE(JSCAN)
    CASE(1)
      ! Pressure levels :
      CLSCAN='B'
      CLEVTYPE='p' 
      IPPLEV=YDRQDYN%YPR%NPXLEV
      ALLOCATE(ZPPLEV(IPPLEV))
      ZPPLEV(1:IPPLEV)=YDRQDYN%YPR%ZPXLEV(1:IPPLEV)
      CALL ALLOCATE_FPRQDYN(YLQTYPE,IFPDOM,IPPLEV)
      IF (LALLOFP) THEN
        CALL INQUIRE_FPRQDYN(YLQTYPE,'YLQTYPE',NULOUT)
      ENDIF
      CLVER='B'
      IF (.NOT.LLHPOS) THEN
        CLHOR='0'
      ELSE
        CLHOR='A'
      ENDIF
      LLOWPASS=ANY(YDFPFILTERS%LFPFIL(:))
      IF (JOVERSCAN==1) THEN
        IF (.NOT.LARPEGEF .AND. NFPCONF==0) THEN
          ! The following statement is there because of obscure historical reasons
          ! At ECMWF we can't store spectral fields as level type surface so some
          ! spectral fields (151 and 152) are arbitrarely stored at pressure level 1000mb
          LLSURF=.TRUE.
        ELSE
          LLSURF=LLSURFVER.AND.YDRQDYN%YPR%NPXLEV > 0
        ENDIF
        CALL SUVPOS(YLQTYPE,YDRQDYN%YPR,YDRQDYN%Y2D,YDAFN,NFPCONF,CLVER,CLHOR,LLSURF,LLOWPASS)
      ELSEIF (JOVERSCAN==2.AND.LLSURFVER) THEN
        LLSURF=.TRUE.
        CALL SUVPOS(YLQTYPE,YDRQDYN%YPR,YDRQDYN%Y2D,YDAFN,NFPCONF,CLVER,CLHOR,LLSURF,LLOWPASS)
      ENDIF
      IF (LLSURF) LLSURFVER=.FALSE.
      CLWFP='P'
    CASE(2)
      IF (JOVERSCAN==2) CYCLE ! extra scan only on P or eta or eta levels
      ! Potential vorticity levels :
      CLSCAN='V'
      CLEVTYPE='v' 
      IPPLEV=YDRQDYN%YPV%NPXLEV
      ALLOCATE(ZPPLEV(IPPLEV))
      ZPPLEV(1:IPPLEV)=YDRQDYN%YPV%ZPXLEV(1:IPPLEV)
      CALL ALLOCATE_FPRQDYN(YLQTYPE,IFPDOM,IPPLEV)
      IF (LALLOFP) THEN
        CALL INQUIRE_FPRQDYN(YLQTYPE,'YLQTYPE',NULOUT)
      ENDIF
      CLVER='V'
      IF (.NOT.LLHPOS) THEN
        CLHOR='0'
      ELSE
        CLHOR='A'
      ENDIF
      LLOWPASS=ANY(YDFPFILTERS%LFPFIL(:))
      LLSURF=LLSURFVER.AND.YDRQDYN%YPV%NPXLEV > 0
      CALL SUVPOS(YLQTYPE,YDRQDYN%YPV,YDRQDYN%Y2D,YDAFN,NFPCONF,CLVER,CLHOR,LLSURF,LLOWPASS)
      IF (LLSURF) LLSURFVER=.FALSE.
      CLWFP=CLSCAN
    CASE(3)
      IF (JOVERSCAN==2) CYCLE ! extra scan only on P or eta or eta levels
      ! Isentropic levels :
      CLSCAN='T'
      CLEVTYPE='t' 
      IPPLEV=YDRQDYN%YTH%NPXLEV
      ALLOCATE(ZPPLEV(IPPLEV))
      ZPPLEV(1:IPPLEV)=YDRQDYN%YTH%ZPXLEV(1:IPPLEV)
      CALL ALLOCATE_FPRQDYN(YLQTYPE,IFPDOM,IPPLEV)
      IF (LALLOFP) THEN
        CALL INQUIRE_FPRQDYN(YLQTYPE,'YLQTYPE',NULOUT)
      ENDIF
      CLVER='T'
      IF (.NOT.LLHPOS) THEN
        CLHOR='0'
      ELSE
        CLHOR='A'
      ENDIF
      LLOWPASS=ANY(YDFPFILTERS%LFPFIL(:))
      LLSURF=LLSURFVER.AND.YDRQDYN%YTH%NPXLEV > 0
      CALL SUVPOS(YLQTYPE,YDRQDYN%YTH,YDRQDYN%Y2D,YDAFN,NFPCONF,CLVER,CLHOR,LLSURF,LLOWPASS)
      IF (LLSURF) LLSURFVER=.FALSE.
      CLWFP=CLSCAN
    CASE(4)
      IF (JOVERSCAN==2) CYCLE ! extra scan only on P or eta levels
      ! Height levels :
      CLSCAN='H'
      CLEVTYPE='h' 
      IPPLEV=YDRQDYN%YHO%NPXLEV
      ALLOCATE(ZPPLEV(IPPLEV))
      ZPPLEV(1:IPPLEV)=YDRQDYN%YHO%ZPXLEV(1:IPPLEV)
      CALL ALLOCATE_FPRQDYN(YLQTYPE,IFPDOM,IPPLEV)
      IF (LALLOFP) THEN
        CALL INQUIRE_FPRQDYN(YLQTYPE,'YLQTYPE',NULOUT)
      ENDIF
      CLVER='H'
      IF (.NOT.LLHPOS) THEN
        CLHOR='0'
        LLOWPASS=ANY(YDFPFILTERS%LFPFIL(:))
        LLSURF=LLSURFVER.AND.YDRQDYN%YHO%NPXLEV > 0
        CALL SUVPOS(YLQTYPE,YDRQDYN%YHO,YDRQDYN%Y2D,YDAFN,NFPCONF,CLVER,CLHOR,LLSURF,LLOWPASS)
        IF (LLSURF) LLSURFVER=.FALSE.
      ELSE
        CLHOR='I'
        LLOWPASS=.FALSE.
        IF (JOVERSCAN==1) THEN
          LLSURF=LLSURFHOR.AND.YDRQDYN%YHO%NPXLEV > 0
          CALL SUVPOS(YLQTYPE,YDRQDYN%YHO,YDRQDYN%Y2D,YDAFN,NFPCONF,CLVER,CLHOR,LLSURF,LLOWPASS)
        ELSEIF (JOVERSCAN==2.AND.LLSURFHOR) THEN
          LLSURF=.TRUE.
          CALL SUVPOS(YLQTYPE,YDRQDYN%YHO,YDRQDYN%Y2D,YDAFN,NFPCONF,CLVER,CLHOR,LLSURF,LLOWPASS)
        ENDIF
        IF (LLSURF) LLSURFHOR=.FALSE.
      ENDIF
      CLWFP=CLSCAN
    CASE(5)
      IF (JOVERSCAN==2.AND..NOT.LLHPOS) CYCLE ! extra scan on eta levels only if horizontal interpolations.
      ! Eta levels :
      CLSCAN='S'
      CLEVTYPE='m' 
      IPPLEV=YDRQDYN%YES%NPXLEV
      ALLOCATE(ZPPLEV(IPPLEV))
      ZPPLEV(1:IPPLEV)=YDRQDYN%YES%ZPXLEV(1:IPPLEV)
      CALL ALLOCATE_FPRQDYN(YLQTYPE,IFPDOM,IPPLEV)
      IF (LALLOFP) THEN
        CALL INQUIRE_FPRQDYN(YLQTYPE,'YLQTYPE',NULOUT)
      ENDIF
      CLVER='S'
      IF (JOVERSCAN==1) THEN
        IF (.NOT.LLHPOS) THEN
          CLHOR='0'
          LLOWPASS=ANY(YDFPFILTERS%LFPFIL(:))
          IF (.NOT.LARPEGEF .AND. NFPCONF==0) THEN
            ! The following statement is there because of obscure recent reasons
            ! At ECMWF spectral surface pressure is expected twice :
            ! at an arbitrary pressure level 1000m and at a model level.
            LLSURF=.TRUE.
          ELSE
            LLSURF=LLSURFVER.AND.YDRQDYN%YES%NPXLEV > 0
          ENDIF
          CALL SUVPOS(YLQTYPE,YDRQDYN%YES,YDRQDYN%Y2D,YDAFN,NFPCONF,CLVER,CLHOR,LLSURF,LLOWPASS)
          IF (LLSURF) LLSURFVER=.FALSE.
        ELSE
          CLHOR='I'
          LLOWPASS=.FALSE.
          LLSURF=LLSURFHOR.AND.YDRQDYN%YES%NPXLEV > 0
          CALL SUVPOS(YLQTYPE,YDRQDYN%YES,YDRQDYN%Y2D,YDAFN,NFPCONF,CLVER,CLHOR,LLSURF,LLOWPASS)
          IF (LLSURF) LLSURFHOR=.FALSE.
        ENDIF
      ELSEIF (JOVERSCAN==2.AND.LLSURFHOR) THEN
        CLHOR='I'
        LLOWPASS=.FALSE.
        LLSURF=.TRUE.
        CALL SUVPOS(YLQTYPE,YDRQDYN%YES,YDRQDYN%Y2D,YDAFN,NFPCONF,CLVER,CLHOR,LLSURF,LLOWPASS)
        IF (LLSURF) LLSURFHOR=.FALSE.
      ENDIF
      CLWFP=CLSCAN
    CASE(6)
      IF (JOVERSCAN==2) CYCLE ! extra scan only on P or eta or eta levels
      ! isothermic levels :
      CLSCAN='K'
      CLEVTYPE='k' 
      IPPLEV=YDRQDYN%YIT%NPXLEV
      ALLOCATE(ZPPLEV(IPPLEV))
      ZPPLEV(1:IPPLEV)=YDRQDYN%YIT%ZPXLEV(1:IPPLEV)
      CALL ALLOCATE_FPRQDYN(YLQTYPE,IFPDOM,IPPLEV)
      IF (LALLOFP) THEN
        CALL INQUIRE_FPRQDYN(YLQTYPE,'YLQTYPE',NULOUT)
      ENDIF
      CLVER='K'
      IF (.NOT.LLHPOS) THEN
        CLHOR='0'
        LLOWPASS=ANY(YDFPFILTERS%LFPFIL(:))
        LLSURF=LLSURFVER.AND.YDRQDYN%YIT%NPXLEV > 0
        CALL SUVPOS(YLQTYPE,YDRQDYN%YIT,YDRQDYN%Y2D,YDAFN,NFPCONF,CLVER,CLHOR,LLSURF,LLOWPASS)
        IF (LLSURF) LLSURFVER=.FALSE.
      ELSE
        CLHOR='I'
        LLOWPASS=.FALSE.
        LLSURF=LLSURFHOR.AND.YDRQDYN%YIT%NPXLEV > 0
        CALL SUVPOS(YLQTYPE,YDRQDYN%YIT,YDRQDYN%Y2D,YDAFN,NFPCONF,CLVER,CLHOR,LLSURF,LLOWPASS)
        IF (LLSURF) LLSURFHOR=.FALSE.
      ENDIF
      CLWFP=CLSCAN
    CASE(7)
      IF (JOVERSCAN==2) CYCLE ! extra scan only on P or eta or eta levels
      ! Flight levels
      CLSCAN='F'
      CLEVTYPE='f' 
      IPPLEV=YDRQDYN%YFL%NPXLEV
      ALLOCATE(ZPPLEV(IPPLEV))
      ZPPLEV(1:IPPLEV)=YDRQDYN%YFL%ZPXLEV(1:IPPLEV)
      CALL ALLOCATE_FPRQDYN(YLQTYPE,IFPDOM,IPPLEV)
      IF (LALLOFP) THEN
        CALL INQUIRE_FPRQDYN(YLQTYPE,'YLQTYPE',NULOUT)
      ENDIF
      CLVER='F'
      IF (.NOT.LLHPOS) THEN
        CLHOR='0'
        LLOWPASS=ANY(YDFPFILTERS%LFPFIL(:))
        LLSURF=LLSURFVER.AND.YDRQDYN%YFL%NPXLEV > 0
        CALL SUVPOS(YLQTYPE,YDRQDYN%YFL,YDRQDYN%Y2D,YDAFN,NFPCONF,CLVER,CLHOR,LLSURF,LLOWPASS)
        IF (LLSURF) LLSURFVER=.FALSE.
      ELSE
        CLHOR='I'
        LLOWPASS=.FALSE.
        LLSURF=LLSURFHOR.AND.YDRQDYN%YFL%NPXLEV > 0
        CALL SUVPOS(YLQTYPE,YDRQDYN%YFL,YDRQDYN%Y2D,YDAFN,NFPCONF,CLVER,CLHOR,LLSURF,LLOWPASS)
        IF (LLSURF) LLSURFHOR=.FALSE.
      ENDIF
      CLWFP=CLSCAN
    END SELECT
    CALL CPVPOSPR(NFPCONF,YDAFN,YLQTYPE)

    IF (YLQTYPE%NFPDYNB > 0) THEN

  !*       2.2 POST-PROCESSING STEP

      CALL USER_CLOCK(PELAPSED_TIME=ZWT,PTOTAL_CP=ZCT,PVECTOR_CP=ZVT)
      ZCT=ZCT-RSTART
      ZVT=ZVT-RVSTART
      ZWT=ZWT-RTIMEF
      RSTART=RSTART+ZCT
      RVSTART=RVSTART+ZVT
      RTIMEF=RTIMEF+ZWT
      IF (LOPDIS) THEN
        CLOPDIS(1:9)='FULLPOS-'//CLVER
        CALL OPDIS(CLOPDIS,'DYNFPOS   ',ZCT,ZVT,ZWT,RSTART,RTIMEF,KITER,YDDYNA%LNHDYN)
      ENDIF

      NULLIFY(ZFPBUF)

      IF (CLHOR /= 'I') THEN
        CALL STEPO_FPOS_VH(YLQTYPE,YLAUX,YDCLIMO,YDNAMFPINT,YDNAMFPSCI,NFPXFLD,YDFPOS,IFPDOM,YDGEOMETRY,YDGMV,YDGFL, &
         & YDSURF,YDXFU,KCUFNR,PMCUFGP,YDMODEL,CLVER,CLHOR,IPPLEV,ZPPLEV,LLHPOS,LLEZO,ZFPBUF,ZSPEC,KP3FIELDS=0)
      ELSE
        IF (.NOT.ASSOCIATED(ZABUF)) THEN
          ! A bit awkward : we have to find in NH primitive fields on model levels 
          ! should be preprocessed and horizontally interpolated :
          LLNHDYN=YDDYNA%LNHDYN
          CALL LCHECK4NHFIELDS(LLNHDYN,TFP,YD3=YDRQDYN%YES,YD2=YDRQDYN%Y2D)
          CALL LCHECK4NHFIELDS(LLNHDYN,TFP,YD3=YDRQDYN%YHO)
          CALL LCHECK4NHFIELDS(LLNHDYN,TFP,YD3=YDRQDYN%YIT)
          CALL LCHECK4NHFIELDS(LLNHDYN,TFP,YD3=YDRQDYN%YFL)
          IF(LTRACEFP) THEN
            WRITE(UNIT=NULOUT,FMT='('' LFPNHDYN = '',L2)') LLNHDYN 
          ENDIF
          CALL STEPO_FPOS_HV(LLNHDYN,YDCLIMO,YDNAMFPINT,YDNAMFPSCI,NFPXFLD,YDFPOS,IFPDOM,YDGEOMETRY,YDGMV,YDGFL, &
           & YDSURF,YDXFU,KCUFNR,PMCUFGP,YDMODEL,LLHPOS,IGPX,LLEZO,ZABUF,ILMOD)
        ENDIF
        CALL STEPO_FPOS_HVLAG(ILMOD,YLQTYPE,YLAUX,YDCLIMO,YDNAMFPINT,YDNAMFPSCI,NFPXFLD,YDFPOS,IFPDOM,YDGEOMETRY, &
         & YDSURF,KCUFNR,YDMODEL,CLVER,IPPLEV,ZPPLEV,0,IGPX,ZABUF,ZFPBUF,ZSPEC)
      ENDIF

  !*       2.2 I/Os and computation of norms

  !   Allocate and initialize IO descriptors
      CALL SUVFPOSL(YLQTYPE,YLRQSP,YLRQGP,TFP_DYNDS(:)%IGRIB,TFP_DYNDS(:)%LLSRF,TFP_DYNDS(:)%CLNAME, &
       & IFPDOM,IPPLEV,ZPPLEV,NFPCONF,CLWFP)

  !   Unless there is a good reason for not doing it (like : re-entering data in
  !   model), the output mapping is applied for LAM :
      IF (LFPMODELSPEC(1) .AND. LFPMODELGRID(1) .AND. LFPMODELCORE(1) .AND. .NOT.LFPCOORD(1) .AND. LFPMAPF(1)) THEN
        IF (.NOT.ASSOCIATED(ZFPBUF)) THEN 
          CALL ABOR1('ALLFPOS : ZFPBUF SHOULD HAVE BEEN ALLOCATED ...')
        ENDIF
        CALL ESPFP(YLQTYPE,YDFPGEO,IFPDOM,NFPRESOL,NSPEC2,TFP_DYNDS(:)%IORDR,TFP_DYNDS(:)%CLNAME, &
         & YLRQGP%NFIELDG,YLRQSP%NFIELDL,YLRQSP%NFIELDG,ZFPBUF,ZSPEC)
      ENDIF

  !   Physical I/O
      IF (NFPWRITE == 1) THEN
        IF (LARPEGEF) THEN
          IF (YLRQSP%NFIELDG > 0) THEN
            ALLOCATE(YLFIODSC(YLRQSP%NFIELDG))
            CALL INI2WRFP(YLRQSP,YLRQGP,YDRQPHY,CLWFP,.FALSE.,RWIDOM,.TRUE.,.TRUE.,YLRQSP%NFIELDG,IFPDOM,NFPGRIB,TFP_DYNDS, &
             & GFP_PHYDS,YLFIODSC)
            YLFIODSC(:)%NSIZPK = SUM(NSPSIZPK(:))
            YLFIODSC(:)%NFLSZ  = SUM(NSPEC2G(:))
            CALL WRSFP(YLRQSP,IFPDOM,YDFPOPH,YDFPVAB,YDFPUSERGEO,ZSPEC,YLOFN%CSH,NFPCHKDAT,YLFIODSC,YLFACTX)
            DEALLOCATE(YLFIODSC)
          ENDIF
          IF (YLRQGP%NFIELDG > 0) THEN
            ALLOCATE(YLFIODSC(YLRQGP%NFIELDG))
            CALL INI2WRFP(YLRQSP,YLRQGP,YDRQPHY,CLWFP,LLPADDING,RWIDOM,.TRUE.,.FALSE.,YLRQGP%NFIELDG,IFPDOM,NFPGRIB,TFP_DYNDS, & 
             & GFP_PHYDS,YLFIODSC)
            YLFIODSC(:)%NSIZPK = SUM(NGPSIZPK(:))
            YLFIODSC(:)%NFLSZ  = SUM(NFPSIZEG(:))
            CALL WRHFP(NFPXFLD,YDFPGEO,IFPDOM,YDFPOPH,YDFPVAB,YDFPUSERGEO,YLRQGP%NFIELDG,CLWFP,YLOFN%CUA,NFPCHKDAT,LLPADDING, &
             & YLFIODSC,ZFPBUF,YLFACTX,PTSTEP)
            DEALLOCATE(YLFIODSC)
          ENDIF
        ELSE
          LLAG=.FALSE.
          DO J=1,IFPDOM
            IF (CLEVTYPE == 'm') THEN
              CALL WRMLFP(YLRQSP,YLRQGP,NFPRESOL(J),NSPEC2(J),NSPEC2G(J),NFPRGPL,NFPRGPG,NFPROMA,YDGEOMETRY,YDMODEL,YDSURF, &
               & YDMODEL%YRML_PHY_EC%YRECLDP,YDMODEL%YRML_PHY_EC%YREPHY, &
               & YDRQPHY,CLEVTYPE,LLAG,LDOCE,YLOFN(J),KPPSTEP,ZFPBUF,PTSTEP=PTSTEP,PSPEC=ZSPEC)
            ELSE
              CALL WRPLFP(YLRQSP,YLRQGP,NFPRESOL(J),NSPEC2(J),NSPEC2G(J),NFPRGPL,NFPROMA,YDGEOMETRY,YDMODEL,YLOFN(J), &
               & ZFPBUF,ZSPEC,CLEVTYPE,PTSTEP)
            ENDIF
          ENDDO
        ENDIF
      ENDIF

      IF (NFPWRITE >= 0) THEN
        ! SPECTRAL NORMS
        IF (YLRQSP%NFIELDG > 0) THEN
          IF (LARPEGEF) THEN
            CALL FPSPNORMS(NFPRESOL,PSPEC=ZSPEC,KVSET=YLRQSP%IVSETG,LDSURF=YLRQSP%LLSURF,CDPREF=YLRQSP%CLPREF, &
             & PLEV=YLRQSP%ZLEV,CDNAME=YLRQSP%CLNAME,CDCONF=CLWFP)
          ELSE
            CALL FPSPNORMS(NFPRESOL,PSPEC=ZSPEC,KVSET=YLRQSP%IVSETG,LDSURF=YLRQSP%LLSURF,CDPREF=YLRQSP%CLPREF, &
             & PLEV=YLRQSP%ZLEV,CDNAME=YLRQSP%CLNAME,KGRIB=YLRQSP%IGRIB,CDCONF=CLWFP)
          ENDIF
        ENDIF
        ! GRIDPOINT NORMS
        IF (YLRQGP%NFIELDG > 0) THEN
          IF (LARPEGEF) THEN
            CALL FPGPNORM(NFPXFLD,YDFPGEO,IFPDOM,CFPDOM,NFPRESOL,NFPSIZEG,PGP=ZFPBUF,LDSURF=YLRQGP%LLSURF, &
             & CDPREF=YLRQGP%CLPREF,PLEV=YLRQGP%ZLEV,KDOM=YLRQGP%IDOM,KDOMPTR=YLRQGP%IDMP,CDNAME=YLRQGP%CLNAME, &
             & CDCONF=CLWFP)
          ELSE
            CALL FPGPNORM(NFPXFLD,YDFPGEO,IFPDOM,CFPDOM,NFPRESOL,NFPSIZEG,PGP=ZFPBUF,LDSURF=YLRQGP%LLSURF, &
             & CDPREF=YLRQGP%CLPREF,PLEV=YLRQGP%ZLEV,KDOM=YLRQGP%IDOM,KDOMPTR=YLRQGP%IDMP,CDNAME=YLRQGP%CLNAME, &
             & KGRIB=YLRQGP%IGRIB,CDCONF=CLWFP)
          ENDIF
        ENDIF
      ENDIF

  !   Deallocate descriptors
      CALL SUVFPOSL(YLQTYPE,YLRQSP,YLRQGP,TFP_DYNDS(:)%IGRIB,TFP_DYNDS(:)%LLSRF,TFP_DYNDS(:)%CLNAME,IFPDOM,IPPLEV,ZPPLEV)

  !   Deallocate output data arrays

      IF (ALLOCATED(ZSPEC)) THEN
        DEALLOCATE(ZSPEC)
        IF (LALLOFP) WRITE(NULOUT,CLFMT0) 'ZSPEC    '
      ENDIF

      IF (ASSOCIATED(ZFPBUF)) THEN
        DEALLOCATE(ZFPBUF)
        NULLIFY(ZFPBUF)
      ENDIF

    ENDIF ! NFPDYNB >0

    DEALLOCATE(ZPPLEV)
    CALL DEALLOCATE_FPRQDYN(YLQTYPE)


  ENDDO ! JSCAN

  ENDDO ! JKIND_OF_PP

  ENDDO ! JOVERSCAN

  IF (ASSOCIATED(ZABUF)) THEN
    DEALLOCATE(ZABUF)
    NULLIFY(ZABUF)
  ENDIF

ENDIF

IF (NFPWRITE == 1) THEN
  IF (LARPEGEF) THEN
    DO J=1,IFPDOM
      CALL FREEFACTX(YLFACTX(J))
    ENDDO
  ENDIF
ENDIF

END ASSOCIATE
END ASSOCIATE
END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('ALLFPOS',1,ZHOOK_HANDLE)
!      -----------------------------------------------------------------
END SUBROUTINE ALLFPOS
