! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE CNT3_GLO(YDGEOMETRY,YDFIELDS,YDMTRAJ,YDMODEL,YDJOT,YDVARBC,YDTCV,KINITMONTH,YDGOM5,YDODB)

!**** *CNT3_GLO*  - CNT3 code for global model

!     Author.
!     -------
!      Philippe Marguinaud *METEO-FRANCE*
!      Original : 15-04-2016
!      Modifications:
!        F.Suzat apr 2018 YDGOM5 by argument
!     -------------
!     P. de Rosnay December 2017 SEKF-EDA jacobians

USE TYPE_MODEL   , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE FIELDS_MOD   , ONLY : FIELDS
USE MTRAJ_MOD    , ONLY : MTRAJ
USE PARKIND1     , ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMCT0       , ONLY : NCONF, LNF, LOBSC1
USE YOMINI       , ONLY : LDFI
USE YOMVAR       , ONLY : LINITCV
USE YOMLCZ       , ONLY : GPFORCEU, GPFORCEV, GPFORCET, GPFORCEQ, GPFORCESP
USE VARBC_CLASS  , ONLY : CLASS_VARBC
USE JO_TABLE_MOD , ONLY : JO_TABLE
USE YOMSEKF      , ONLY : LUSE_EDA_JACOB
USE TOVSCV_MOD   , ONLY : TOVSCV
USE SPECTRAL_FIELDS_MOD
USE SUPERGOM_CLASS     , ONLY : CLASS_SUPERGOM
USE DBASE_MOD    , ONLY : DBASE
!      -----------------------------------------------------------

IMPLICIT NONE

TYPE (GEOMETRY)              , INTENT(INOUT) :: YDGEOMETRY
TYPE (FIELDS)                , INTENT(INOUT) :: YDFIELDS
TYPE (MTRAJ)                 , INTENT(INOUT) :: YDMTRAJ
TYPE(MODEL)                  , INTENT(INOUT) :: YDMODEL
TYPE(JO_TABLE)               , INTENT(INOUT) :: YDJOT
TYPE (CLASS_VARBC),  OPTIONAL, INTENT(INOUT) :: YDVARBC
TYPE(CLASS_SUPERGOM),OPTIONAL, INTENT(INOUT) :: YDGOM5
CLASS(DBASE)        ,OPTIONAL, INTENT(INOUT) :: YDODB
TYPE(TOVSCV), OPTIONAL      , INTENT(IN)     :: YDTCV
INTEGER(KIND=JPIM), OPTIONAL, INTENT(IN)     :: KINITMONTH
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
!      -----------------------------------------------------------

#include "csta.intfb.h"
#include "reresf_part1.intfb.h"
#include "reresf_part2.intfb.h"
#include "spnorm.intfb.h"




#include "updo3ch.intfb.h"
#include "updrgas.intfb.h"



#include "dfi.intfb.h"
#include "ininemo.intfb.h"
#include "coupinfout.intfb.h"

!      -----------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('CNT3_GLO',0,ZHOOK_HANDLE)

!*     3.1   Spherical geometry

! * restart and some other operations:
IF (NCONF == 1.OR.NCONF == 302) THEN
  CALL RERESF_PART1 (YDGEOMETRY, YDFIELDS, YDMODEL)
  CALL RERESF_PART2 (YDGEOMETRY, YDFIELDS, YDMODEL)
! SETUP OZONE CHEMISTRY IN CASE OF RESTART
  IF(.NOT.LNF.AND.YDMODEL%YRML_PHY_EC%YREPHY%LEO3CH) THEN
    CALL UPDO3CH(YDGEOMETRY,YDMODEL%YRML_DYN%YRDYNA,YDMODEL%YRML_CHEM%YROZO,YDMODEL%YRML_PHY_EC%YREPHY,YDMODEL%YRML_PHY_G%YRDPHY,YDMODEL%YRML_GCONF%YRRIP)
  ENDIF
  IF(.NOT.LNF.AND.YDMODEL%YRML_PHY_RAD%YRERAD%LHGHG) THEN
    CALL UPDRGAS(YDMODEL%YRML_DYN%YRDYNA,YDMODEL%YRML_PHY_RAD%YRERAD,&
     & YDMODEL%YRML_PHY_RAD%YRERDI,YDMODEL%YRML_GCONF%YRRIP)
  ENDIF
ELSE
  LNF=.TRUE.
ENDIF

! * start:
IF (LNF) THEN
  IF (YDMODEL%YRML_PHY_STOCH%YRSTOPH%LFORCENL) THEN
    CALL SUFORCE(YDGEOMETRY,YDFIELDS,YDMTRAJ,YDMODEL)
  ELSE
    IF(ALLOCATED(GPFORCEU))  DEALLOCATE(GPFORCEU)
    IF(ALLOCATED(GPFORCEV))  DEALLOCATE(GPFORCEV)
    IF(ALLOCATED(GPFORCET))  DEALLOCATE(GPFORCET)
    IF(ALLOCATED(GPFORCEQ))  DEALLOCATE(GPFORCEQ)
    IF(ALLOCATED(GPFORCESP)) DEALLOCATE(GPFORCESP)
    ALLOCATE(GPFORCEU(1,1,1,YDMODEL%YRML_GCONF%YRRIP%NSTART:1))
    ALLOCATE(GPFORCEV(1,1,1,YDMODEL%YRML_GCONF%YRRIP%NSTART:1))
    ALLOCATE(GPFORCET(1,1,1,YDMODEL%YRML_GCONF%YRRIP%NSTART:1))
    ALLOCATE(GPFORCEQ(1,1,1,YDMODEL%YRML_GCONF%YRRIP%NSTART:1))
    ALLOCATE(GPFORCESP(1,1,YDMODEL%YRML_GCONF%YRRIP%NSTART:1))
  ENDIF
  CALL CSTA(YDGEOMETRY,YDFIELDS,YDMODEL,KINITMONTH)
ENDIF

! * perturb initial conditions for the SEKF run:
IF (NCONF == 302.and. .NOT.LUSE_EDA_JACOB) THEN
  CALL PERTSEKF_V2(YDGEOMETRY,YDFIELDS%YRSURF)
ENDIF

!* NEMO initialization.
IF (YDMODEL%YRML_AOC%YRMCC%LNEMOCOUP) CALL ININEMO(YDGEOMETRY,YDFIELDS%YRSURF,YDMODEL%YRML_AOC%YRMCC,YDMODEL%YRML_GCONF%YRRIP)

!* Optional coupling write out coupling informaion
IF (YDMODEL%YRML_AOC%YRMCC%LCOUPINFOUT) CALL COUPINFOUT(YDGEOMETRY,YDFIELDS%YRSURF,YDMODEL%YRML_AOC%YRMCC,YDMODEL%YRML_GCONF%YRRIP)
! * Jc computation: all computation in CNT3_GLO.

IF(LNF) CALL SPNORM(YDGEOMETRY,YDMODEL%YRML_GCONF,YDMODEL%YRML_DYN%YRDYNA,YDFIELDS%YRSPEC)

! * Jg computation: all computation in CNT3AD.

! * digital filter initialisation:
IF (LNF.AND.LDFI) CALL DFI(YDGEOMETRY,YDFIELDS,YDMTRAJ,YDMODEL,YDVARBC=YDVARBC,YDTCV=YDTCV,YDJOT=YDJOT,YDGOM5=YDGOM5,YDODB=YDODB)


!     ------------------------------------------------------------------


IF (LHOOK) CALL DR_HOOK('CNT3_GLO',1,ZHOOK_HANDLE)

END SUBROUTINE CNT3_GLO
