! (C) Copyright 1989- Meteo-France.

SUBROUTINE SUFPC(CDPATH,LDNAMELIST,LDPRINT,LDMODULE,YDNAMFPOBJ,YDNAMFPL,YDNAMFPSCI,YDNAMFPINT,KFPCONF)

!**** *SUFPC*  - INITIALIZE FULL POST PROCESSING (scientif. and techn. options)

!     PURPOSE.
!     --------
!        SETS DEFAULT VALUES, THEN READS NAMELIST NAMFPC AND CHECKS IT.

!**   INTERFACE.
!     ----------
!       *CALL* *SUFPC(...)

!        EXPLICIT ARGUMENTS  
!         -------------------
!           CDPATH     : PATH NAME OF NAMELIST FILE IF CDPATH IS ABSENT, FILE NULNAM IS READ
!           LDNAMELIST : concatenated namelist file
!           LDPRINT    : .TRUE. to print out
!           LDMODULE   : .TRUE. to initialize variables kept in module (shared by all objects)
!           YDNAMFPL   : fields request (structure)
!           YDNAMFPSCI : scientific aspects
!           YDNAMFPINT : parameters driving the horizontal interpolations
!           YDNAMFPOBJ : parameters needed to control different objects simultaneously
!           KFPCONF    : general configuration of the post-processor (object-dependent !)

!        IMPLICIT ARGUMENTS
!        --------------------

!     METHOD.
!     -------
!        SEE DOCUMENTATION

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     AUTHOR.
!     -------
!      RYAD EL KHATIB *METEO-FRANCE*
!      ORIGINAL : 94-04-08

!     MODIFICATIONS.
!     --------------
!    R. El Khatib : 01-05-07 control HUn,HUx
!    R. El Khatib : 01-06-14 LFPLAKE => NFPLAKE
!    R. El Khatib : 01-08-07 Pruning options
!    R. El Khatib : 02-21-20 Fullpos B-level distribution + remove IO scheme
!    R. El Khatib : 03-08-25 gfl
!    O.Spaniel    : 03-04-15 cleaning - a same named entity from modules
!    R. El Khatib : 03-04-17 Fullpos improvments
!    R. El Khatib : 03-09-03 LTRACEFP active per default if not LECMWF
!    M.Hamrud      01-Oct-2003 CY28 Cleaning
!    D. Paradis & R. El Khatib : 04-07-22 GRIBEX
!    G. Hello     : 05-04-25 lground specificities (Arome + ee927)
!    R. El Khatib : 05-03-23 NFPSURFEX NFPMASK
!    S. Serrar    : 05-06-23 GFP_PHYDS include parameters from table 210
!    Y. Seity     : 06-07-10 LMSE = T in case NFPSURFEX=1
!    R. El Ouaraini : 03-Oct-2006 NFPGRIB= -1,0,1,2,3 (Before: NFPGRIB=0,1,2,3)
!    Y. Seity     : 07-03-06 Tests if LNEIGE for Graupel and Hail.
!    F. Bouyssel  : 08-02-15 LPUTZS
!    P. Marquet   : 09-01-16 (RENTR->RENTRA by ??) ; allow NFPCAPE=5 ;
!                            print the final value for RENTRA
!    K.Maynard    : 09-07-01 LFPISOPV new diagnostic of iso-PV level
!                            NITERPV nb of vertical iter for this diagnostic
!    F. Bouyssel  : 09-07-15 LFPCAPEX
!    K. Yessad (Aug 2009): add FPRHMAX et FPRHMIN.
!    G. Kerdraon  : 10-09-02 add L_READ_MODEL_DATE
!    K. Yessad (oct 2010): multi-linear interpolations, organigramme simplification.
!    T. Aspelien  : 11-04-11 Add LCRITSNOWTEMP
!      R. El Khatib : 01-Mar-2012 (LFPOS,LFPSPEC) => NFPOS
!    D. Degrauwe (Feb 2012) : Boyd periodization
!    R. El Khatib : 19-Jul-2012 LFIT* => NFIT* + NFITH, NFITS + control with NFPOS
!                               Control of CFPFMT with NFPOS
!      R. El Khatib 17-Jul-2013 FABEC post-processing
!      R. El Khatib 27-Sep-2013 Flexible location of biperiodicization (temporary)
!      R. El Khatib 17-Apr-2014 Split to sufpc + sufp_ctl
!      R. El Khatib 16-May-2014 Fix the value of NFITI
!      R. El Khatib 27-Jun-2014 Disable LRAW_BIPER=.T. (does not work properly)
!      P. Towers    13-Nov-2014 Add logic for a concatenated namelist
!      R. El Khatib : 07-Mar-2016 protection against simultaneous write of dirlst to disk
!      R. El Khatib 08-Dec-2015 Interoperability GRIB2 vs FA
!      R. El Khatib 27-Jul-2016 move NFPSLWIDE to NAMFPSC2
!      R. El Khatib 09-Aug-2016 Cleanings 
!      R. El Khatib 09-Sep-2016 Interoperability options (incl. LCRITSNOWTEMP)
!      R. El Khatib 13-Sep-2017 Interoperability Surfex -> ISBA (following Bouyssel, Fischer & Degrauwe, 2017)
!      R. El Khatib 10-Jul-2018 bugfix against CDPATH being re-opened by another LUN than NULNAM (OOPS side effect)
!      R. El Khatib 29-Aug-2018 KFPCONF (support of multiple post-processing objects of different configurations)
!     ------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK

USE YOMLUN   , ONLY : NULOUT   ,NULNAM   ,NPPPSH
USE PARFPOS  , ONLY : JPOSLEN, JPOSDOM, JPOSDIR
USE YOMFPC   , ONLY : TNAMFPL, TNAMFPSCI, TNAMFPINT, TNAMFPOBJ, LTRACEFP ,LALLOFP ,L_READ_MODEL_DATE, LFPPACKING, LFPMOIS, &
 & LWIDER_DOM, NFPCHKDAT, NFPSFXWRT, RWIDOM, LOCEDELAY
USE YOMCT0   , ONLY : LECMWF   ,LELAM    ,NFPOS, LARPEGEF, NPOSTS, NPOSTSMIN, NFRPOS
USE YOMARG   , ONLY : NGRIBFILE, NSUPERSEDE
USE YOMFA    , ONLY : NVGRIB

!     ------------------------------------------------------------------

IMPLICIT NONE

CHARACTER(LEN=*)  , INTENT(IN), OPTIONAL :: CDPATH
LOGICAL           , INTENT(IN), OPTIONAL :: LDNAMELIST
LOGICAL           , INTENT(IN), OPTIONAL :: LDPRINT
LOGICAL           , INTENT(IN), OPTIONAL :: LDMODULE
TYPE(TNAMFPL)     , INTENT(OUT), OPTIONAL :: YDNAMFPL
TYPE(TNAMFPSCI)   , INTENT(OUT), OPTIONAL :: YDNAMFPSCI
TYPE(TNAMFPINT)   , INTENT(OUT), OPTIONAL :: YDNAMFPINT
TYPE(TNAMFPOBJ)   , INTENT(OUT), OPTIONAL :: YDNAMFPOBJ
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KFPCONF

!     ------------------------------------------------------------------

CHARACTER(LEN=1024) :: CLFILE

! IFPFILMAX : maximum filter level (according to the configuration)
!             1 : spectral fit only
!             2 : gaussian filter in spectral space
!             3 : low-pass filter in spectral space

INTEGER(KIND=JPIM) :: IERR, IWARN, J, JJ, IFPFILMAX, ICONF
TYPE(TNAMFPL), TARGET :: YLNAMFPL
TYPE(TNAMFPSCI), TARGET :: YLNAMFPSCI
TYPE(TNAMFPINT), TARGET :: YLNAMFPINT
TYPE(TNAMFPOBJ), TARGET :: YLNAMFPOBJ

LOGICAL :: LLPPNAMELIST, LLPRINT, LMOCONVAR, LLMODULE, LLOPENED

! namelist variables becoming pointers, targetting a structure

! TNAMFPL
REAL(KIND=JPRB), POINTER :: RFP3P(:)
REAL(KIND=JPRB), POINTER :: RFP3H(:)
REAL(KIND=JPRB), POINTER :: RFP3TH(:)
REAL(KIND=JPRB), POINTER :: RFP3PV(:)
REAL(KIND=JPRB), POINTER :: RFP3I(:)
REAL(KIND=JPRB), POINTER :: RFP3F(:)
INTEGER(KIND=JPIM), POINTER :: NRFP3S(:)
INTEGER(KIND=JPIM), POINTER :: NFP3DFP
INTEGER(KIND=JPIM), POINTER :: NFP3DFH
INTEGER(KIND=JPIM), POINTER :: NFP3DFT
INTEGER(KIND=JPIM), POINTER :: NFP3DFV
INTEGER(KIND=JPIM), POINTER :: NFP3DFI
INTEGER(KIND=JPIM), POINTER :: NFP3DFF
INTEGER(KIND=JPIM), POINTER :: NFP3DFS
INTEGER(KIND=JPIM), POINTER :: MFP3DFP(:)
INTEGER(KIND=JPIM), POINTER :: MFP3DFH(:)
INTEGER(KIND=JPIM), POINTER :: MFP3DFT(:)
INTEGER(KIND=JPIM), POINTER :: MFP3DFV(:)
INTEGER(KIND=JPIM), POINTER :: MFP3DFI(:)
INTEGER(KIND=JPIM), POINTER :: MFP3DFF(:)
INTEGER(KIND=JPIM), POINTER :: MFP3DFS(:)
INTEGER(KIND=JPIM), POINTER :: NFP2DF
INTEGER(KIND=JPIM), POINTER :: NFPPHY
INTEGER(KIND=JPIM), POINTER :: MFP2DF(:)
INTEGER(KIND=JPIM), POINTER :: MFPPHY(:)
CHARACTER(LEN=16), POINTER :: CFPCFU(:)
CHARACTER(LEN=16), POINTER :: CFPXFU(:)
CHARACTER(LEN=16), POINTER :: CFPPHY(:)
CHARACTER(LEN=12), POINTER :: CFP3DF(:)
CHARACTER(LEN=16), POINTER :: CFP2DF(:)

! TNAMFPSCI
INTEGER(KIND=JPIM), POINTER :: NFPSURFEX
INTEGER(KIND=JPIM), POINTER :: NFPBOYD
REAL(KIND=JPRB), POINTER :: RFPBSCAL
LOGICAL           , POINTER :: LFPCAPEX
INTEGER(KIND=JPIM), POINTER :: NFPCLI
INTEGER(KIND=JPIM), POINTER :: NFPLAKE
INTEGER(KIND=JPIM), POINTER :: NFPMASK
INTEGER(KIND=JPIM), POINTER :: NFPSWI
INTEGER(KIND=JPIM), POINTER :: NFPCAPE
REAL(KIND=JPRB), POINTER :: RFPVCAP
LOGICAL, POINTER :: LFPISOPV
INTEGER(KIND=JPIM), POINTER :: NITERPV
REAL(KIND=JPRB), POINTER :: RENTRA
REAL(KIND=JPRB), POINTER :: FPRHMIN
REAL(KIND=JPRB), POINTER :: FPRHMAX
LOGICAL, POINTER :: LSATURCAP
LOGICAL, POINTER :: LFITBETWEEN
LOGICAL, POINTER :: LFPQ
LOGICAL, POINTER :: LFPLOSP
LOGICAL, POINTER :: LFPRH100
LOGICAL, POINTER :: LPUTZS
LOGICAL, POINTER :: LFPCLSTOGMV
LOGICAL, POINTER :: LCRITSNOWTEMP
LOGICAL, POINTER :: LCLIMALBEDOS
LOGICAL, POINTER :: LCLIMAEROSOL
LOGICAL, POINTER :: LCLIMOZONE
LOGICAL, POINTER :: LISOT_ABOVEG
REAL(KIND=JPRB), POINTER :: TSRESERV1
REAL(KIND=JPRB), POINTER :: TSRESERV2
REAL(KIND=JPRB), POINTER :: TDELTA1
REAL(KIND=JPRB), POINTER :: TDELTA2
REAL(KIND=JPRB), POINTER :: RWPITPN
REAL(KIND=JPRB), POINTER :: RWPITPX
REAL(KIND=JPRB), POINTER :: RSNSTPN
REAL(KIND=JPRB), POINTER :: RSNSTPX
REAL(KIND=JPRB), POINTER :: RSNSMOD
REAL(KIND=JPRB), POINTER :: RFPCORR
REAL(KIND=JPRB), POINTER :: RFPCSAB
REAL(KIND=JPRB), POINTER :: RFPCD2

REAL(KIND=JPRB), POINTER :: RSRHH
REAL(KIND=JPRB), POINTER :: RSTRMMH

INTEGER(KIND=JPIM), POINTER :: NFITP
INTEGER(KIND=JPIM), POINTER :: NFITT
INTEGER(KIND=JPIM), POINTER :: NFITV
INTEGER(KIND=JPIM), POINTER :: NFITI
INTEGER(KIND=JPIM), POINTER :: NFITF
INTEGER(KIND=JPIM), POINTER :: NFITH
INTEGER(KIND=JPIM), POINTER :: NFITS
INTEGER(KIND=JPIM), POINTER :: NSPFILP
INTEGER(KIND=JPIM), POINTER :: NSPFILT
INTEGER(KIND=JPIM), POINTER :: NSPFILV
INTEGER(KIND=JPIM), POINTER :: NSPFILI
INTEGER(KIND=JPIM), POINTER :: NSPFILF
INTEGER(KIND=JPIM), POINTER :: NSPFILH
INTEGER(KIND=JPIM), POINTER :: NSPFILS
INTEGER(KIND=JPIM), POINTER :: NSPFIL2

! TNAMFPINT
LOGICAL, POINTER :: LFPML_STD
LOGICAL, POINTER :: LFPML_LAN
LOGICAL, POINTER :: LFPML_SEA
INTEGER(KIND=JPIM), POINTER :: NFPINDYN
INTEGER(KIND=JPIM), POINTER :: NFPINPHY
INTEGER(KIND=JPIM), POINTER :: NFPSFXINT
REAL(KIND=JPRB), POINTER :: RFPCR_STD(:)
REAL(KIND=JPRB), POINTER :: RFPCR_LAN(:)
REAL(KIND=JPRB), POINTER :: RFPCR_SEA(:)

! TNAMFPOBJ
CHARACTER(LEN=5), POINTER :: CFPFMT
CHARACTER(LEN=JPOSLEN), POINTER :: CFPDOM(:)
CHARACTER(LEN=JPOSDIR), POINTER :: CFPDIR
CHARACTER(LEN=180), POINTER :: CFPMONIPATH_IN
CHARACTER(LEN=180), POINTER :: CFPMONIPATH_OUT
INTEGER(KIND=JPIM), POINTER :: NFPGRIB
INTEGER(KIND=JPIM), POINTER :: NFPOSTS(:)
INTEGER(KIND=JPIM), POINTER :: NFPOSTSMIN(:)
INTEGER(KIND=JPIM), POINTER :: NFRFPOS

!   --------------------------------------------------------------------------------------------

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

#include "abor1.intfb.h"
#include "posnam.intfb.h"

!     ------------------------------------------------------------------
#include "namfpc.nam.h"
!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('SUFPC',0,ZHOOK_HANDLE)
!     ------------------------------------------------------------------

!*       1. SET NAMELIST POINTERS TO THE NAMELIST DATA STRUCTURE
!           ----------------------------------------------------

! TNAMFPL
RFP3P=>YLNAMFPL%RFP3P(:)
RFP3H=>YLNAMFPL%RFP3H(:)
RFP3TH=>YLNAMFPL%RFP3TH(:)
RFP3PV=>YLNAMFPL%RFP3PV(:)
RFP3I=>YLNAMFPL%RFP3I(:)
RFP3F=>YLNAMFPL%RFP3F(:)
NRFP3S=>YLNAMFPL%NRFP3S(:)
NFP3DFP=>YLNAMFPL%NFP3DFP
NFP3DFH=>YLNAMFPL%NFP3DFH
NFP3DFT=>YLNAMFPL%NFP3DFT
NFP3DFV=>YLNAMFPL%NFP3DFV
NFP3DFI=>YLNAMFPL%NFP3DFI
NFP3DFF=>YLNAMFPL%NFP3DFF
NFP3DFS=>YLNAMFPL%NFP3DFS
MFP3DFP=>YLNAMFPL%MFP3DFP(:)
MFP3DFH=>YLNAMFPL%MFP3DFH(:)
MFP3DFT=>YLNAMFPL%MFP3DFT(:)
MFP3DFV=>YLNAMFPL%MFP3DFV(:)
MFP3DFI=>YLNAMFPL%MFP3DFI(:)
MFP3DFF=>YLNAMFPL%MFP3DFF(:)
MFP3DFS=>YLNAMFPL%MFP3DFS(:)
CFP3DF=>YLNAMFPL%CFP3DF(:)
CFP2DF=>YLNAMFPL%CFP2DF(:)
MFP2DF=>YLNAMFPL%MFP2DF(:)
CFPCFU=>YLNAMFPL%CFPCFU(:)
CFPXFU=>YLNAMFPL%CFPXFU(:)
CFPPHY=>YLNAMFPL%CFPPHY(:)
MFPPHY=>YLNAMFPL%MFPPHY(:)
NFP2DF=>YLNAMFPL%NFP2DF
NFPPHY=>YLNAMFPL%NFPPHY

! TNAMFPSCI
NFPSURFEX=>YLNAMFPSCI%NFPSURFEX
NFPBOYD=>YLNAMFPSCI%NFPBOYD
RFPBSCAL=>YLNAMFPSCI%RFPBSCAL
LFPCAPEX=>YLNAMFPSCI%LFPCAPEX
NFPCLI=>YLNAMFPSCI%NFPCLI
NFPLAKE=>YLNAMFPSCI%NFPLAKE
NFPMASK=>YLNAMFPSCI%NFPMASK
NFPSWI=>YLNAMFPSCI%NFPSWI
NFPCAPE=>YLNAMFPSCI%NFPCAPE
RFPVCAP=>YLNAMFPSCI%RFPVCAP
LFPISOPV=>YLNAMFPSCI%LFPISOPV
NITERPV=>YLNAMFPSCI%NITERPV
RENTRA=>YLNAMFPSCI%RENTRA
RSTRMMH=>YLNAMFPSCI%RSTRMMH
RSRHH=>YLNAMFPSCI%RSRHH
FPRHMIN=>YLNAMFPSCI%FPRHMIN
FPRHMAX=>YLNAMFPSCI%FPRHMAX
LSATURCAP=>YLNAMFPSCI%LSATURCAP
LFITBETWEEN=>YLNAMFPSCI%LFITBETWEEN
LFPQ=>YLNAMFPSCI%LFPQ
LFPLOSP=>YLNAMFPSCI%LFPLOSP
LFPRH100=>YLNAMFPSCI%LFPRH100
LPUTZS=>YLNAMFPSCI%LPUTZS
LFPCLSTOGMV=>YLNAMFPSCI%LFPCLSTOGMV
LCRITSNOWTEMP=>YLNAMFPSCI%LCRITSNOWTEMP
LCLIMALBEDOS=>YLNAMFPSCI%LCLIMALBEDOS
LCLIMAEROSOL=>YLNAMFPSCI%LCLIMAEROSOL
LCLIMOZONE=>YLNAMFPSCI%LCLIMOZONE
LISOT_ABOVEG=>YLNAMFPSCI%LISOT_ABOVEG
TSRESERV1=>YLNAMFPSCI%TSRESERV1
TSRESERV2=>YLNAMFPSCI%TSRESERV2
TDELTA1=>YLNAMFPSCI%TDELTA1
TDELTA2=>YLNAMFPSCI%TDELTA2
RWPITPN=>YLNAMFPSCI%RWPITPN
RWPITPX=>YLNAMFPSCI%RWPITPX
RSNSTPN=>YLNAMFPSCI%RSNSTPN
RSNSTPX=>YLNAMFPSCI%RSNSTPX
RSNSMOD=>YLNAMFPSCI%RSNSMOD
RFPCORR=>YLNAMFPSCI%RFPCORR
RFPCSAB=>YLNAMFPSCI%RFPCSAB
RFPCD2=>YLNAMFPSCI%RFPCD2
NFITP=>YLNAMFPSCI%NFITP
NFITT=>YLNAMFPSCI%NFITT
NFITV=>YLNAMFPSCI%NFITV
NFITI=>YLNAMFPSCI%NFITI
NFITF=>YLNAMFPSCI%NFITF
NFITH=>YLNAMFPSCI%NFITH
NFITS=>YLNAMFPSCI%NFITS
NSPFILP=>YLNAMFPSCI%NSPFILP
NSPFILT=>YLNAMFPSCI%NSPFILT
NSPFILV=>YLNAMFPSCI%NSPFILV
NSPFILI=>YLNAMFPSCI%NSPFILI
NSPFILF=>YLNAMFPSCI%NSPFILF
NSPFILH=>YLNAMFPSCI%NSPFILH
NSPFILS=>YLNAMFPSCI%NSPFILS
NSPFIL2=>YLNAMFPSCI%NSPFIL2

! TNAMFPINT
LFPML_STD=>YLNAMFPINT%LFPML_STD
LFPML_LAN=>YLNAMFPINT%LFPML_LAN
LFPML_SEA=>YLNAMFPINT%LFPML_SEA
NFPINDYN=>YLNAMFPINT%NFPINDYN
NFPINPHY=>YLNAMFPINT%NFPINPHY
NFPSFXINT=>YLNAMFPINT%NFPSFXINT
RFPCR_STD=>YLNAMFPINT%RFPCR_STD(:)
RFPCR_LAN=>YLNAMFPINT%RFPCR_LAN(:)
RFPCR_SEA=>YLNAMFPINT%RFPCR_SEA(:)

! TNAMFPOBJ
CFPFMT=>YLNAMFPOBJ%CFPFMT
CFPDOM=>YLNAMFPOBJ%CFPDOM(:)
CFPDIR=>YLNAMFPOBJ%CFPDIR
CFPMONIPATH_IN=>YLNAMFPOBJ%CFPMONIPATH_IN
CFPMONIPATH_OUT=>YLNAMFPOBJ%CFPMONIPATH_OUT
NFPGRIB=>YLNAMFPOBJ%NFPGRIB
NFPOSTS(0:)=>YLNAMFPOBJ%NFPOSTS(0:)
NFPOSTSMIN(0:)=>YLNAMFPOBJ%NFPOSTSMIN(0:)
NFRFPOS=>YLNAMFPOBJ%NFRFPOS

IF (PRESENT(KFPCONF)) THEN
  ! object-dependent value
  ICONF=KFPCONF
ELSE
  ! use the default global value
  ICONF=NFPOS
ENDIF

!*       2. SET DEFAULT VALUES
!           ------------------

IF (LELAM) THEN
  CFPFMT='LELAM'
ELSE
  CFPFMT='GAUSS'
ENDIF
CFPDOM(1)='000'
DO JJ=2, JPOSDOM
  CFPDOM(JJ)=' '
ENDDO
IF (LARPEGEF) THEN
  CFPDIR='PF'
ENDIF
NFPGRIB=NVGRIB
NFPOSTS(0:)=NPOSTS(0:)
NFPOSTSMIN(0:)=NPOSTSMIN(0:)
NFRFPOS=NFRPOS

LTRACEFP=LARPEGEF
LFPPACKING=(NFPOS /=0) .AND. (NGRIBFILE==0)
RWIDOM=HUGE(RWIDOM)
LOCEDELAY=LECMWF

! Scientific choices :

IF (ICONF==1) THEN
  NFITP=1
  NFITT=1
  NFITV=1
  NFITI=0
  NFITS=1
  NFITH=0
  NFITF=0
ELSE
  NFITP=2
  NFITT=2
  NFITV=2
  NFITI=2
  NFITS=2
  NFITH=0
  NFITF=0
ENDIF
NSPFILP=1
NSPFILT=1
IF (ICONF==1) THEN
  IF (.NOT.LECMWF) THEN
    NSPFILV=3 ! potential stretching for arpege - for now simpler than searching for a stretching factor
    NSPFIL2=3
  ELSE
    NSPFILV=1
    NSPFIL2=1
  ENDIF
  NSPFILI=2
ELSE
  NSPFILV=1
  NSPFIL2=1
  NSPFILI=1
ENDIF
NSPFILF=1
NSPFILH=1
NSPFILS=1

IF (LECMWF.AND..NOT.LARPEGEF) THEN
  LCRITSNOWTEMP=.FALSE.
  LFPRH100=.TRUE.
  RFPVCAP=8900._JPRB
  FPRHMAX=2.0_JPRB
ELSE
  LCRITSNOWTEMP=.TRUE.
  LFPRH100=.FALSE.
  RFPVCAP=15000._JPRB
  FPRHMAX=1.0_JPRB
ENDIF

LISOT_ABOVEG=.FALSE.

! experimented values for conversion Surfex to ISBA :
! RWPITPX=278._JPRB
! RSNSTPX=275._JPRB

LMOCONVAR=.FALSE.

!*       3. READ NAMELIST
!           -------------

IF(.NOT.PRESENT(CDPATH)) THEN

  CALL POSNAM(NULNAM,'NAMFPC')
  READ(NULNAM,NAMFPC)

ELSE

! CDPATH has been supplied. Check for PP namelists file
  IF (PRESENT(LDNAMELIST)) THEN
    LLPPNAMELIST=LDNAMELIST
  ELSE
    LLPPNAMELIST=.FALSE.
  ENDIF
  IF (LLPPNAMELIST) THEN
    REWIND(NPPPSH)
    DO WHILE(LLPPNAMELIST)
      READ(NPPPSH,'(A)',END=900) CLFILE
      IF(CLFILE == CDPATH) THEN
        READ(NPPPSH,NAMFPC)
        GOTO 910
      ENDIF
    ENDDO
    900 CONTINUE
    WRITE(CLFILE,FMT='('' NO NAMELIST ENTRY FOUND IN ppnamelist '')')
    WRITE(NULOUT,'(A)') CLFILE
    CALL ABOR1(CLFILE)
  ELSE
    ! CDPATH might be already opened by nulnam :
    INQUIRE(UNIT=NULNAM,OPENED=LLOPENED,NAME=CLFILE)
    IF (LEN(CLFILE) < LEN(CDPATH)) THEN
      CALL ABOR1('SUFPC INTERNAL ERROR : LEN(CLFILE) TOO SMALL !')
    ENDIF
    IF (LLOPENED.AND.TRIM(CLFILE)==TRIM(CDPATH)) THEN
      CALL POSNAM(NULNAM,'NAMFPC')
      READ(NULNAM,NAMFPC)
    ELSE
      OPEN(NPPPSH,FILE=CDPATH,ACTION='READ')
      CALL POSNAM(NPPPSH,'NAMFPC')
      READ(NPPPSH,NAMFPC)
      CLOSE(NPPPSH)
    ENDIF
  ENDIF
  910 CONTINUE


ENDIF


!*       4. PRINT OUT, CHECK AND RETURN FINAL VALUES
!           ----------------------------------------

IF (LMOCONVAR) THEN
  WRITE(NULOUT,*) 'LMOCONVAR IS NOW INACTIVE. TO GET THE SURFACE MOISTURE CONVERGENCE FOR VARPACK' 
  WRITE(NULOUT,*) 'AS BEFORE, PROCEED AS FOLLOWS : ' 
  WRITE(NULOUT,*) '- REMOVE LMOCONVAR FROM THE NAMELIST NAMFPC' 
  WRITE(NULOUT,*) '- INTERCHANGE THE FA NAME OF THE FIELDS IN THE NAMELIST NAMFA ; LIKE THIS :' 
  WRITE(NULOUT,*) '  YFA_VSMC%CLNAME=''SURFANAMOCON.POS''' 
  WRITE(NULOUT,*) '  YFA_ASMC%CLNAME=''VARPACKSURFMOCON''' 
  CALL ABOR1('SUFPC :LMOCONVAR SUPPORT HAS CHANGED')
ENDIF


IF (PRESENT(LDPRINT)) THEN
  LLPRINT=LDPRINT
ELSE
  LLPRINT=.TRUE.
ENDIF

IF (LLPRINT) THEN
  WRITE(UNIT=NULOUT,FMT='('' COMMON YOMFPC'')')
ENDIF


!       4.0 YOMFPC (Constant parameters)

IF (PRESENT(LDMODULE)) THEN
  LLMODULE=LDMODULE
ELSE
  LLMODULE=.FALSE.
ENDIF

IF (LLMODULE) THEN

  NFPCHKDAT=MAX(0,MIN(1,NFPCHKDAT))
  NFPSFXWRT=MAX(0,MIN(1,NFPSFXWRT))

  IF (LLPRINT) THEN
    WRITE(UNIT=NULOUT,FMT='('' LTRACEFP = '',L2, '' LALLOFP = '',L2,'' LFPMOIS = '',L2,'' LFPPACKING = '',L2, &
     & '' L_READ_MODEL_DATE = '',L2, '' LWIDER_DOM = '',L2,'' NFPSFXWRT = '',I2, '' LOCEDELAY = '',L2)')  &
     & LTRACEFP, LALLOFP, LFPMOIS, LFPPACKING, L_READ_MODEL_DATE, LWIDER_DOM, NFPSFXWRT, LOCEDELAY
    IF (LWIDER_DOM) THEN
      WRITE(UNIT=NULOUT,FMT='('' RWIDOM = '',E15.7)') RWIDOM
    ENDIF
  ENDIF

  IF (NFPOS /= 0) THEN
    IF (LFPMOIS .AND. NSUPERSEDE /= 1) THEN
     ! A helpful restriction :
      CALL ABOR1('SUFPC :LFPMOIS==T NEEDS NSUPERSEDE==1')
    ENDIF
  ENDIF

ENDIF

!       4.1 NAMFPOBJ (Fields object dependent parameters)

IF (PRESENT(YDNAMFPOBJ)) THEN

  IF (LLPRINT) THEN
    WRITE(UNIT=NULOUT,FMT='('' NFPGRIB = '',I3)') NFPGRIB
  ENDIF
  IF (NFPGRIB == 3) THEN
    WRITE(NULOUT,*) 'WARNING : GRIBEX TABLES ARE STILL HARD-CODED FOR FULL-POS FIELDS'
  ELSEIF ((NFPGRIB < -1 .OR.NFPGRIB > 3) .AND. (NFPGRIB < 100 .OR. NFPGRIB > 200)) THEN
    CALL ABOR1('SUFPC : ILLEGAL VALUE NFPGRIB')
  ENDIF

  IF (PRESENT(YDNAMFPSCI)) THEN
    IF (CFPFMT == 'MODEL' .AND. ICONF /= 2) THEN
      IF (PRESENT(KFPCONF)) THEN
        CALL ABOR1('SUFPC : CFPFMT=MODEL REQUIRES NFPCONF=2')
      ELSE
        CALL ABOR1('SUFPC : CFPFMT=MODEL REQUIRES NFPOS=2')
      ENDIF
    ENDIF
    IF (CFPFMT == 'MODEL'.AND. NFPCLI /= 0) THEN
      CALL ABOR1('SUFPC : CFPFMT=MODEL NOT COMPATIBLE WITH NFPCLI /=0')
    ENDIF
  ENDIF

  ! When everything is OK, save the structure
  YDNAMFPOBJ=YLNAMFPOBJ

ENDIF


!       4.2 NAMFPSCI (scientific parameters)

IF (PRESENT(YDNAMFPSCI)) THEN

  NFPSURFEX=MAX(0,MIN(NFPSURFEX,2))
  NFPSWI=MIN(MAX(0,NFPSWI),2)
  IF (NFPSWI==2) THEN
    NFPCLI=3
  ELSE
    NFPCLI=MAX(0,MIN(NFPCLI,3))
  ENDIF

  ! NFIT* validity
  IF (ICONF==1) THEN
  ! Spectral fit for terrain-following levels on model geometry is excluded ; => reset to 0 if not 2 :
    IF (NFITS==1) NFITS=0
    IF (NFITH==1) NFITH=0
    IF (NFITI==1) NFITI=0
    IF (NFITF==1) NFITF=0
  ELSE
  ! Spectral fit on model geometry is excluded ; => change to 2 if not 0 :
    IF (NFITP /= 0) NFITP=2
    IF (NFITT /= 0) NFITT=2
    IF (NFITV /= 0) NFITV=2
    IF (NFITI /= 0) NFITI=2
    IF (NFITS /= 0) NFITS=2
    IF (NFITH /= 0) NFITH=2
    IF (NFITF /= 0) NFITF=2
  ENDIF

  IF (CFPFMT=='MODEL') THEN
  ! No "stretched" filters
    IFPFILMAX=2
  ELSE
    IFPFILMAX=3
  ENDIF
  NSPFILP=MIN(IFPFILMAX,MAX(1,NSPFILP))
  NSPFILT=MIN(IFPFILMAX,MAX(1,NSPFILT))
  NSPFILV=MIN(IFPFILMAX,MAX(1,NSPFILV))
  NSPFILI=MIN(IFPFILMAX,MAX(1,NSPFILI))
  NSPFILF=MIN(IFPFILMAX,MAX(1,NSPFILF))
  NSPFILH=MIN(IFPFILMAX,MAX(1,NSPFILH))
  NSPFILS=MIN(IFPFILMAX,MAX(1,NSPFILS))
  NSPFIL2=MIN(IFPFILMAX,MAX(1,NSPFIL2))

  IF (LLPRINT) THEN
    WRITE(UNIT=NULOUT,FMT='('' NFPLAKE = '',I2,'' NFPCLI = '',I1,'' NFPMASK = '',I3,'' NFPSURFEX = '',I2)') &
     & NFPLAKE, NFPCLI, NFPMASK, NFPSURFEX
    WRITE(UNIT=NULOUT,FMT='('' LFPCAPEX = '',L2,'' NFPCAPE = '',I3)') LFPCAPEX, NFPCAPE
    WRITE(UNIT=NULOUT,FMT='('' LFPISOPV = '',L2,'' NITERPV = '',I3)') LFPISOPV, NITERPV
    WRITE(UNIT=NULOUT,FMT='('' RSTRMMH = '',F9.2,'' RSRHH = '',F9.2)') RSTRMMH,RSRHH
    WRITE(UNIT=NULOUT,FMT='('' LPUTZS = '',L2,'' LCRITSNOWTEMP = '',L2)') LPUTZS, LCRITSNOWTEMP
    WRITE(UNIT=NULOUT,FMT='('' LISOT_ABOVEG = '',L2)') LISOT_ABOVEG
    WRITE(UNIT=NULOUT,FMT='('' LFPQ = '',L2,'' LFPLOSP = '',L2,'' LFPRH100 = '',L2,'' RFPCSAB = '',F9.6, &
     & '' RFPCD2  = '',F9.4,'' RFPCORR = '',F9.2)') LFPQ, LFPLOSP, LFPRH100,RFPCSAB,RFPCD2,RFPCORR
    WRITE(UNIT=NULOUT,FMT='('' RENTRA  = '',E13.6 )') RENTRA
    WRITE(UNIT=NULOUT,FMT='('' FPRHMIN  = '',E13.6,'' FPRHMAX  = '',E13.6 )') FPRHMIN,FPRHMAX
    WRITE (NULOUT,'('' NFPBOYD = '',I2,'' RFPBSCAL = '',E13.6)') NFPBOYD, RFPBSCAL
    WRITE(UNIT=NULOUT,FMT='('' NFPSWI = '',I3,'' TSRESERV1  = '',E13.6,'' TSRESERV2  = '',E13.6,&
     & '' TDELTA1  = '',E13.6,'' TDELTA2  = '',E13.6 )') NFPSWI,TSRESERV1,TSRESERV2,TDELTA1,TDELTA2
    WRITE(UNIT=NULOUT,FMT='('' RWPITPN  = '',E13.6,'' RWPITPX  = '',E13.6,&
     & '' RSNSTPN  = '',E13.6,'' RSNSTPX  = '',E13.6, '' RSNSMOD '',E13.6)') &
     & RWPITPN,RWPITPX, RSNSTPN, RSNSTPX, RSNSMOD
    WRITE(UNIT=NULOUT,FMT='('' LSATURCAP = '',L2, '' LFITBETWEEN = '',L2)')  LSATURCAP, LFITBETWEEN
    WRITE(UNIT=NULOUT,FMT='('' NFITP = '',I2,'' NFITT = '',I2,'' NFITV = '',I2,&
     & '' NFITI = '',I2,'' NFITH = '',I2,'' NFITS = '',I2,'' NFITF = '',I2)')&
     & NFITP, NFITT, NFITV,NFITI, NFITH, NFITS, NFITF
    WRITE(UNIT=NULOUT,FMT='('' NSPFILP = '',I2,'' NSPFILT = '',I2,'' NSPFILV = '', &
     & I2,'' NSPFILI = '',I2,'' NSPFILH = '',I2, '' NSPFILS = '',I2, '' NSPFILF = '',I2, &
     & '' NSPFIL2 = '',I2)') &
     & NSPFILP, NSPFILT, NSPFILV, NSPFILI, NSPFILH, NSPFILS, NSPFILF, NSPFIL2
    IF (NFPCLI > 1) THEN
      WRITE(UNIT=NULOUT,FMT='('' LCLIMALBEDOS = '',L2,'' LCLIMAEROSOL = '',L2,'' LCLIMOZONE = '',L2)') &
       & LCLIMALBEDOS, LCLIMAEROSOL, LCLIMOZONE
    ENDIF
  ENDIF

  IERR=0
  IF (NFPCAPE < 0.OR.NFPCAPE > 6.OR.NFPCAPE==4) THEN
    IERR=IERR+1
    WRITE(NULOUT,*) 'ILLEGAL VALUE NFPCAPE'
  ENDIF
  IF (NFPMASK < 0 .OR. NFPMASK > 2) THEN
    IERR=IERR+1
    WRITE(NULOUT,*) 'ILLEGAL VALUE NFPMASK'
  ENDIF
  IF (NFPMASK >= 2 .AND. NFPCLI > 2) THEN
    IERR=IERR+1
    WRITE(NULOUT,*) 'NFPMASK >= 2 NEEDS NFPCLI <= 2'
  ENDIF
  IF (ABS(NFPLAKE) > 1) THEN
    IERR=IERR+1
    WRITE(NULOUT,*) 'ILLEGAL VALUE NFPLAKE'
  ENDIF
  IF (NFPLAKE == 1 .AND. NFPCLI <= 1) THEN
    IERR=IERR+1
    WRITE(NULOUT,*) 'NFPLAKE = 1 NEEDS NFPCLI > 1'
  ENDIF
  IF (NFPLAKE /= 0 .AND. NFPMASK == 0) THEN
    IERR=IERR+1
    WRITE(NULOUT,*) 'NFPLAKE /= 0 NEEDS NFPMASK > 0'
  ENDIF
  IF (IERR > 0) THEN
    CALL ABOR1('SUFPC : ABOR1 CALLED')
  ENDIF

  ! When everything is OK, save the structure
  YDNAMFPSCI=YLNAMFPSCI

ENDIF


!       4.3 NAMFPINT (Horizontal interpolations parameters)

IF (PRESENT(YDNAMFPINT)) THEN

  IWARN=0
  IF (NFPINDYN /= 0 .AND. NFPINDYN /= 4 .AND. NFPINDYN /= 12) THEN
    NFPINDYN=12
    IWARN=IWARN+1
  ENDIF
  IF (NFPINPHY /= 0 .AND. NFPINPHY /= 4 .AND. NFPINPHY /= 12) THEN
    NFPINPHY=12
    IWARN=IWARN+1
  ENDIF
  IF (IWARN /= 0) WRITE(NULOUT,*) 'FULL-POS WARNING : UNKNOWN INTERPOLATION TYPE, RESET TO 12 POINTS'

  IF (LLPRINT) THEN
    WRITE(UNIT=NULOUT,FMT='('' LFPML_STD = '',L2,'' RFPCR_STD(1)='',E20.14,'', RFPCR_STD(2)='',E20.14)') &
     & LFPML_STD,RFPCR_STD(1),RFPCR_STD(2)
    WRITE(UNIT=NULOUT,FMT='('' LFPML_LAN = '',L2,'' RFPCR_LAN(1)='',E20.14,'', RFPCR_LAN(2)='',E20.14)') &
     & LFPML_LAN,RFPCR_LAN(1),RFPCR_LAN(2)
    WRITE(UNIT=NULOUT,FMT='('' LFPML_SEA = '',L2,'' RFPCR_SEA(1)='',E20.14,'', RFPCR_SEA(2)='',E20.14)') &
     & LFPML_SEA,RFPCR_SEA(1),RFPCR_SEA(2)
    WRITE(UNIT=NULOUT,FMT='(I3,'' POINTS INTERP. FOR DYN. FIELDS'')') NFPINDYN
    WRITE(UNIT=NULOUT,FMT='(I3,'' POINTS INTERP. FOR PHY. FIELDS'')') NFPINPHY
    WRITE(UNIT=NULOUT,FMT='('' NFPSFXINT = '',I2)') NFPSFXINT
  ENDIF

  IF (NFPSFXINT < 0 .OR. NFPSFXINT > 2) THEN
    CALL ABOR1('SUFPC : NFPSFXINT MUST BE EITHER 0, 1 OR 2')
  ENDIF

  ! When everything is OK, save the structure
  YDNAMFPINT=YLNAMFPINT

ENDIF


!       4.3 NAMFPL (List of output fields)
IF (PRESENT(YDNAMFPL)) THEN

  IF (.NOT.LARPEGEF) THEN

    IF (LLPRINT) THEN
      IF (NFP3DFS > 0) THEN
        WRITE(NULOUT,'('' THE FOLLOWING '',I6,'' 3DYN. FIELDS'','' WILL BE WRITTEN OUT ON MODEL LEVELS'')')NFP3DFS
        WRITE(NULOUT,'(20(1X,I6))') (MFP3DFS(J),J=1,NFP3DFS)
      ENDIF
      IF (NFP3DFH > 0) THEN
        WRITE(NULOUT,'('' THE FOLLOWING '',I6,'' 3DYN. FIELDS'','' WILL BE WRITTEN OUT ON H LEVELS'')')NFP3DFH
        WRITE(NULOUT,'(20(1X,I3))') (MFP3DFH(J),J=1,NFP3DFH)
      ENDIF
      IF (NFP3DFP > 0) THEN
        WRITE(NULOUT,'('' THE FOLLOWING '',I6,'' 3DYN. FIELDS'','' WILL BE WRITTEN OUT ON PRESSURE LEVELS'')')NFP3DFP
        WRITE(NULOUT,'(20(1X,I6))') (MFP3DFP(J),J=1,NFP3DFP)
      ENDIF
      IF (NFP3DFT > 0) THEN
        WRITE(NULOUT,'('' THE FOLLOWING '',I6,'' 3DYN. FIELDS'','' WILL BE WRITTEN OUT ON THETA LEVELS'')')NFP3DFT
        WRITE(NULOUT,'(20(1X,I3))') (MFP3DFT(J),J=1,NFP3DFT)
      ENDIF
      IF (NFP3DFV > 0) THEN
        WRITE(NULOUT,'('' THE FOLLOWING '',I6,'' 3DYN. FIELDS'','' WILL BE WRITTEN OUT ON PV LEVELS'')')NFP3DFV
        WRITE(NULOUT,'(20(1X,I3))') (MFP3DFV(J),J=1,NFP3DFV)
      ENDIF
      IF (NFP3DFI > 0) THEN
        WRITE(NULOUT,'('' THE FOLLOWING '',I6,'' 3DYN. FIELDS'','' WILL BE WRITTEN OUT ON TEMPERATURE LEVELS'')')NFP3DFI
        WRITE(NULOUT,'(20(1X,I3))') (MFP3DFI(J),J=1,NFP3DFI)
      ENDIF
      IF (NFP3DFF > 0) THEN
        WRITE(NULOUT,'('' THE FOLLOWING '',I6,'' 3DYN. FIELDS'','' WILL BE WRITTEN OUT ON FLIGHT LEVELS'')')NFP3DFF
        WRITE(NULOUT,'(20(1X,I3))') (MFP3DFF(J),J=1,NFP3DFF)
      ENDIF
      IF (NFP2DF > 0) THEN
        WRITE(NULOUT,'('' THE FOLLOWING '',I3,'' DYN.SURFACE FIELDS'','' WILL BE WRITTEN OUT '')')NFP2DF
        WRITE(NULOUT,'(20(1X,I3))') (MFP2DF(J),J=1,NFP2DF)
      ENDIF
      IF (NFPPHY > 0) THEN
        WRITE(NULOUT,'('' THE FOLLOWING '',I6,'' PHY.SURFACE FIELDS'','' WILL BE WRITTEN OUT '')')NFPPHY
        WRITE(NULOUT,'(20(1X,I6))') (MFPPHY(J),J=1,NFPPHY)
      ENDIF
    ENDIF

    IERR=0
    DO J=1, NFPPHY
      IF (MFPPHY(J) < 1) THEN
        WRITE(NULOUT,*) 'SUFPC: ILLEGAL GRIB CODE FOR PHYSICS FIELD NO',J,MFPPHY(J)
        IERR=IERR+1
      ENDIF
    ENDDO
    IF (IERR > 0) THEN
      CALL ABOR1(' SUFPC: ABOR1 CALLED')
    ENDIF

  ENDIF

  ! When everything is OK, save the structure
  YDNAMFPL=YLNAMFPL


ENDIF


!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('SUFPC',1,ZHOOK_HANDLE)
END SUBROUTINE SUFPC
