! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE AERO_INIT(YGFL,YDCOMPO,YDEAERATM,KDIM,GEMSL)

!-----------------------------------------------------------------------

USE PARKIND1 , ONLY : JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOM_YGFL , ONLY : TYPE_GFLD
USE YOMCOMPO , ONLY : TCOMPO
USE YOEAERATM, ONLY : TEAERATM
USE YOMPHYDER, ONLY : DIMENSION_TYPE, GEMS_LOCAL_TYPE
USE YOE_AERODIAG, ONLY : NPAERAOT, NPAERLISI_VAR, NPAERLISI_WVL
USE UKCA_MODE_SETUP, ONLY: NMODES, NCP

!-----------------------------------------------------------------------
! ****  AERO_INIT - Initialization for aerosols
!
!   F. Vana  (ECMWF)
!
!     MODIFICATIONS.
!     -------------
!    Original 18-May-2012
!    JJMorcrette 20131001 MACC-related diagnostics
!
!-----------------------------------------------------------------------

IMPLICIT NONE

TYPE(TYPE_GFLD)                 ,INTENT(INOUT) :: YGFL
TYPE(TCOMPO)                    ,INTENT(IN)    :: YDCOMPO
TYPE(TEAERATM)                  ,INTENT(IN)    :: YDEAERATM
TYPE (DIMENSION_TYPE)          , INTENT (IN)   :: KDIM
TYPE (GEMS_LOCAL_TYPE)         , INTENT(INOUT) :: GEMSL

!-----------------------------------------------------------------------

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!-----------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('AERO_INIT',0,ZHOOK_HANDLE)
ASSOCIATE(NACTAERO=>YGFL%NACTAERO, NAERO=>YGFL%NAERO, LAERCHEM=>YGFL%LAERCHEM, &
 & NTYPAER=>YDEAERATM%NTYPAER)
!-----------------------------------------------------------------------

ALLOCATE( GEMSL%ZCAERO (KDIM%KLON,KDIM%KLEV,NACTAERO) )
ALLOCATE( GEMSL%ZAEROP (KDIM%KLON,KDIM%KLEV,NAERO) )
GEMSL%ZCAERO (:,:,:)=0._JPRB
GEMSL%ZAEROP (:,:,:)=0._JPRB

!-- diagnostic fluxes
ALLOCATE( GEMSL%ZAERSRC(KDIM%KLON,NACTAERO) )
ALLOCATE( GEMSL%ZAERDDP(KDIM%KLON,NACTAERO) )
ALLOCATE( GEMSL%ZAERSDM(KDIM%KLON,NACTAERO) )

! RCHG -> as commented in other subroutines explain what is 5, 12 and 9
ALLOCATE( GEMSL%ZAERMAP(KDIM%KLON,5) )
ALLOCATE( GEMSL%ZAERFLX_M7(KDIM%KLON,12,9) )
!ALLOCATE( GEMSL%ZAERLIF(KDIM%KLON,9) )
GEMSL%ZAERSRC(:,:)=0._JPRB
GEMSL%ZAERDDP(:,:)=0._JPRB
GEMSL%ZAERSDM(:,:)=0._JPRB

! Extra arrays for aerosol 
IF (NTYPAER(2) > 0) THEN
  ALLOCATE( GEMSL%ZAERFLX(KDIM%KLON,NTYPAER(2)) )
  ALLOCATE( GEMSL%ZAERLIF(KDIM%KLON,NTYPAER(2)) )
ELSE
  ALLOCATE( GEMSL%ZAERFLX(1,1) )
  ALLOCATE( GEMSL%ZAERLIF(1,1) )
ENDIF

ALLOCATE( GEMSL%ZTAUAER(KDIM%KLON,KDIM%KLEV,7) )
ALLOCATE( GEMSL%ZAERAOT(KDIM%KLON,KDIM%KLEV,NPAERAOT) )
ALLOCATE( GEMSL%ZAERAOTLEV(KDIM%KLON,KDIM%KLEV,6) )
ALLOCATE( GEMSL%ZAERAAOTLEV(KDIM%KLON,KDIM%KLEV,6) )
ALLOCATE( GEMSL%ZAERASYLEV(KDIM%KLON,KDIM%KLEV,6) )
ALLOCATE( GEMSL%ZAERLISI(KDIM%KLON,KDIM%KLEV,NPAERLISI_WVL,NPAERLISI_VAR) )
GEMSL%ZAERFLX_M7(:,:,:)=0._JPRB
GEMSL%ZAERFLX(:,:)=0._JPRB
GEMSL%ZAERLIF(:,:)=0._JPRB
GEMSL%ZTAUAER(:,:,:)=0._JPRB
GEMSL%ZAERAOT(:,:,:)=0._JPRB
GEMSL%ZAERAOTLEV(:,:,:)=0._JPRB
GEMSL%ZAERAAOTLEV(:,:,:)=0._JPRB
GEMSL%ZAERASYLEV(:,:,:)=0._JPRB
GEMSL%ZAERLISI(:,:,:,:)=0._JPRB


!M7 aerosols
IF (TRIM(YDCOMPO%AERO_SCHEME)=='hamm7') THEN
    ALLOCATE( GEMSL%ZAEROTAU(KDIM%KLON,KDIM%KLEV,14) )
    ALLOCATE( GEMSL%ZAEROSSA(KDIM%KLON,KDIM%KLEV,14) )
    ALLOCATE( GEMSL%ZAEROASY(KDIM%KLON,KDIM%KLEV,14) )
    ALLOCATE( GEMSL%ZAEROTAULW(KDIM%KLON,KDIM%KLEV,16) )
    GEMSL%ZAEROTAU(:,:,:)=0._JPRB
    GEMSL%ZAEROSSA(:,:,:)=0._JPRB
    GEMSL%ZAEROASY(:,:,:)=0._JPRB
    GEMSL%ZAEROTAULW(:,:,:)=0._JPRB
ELSE
    ALLOCATE( GEMSL%ZAEROTAU(1,1,1) )
    ALLOCATE( GEMSL%ZAEROSSA(1,1,1) )
    ALLOCATE( GEMSL%ZAEROASY(1,1,1) )
    ALLOCATE( GEMSL%ZAEROTAULW(1,1,1) )
ENDIF



IF (TRIM(YDCOMPO%AERO_SCHEME)=='glomap') THEN
  ! Extra diags for GLOMAP: dry and wet diameter/volume + effective radius
  ALLOCATE( GEMSL%ZDRYDIAM(KDIM%KLON,KDIM%KLEV,NMODES) )
  ALLOCATE( GEMSL%ZWETDIAM(KDIM%KLON,KDIM%KLEV,NMODES) )
  ALLOCATE( GEMSL%ZDRYVOL(KDIM%KLON,KDIM%KLEV,NMODES) )
  ALLOCATE( GEMSL%ZWETVOL(KDIM%KLON,KDIM%KLEV,NMODES) )
  ALLOCATE( GEMSL%ZVOL_WAT(KDIM%KLON,KDIM%KLEV,NMODES) )
  ALLOCATE( GEMSL%ZRHOPAR(KDIM%KLON,KDIM%KLEV,NMODES) )
  ALLOCATE( GEMSL%ZMD(KDIM%KLON,KDIM%KLEV,NMODES,NCP) )
  ALLOCATE( GEMSL%ZMDT(KDIM%KLON,KDIM%KLEV,NMODES) )
  ALLOCATE( GEMSL%ZND(KDIM%KLON,KDIM%KLEV,NMODES) )
  GEMSL%ZDRYDIAM(:,:,:)=0._JPRB
  GEMSL%ZWETDIAM(:,:,:)=0._JPRB
  GEMSL%ZDRYVOL(:,:,:)=0._JPRB
  GEMSL%ZWETVOL(:,:,:)=0._JPRB
  GEMSL%ZVOL_WAT(:,:,:)=0._JPRB
  GEMSL%ZRHOPAR(:,:,:)=0._JPRB
  GEMSL%ZMD(:,:,:,:)=0._JPRB
  GEMSL%ZMDT(:,:,:)=0._JPRB
  GEMSL%ZND(:,:,:)=0._JPRB
ELSE
  ALLOCATE( GEMSL%ZDRYDIAM(1,1,1) )
  ALLOCATE( GEMSL%ZWETDIAM(1,1,1) )
  ALLOCATE( GEMSL%ZDRYVOL(1,1,1) )
  ALLOCATE( GEMSL%ZWETVOL(1,1,1) )
  ALLOCATE( GEMSL%ZVOL_WAT(1,1,1) )
  ALLOCATE( GEMSL%ZRHOPAR(1,1,1) )
  ALLOCATE( GEMSL%ZMD(1,1,1,1) )
  ALLOCATE( GEMSL%ZMDT(1,1,1) )
  ALLOCATE( GEMSL%ZND(1,1,1) )
ENDIF


!-----------------------------------------------------------------------
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('AERO_INIT',1,ZHOOK_HANDLE)
END SUBROUTINE AERO_INIT
