SUBROUTINE CMIP_STRATO_AERO(YDMODEL,YDDYNA)

!     PURPOSE.
!     --------
!     Read stratospheric aerosol from CMIP6/CMIP7

!     INTERFACE.
!     ----------
!     CALL *CMIP_STRATO_AERO* FROM *UPDTIM*

!     AUTHOR.
!     -------
!     M.Ménégoz for EC-EARTH 2017
!     A.Laakso for EC-EARTH4/OIFS 2022
!     A.Laakso for OIFS48 2025 CMIP6 and CMIP7

!     Reading the CMIP stratospheric aerosol dataset.
!     The vertical interpolation of this data is done off-line.
  
!     Horizontal and time interpolation are done in
!     cmip_strato_aero_interp.F90 and cmip_strato_aero_process.F90
  
!     The data is read with a broadcast approach.
!     Forcing in the SW (AOD_SUN, AAOD_SUN, REF_AOD_SUN) and in the LW
!     (AAOD_EARTH)

!     Note: The code has not been tested in longer simulations, especially at the threshold year
!     of historical and future climatological aerosols. 
!     Please contact anton.laakso@fmi.fi if you experience any issues.

!     MODIFICATIONS.
!     --------------

!--------------------------------------------------------------------- 

! Modules
USE NETCDF
USE PARKIND1, ONLY: JPIM, JPIB, JPRB, JPRD
USE YOMLUN,   ONLY: NULOUT, NULERR
USE YOMDYNA,  ONLY: TDYNA
USE YOMCT0,   ONLY: LNF
USE YOMCT2,   ONLY: NSTAR2
USE YOMCST,   ONLY: RDAY
USE YOMRIP0,  ONLY: NINDAT
USE YOEAEROP, ONLY: STRATO_FIRSTYEAR, STRATO_CMIP_NLAT, STRATO_CMIP_NALT, STRATO_CMIP_NTIME, &
                  & STRATO_LASTYEAR, STRATO_CMIP_LAT, STRATO_CMIP_SB, STRATO_CMIP_TB,&
                  & STRATO_CMIP_NSB, STRATO_CMIP_NTB, &
                  & STRATO_CMIP_NMONTH, &
                  & CHECK_SUN_MEAN, CHECK_EARTH_MEAN
USE YOMMP0,     ONLY: MYPROC
USE MPL_MODULE, ONLY: MPL_BROADCAST
USE TYPE_MODEL, ONLY: MODEL
USE YOMHOOK,    ONLY: LHOOK, DR_HOOK, JPHOOK
USE ECE_CMIP,   ONLY: NCMIPFIXYR  ! LCMIP6, LCMIP7

IMPLICIT NONE

TYPE(MODEL), INTENT(INOUT) :: YDMODEL
TYPE(TDYNA), INTENT(IN)    :: YDDYNA
! Local variables
INTEGER                      :: IUNIT,FORC_MONTH
INTEGER(KIND=JPIM)           :: ILAT, ILEV, ILON, IMONTH,IB, JLEV
INTEGER(KIND=JPIM)           :: ISTADD, IJ0, IM0, IA0, IDAY, IMON, IMODYR, ILMOIS(12)
INTEGER(KIND=JPIB)           :: ITIME, IZT
INTEGER(KIND=JPIM)           :: IYR1, IMV1
INTEGER(KIND=JPIM), SAVE     :: IMONOLD=-999
INTEGER(KIND=JPIM), PARAMETER :: ITAG = 98684
INTEGER(KIND=JPIM), PARAMETER :: RPRC = 1

REAL(KIND=JPRB) :: TIME(STRATO_CMIP_NTIME)
CHARACTER (LEN=*), PARAMETER :: LAT_NAME='latitude'
CHARACTER (LEN=*), PARAMETER :: ALT_NAME='altitude'
CHARACTER (LEN=*), PARAMETER :: TIME_NAME='month'
CHARACTER (LEN=*), PARAMETER :: SB_NAME='solar_bands'
CHARACTER (LEN=*), PARAMETER :: TB_NAME='terrestrial_bands'
INTEGER :: LAT_VARID, ALT_VARID, TIME_VARID, SB_VARID, TB_VARID, IOS
LOGICAL :: LLOPEN, LLSTRAT, LLOPENC,LLSTRATC

! Triplets of variable for SW and only absorption for LW (because IFS
! is currently not considering aerosol scattering in the LW):

CHARACTER (LEN=*), PARAMETER :: AOD_SUN_NAME='AOD_sun'
INTEGER :: AOD_SUN_VARID
REAL(KIND=JPRB), ALLOCATABLE :: AOD_SUN_ORIG(:,:,:,:)

CHARACTER (LEN=*), PARAMETER :: AAOD_SUN_NAME='AAOD_sun'
INTEGER :: AAOD_SUN_VARID
REAL(KIND=JPRB), ALLOCATABLE :: AAOD_SUN_ORIG(:,:,:,:)

CHARACTER (LEN=*), PARAMETER :: REFAOD_SUN_NAME='REFAOD_sun'
INTEGER :: REFAOD_SUN_VARID
REAL(KIND=JPRB), ALLOCATABLE :: REFAOD_SUN_ORIG(:,:,:,:)

CHARACTER (LEN=*), PARAMETER :: AAOD_EARTH_NAME='AAOD_earth'
INTEGER :: AAOD_EARTH_VARID
REAL(KIND=JPRB), ALLOCATABLE :: AAOD_EARTH_ORIG(:,:,:,:)

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

! Read the nectdf data with an adequate format and order.
INTEGER, DIMENSION(4) :: START, FINAL, FINAL_LW, FINAL_MEAN, FINAL_LW_MEAN

!REAL, POINTER :: AOD_SUN(:,:,:,:), REFAOD_SUN(:,:,:,:), AOD_SUN_MEAN(:,:,:,:), AAOD_SUN_MEAN(:,:,:,:)
!REAL, POINTER :: AAOD_EARTH_MEAN(:,:,:,:), AAOD_EARTH(:,:,:,:)

!#include "netcdf.inc"
#include "abor1.intfb.h"
#include "updcal.intfb.h"
#include "fcttim.func.h"

IF (LHOOK) CALL DR_HOOK('CMIP_STRATO_AERO',0,ZHOOK_HANDLE)

ASSOCIATE(&
  &  YDERAD=>YDMODEL%YRML_PHY_RAD%YRERAD, YDPHYAER     => YDMODEL%YRML_PHY_AER,  &
  &  YDRIP=>YDMODEL%YRML_GCONF%YRRIP&
  )

ASSOCIATE(NSTADD=>YDRIP%NSTADD, TSTEP=>YDRIP%TSTEP)

ASSOCIATE(YDAERSTRAT => YDPHYAER%YREAEROSTRAT)

ASSOCIATE(&
  &  LSTRATAERO_UPDATED=>YDERAD%LSTRATAERO_UPDATED, CCMIP_STRAT_FULL=>YDERAD%CCMIP_STRAT_FULL,  &
  &  CCMIP_STRAT_FULL_CLIM=>YDERAD%CCMIP_STRAT_FULL_CLIM,  &
  &  LCMIP_STRATAER_BCKGD =>YDERAD%LCMIP_STRATAER_BCKGD,  &
  &  LCMIP_STRATAER_CMIP6 =>YDERAD%LCMIP_STRATAER_CMIP6,  &
  &  LCMIP_STRATAER_CMIP7 =>YDERAD%LCMIP_STRATAER_CMIP7  &
  )

ASSOCIATE(&
  & AOD_SUN=>YDAERSTRAT%AOD_SUN,AAOD_SUN=>YDAERSTRAT%AAOD_SUN,REFAOD_SUN=>YDAERSTRAT%REFAOD_SUN, &
  & AOD_SUN_MEAN=>YDAERSTRAT%AOD_SUN_MEAN, AAOD_SUN_MEAN=>YDAERSTRAT%AAOD_SUN_MEAN,REFAOD_SUN_MEAN=>YDAERSTRAT%REFAOD_SUN_MEAN, &
  & AAOD_EARTH_MEAN=>YDAERSTRAT%AAOD_EARTH_MEAN, AAOD_EARTH=>YDAERSTRAT%AAOD_EARTH& 
  )

! Number of steps since start of integration
IF(.NOT.LNF.AND.NSTADD == 0) THEN ! is restart
  IF (YDDYNA%LTWOTL) THEN
    IZT=NINT(TSTEP*(REAL(NSTAR2,JPRB)+0.5_JPRB), KIND=JPIB)
  ELSE
    ITIME=NINT(TSTEP, KIND=JPIB)
    IZT=ITIME*INT(NSTAR2, KIND=JPIB)
  ENDIF
  ISTADD=INT(IZT/NINT(RDAY, KIND=JPIB), KIND=JPIM)
ELSE
  ISTADD=NSTADD
ENDIF

IJ0=NDD(NINDAT)
IM0=NMM(NINDAT)
IA0=NCCAA(NINDAT)
CALL UPDCAL(IJ0,IM0,IA0,ISTADD,IDAY,IMON,IMODYR,ILMOIS,NULOUT)

! Note this has no effect if LCMIP_STRATAER_BCKGD=T (ie if climatology is requested)
IF (NCMIPFIXYR > 0) THEN
  IMODYR = NCMIPFIXYR
ENDIF

! Open the file only if we begin a new month and I am the master process
NEWMONTH: IF (IMON/=IMONOLD) THEN
  IMONOLD=IMON
   
  ROOT: IF (MYPROC==RPRC) THEN

    ! Forcing file includes 1980 months since 1850-01 for CMIP6, and 3288 months starting on 1750-01 for CMIP7
    FORC_MONTH=(IMODYR-STRATO_FIRSTYEAR)*12+IMON
    !WRITE(NULOUT,'(A,I4,A,I4,A,I4)') 'CMIP_STRATO_AERO: FORCING MONTH NB= ', FORC_MONTH, '/', STRATO_CMIP_NTIME, ', starting from the year ', STRATO_FIRSTYEAR
    !WRITE(NULOUT,*) 'CCMIP_STRAT_FULL: ',TRIM(CCMIP_STRAT_FULL)

    ! Check on transient file
    LLOPEN=.FALSE.
    IOS= 0
    INQUIRE(FILE=CCMIP_STRAT_FULL,IOSTAT=IOS,EXIST=LLSTRAT,OPENED=LLOPEN)
    LLSTRAT = LLSTRAT .AND. (IOS == 0) .AND. .NOT.LLOPEN
    
    IF (.NOT.LLSTRAT) THEN
      WRITE(NULERR,'('' ERROR IN CMIP_STRATO_AERO.F90 :'',&
       & '' THE FORCING FILE IS NOT AVAILABLE OR ALREADY OPENED !'')')
      CALL ABOR1('CMIP_STRATO_AERO')
    ENDIF

    ! Any available month except 1st or last
    AVAIL: IF (IMODYR>=STRATO_FIRSTYEAR .AND. IMODYR<=STRATO_LASTYEAR .AND. .NOT. LCMIP_STRATAER_BCKGD .AND. FORC_MONTH/=1 .AND. FORC_MONTH/=STRATO_CMIP_NTIME) THEN

      WRITE(NULOUT,'(A,I4,A,I4,A,I4)') 'CMIP_STRATO_AERO [1]: GETTING FORCING FOR MONTH NB= ', FORC_MONTH, '/', STRATO_CMIP_NTIME, ', starting from the year ', STRATO_FIRSTYEAR
      WRITE(NULOUT,FMT='('' CCMIP_STRAT_FULL = '',A)') TRIM(CCMIP_STRAT_FULL)

      START=(/1, 1, 1, FORC_MONTH-1/)
      FINAL=(/STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,STRATO_CMIP_NMONTH/)
      FINAL_LW=(/STRATO_CMIP_NTB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,STRATO_CMIP_NMONTH/)
    
      ! Allocate temporary arrays
      ALLOCATE(AOD_SUN_ORIG   (STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,STRATO_CMIP_NMONTH))
      ALLOCATE(AAOD_SUN_ORIG  (STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,STRATO_CMIP_NMONTH))
      ALLOCATE(REFAOD_SUN_ORIG(STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,STRATO_CMIP_NMONTH))
      ALLOCATE(AAOD_EARTH_ORIG(STRATO_CMIP_NTB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,STRATO_CMIP_NMONTH))

      ! Initialise arrays:
      AOD_SUN_ORIG(:,:,:,:)=0._JPRB
      AAOD_SUN_ORIG(:,:,:,:)=0._JPRB
      REFAOD_SUN_ORIG(:,:,:,:)=0._JPRB
      AAOD_EARTH_ORIG(:,:,:,:)=0._JPRB
    
      ! OPEN NETCDF FILE
      CALL CHECK( NF90_OPEN(CCMIP_STRAT_FULL,NF90_NOWRITE,IUNIT) )
  
      ! Reading latitudes needed for the interpolation.
      CALL CHECK( NF90_INQ_VARID(IUNIT, LAT_NAME, LAT_VARID) )
      CALL CHECK( NF90_GET_VAR(IUNIT, LAT_VARID, STRATO_CMIP_LAT) )
      
      ! READ 4-D FIELDS
      CALL CHECK( NF90_INQ_VARID(IUNIT, AOD_SUN_NAME, AOD_SUN_VARID) )
      CALL CHECK( NF90_GET_VAR(IUNIT, AOD_SUN_VARID, AOD_SUN_ORIG, START, FINAL) )
  
      CALL CHECK( NF90_INQ_VARID(IUNIT, AAOD_SUN_NAME, AAOD_SUN_VARID) )
      CALL CHECK( NF90_GET_VAR(IUNIT, AAOD_SUN_VARID, AAOD_SUN_ORIG, START, FINAL) )
  
      CALL CHECK( NF90_INQ_VARID(IUNIT, REFAOD_SUN_NAME, REFAOD_SUN_VARID) )
      CALL CHECK( NF90_GET_VAR(IUNIT, REFAOD_SUN_VARID, REFAOD_SUN_ORIG, START, FINAL) )
  
      CALL CHECK( NF90_INQ_VARID(IUNIT, AAOD_EARTH_NAME, AAOD_EARTH_VARID) )
      CALL CHECK( NF90_GET_VAR(IUNIT, AAOD_EARTH_VARID, AAOD_EARTH_ORIG, START, FINAL_LW) )
  
      ! CLOSE NETCDF FILE
      CALL CHECK( NF90_CLOSE(IUNIT) )
  
      ! Fill the data for the current month and reorder the arrays
      DO ILEV=1,STRATO_CMIP_NALT
        JLEV=STRATO_CMIP_NALT-ILEV+1
        DO ILAT=1,STRATO_CMIP_NLAT
          ! SW parameters
          DO IB=1,STRATO_CMIP_NSB
            ! We keep three months to make a smoothed forcing (linear interpolation along the axis time)
            DO IMONTH=1,STRATO_CMIP_NMONTH
              AOD_SUN(ILEV,ILAT,IB,IMONTH)=AOD_SUN_ORIG(IB,ILAT,JLEV,IMONTH)
              AAOD_SUN(ILEV,ILAT,IB,IMONTH)=AAOD_SUN_ORIG(IB,ILAT,JLEV,IMONTH)
              REFAOD_SUN(ILEV,ILAT,IB,IMONTH)=REFAOD_SUN_ORIG(IB,ILAT,JLEV,IMONTH)
            ENDDO
          ENDDO
          ! LW parameter
          DO IB=1,STRATO_CMIP_NTB
            DO IMONTH=1,STRATO_CMIP_NMONTH
              AAOD_EARTH(ILEV,ILAT,IB,IMONTH)=AAOD_EARTH_ORIG(IB,ILAT,JLEV,IMONTH)
            ENDDO
          ENDDO
        ENDDO
      ENDDO
      
      DEALLOCATE(AOD_SUN_ORIG   )
      DEALLOCATE(AAOD_SUN_ORIG  )
      DEALLOCATE(REFAOD_SUN_ORIG)
      DEALLOCATE(AAOD_EARTH_ORIG)

    ! Special cases of 1st and last available month
    ELSE IF (.NOT. LCMIP_STRATAER_BCKGD .AND. (FORC_MONTH==1 .OR. FORC_MONTH==STRATO_CMIP_NTIME)) THEN

      IF(LCMIP_STRATAER_CMIP6) THEN
        WRITE(NULOUT,'(A,I4,A,I4,A,I4)') 'CMIP_STRATO_AERO [2]: GETTING FORCING FOR MONTH NB= ', FORC_MONTH, '/', STRATO_CMIP_NTIME, ', starting from the year ', STRATO_FIRSTYEAR
        WRITE(NULOUT,*)'CMIP_STRATO_AERO [1] computing CMIP6 climatological stratospheric forcing'

        START=(/1, 1, 1, 1/)
        FINAL=(/STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,STRATO_CMIP_NTIME/)
        FINAL_LW=(/STRATO_CMIP_NTB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,STRATO_CMIP_NTIME/)
    
        ! Allocate temporary arrays
        ALLOCATE(AOD_SUN_ORIG (STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,STRATO_CMIP_NTIME))
        ALLOCATE(AAOD_SUN_ORIG(STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,STRATO_CMIP_NTIME))
        ALLOCATE(REFAOD_SUN_ORIG(STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,STRATO_CMIP_NTIME))
        ALLOCATE(AAOD_EARTH_ORIG(STRATO_CMIP_NTB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,STRATO_CMIP_NTIME))
        
        ! Initialise arrays:
        AOD_SUN_ORIG(:,:,:,:)=0._JPRB
        AAOD_SUN_ORIG(:,:,:,:)=0._JPRB
        REFAOD_SUN_ORIG(:,:,:,:)=0._JPRB
        AAOD_EARTH_ORIG(:,:,:,:)=0._JPRB

        ! OPEN NETCDF FILE
        CALL CHECK( NF90_OPEN(CCMIP_STRAT_FULL,NF90_NOWRITE,IUNIT) )

        ! Reading latitudes needed for the interpolation.
        CALL CHECK( NF90_INQ_VARID(IUNIT, LAT_NAME, LAT_VARID) )
        CALL CHECK( NF90_GET_VAR(IUNIT, LAT_VARID, STRATO_CMIP_LAT) )

        ! READ 4-D FIELDS
        CALL CHECK( NF90_INQ_VARID(IUNIT, AOD_SUN_NAME, AOD_SUN_VARID) )
        CALL CHECK( NF90_GET_VAR(IUNIT, AOD_SUN_VARID, AOD_SUN_ORIG, START, FINAL) )

        CALL CHECK( NF90_INQ_VARID(IUNIT, AAOD_SUN_NAME, AAOD_SUN_VARID) )
        CALL CHECK( NF90_GET_VAR(IUNIT, AAOD_SUN_VARID, AAOD_SUN_ORIG, START, FINAL) )

        CALL CHECK( NF90_INQ_VARID(IUNIT, REFAOD_SUN_NAME, REFAOD_SUN_VARID) )
        CALL CHECK( NF90_GET_VAR(IUNIT, REFAOD_SUN_VARID, REFAOD_SUN_ORIG, START, FINAL) )

        CALL CHECK( NF90_INQ_VARID(IUNIT, AAOD_EARTH_NAME, AAOD_EARTH_VARID) )
        CALL CHECK( NF90_GET_VAR(IUNIT, AAOD_EARTH_VARID, AAOD_EARTH_ORIG, START, FINAL_LW) )

        ! CLOSE NETCDF FILE
        CALL CHECK( NF90_CLOSE(IUNIT) )
 
        ! Climatology computed on-line. Transition between climatological and time-resolved stratospheric forcing
        DO ILEV=1,STRATO_CMIP_NALT
          JLEV=STRATO_CMIP_NALT-ILEV+1
          DO ILAT=1,STRATO_CMIP_NLAT
            ! SW parameters
            DO IB=1,STRATO_CMIP_NSB
              AOD_SUN_MEAN(ILEV,ILAT,IB)=SUM(AOD_SUN_ORIG(IB,ILAT,JLEV,:))/STRATO_CMIP_NTIME
              AAOD_SUN_MEAN(ILEV,ILAT,IB)=SUM(AAOD_SUN_ORIG(IB,ILAT,JLEV,:))/STRATO_CMIP_NTIME
              REFAOD_SUN_MEAN(ILEV,ILAT,IB)=SUM(REFAOD_SUN_ORIG(IB,ILAT,JLEV,:))/STRATO_CMIP_NTIME

              IF (FORC_MONTH==1) THEN
                AOD_SUN(ILEV,ILAT,IB,1)=AOD_SUN_MEAN(ILEV,ILAT,IB)
                AAOD_SUN(ILEV,ILAT,IB,1)=AAOD_SUN_MEAN(ILEV,ILAT,IB)
                REFAOD_SUN(ILEV,ILAT,IB,1)=REFAOD_SUN_MEAN(ILEV,ILAT,IB)

                DO IMONTH=2,STRATO_CMIP_NMONTH
                  AOD_SUN(ILEV,ILAT,IB,IMONTH)=AOD_SUN_ORIG(IB,ILAT,JLEV,IMONTH-1)
                  AAOD_SUN(ILEV,ILAT,IB,IMONTH)=AAOD_SUN_ORIG(IB,ILAT,JLEV,IMONTH-1)
                  REFAOD_SUN(ILEV,ILAT,IB,IMONTH)=REFAOD_SUN_ORIG(IB,ILAT,JLEV,IMONTH-1)
                ENDDO

              ELSE IF (FORC_MONTH==STRATO_CMIP_NTIME) THEN

                AOD_SUN(ILEV,ILAT,IB,STRATO_CMIP_NMONTH)=AOD_SUN_MEAN(ILEV,ILAT,IB)
                AAOD_SUN(ILEV,ILAT,IB,STRATO_CMIP_NMONTH)=AAOD_SUN_MEAN(ILEV,ILAT,IB)
                REFAOD_SUN(ILEV,ILAT,IB,STRATO_CMIP_NMONTH)=REFAOD_SUN_MEAN(ILEV,ILAT,IB)
                DO IMONTH=1,STRATO_CMIP_NMONTH-1
                  AOD_SUN(ILEV,ILAT,IB,IMONTH)=AOD_SUN_ORIG(IB,ILAT,JLEV,STRATO_CMIP_NTIME+IMONTH-2)
                  AAOD_SUN(ILEV,ILAT,IB,IMONTH)=AAOD_SUN_ORIG(IB,ILAT,JLEV,STRATO_CMIP_NTIME+IMONTH-2)
                  REFAOD_SUN(ILEV,ILAT,IB,IMONTH)=REFAOD_SUN_ORIG(IB,ILAT,JLEV,STRATO_CMIP_NTIME+IMONTH-2)
                ENDDO

              ENDIF
            ENDDO

            ! LW parameters
            DO IB=1,STRATO_CMIP_NTB
              AAOD_EARTH_MEAN(ILEV,ILAT,IB)=SUM(AAOD_EARTH_ORIG(IB,ILAT,JLEV,:))/STRATO_CMIP_NTIME
              IF (FORC_MONTH==1) THEN
                AAOD_EARTH(ILEV,ILAT,IB,1)=AAOD_EARTH_MEAN(ILEV,ILAT,IB)
                DO IMONTH=2,STRATO_CMIP_NMONTH
                  AAOD_EARTH(ILEV,ILAT,IB,IMONTH)=AAOD_EARTH_ORIG(IB,ILAT,JLEV,IMONTH-1)
                ENDDO
              ELSE IF (FORC_MONTH==STRATO_CMIP_NTIME) THEN
                AAOD_EARTH(ILEV,ILAT,IB,STRATO_CMIP_NMONTH)=AAOD_EARTH_MEAN(ILEV,ILAT,IB)
                DO IMONTH=1,STRATO_CMIP_NMONTH-1
                  AAOD_EARTH(ILEV,ILAT,IB,IMONTH)=AAOD_EARTH_ORIG(IB,ILAT,JLEV,STRATO_CMIP_NTIME+IMONTH-2)
                ENDDO
              ENDIF
            ENDDO

          ENDDO
        ENDDO

        DEALLOCATE(AOD_SUN_ORIG   )
        DEALLOCATE(AAOD_SUN_ORIG  )
        DEALLOCATE(REFAOD_SUN_ORIG)
        DEALLOCATE(AAOD_EARTH_ORIG)

      ELSEIF (LCMIP_STRATAER_CMIP7) THEN

        ! Check on climatology file
        WRITE(NULOUT,*) 'CMIP7 CCMIP_STRAT_FULL_CLIM: ',TRIM(CCMIP_STRAT_FULL_CLIM)
        LLOPENC=.FALSE.
        IOS= 0
        INQUIRE(FILE=CCMIP_STRAT_FULL_CLIM,IOSTAT=IOS,EXIST=LLSTRATC,OPENED=LLOPENC)
        LLSTRATC = LLSTRATC .AND. (IOS == 0) .AND. .NOT.LLOPENC
        
        IF (.NOT.LLSTRATC) THEN
          WRITE(NULERR,'('' ERROR IN CMIP_STRATO_AERO.F90 :'',&
           & '' THE CMIP7 CLIMATOLOGICAL FORCING FILE IS NOT AVAILABLE !'')')
          CALL ABOR1('CMIP_STRATO_AERO')
        ENDIF
        
        WRITE(NULOUT,'(A,I4,A,I4,A,I4)') 'CMIP_STRATO_AERO [2]: GETTING FORCING FOR MONTH NB= ', FORC_MONTH, '/', STRATO_CMIP_NTIME, ', starting from the year ', STRATO_FIRSTYEAR
        WRITE(NULOUT,*) 'CCMIP_STRAT_FULL: ',TRIM(CCMIP_STRAT_FULL)
        
        IF (FORC_MONTH==1) THEN
          START=(/1, 1, 1, 1/)
          FINAL=(/STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,2/)
          FINAL_LW=(/STRATO_CMIP_NTB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,2/)
        
          ! Allocate temporary arrays
          ALLOCATE(AOD_SUN_ORIG (STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,2))
          ALLOCATE(AAOD_SUN_ORIG(STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,2))
          ALLOCATE(REFAOD_SUN_ORIG(STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,2))
          ALLOCATE(AAOD_EARTH_ORIG(STRATO_CMIP_NTB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,2))
    
          ! Initialise arrays:
          AOD_SUN_ORIG(:,:,:,:)=0._JPRB
          AAOD_SUN_ORIG(:,:,:,:)=0._JPRB
          REFAOD_SUN_ORIG(:,:,:,:)=0._JPRB
          AAOD_EARTH_ORIG(:,:,:,:)=0._JPRB
        
          ! OPEN NETCDF FILE
          CALL CHECK( NF90_OPEN(CCMIP_STRAT_FULL,NF90_NOWRITE,IUNIT) )
      
          ! Reading latitudes needed for the interpolation.
          CALL CHECK( NF90_INQ_VARID(IUNIT, LAT_NAME, LAT_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, LAT_VARID, STRATO_CMIP_LAT) )
        
          ! READ 4-D FIELDS
          CALL CHECK( NF90_INQ_VARID(IUNIT, AOD_SUN_NAME, AOD_SUN_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, AOD_SUN_VARID, AOD_SUN_ORIG, START, FINAL) )
       
          CALL CHECK( NF90_INQ_VARID(IUNIT, AAOD_SUN_NAME, AAOD_SUN_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, AAOD_SUN_VARID, AAOD_SUN_ORIG, START, FINAL) )
       
          CALL CHECK( NF90_INQ_VARID(IUNIT, REFAOD_SUN_NAME, REFAOD_SUN_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, REFAOD_SUN_VARID, REFAOD_SUN_ORIG, START, FINAL) )
      
          CALL CHECK( NF90_INQ_VARID(IUNIT, AAOD_EARTH_NAME, AAOD_EARTH_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, AAOD_EARTH_VARID, AAOD_EARTH_ORIG, START, FINAL_LW) )
      
          ! CLOSE NETCDF FILE
          CALL CHECK( NF90_CLOSE(IUNIT) )
          
          DO ILEV=1,STRATO_CMIP_NALT
            JLEV=STRATO_CMIP_NALT-ILEV+1
            DO ILAT=1,STRATO_CMIP_NLAT
              ! SW parameters
              DO IB=1,STRATO_CMIP_NSB
                ! We keep three months to make a smoothed forcing (linear interpolation along the axis time)           
                DO IMONTH=2,STRATO_CMIP_NMONTH
                  AOD_SUN(ILEV,ILAT,IB,IMONTH)=AOD_SUN_ORIG(IB,ILAT,JLEV,IMONTH-1)
                  AAOD_SUN(ILEV,ILAT,IB,IMONTH)=AAOD_SUN_ORIG(IB,ILAT,JLEV,IMONTH-1)
                  REFAOD_SUN(ILEV,ILAT,IB,IMONTH)=REFAOD_SUN_ORIG(IB,ILAT,JLEV,IMONTH-1)
                ENDDO
              ENDDO
              ! LW parameter
              DO IB=1,STRATO_CMIP_NTB 
                DO IMONTH=2,STRATO_CMIP_NMONTH
                  AAOD_EARTH(ILEV,ILAT,IB,IMONTH)=AAOD_EARTH_ORIG(IB,ILAT,JLEV,IMONTH-1)
                ENDDO
              ENDDO
            ENDDO
          ENDDO
          DEALLOCATE(AOD_SUN_ORIG   )
          DEALLOCATE(AAOD_SUN_ORIG  )
          DEALLOCATE(REFAOD_SUN_ORIG)
          DEALLOCATE(AAOD_EARTH_ORIG)

          !Climatological file
          START=(/1, 1, 1, 12/)
          FINAL=(/STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,12/)
          FINAL_LW=(/STRATO_CMIP_NTB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,12/)
        
          ! Allocate temporary arrays
          ALLOCATE(AOD_SUN_ORIG (STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,1))
          ALLOCATE(AAOD_SUN_ORIG(STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,1))
          ALLOCATE(REFAOD_SUN_ORIG(STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,1))
          ALLOCATE(AAOD_EARTH_ORIG(STRATO_CMIP_NTB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,1))
    
          ! Initialise arrays:
          AOD_SUN_ORIG(:,:,:,:)=0._JPRB
          AAOD_SUN_ORIG(:,:,:,:)=0._JPRB
          REFAOD_SUN_ORIG(:,:,:,:)=0._JPRB
          AAOD_EARTH_ORIG(:,:,:,:)=0._JPRB
        
          ! OPEN NETCDF FILE
          CALL CHECK( NF90_OPEN(CCMIP_STRAT_FULL_CLIM,NF90_NOWRITE,IUNIT) )
      
          ! Reading latitudes needed for the interpolation.
          CALL CHECK( NF90_INQ_VARID(IUNIT, LAT_NAME, LAT_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, LAT_VARID, STRATO_CMIP_LAT) )
          
          ! READ 4-D FIELDS
          CALL CHECK( NF90_INQ_VARID(IUNIT, AOD_SUN_NAME, AOD_SUN_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, AOD_SUN_VARID, AOD_SUN_ORIG, START, FINAL) )

          CALL CHECK( NF90_INQ_VARID(IUNIT, AAOD_SUN_NAME, AAOD_SUN_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, AAOD_SUN_VARID, AAOD_SUN_ORIG, START, FINAL) )

          CALL CHECK( NF90_INQ_VARID(IUNIT, REFAOD_SUN_NAME, REFAOD_SUN_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, REFAOD_SUN_VARID, REFAOD_SUN_ORIG, START, FINAL) )

          CALL CHECK( NF90_INQ_VARID(IUNIT, AAOD_EARTH_NAME, AAOD_EARTH_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, AAOD_EARTH_VARID, AAOD_EARTH_ORIG, START, FINAL_LW) )

          ! CLOSE NETCDF FILE
          CALL CHECK( NF90_CLOSE(IUNIT) )
          DO ILEV=1,STRATO_CMIP_NALT
            JLEV=STRATO_CMIP_NALT-ILEV+1
            DO ILAT=1,STRATO_CMIP_NLAT
              ! SW parameters
              DO IB=1,STRATO_CMIP_NSB
                ! We keep three months to make a smoothed forcing (linear interpolation along the axis time)           
                AOD_SUN(ILEV,ILAT,IB,1)=AOD_SUN_ORIG(IB,ILAT,JLEV,1)
                AAOD_SUN(ILEV,ILAT,IB,1)=AAOD_SUN_ORIG(IB,ILAT,JLEV,1)
                REFAOD_SUN(ILEV,ILAT,IB,1)=REFAOD_SUN_ORIG(IB,ILAT,JLEV,1)    
              ENDDO
              ! LW parameter
              DO IB=1,STRATO_CMIP_NTB
                AAOD_EARTH(ILEV,ILAT,IB,1)=AAOD_EARTH_ORIG(IB,ILAT,JLEV,1)     
              ENDDO
            ENDDO
          ENDDO
          DEALLOCATE(AOD_SUN_ORIG   )
          DEALLOCATE(AAOD_SUN_ORIG  )
          DEALLOCATE(REFAOD_SUN_ORIG)
          DEALLOCATE(AAOD_EARTH_ORIG)

        !December 2023
        ELSEIF (FORC_MONTH==STRATO_CMIP_NTIME) THEN
          START=(/1, 1, 1, STRATO_CMIP_NTIME-1/)
          FINAL=(/STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,STRATO_CMIP_NTIME/)
          FINAL_LW=(/STRATO_CMIP_NTB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,STRATO_CMIP_NTIME/)
        
          ! Allocate temporary arrays
          ALLOCATE(AOD_SUN_ORIG (STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,2))
          ALLOCATE(AAOD_SUN_ORIG(STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,2))
          ALLOCATE(REFAOD_SUN_ORIG(STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,2))
          ALLOCATE(AAOD_EARTH_ORIG(STRATO_CMIP_NTB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,2))
    
          ! Initialise arrays:
          AOD_SUN_ORIG(:,:,:,:)=0._JPRB
          AAOD_SUN_ORIG(:,:,:,:)=0._JPRB
          REFAOD_SUN_ORIG(:,:,:,:)=0._JPRB
          AAOD_EARTH_ORIG(:,:,:,:)=0._JPRB
        
          ! OPEN NETCDF FILE
          CALL CHECK( NF90_OPEN(CCMIP_STRAT_FULL,NF90_NOWRITE,IUNIT) )
      
          ! Reading latitudes needed for the interpolation.
          CALL CHECK( NF90_INQ_VARID(IUNIT, LAT_NAME, LAT_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, LAT_VARID, STRATO_CMIP_LAT) )
        
          ! READ 4-D FIELDS
          CALL CHECK( NF90_INQ_VARID(IUNIT, AOD_SUN_NAME, AOD_SUN_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, AOD_SUN_VARID, AOD_SUN_ORIG, START, FINAL) )
       
          CALL CHECK( NF90_INQ_VARID(IUNIT, AAOD_SUN_NAME, AAOD_SUN_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, AAOD_SUN_VARID, AAOD_SUN_ORIG, START, FINAL) )
       
          CALL CHECK( NF90_INQ_VARID(IUNIT, REFAOD_SUN_NAME, REFAOD_SUN_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, REFAOD_SUN_VARID, REFAOD_SUN_ORIG, START, FINAL) )
      
          CALL CHECK( NF90_INQ_VARID(IUNIT, AAOD_EARTH_NAME, AAOD_EARTH_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, AAOD_EARTH_VARID, AAOD_EARTH_ORIG, START, FINAL_LW) )
      
          ! CLOSE NETCDF FILE
          CALL CHECK( NF90_CLOSE(IUNIT) )

          DO ILEV=1,STRATO_CMIP_NALT
            JLEV=STRATO_CMIP_NALT-ILEV+1
            DO ILAT=1,STRATO_CMIP_NLAT
              ! SW parameters
              DO IB=1,STRATO_CMIP_NSB
                ! We keep three months to make a smoothed forcing (linear interpolation along the axis time)
                DO IMONTH=1,STRATO_CMIP_NMONTH-1
                  AOD_SUN(ILEV,ILAT,IB,IMONTH)=AOD_SUN_ORIG(IB,ILAT,JLEV,IMONTH)
                  AAOD_SUN(ILEV,ILAT,IB,IMONTH)=AAOD_SUN_ORIG(IB,ILAT,JLEV,IMONTH)
                  REFAOD_SUN(ILEV,ILAT,IB,IMONTH)=REFAOD_SUN_ORIG(IB,ILAT,JLEV,IMONTH)
                ENDDO
              ENDDO
              ! LW parameter
              DO IB=1,STRATO_CMIP_NTB
                DO IMONTH=1,STRATO_CMIP_NMONTH-1
                  AAOD_EARTH(ILEV,ILAT,IB,IMONTH)=AAOD_EARTH_ORIG(IB,ILAT,JLEV,IMONTH)
                ENDDO
              ENDDO
            ENDDO
          ENDDO
          DEALLOCATE(AOD_SUN_ORIG   )
          DEALLOCATE(AAOD_SUN_ORIG  )
          DEALLOCATE(REFAOD_SUN_ORIG)
          DEALLOCATE(AAOD_EARTH_ORIG)

          !Climatological file
          START=(/1, 1, 1, 1/)
          FINAL=(/STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,1/)
          FINAL_LW=(/STRATO_CMIP_NTB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,1/)
        
          ! Allocate temporary arrays
          ALLOCATE(AOD_SUN_ORIG (STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,1))
          ALLOCATE(AAOD_SUN_ORIG(STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,1))
          ALLOCATE(REFAOD_SUN_ORIG(STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,1))
          ALLOCATE(AAOD_EARTH_ORIG(STRATO_CMIP_NTB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,1))
    
          ! Initialise arrays:
          AOD_SUN_ORIG(:,:,:,:)=0._JPRB
          AAOD_SUN_ORIG(:,:,:,:)=0._JPRB
          REFAOD_SUN_ORIG(:,:,:,:)=0._JPRB
          AAOD_EARTH_ORIG(:,:,:,:)=0._JPRB
        
          ! OPEN NETCDF FILE
          CALL CHECK( NF90_OPEN(CCMIP_STRAT_FULL_CLIM,NF90_NOWRITE,IUNIT) )
      
          ! Reading latitudes needed for the interpolation.
          CALL CHECK( NF90_INQ_VARID(IUNIT, LAT_NAME, LAT_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, LAT_VARID, STRATO_CMIP_LAT) )
        
          ! READ 4-D FIELDS
          CALL CHECK( NF90_INQ_VARID(IUNIT, AOD_SUN_NAME, AOD_SUN_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, AOD_SUN_VARID, AOD_SUN_ORIG, START, FINAL) )
       
          CALL CHECK( NF90_INQ_VARID(IUNIT, AAOD_SUN_NAME, AAOD_SUN_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, AAOD_SUN_VARID, AAOD_SUN_ORIG, START, FINAL) )

          CALL CHECK( NF90_INQ_VARID(IUNIT, REFAOD_SUN_NAME, REFAOD_SUN_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, REFAOD_SUN_VARID, REFAOD_SUN_ORIG, START, FINAL) )

          CALL CHECK( NF90_INQ_VARID(IUNIT, AAOD_EARTH_NAME, AAOD_EARTH_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, AAOD_EARTH_VARID, AAOD_EARTH_ORIG, START, FINAL_LW) )

          ! CLOSE NETCDF FILE
          CALL CHECK( NF90_CLOSE(IUNIT) )
          DO ILEV=1,STRATO_CMIP_NALT
            JLEV=STRATO_CMIP_NALT-ILEV+1
            DO ILAT=1,STRATO_CMIP_NLAT
              ! SW parameters
              DO IB=1,STRATO_CMIP_NSB
                ! We keep three months to make a smoothed forcing (linear interpolation along the axis time)
                AOD_SUN(ILEV,ILAT,IB,STRATO_CMIP_NMONTH)=AOD_SUN_ORIG(IB,ILAT,JLEV,1)
                AAOD_SUN(ILEV,ILAT,IB,STRATO_CMIP_NMONTH)=AAOD_SUN_ORIG(IB,ILAT,JLEV,1)
                REFAOD_SUN(ILEV,ILAT,IB,STRATO_CMIP_NMONTH)=REFAOD_SUN_ORIG(IB,ILAT,JLEV,1)
              ENDDO
              ! LW parameter
              DO IB=1,STRATO_CMIP_NTB
                AAOD_EARTH(ILEV,ILAT,IB,STRATO_CMIP_NMONTH)=AAOD_EARTH_ORIG(IB,ILAT,JLEV,1)
              ENDDO
            ENDDO
          ENDDO
          DEALLOCATE(AOD_SUN_ORIG   )
          DEALLOCATE(AAOD_SUN_ORIG  )
          DEALLOCATE(REFAOD_SUN_ORIG)
          DEALLOCATE(AAOD_EARTH_ORIG)

        ENDIF ! 1st or last month of CMIP7
      ENDIF   ! CMIP6 or CMIP7

    ELSE ! PURE CLIMATOLOGY CASES  (IMODYR<1850/1750 .OR. IMODYR>2014/2023 .OR. LCMIP_STRATAER_BCKGD)
      
      CMIP: IF(LCMIP_STRATAER_CMIP6) THEN
        
        IF (MINVAL(AOD_SUN_MEAN)==CHECK_SUN_MEAN .OR. MINVAL(AAOD_SUN_MEAN)==CHECK_SUN_MEAN &
             & .OR. MINVAL(REFAOD_SUN_MEAN)==CHECK_SUN_MEAN .OR. MINVAL(AAOD_EARTH_MEAN)==CHECK_EARTH_MEAN) THEN
     
          WRITE(NULOUT,*)'CMIP_STRATO_AERO [2] computing CMIP6 climatological stratospheric forcing'

          START=(/1, 1, 1, 1/)
          FINAL=(/STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,STRATO_CMIP_NTIME/)
          FINAL_LW=(/STRATO_CMIP_NTB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,STRATO_CMIP_NTIME/)
    
          ! Allocate temporary arrays
          ALLOCATE(AOD_SUN_ORIG (STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,STRATO_CMIP_NTIME))
          ALLOCATE(AAOD_SUN_ORIG(STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,STRATO_CMIP_NTIME))
          ALLOCATE(REFAOD_SUN_ORIG(STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,STRATO_CMIP_NTIME))
          ALLOCATE(AAOD_EARTH_ORIG(STRATO_CMIP_NTB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,STRATO_CMIP_NTIME))

          ! Initialise arrays:
          AOD_SUN_ORIG(:,:,:,:)=0._JPRB
          AAOD_SUN_ORIG(:,:,:,:)=0._JPRB
          REFAOD_SUN_ORIG(:,:,:,:)=0._JPRB
          AAOD_EARTH_ORIG(:,:,:,:)=0._JPRB

          ! OPEN NETCDF FILE
          CALL CHECK( NF90_OPEN(CCMIP_STRAT_FULL,NF90_NOWRITE,IUNIT) )

          ! Reading latitudes needed for the interpolation.
          CALL CHECK( NF90_INQ_VARID(IUNIT, LAT_NAME, LAT_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, LAT_VARID, STRATO_CMIP_LAT) )

          ! READ 4-D FIELDS
          CALL CHECK( NF90_INQ_VARID(IUNIT, AOD_SUN_NAME, AOD_SUN_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, AOD_SUN_VARID, AOD_SUN_ORIG, START, FINAL ) )

          CALL CHECK( NF90_INQ_VARID(IUNIT, AAOD_SUN_NAME, AAOD_SUN_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, AAOD_SUN_VARID, AAOD_SUN_ORIG, START, FINAL) )

          CALL CHECK( NF90_INQ_VARID(IUNIT, REFAOD_SUN_NAME, REFAOD_SUN_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, REFAOD_SUN_VARID, REFAOD_SUN_ORIG, START, FINAL) )

          CALL CHECK( NF90_INQ_VARID(IUNIT, AAOD_EARTH_NAME, AAOD_EARTH_VARID) )
          CALL CHECK( NF90_GET_VAR(IUNIT, AAOD_EARTH_VARID, AAOD_EARTH_ORIG, START, FINAL_LW) )

          ! CLOSE NETCDF FILE
          CALL CHECK( NF90_CLOSE(IUNIT) )

          ! Climatology computed on-line, only once
          DO ILEV=1,STRATO_CMIP_NALT
            JLEV=STRATO_CMIP_NALT-ILEV+1
            DO ILAT=1,STRATO_CMIP_NLAT
              ! SW parameters
              DO IB=1,STRATO_CMIP_NSB
                AOD_SUN_MEAN(JLEV,ILAT,IB)=SUM(AOD_SUN_ORIG(IB,ILAT,ILEV,:))/STRATO_CMIP_NTIME
                AAOD_SUN_MEAN(JLEV,ILAT,IB)=SUM(AAOD_SUN_ORIG(IB,ILAT,ILEV,:))/STRATO_CMIP_NTIME
                REFAOD_SUN_MEAN(JLEV,ILAT,IB)=SUM(REFAOD_SUN_ORIG(IB,ILAT,ILEV,:))/STRATO_CMIP_NTIME
              ENDDO
              ! LW parameters
              DO IB=1,STRATO_CMIP_NTB
                AAOD_EARTH_MEAN(JLEV,ILAT,IB)=SUM(AAOD_EARTH_ORIG(IB,ILAT,ILEV,:))/STRATO_CMIP_NTIME
              ENDDO
            ENDDO
          ENDDO

          DEALLOCATE(AOD_SUN_ORIG   )
          DEALLOCATE(AAOD_SUN_ORIG  )
          DEALLOCATE(REFAOD_SUN_ORIG)
          DEALLOCATE(AAOD_EARTH_ORIG)
  
        ENDIF

        WRITE(NULOUT,*)'CMIP_STRATO_AERO: using CMIP6 climatological stratospheric forcing'
        DO IMONTH=1,STRATO_CMIP_NMONTH
          ! SW parameters
          AOD_SUN(:,:,:,IMONTH)=AOD_SUN_MEAN(:,:,:)
          AAOD_SUN(:,:,:,IMONTH)=AAOD_SUN_MEAN(:,:,:)
          REFAOD_SUN(:,:,:,IMONTH)=REFAOD_SUN_MEAN(:,:,:)
          ! LW parameters
          AAOD_EARTH(:,:,:,IMONTH)=AAOD_EARTH_MEAN(:,:,:)
        ENDDO

      ELSEIF (LCMIP_STRATAER_CMIP7) THEN

        WRITE(NULOUT,*) 'CMIP_STRATO_AERO: Reading CMIP7 climatological stratospheric forcing (3 months)'
        WRITE(NULOUT,FMT='('' CMIP7 CCMIP_STRAT_FULL_CLIM = '',A)') TRIM(CCMIP_STRAT_FULL_CLIM)
        LLOPENC=.FALSE.
        IOS= 0
        INQUIRE(FILE=CCMIP_STRAT_FULL_CLIM,IOSTAT=IOS,EXIST=LLSTRATC,OPENED=LLOPENC)
        LLSTRATC = LLSTRATC .AND. (IOS == 0) .AND. .NOT.LLOPENC

        IF (.NOT.LLSTRATC) THEN
          WRITE(NULERR,'('' ERROR IN CMIP_STRATO_AERO.F90 :'',&
               & '' THE CMIP7 CLIMATOLOGICAL FORCING FILE IS NOT AVAILABLE OR ALREADY OPENED !'')')
          CALL ABOR1('CMIP_STRATO_AERO')
        ENDIF

        !Climatological file for CMIP7 - All months are readed
        START=(/1, 1, 1, 1/)
        FINAL=(/STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,12/)
        FINAL_LW=(/STRATO_CMIP_NTB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,12/)

        ! Allocate temporary arrays
        ALLOCATE(AOD_SUN_ORIG   (STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,12))
        ALLOCATE(AAOD_SUN_ORIG  (STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,12))
        ALLOCATE(REFAOD_SUN_ORIG(STRATO_CMIP_NSB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,12))
        ALLOCATE(AAOD_EARTH_ORIG(STRATO_CMIP_NTB,STRATO_CMIP_NLAT,STRATO_CMIP_NALT,12))

        ! Initialise arrays:
        AOD_SUN_ORIG(:,:,:,:)=0._JPRB
        AAOD_SUN_ORIG(:,:,:,:)=0._JPRB
        REFAOD_SUN_ORIG(:,:,:,:)=0._JPRB
        AAOD_EARTH_ORIG(:,:,:,:)=0._JPRB

        ! OPEN NETCDF FILE
        CALL CHECK( NF90_OPEN(CCMIP_STRAT_FULL_CLIM,NF90_NOWRITE,IUNIT) )

        ! Reading latitudes needed for the interpolation.
        CALL CHECK( NF90_INQ_VARID(IUNIT, LAT_NAME, LAT_VARID) )
        CALL CHECK( NF90_GET_VAR(IUNIT, LAT_VARID, STRATO_CMIP_LAT) )

        ! READ 4-D FIELDS
        CALL CHECK( NF90_INQ_VARID(IUNIT, AOD_SUN_NAME, AOD_SUN_VARID) )
        CALL CHECK( NF90_GET_VAR(IUNIT, AOD_SUN_VARID, AOD_SUN_ORIG, START, FINAL) )

        CALL CHECK( NF90_INQ_VARID(IUNIT, AAOD_SUN_NAME, AAOD_SUN_VARID) )
        CALL CHECK( NF90_GET_VAR(IUNIT, AAOD_SUN_VARID, AAOD_SUN_ORIG, START, FINAL) )

        CALL CHECK( NF90_INQ_VARID(IUNIT, REFAOD_SUN_NAME, REFAOD_SUN_VARID) )
        CALL CHECK( NF90_GET_VAR(IUNIT, REFAOD_SUN_VARID, REFAOD_SUN_ORIG, START, FINAL) )

        CALL CHECK( NF90_INQ_VARID(IUNIT, AAOD_EARTH_NAME, AAOD_EARTH_VARID) )
        CALL CHECK( NF90_GET_VAR(IUNIT, AAOD_EARTH_VARID, AAOD_EARTH_ORIG, START, FINAL_LW) )

        ! CLOSE NETCDF FILE
        CALL CHECK( NF90_CLOSE(IUNIT) )
  
        ! Fill the data for the current month and reorder the arrays
        IF (IMON==1)THEN
          DO ILEV=1,STRATO_CMIP_NALT
            JLEV=STRATO_CMIP_NALT-ILEV+1
            DO ILAT=1,STRATO_CMIP_NLAT
              ! SW parameters
              DO IB=1,STRATO_CMIP_NSB
                ! We keep three months to make a smoothed forcing (linear interpolation along the axis time)           
                AOD_SUN(ILEV,ILAT,IB,1)=AOD_SUN_ORIG(IB,ILAT,JLEV,12)
                AAOD_SUN(ILEV,ILAT,IB,1)=AAOD_SUN_ORIG(IB,ILAT,JLEV,12)
                REFAOD_SUN(ILEV,ILAT,IB,1)=REFAOD_SUN_ORIG(IB,ILAT,JLEV,12)
                DO IMONTH=2,STRATO_CMIP_NMONTH
                  AOD_SUN(ILEV,ILAT,IB,IMONTH)=AOD_SUN_ORIG(IB,ILAT,JLEV,IMON-2+IMONTH)
                  AAOD_SUN(ILEV,ILAT,IB,IMONTH)=AAOD_SUN_ORIG(IB,ILAT,JLEV,IMON-2+IMONTH)
                  REFAOD_SUN(ILEV,ILAT,IB,IMONTH)=REFAOD_SUN_ORIG(IB,ILAT,JLEV,IMON-2+IMONTH)
                ENDDO
              ENDDO
              ! LW parameter
              DO IB=1,STRATO_CMIP_NTB
                AAOD_EARTH(ILEV,ILAT,IB,1)=AAOD_EARTH_ORIG(IB,ILAT,JLEV,12)
                DO IMONTH=2,STRATO_CMIP_NMONTH
                  AAOD_EARTH(ILEV,ILAT,IB,IMONTH)=AAOD_EARTH_ORIG(IB,ILAT,JLEV,IMON-2+IMONTH)
                ENDDO
              ENDDO
            ENDDO
          ENDDO

        ELSEIF(IMON==12) THEN
          DO ILEV=1,STRATO_CMIP_NALT
            JLEV=STRATO_CMIP_NALT-ILEV+1
            DO ILAT=1,STRATO_CMIP_NLAT
              ! SW parameters
              DO IB=1,STRATO_CMIP_NSB
                ! We keep three months to make a smoothed forcing (linear interpolation along the axis time)
                DO IMONTH=1,STRATO_CMIP_NMONTH-1
                  AOD_SUN(ILEV,ILAT,IB,IMONTH)=AOD_SUN_ORIG(IB,ILAT,JLEV,IMON-2+IMONTH)
                  AAOD_SUN(ILEV,ILAT,IB,IMONTH)=AAOD_SUN_ORIG(IB,ILAT,JLEV,IMON-2+IMONTH)
                  REFAOD_SUN(ILEV,ILAT,IB,IMONTH)=REFAOD_SUN_ORIG(IB,ILAT,JLEV,IMON-2+IMONTH)
                ENDDO
                AOD_SUN(ILEV,ILAT,IB,STRATO_CMIP_NMONTH)=AOD_SUN_ORIG(IB,ILAT,JLEV,1)
                AAOD_SUN(ILEV,ILAT,IB,STRATO_CMIP_NMONTH)=AAOD_SUN_ORIG(IB,ILAT,JLEV,1)
                REFAOD_SUN(ILEV,ILAT,IB,STRATO_CMIP_NMONTH)=REFAOD_SUN_ORIG(IB,ILAT,JLEV,1)
              ENDDO
              ! LW parameter
              DO IB=1,STRATO_CMIP_NTB
                DO IMONTH=1,STRATO_CMIP_NMONTH-1
                  AAOD_EARTH(ILEV,ILAT,IB,IMONTH)=AAOD_EARTH_ORIG(IB,ILAT,JLEV,IMON-2+IMONTH)
                ENDDO
                AAOD_EARTH(ILEV,ILAT,IB,STRATO_CMIP_NMONTH)=AAOD_EARTH_ORIG(IB,ILAT,JLEV,1)
              ENDDO
            ENDDO
          ENDDO

        ELSE 
          DO ILEV=1,STRATO_CMIP_NALT
            JLEV=STRATO_CMIP_NALT-ILEV+1
            DO ILAT=1,STRATO_CMIP_NLAT
              ! SW parameters
              DO IB=1,STRATO_CMIP_NSB
                ! We keep three months to make a smoothed forcing (linear interpolation along the axis time)
                DO IMONTH=1,STRATO_CMIP_NMONTH
                  AOD_SUN(ILEV,ILAT,IB,IMONTH)=AOD_SUN_ORIG(IB,ILAT,JLEV,IMON-2+IMONTH)
                  AAOD_SUN(ILEV,ILAT,IB,IMONTH)=AAOD_SUN_ORIG(IB,ILAT,JLEV,IMON-2+IMONTH)
                  REFAOD_SUN(ILEV,ILAT,IB,IMONTH)=REFAOD_SUN_ORIG(IB,ILAT,JLEV,IMON-2+IMONTH)
                ENDDO
              ENDDO
              ! LW parameter
              DO IB=1,STRATO_CMIP_NTB
                DO IMONTH=1,STRATO_CMIP_NMONTH
                  AAOD_EARTH(ILEV,ILAT,IB,IMONTH)=AAOD_EARTH_ORIG(IB,ILAT,JLEV,IMON-2+IMONTH)
                ENDDO
              ENDDO
            ENDDO
          ENDDO
        ENDIF !IMON
        DEALLOCATE(AOD_SUN_ORIG   )
        DEALLOCATE(AAOD_SUN_ORIG  )
        DEALLOCATE(REFAOD_SUN_ORIG)
        DEALLOCATE(AAOD_EARTH_ORIG)
      ENDIF CMIP
    ENDIF AVAIL
  ENDIF ROOT
  
  CALL BROADCAST_AER_CMIP_PROP(YDMODEL)
  LSTRATAERO_UPDATED = .TRUE. ! In effect it means "need remapping"

ENDIF NEWMONTH

END ASSOCIATE
END ASSOCIATE
END ASSOCIATE
END ASSOCIATE
END ASSOCIATE

IF (LHOOK) CALL DR_HOOK('CMIP_STRATO_AERO',1,ZHOOK_HANDLE)

CONTAINS

  SUBROUTINE CHECK(STATUS)
    INTEGER, INTENT ( IN) :: STATUS

    IF(STATUS /= NF90_NOERR) THEN
      CALL ABOR1('CMIP_STRATO_AERO: '//TRIM(NF90_STRERROR(STATUS)))
    END IF
  END SUBROUTINE CHECK

!--------------------------------------------------------------------------------------------------------------

 SUBROUTINE BROADCAST_AER_CMIP_PROP(YDMODEL)
    !--- inherited types, functions and data
    USE YOMHOOK,    ONLY: LHOOK, DR_HOOK, JPHOOK
    USE MPL_MODULE, ONLY: MPL_BROADCAST

    USE YOEAEROP,   ONLY: STRATO_CMIP_LAT
    USE TYPE_MODEL, ONLY: MODEL

    IMPLICIT NONE
    
    TYPE(MODEL), INTENT(INOUT) :: YDMODEL
    !---local data
    REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

    !---executable procedure
    IF (LHOOK) CALL DR_HOOK('BROADCAST_AER_CMIP_PROP',0,ZHOOK_HANDLE)

    ASSOCIATE(&
      &  YDPHYAER     => YDMODEL%YRML_PHY_AER  &
      )
    
    ASSOCIATE(&
        & YDAERSTRAT        => YDPHYAER%YREAEROSTRAT &
        )
    
    ASSOCIATE(&
      & AOD_SUN=>YDAERSTRAT%AOD_SUN,AAOD_SUN=>YDAERSTRAT%AAOD_SUN, &
      & AAOD_EARTH=>YDAERSTRAT%AAOD_EARTH,REFAOD_SUN=>YDAERSTRAT%REFAOD_SUN&
        )

      CALL MPL_BROADCAST(AOD_SUN,          KTAG=ITAG+1,KROOT=RPRC,CDSTRING='AER_CMIP_PROP-1: ')
      CALL MPL_BROADCAST(AAOD_SUN,         KTAG=ITAG+2,KROOT=RPRC,CDSTRING='AER_CMIP_PROP-2: ')
      CALL MPL_BROADCAST(REFAOD_SUN,       KTAG=ITAG+3,KROOT=RPRC,CDSTRING='AER_CMIP_PROP-3: ')
      CALL MPL_BROADCAST(AAOD_EARTH,       KTAG=ITAG+4,KROOT=RPRC,CDSTRING='AER_CMIP_PROP-4: ')
      CALL MPL_BROADCAST(STRATO_CMIP_LAT,  KTAG=ITAG+5,KROOT=RPRC,CDSTRING='AER_CMIP_PROP-5: ')
    END ASSOCIATE
    END ASSOCIATE
    END ASSOCIATE
    IF (LHOOK) CALL DR_HOOK('BROADCAST_AER_CMIP_PROP',1,ZHOOK_HANDLE)
  END SUBROUTINE BROADCAST_AER_CMIP_PROP

END SUBROUTINE CMIP_STRATO_AERO
