SUBROUTINE CMIP_STRATO_AERO_INTERP & 
&(YDMODEL, KIDIA, KFDIA, KLON ,KLEV,        &
& KRINT, KSHIFT,                    &
& PAPRS, PGELAM, PSINLAT,           &
& STRATAOD, STRATAAOD, STRATREFAOD, &
& STRATAAOD_LW)

!     PURPOSE.
!     --------

!     INTERFACE.
!     ----------
!     CALL *CMIP_STRATO_AERO_INTERP* FROM *RADLSWR*

!     AUTHOR.
!     -------
!     M.Ménégoz for EC-EARTH 2017
!     A.Laakso for EC-EARTH4/OIFS 2022
!
!     Horizontal interpolation of the stratospheric aerosol CMIP
!     dataset. The data need to have the correct vertical resolution.
!     The vertical interpolation is done off-line.
!     The horizontal interpolation id done on-line.
!     In the SW, the triplet (AOD, AAOD, REFAOD) is used
!     In the LW, only AAOD is used, since only the aerosol absorption
!     is taken into account in IFS (aerosol scattering neglected in
!     the LW in IFS)

!     MODIFICATIONS.
!     -------------- 

!---------------------------------------------------------------------

!--- inherited types, functions and data
USE PARKIND1, ONLY: JPIM, JPRB, JPRD
USE YOMHOOK,  ONLY: LHOOK, DR_HOOK, JPHOOK
USE YOMLUN,   ONLY: NULOUT, NULERR
USE YOMCST,   ONLY: RPI
USE YOMMP0,   ONLY: MYPROC

USE YOEAEROP, ONLY: STRATO_CMIP_NLAT, STRATO_CMIP_NALT, STRATO_CMIP_NTIME, &
                & STRATO_CMIP_LAT, STRATO_CMIP_SB, STRATO_CMIP_TB,         &
                & STRATO_CMIP_NSB, STRATO_CMIP_NTB, STRATO_CMIP_NMONTH

USE YOMCT3,     ONLY: NSTEP
USE TYPE_MODEL, ONLY: MODEL

IMPLICIT NONE
TYPE(MODEL),       INTENT(IN)  :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN)  :: KLON 
INTEGER(KIND=JPIM),INTENT(IN)  :: KLEV 
INTEGER(KIND=JPIM),INTENT(IN)  :: KIDIA 
INTEGER(KIND=JPIM),INTENT(IN)  :: KFDIA 
INTEGER(KIND=JPIM),INTENT(IN)  :: KRINT 
INTEGER(KIND=JPIM),INTENT(IN)  :: KSHIFT 
REAL(KIND=JPRB)   ,INTENT(IN)  :: PAPRS(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(IN)  :: PGELAM(KLON)
REAL(KIND=JPRB)   ,INTENT(IN)  :: PSINLAT(KLON)
REAL(KIND=JPRB)   ,INTENT(OUT) :: STRATAOD(KLON,KLEV,STRATO_CMIP_NSB,STRATO_CMIP_NMONTH)
REAL(KIND=JPRB)   ,INTENT(OUT) :: STRATAAOD(KLON,KLEV,STRATO_CMIP_NSB,STRATO_CMIP_NMONTH)
REAL(KIND=JPRB)   ,INTENT(OUT) :: STRATREFAOD(KLON,KLEV,STRATO_CMIP_NSB,STRATO_CMIP_NMONTH)
REAL(KIND=JPRB)   ,INTENT(OUT) :: STRATAAOD_LW(KLON,KLEV,STRATO_CMIP_NTB,STRATO_CMIP_NMONTH)

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

INTEGER(KIND=JPIM), PARAMETER :: RPRC = 1

REAL(KIND=JPRB) :: ZSTRATAOD(KLON,KLEV)
REAL(KIND=JPRB) :: ZSTRATAAOD(KLON,KLEV)
REAL(KIND=JPRB) :: ZSTRATREFAOD(KLON,KLEV)
REAL(KIND=JPRB) :: ZSTRATAAOD_LW(KLON,KLEV)

REAL(KIND=JPRB) :: ZAOD_SUN(STRATO_CMIP_NALT, STRATO_CMIP_NLAT)
REAL(KIND=JPRB) :: ZAAOD_SUN(STRATO_CMIP_NALT, STRATO_CMIP_NLAT)
REAL(KIND=JPRB) :: ZREFAOD_SUN(STRATO_CMIP_NALT, STRATO_CMIP_NLAT)
REAL(KIND=JPRB) :: ZAAOD_EARTH(STRATO_CMIP_NALT, STRATO_CMIP_NLAT)

REAL(KIND=JPRB) :: ZLAT(KLON)
REAL(KIND=JPRB) :: ZGLAT(KLON)
REAL(KIND=JPRB) :: ZGLON(KLON)
REAL(KIND=JPRB) :: ZRPI
INTEGER(KIND=JPIM) :: IMONTH, ILEV
INTEGER(KIND=JPIM) :: JN, JL, JK

REAL, POINTER :: AOD_SUN(:,:,:,:), AAOD_SUN(:,:,:,:), AAOD_EARTH(:,:,:,:), REFAOD_SUN(:,:,:,:)
REAL, POINTER :: STRATO_CMIP_ALT(:)

#include "abor1.intfb.h"

!---executable procedure
IF (LHOOK) CALL DR_HOOK('CMIP_STRATO_AERO_INTERP',0,ZHOOK_HANDLE)

ASSOCIATE(YDPHYAER     => YDMODEL%YRML_PHY_AER)
ASSOCIATE(YDAERSTRAT   => YDPHYAER%YREAEROSTRAT)
ASSOCIATE(&
  & AOD_SUN=>YDAERSTRAT%AOD_SUN,AAOD_SUN=>YDAERSTRAT%AAOD_SUN, &
  & AAOD_EARTH=>YDAERSTRAT%AAOD_EARTH,STRATO_CMIP_ALT=>YDAERSTRAT%STRATO_CMIP_ALT,&
  & REFAOD_SUN=>YDAERSTRAT%REFAOD_SUN&
  )

  STRATAOD(KIDIA:KFDIA,:,:,:)=0._JPRB   
  STRATAAOD(KIDIA:KFDIA,:,:,:)=0._JPRB 
  STRATREFAOD(KIDIA:KFDIA,:,:,:)=0._JPRB 
  STRATAAOD_LW(KIDIA:KFDIA,:,:,:)=0._JPRB 
  ZAOD_SUN(KIDIA:KFDIA,:)=0._JPRB 
  ZAAOD_SUN(KIDIA:KFDIA,:)=0._JPRB 
  ZREFAOD_SUN(KIDIA:KFDIA,:)=0._JPRB 
  ZAAOD_EARTH(KIDIA:KFDIA,:)=0._JPRB 

  ZSTRATAOD(KIDIA:KFDIA,:)=0._JPRB
  ZSTRATAAOD(KIDIA:KFDIA,:)=0._JPRB
  ZSTRATREFAOD(KIDIA:KFDIA,:)=0._JPRB
  ZSTRATAAOD_LW(KIDIA:KFDIA,:)=0._JPRB

  ZRPI=1.0_JPRB/RPI
  DO JL=KIDIA,KFDIA
    ZLAT(JL) = ASIN(PSINLAT(JL))
    ZGLAT(JL)= ZLAT(JL) * 180._JPRB*ZRPI
    ZGLON(JL)= PGELAM(JL) * 180._JPRB*ZRPI  
  END DO

  DO JN=1,STRATO_CMIP_NSB
    DO IMONTH=1,STRATO_CMIP_NMONTH
      IF (STRATO_CMIP_NALT == KLEV) THEN
        ! No vertical regridding, therefore no conversion to intensive properties
        ZAOD_SUN(:,:)=AOD_SUN(:,:,JN,IMONTH)
        ZAAOD_SUN(:,:)=AAOD_SUN(:,:,JN,IMONTH)
        ZREFAOD_SUN(:,:)=REFAOD_SUN(:,:,JN,IMONTH)
      ELSE
        WRITE(NULERR,*) 'MITKA', STRATO_CMIP_NALT, KLEV
        CALL ABOR1('Number of levels of stratospheric aerosol CMIP forcing unequal to model resolution!')
      ENDIF

      CALL INTERPOLATE_STRATAERO(KIDIA, KFDIA, KLON, KLEV, KRINT, KSHIFT, &
                         &  PGELAM, PSINLAT, STRATO_CMIP_LAT, &
                         &  PAPRS, ZAOD_SUN, ZSTRATAOD )

      CALL INTERPOLATE_STRATAERO(KIDIA, KFDIA, KLON, KLEV, KRINT, KSHIFT, &
                         &  PGELAM, PSINLAT, STRATO_CMIP_LAT, &
                         &  PAPRS, ZAAOD_SUN, ZSTRATAAOD )

      CALL INTERPOLATE_STRATAERO(KIDIA, KFDIA, KLON, KLEV, KRINT, KSHIFT, &
                         &  PGELAM, PSINLAT, STRATO_CMIP_LAT, &
                         &  PAPRS, ZREFAOD_SUN, ZSTRATREFAOD)
 
      DO JL=KIDIA,KFDIA,KRINT
        STRATAOD(JL,:,JN,IMONTH)=ZSTRATAOD(JL,:)
        STRATAAOD(JL,:,JN,IMONTH)=ZSTRATAAOD(JL,:)
        STRATREFAOD(JL,:,JN,IMONTH)=ZSTRATREFAOD(JL,:)
      END DO

    END DO
  END DO

  DO JN=1,STRATO_CMIP_NTB
    DO IMONTH=1,STRATO_CMIP_NMONTH
      IF (STRATO_CMIP_NALT == KLEV) THEN
        ! No vertical regridding, therefore no conversion to intensive properties
        ZAAOD_EARTH(:,:)=AAOD_EARTH(:,:,JN,IMONTH)
      ELSE
        CALL ABOR1('Number of levels of stratospheric aerosol CMIP forcing unequal to model resolution!')
      ENDIF

      CALL INTERPOLATE_STRATAERO(KIDIA, KFDIA, KLON, KLEV, KRINT, KSHIFT, &
                         &  PGELAM, PSINLAT, STRATO_CMIP_LAT, &
                         &  PAPRS, ZAAOD_EARTH, ZSTRATAAOD_LW )

      DO JL=KIDIA,KFDIA,KRINT
        STRATAAOD_LW(JL,:,JN,IMONTH)=ZSTRATAAOD_LW(JL,:)
      END DO
    END DO
  END DO
  
END ASSOCIATE
END ASSOCIATE
END ASSOCIATE

IF (LHOOK) CALL DR_HOOK('CMIP_STRATO_AERO_INTERP',1,ZHOOK_HANDLE)

CONTAINS
 
  !--------------------------------------------------------------------------------------------------------------
  SUBROUTINE INTERPOLATE_STRATAERO(KIDIA, KFDIA, KLON, KLEV, KRINT, KSHIFT, &
                        &  PGELAM, PSINLAT, PSTRATO_CMIP_LAT, &
                        &  PAPRS, PIN_FIELD, POUT_FIELD )

USE YOMHOOK, ONLY : LHOOK, DR_HOOK
USE YOMCST,  ONLY : RPI 
!---subroutine interface
INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM), INTENT(IN) :: KLON
INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN)  :: KRINT 
INTEGER(KIND=JPIM),INTENT(IN)  :: KSHIFT 
REAL(KIND=JPRB), INTENT(IN) :: PGELAM(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PSINLAT(KLON)
REAL(KIND=JPRB), INTENT(IN) :: PSTRATO_CMIP_LAT(STRATO_CMIP_NLAT)
REAL(KIND=JPRB), INTENT(IN) :: PIN_FIELD(STRATO_CMIP_NALT,STRATO_CMIP_NLAT)
REAL(KIND=JPRB), INTENT(IN) :: PAPRS(KLON,KLEV+1) 

REAL(KIND=JPRB), INTENT(OUT) :: POUT_FIELD(KLON,KLEV)
!---local data
INTEGER(KIND=JPIM) :: IINLA1(KLON), IINLA2(KLON)
INTEGER(KIND=JPIM) :: IINLO1(KLON), IINLO2(KLON)
INTEGER(KIND=JPIM) :: IL, JL, JLR, JK 
INTEGER(KIND=JPIM) :: INLA1, INLA2, INLO1, INLO2, ILEV, INLA

REAL(KIND=JPRB) :: ZSILAT(KLON)
REAL(KIND=JPRB) :: ZLON(KLON)
REAL(KIND=JPRB) :: ZNLO1(KLON)
REAL(KIND=JPRB) :: ZNLO2(KLON)

REAL(KIND=JPRB) :: ZGELAM(KLON)
REAL(KIND=JPRB) :: ZAER1, ZAER2,ZRPI, Z2PI, ZZRPI
REAL(KIND=JPRB) :: ZAERLEV1, ZAERLEV2 

REAL(KIND=JPRB) :: ZSINT

REAL(KIND=JPRB) :: ZSINR(STRATO_CMIP_NLAT)
REAL(KIND=JPRB) :: ZGRIDR, ZLATR, ZDLONR

!---local data
REAL(KIND=JPRB) :: ZOUT_FIELD(KLON, STRATO_CMIP_NALT)
REAL(KIND=JPRB) :: ZP_STR_LEV(KLON, STRATO_CMIP_NALT)
REAL(KIND=JPRB) :: ZINFIELD(KLON, STRATO_CMIP_NALT)
REAL(KIND=JPRB) :: ZPRE(KLON)

REAL(KIND=JPRB) :: ZRRR
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "abor1.intfb.h"
POUT_FIELD(:,:)=0._JPRB
!ZOUT_FIELD(:,:)=0._JPRB
IINLA1(:)=0
IINLA2(:)=0
ZSILAT(:)=0._JPRB
ZAER1=0._JPRB
!---executable procedure
IF (LHOOK) CALL DR_HOOK('INTERPOLATE_STRATAERO',0, ZHOOK_HANDLE)

!================================================================================================
!
ZRPI=RPI/180.0_JPRB
Z2PI=2._JPRB*RPI
ZZRPI=180._JPRB/RPI
ZSINR(:) = SIN(ZRPI*PSTRATO_CMIP_LAT(:))

!-- latitudinal interpolation
IL=KSHIFT
DO JL=KIDIA,KFDIA,KRINT 
  IL=IL+1
  IINLA1(IL)=0
  IINLA2(IL)=0
  ZSILAT(IL)=-9999._JPRB
  ZSINT=PSINLAT(JL)
  IF (ZSINT <= ZSINR(1)) THEN
    INLA=1
    IINLA1(IL)=1
    IINLA2(IL)=1
    ZSILAT(IL)=0._JPRB
  ENDIF
  IF (ZSINT >= ZSINR(STRATO_CMIP_NLAT)) THEN
    INLA=STRATO_CMIP_NLAT
    IINLA1(IL)=STRATO_CMIP_NLAT
    IINLA2(IL)=STRATO_CMIP_NLAT
    ZSILAT(IL)=0._JPRB
  ENDIF

  DO JLR=1,STRATO_CMIP_NLAT-1

    IF (ZSINT >= ZSINR(JLR) .AND. ZSINT < ZSINR(JLR+1)) THEN
      INLA=JLR
      IINLA1(IL)=JLR
      IINLA2(IL)=JLR+1
      ZSILAT(IL)=(ZSINT-ZSINR(INLA))/(ZSINR(INLA+1)-ZSINR(INLA))
    ENDIF
    
  ENDDO

  !IF (INLA == 0) THEN 
  IF (IINLA1(IL) == 0 .OR. IINLA2(IL) == 0) THEN
    CALL ABOR1(' Problem with lat. interpolation in in CMIP_strato_aero_interp!')
  ENDIF
ENDDO

DO JK=1,STRATO_CMIP_NALT
  !-- compute interpolated field
  IL=KSHIFT
  DO JL=KIDIA,KFDIA, KRINT
    IL=IL+1
    INLA1=IINLA1(IL)
    INLA2=IINLA2(IL)

    ZAER1=PIN_FIELD(JK,INLA1) &
         & +ZSILAT(IL)*(PIN_FIELD(JK,INLA2)-PIN_FIELD(JK,INLA1))
    POUT_FIELD(IL,JK)=ZAER1

  END DO
END DO         ! JK (vertical loop)
     
!================================================================================================
! DO JL=KIDIA,KFDIA, KRINT
!   POUT_FIELD(JL,:) = ZOUT_FIELD(JL,:)
! END DO

!================================================================================================ 

IF (LHOOK) CALL DR_HOOK('INTERPOLATE_STRATAERO',1,ZHOOK_HANDLE)
END SUBROUTINE INTERPOLATE_STRATAERO
  !--------------------------------------------------------------------------------------------------------------

END SUBROUTINE CMIP_STRATO_AERO_INTERP
