! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

#ifdef RS6K
@PROCESS NOCHECK
#endif
SUBROUTINE EC_PHYS_DRV(YDGEOMETRY,YDFIELDS,YDVARS,YDGMV,YDSURF,YDMODEL,CDCONF,&
      & PB2,PPBUP9, PPBVP9, PPBTP9,PPBGFLP9,PEXTRADYN,PSD_PF,&
      & PGMV,PGMVS,PGMVT1,PGMVT1S,&
      & PGFLT1,PGFLPT,PGFL,PGFLSLP,&
      & PSP_SB,PSP_SG,PSP_SL,PSP_RR,&
      & PSP_EP,PSP_X2,&
      & PSD_VF,PSD_VN,PSD_VD,&
      & PSD_WS,PSD_WW,&
      & PSD_XA,PSD_X2,&
      & PSD_SM,&
      & PSP_OM,PSD_V2,PSD_V3,&!KPP
      & YDTILEPROP,&
      & YDPHYSMWAVE,&
      & PSMOS_OBS_BUF,PSMOS_TB_BUF,PSMOS_ANGLE,PSMOS_FARAD,PSMOS_GEOMET,&
      & KSMOS_BUF,PSMAP_OBS_BUF,PSMAP_TB_BUF,PSMAP_ANGLE,KSMAP_BUF,&
      & PTRAJEC,PTRAJEC_OOPS)

!**** *EC_PHYS_DRV* - Coarse physics driver routine

!     Purpose.
!     --------
!           The motivation for this routine is primarily to call EC_PHYS.
!           It emulates RADDRV

!**   Interface.
!     ----------
!        *CALL* *EC_PHYS_DRV(CDCONF,PB2,PPBUP9, PPBVP9, PPBTP9,PPBGFLP9)*

!        Explicit arguments :
!        --------------------
!        CDCONF    : configuration of work
!        PB2       : input grid point array

!        Implicit arguments :
!        --------------------

!     Method.
!     -------
!        See documentation

!     Externals.
!     ----------
!        Called by GP_MODEL.

!     Reference.
!     ----------
!        see documentation

!     Author.
!     -------
!        M. Hortal after George Mozdzynski's RADDRV  *ECMWF*

!     Modifications.
!     --------------
!      Original : 05-02-14
!        J. Hague      22-Nov-2005  Clean Load balancing
!   N. Wedi and K. Yessad (Jan 2008): different dev for NH model and PC scheme
!      GMozdzynski/JJMorcrette 20080128 bugfix dynamical extra fields
!      JJMorcrette 20070321 Prognostic aerosols in radiation and clouds
!        A. Geer       15-Apr-2008  Multiple sensors for rainy 4D-Var
!        A. Geer       10-Jun-2008  Rainy 4D-Var passive mode and diagnostics
!        A. Geer       01-Oct-2008  Rainy 4D-Var tidying
!        Y. Takaya     01-Feb-2009  Ocean mixed layer model
!        W. Bell       06-Mar-2009  Add Windsat azimuth angle
!      K. Yessad (Nov 2009): prune lpc_old.
!        JJMorcrette 20091201 Total and clear-sky direct SW radiation flux at surface
!    R.Forbes/A.Tompkins  Dec 2009  Remove liq water/ice split,add snow/rain
!    F. Karbou     16-Dec-2009  Surface emissivity estimation
!    P. Lopez      07-Oct-2010 Added handling of ground-based radar precip data (GBRAD)
!    G.Mozdzynski (Feb 2011): OOPS cleaning, use of derived type TGSGEOM
!    M Ahlgrimm 31 Oct 2011  Clear-sky downward radiation at surface
!    A. Geer       14-Dec-2011 Removed the all-sky observation operator
!    P. Lopez      17-Aug-2012  Added rain gauge assimilation (RAINGG)
!    F. Vana       15-Mar-2013  Adapted to the new derived structures dataflow + cleaning.
!    F. Vana       28-Nov-2013 : Redesigned trajectory handling
!    G. Balsamo    15-Jan-2014  Add lake prognostic buffer
!    M. Ahlgrimm Apr 2014: Add precip fraction buffer for DDH output
!    T. Wilhelmsson (Sept 2013) Geometry and setup refactoring.
!    F. Vana       28-Nov-2013 : Redesigned trajectory handling
!    R. Hogan      29-May-2014 : Added surface downwelling longwave
!    K. Yessad      (July 2014): Move some variables.
!    F. Vana       17-Dec-2015 : Small fix in stoch. physics
!    M. Leutbecher & S.-J. Lock 27-Jan-2016 : Introduced SPP scheme (LSPP)
!    S. Lang       21-Jan-2016 : add constrain to SPPT perturbed tendencies (LSPPTGFIX)
!    A. Geer       04-Jan-2017 : remove rainy 1D-Var code
!    E. Dutra/G.Arduini Jan 2018 : snow multi-layer PSP_SG 4 dimensions
!    M. Lange      10-Jan-2020 : Adding VARIABLE and FIELD types in EC-physics and surface (IFS-1175)
!    P. Weston     20-Aug-2020 : Add SMAP
!    M. Leutbecher 12-Oct-2020 : removed spp_mod
!    S. Massart   March-2021 : Adding BFAS parameters
!     ------------------------------------------------------------------

USE TYPE_MODEL         , ONLY : MODEL
USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE FIELDS_MOD         , ONLY : FIELDS
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMGMV             , ONLY : TGMV
USE PARKIND1           , ONLY : JPIM, JPRB
USE YOMHOOK            , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMCT3             , ONLY : NSTEP
USE YOMLCZ             , ONLY : GPFORCEU, GPFORCEV, GPFORCET, GPFORCEQ
USE YOMSMOS            , ONLY : NPOL_MAX, NANG_MAX
USE YOMDYNCORE         , ONLY : LHELDSUAREZ
USE YOE_AERODIAG       , ONLY : NPAERODIAG
USE YOE_TILE_PROP      , ONLY : TETILEPROP
USE YOE_PHYS_MWAVE     , ONLY : TEPHYSMWAVE
USE YOMPHYDER          , ONLY : SURF_AND_MORE_TYPE, PERTURB_TYPE, MODEL_STATE_TYPE, AUX_TYPE, AUX_RAD_TYPE,&
 &                              DIMENSION_TYPE, FLUX_TYPE, AUX_DIAG_TYPE, AUX_DIAG_LOCAL_TYPE, DDH_SURF_TYPE, &
 &                              SURF_AND_MORE_LOCAL_TYPE, KEYS_LOCAL_TYPE, PERTURB_LOCAL_TYPE
USE YOMTRAJ            , ONLY : TRAJ_TYPE, TRAJ_PHYS_TYPE
USE YOMTRAJ_OOPS       , ONLY : TRAJ_TYPE_OOPS
USE ECPHYS_STATE_TYPE_MOD, ONLY: STATE_TYPE, MASK_GFL_TYPE
USE FIELD_VARIABLES_MOD, ONLY: FIELD_VARIABLES
USE YOMVAR             , ONLY : LECV
USE YOMJBECV           , ONLY : YRECV5
USE YOMJBECPHYSECV      , ONLY : LSIGFLTORO, GET_PHYS_ECV




!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)         :: YDGEOMETRY
TYPE(FIELDS)      ,INTENT(INOUT)      :: YDFIELDS
TYPE(FIELD_VARIABLES), INTENT(INOUT)  :: YDVARS
TYPE(TGMV)        ,INTENT(INOUT)      :: YDGMV
TYPE(TSURF)       ,INTENT(INOUT)      :: YDSURF
TYPE(MODEL)       ,INTENT(INOUT),TARGET :: YDMODEL
CHARACTER         ,INTENT(IN)         :: CDCONF
REAL(KIND=JPRB)   ,INTENT(IN),TARGET  :: PB2(YDGEOMETRY%YRDIM%NPROMA,YDMODEL%YRML_DYN%YRPTRSLB2%NFLDSLB2,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(IN),TARGET  :: PPBUP9(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(IN),TARGET  :: PPBVP9(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(IN),TARGET  :: PPBTP9(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(IN),TARGET  :: PPBGFLP9(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG, &
 &                                                YDMODEL%YRML_GCONF%YGFL%NDIMSLP,&
 &                                                YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(IN) , TARGET   :: PEXTRADYN(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG, &
 &                                                    YDMODEL%YRML_PHY_G%YRDPHY%NVEXTRDYN,&
 &                                                    YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT), TARGET :: PSD_PF(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSD_PFD%NLEVS,YDSURF%YSD_PFD%NDIM,&
 &                                                 YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGMV(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGMV%NDIMGMV,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGMVS(YDGEOMETRY%YRDIM%NPROMA,YDGMV%NDIMGMVS,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGMVT1(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGMV%YT1%NDIM,&
 &                                         YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGMVT1S(YDGEOMETRY%YRDIM%NPROMA,YDGMV%YT1%NDIMS,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGFLT1(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM1, &
 &                                         YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGFLPT(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIMPT, &
 &                                         YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGFL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM, &
 &                                       YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PGFLSLP(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIMSLP,&
 &                                          YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT), TARGET :: PSP_SB(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSP_SBD%NLEVS,YDSURF%YSP_SBD%NDIM,&
 &                                                 YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT), TARGET :: PSP_SG(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSP_SGD%NLEVS,YDSURF%YSP_SGD%NDIM,&
 &                                                 YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT), TARGET :: PSP_SL(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSP_SLD%NDIM,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT), TARGET :: PSP_RR(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSP_RRD%NDIM,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT), TARGET :: PSP_EP(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSP_EPD%NLEVS,YDSURF%YSP_EPD%NDIM,&
 &                                                 YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT), TARGET :: PSP_X2(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSP_X2D%NDIM,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT), TARGET :: PSD_VF(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSD_VFD%NDIM,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT), TARGET :: PSD_VN(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSD_VND%NDIM,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT), TARGET :: PSD_VD(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSD_VDD%NDIM,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT), TARGET :: PSD_WS(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSD_WSD%NDIM,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT), TARGET :: PSD_WW(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSD_WWD%NDIM,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT), TARGET :: PSD_XA(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSD_XAD%NLEVS,YDSURF%YSD_XAD%NDIM,&
 &                                                 YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT), TARGET :: PSD_X2(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSD_X2D%NDIM,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT), TARGET :: PSD_SM(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSD_SMD%NLEVS,YDSURF%YSD_SMD%NDIM,&
 &                                                 YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT), TARGET :: PSP_OM(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSP_OMD%NLEVS,YDSURF%YSP_OMD%NDIM,&
 &                                                 YDGEOMETRY%YRDIM%NGPBLKS)  !KPP
REAL(KIND=JPRB)   ,INTENT(INOUT), TARGET :: PSD_V2(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSD_V2D%NDIM,YDGEOMETRY%YRDIM%NGPBLKS) !KPP
REAL(KIND=JPRB)   ,INTENT(INOUT), TARGET :: PSD_V3(YDGEOMETRY%YRDIM%NPROMA,YDSURF%YSD_V3D%NLEVS,YDSURF%YSD_V3D%NDIM,&
 &                                                 YDGEOMETRY%YRDIM%NGPBLKS)  !KPP
TYPE(TETILEPROP), INTENT(INOUT), TARGET  :: YDTILEPROP
TYPE(TEPHYSMWAVE), INTENT(INOUT), TARGET  :: YDPHYSMWAVE
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSMOS_OBS_BUF(YDGEOMETRY%YRGEM%NGPTOT,0:NPOL_MAX-1,NANG_MAX)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSMOS_ANGLE(YDGEOMETRY%YRGEM%NGPTOT,0:NPOL_MAX-1,NANG_MAX)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSMOS_FARAD(YDGEOMETRY%YRGEM%NGPTOT,0:NPOL_MAX-1,NANG_MAX)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSMOS_GEOMET(YDGEOMETRY%YRGEM%NGPTOT,0:NPOL_MAX-1,NANG_MAX)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PSMOS_TB_BUF(YDGEOMETRY%YRGEM%NGPTOT,0:NPOL_MAX-1,NANG_MAX)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KSMOS_BUF(YDGEOMETRY%YRGEM%NGPTOT,0:NPOL_MAX-1,NANG_MAX)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSMAP_OBS_BUF(YDGEOMETRY%YRGEM%NGPTOT,0:NPOL_MAX-1)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSMAP_ANGLE(YDGEOMETRY%YRGEM%NGPTOT,0:NPOL_MAX-1)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PSMAP_TB_BUF(YDGEOMETRY%YRGEM%NGPTOT,0:NPOL_MAX-1)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KSMAP_BUF(YDGEOMETRY%YRGEM%NGPTOT,0:NPOL_MAX-1)
TYPE(TRAJ_TYPE)      ,TARGET ,OPTIONAL, INTENT(INOUT) :: PTRAJEC
TYPE(TRAJ_TYPE_OOPS) ,TARGET ,OPTIONAL, INTENT(INOUT) :: PTRAJEC_OOPS
REAL(KIND=JPRB), DIMENSION(:,:,:,:,:), ALLOCATABLE, TARGET :: ZSPPTGFIX

INTEGER(KIND=JPIM), TARGET :: IBL,ICEND,JKGLO
INTEGER(KIND=JPIM)         :: IOFF,ICST

LOGICAL :: LLRADFR

TYPE (MASK_GFL_TYPE) :: KEYMASK, KMASK_SDT
TYPE (STATE_TYPE) :: STATE_T0, TENDENCY_DYN, TENDENCY_CML
TYPE (STATE_TYPE) :: STATE_TMP, TENDENCY_TMP, TENDENCY_VDF, TENDENCY_SATADJ, TENDENCY_LOC
TYPE (STATE_TYPE), ALLOCATABLE :: TENDENCY_PHY(:)

TYPE (SURF_AND_MORE_TYPE) :: ZSURF
TYPE (PERTURB_TYPE)       :: ZPERT
TYPE (MODEL_STATE_TYPE)   :: ZSLPHY9
TYPE (AUX_TYPE)           :: ZAUX
TYPE (AUX_RAD_TYPE)       :: ZRAD
TYPE (FLUX_TYPE)          :: ZFLUX
TYPE (AUX_DIAG_TYPE)      :: ZDIAG
TYPE (AUX_DIAG_LOCAL_TYPE):: ZAUXL
TYPE (DDH_SURF_TYPE)      :: ZDDHS
TYPE (SURF_AND_MORE_LOCAL_TYPE) :: ZSURFL
TYPE (KEYS_LOCAL_TYPE)    :: ZLLKEYS
TYPE (PERTURB_LOCAL_TYPE) :: ZPERTL
TYPE (DIMENSION_TYPE)     :: IDIMS
TYPE (TRAJ_PHYS_TYPE), POINTER :: TRAJECTORY_PHYSICS

INTEGER(KIND=JPIM) :: J2D

!!! Array with dynamics tendency of GFL
REAL(KIND=JPRB) :: ZGFL_DYN(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM1,YDGEOMETRY%YRDIM%NGPBLKS)
!!! Vert. div. of mass flux from conv. scheme
REAL(KIND=JPRB) :: ZCONVCTY(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGEOMETRY%YRDIM%NGPBLKS)
!!! Std. dev. filtered orograpphy
REAL(KIND=JPRB) :: ZHSDFOR(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB) :: ZCGPP(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB) :: ZCREC(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIM%NGPBLKS)

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE_BAR

!     ------------------------------------------------------------------

! #include "abor1.intfb.h"
#include "ec_phys.intfb.h"
#include "cpqtuv.intfb.h"
#include "gpmktend.intfb.h"
#include "heldsuarez.intfb.h"
#include "spptgfix.intfb.h"

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('EC_PHYS_DRV',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV, YDGEM=>YDGEOMETRY%YRGEM, YDGSGEOM=>YDGEOMETRY%YRGSGEOM, &
 &  YDOROG=>YDGEOMETRY%YROROG, YDVAB=>YDGEOMETRY%YRVAB, YDRADF=>YDMODEL%YRML_PHY_RAD%YRRADF, &
 & YDPTRSLB2=>YDMODEL%YRML_DYN%YRPTRSLB2,YDSTOPH=>YDMODEL%YRML_PHY_STOCH%YRSTOPH,YDMDDH=>YDMODEL%YRML_DIAG%YRMDDH, &
 & YDECUCONVCA=>YDMODEL%YRML_PHY_EC%YRECUCONVCA,YDDPHY=>YDMODEL%YRML_PHY_G%YRDPHY,YDERAD=>YDMODEL%YRML_PHY_RAD%YRERAD, &
 & YDPHY2=>YDMODEL%YRML_PHY_MF%YRPHY2,YGFL=>YDMODEL%YRML_GCONF%YGFL,YDSLPHY=>YDMODEL%YRML_PHY_G%YRSLPHY,YDDYN=>YDMODEL%YRML_DYN%YRDYN, &
 & YT0=>YDGMV%YT0, YDSPPT_CONFIG=>YDMODEL%YRML_GCONF%YRSPPT_CONFIG, YDSPPT=>YDMODEL%YRML_SPPT)


ASSOCIATE(NDIM=>YGFL%NDIM, NDIM1=>YGFL%NDIM1, NDIMPT=>YGFL%NDIMPT, &
 & NDIMSLP=>YGFL%NDIMSLP, NUMFLDS=>YGFL%NUMFLDS, &
 & NGPBLKS=>YDDIM%NGPBLKS, NPROMA=>YDDIM%NPROMA, NSMAX=>YDDIM%NSMAX, &
 & NFLEVG=>YDDIMV%NFLEVG, &
 & NCOM=>YDDPHY%NCOM, NCSI=>YDDPHY%NCSI, NCSNEC=>YDDPHY%NCSNEC, &
 & NTILES=>YDDPHY%NTILES, NVCLIS=>YDDPHY%NVCLIS, NVEXTRDYN=>YDDPHY%NVEXTRDYN, &
 & LCUCONV_CA=>YDECUCONVCA%LCUCONV_CA, RCAPECONVCA=>YDECUCONVCA%RCAPECONVCA, &
 & RCUCONVCA=>YDECUCONVCA%RCUCONVCA, RNLCONVCA=>YDECUCONVCA%RNLCONVCA, &
 & NRADFR=>YDERAD%NRADFR, &
 & NGPTOT=>YDGEM%NGPTOT, &
 & NDIMGMV=>YDGMV%NDIMGMV, NDIMGMVS=>YDGMV%NDIMGMVS, YPH9=>YDGMV%YPH9, &
 & YT1=>YDGMV%YT1, &
 & NDHFIIS=>YDMDDH%NDHFIIS, NDHFSSS=>YDMDDH%NDHFSSS, NDHFTIS=>YDMDDH%NDHFTIS, &
 & NDHFTLS=>YDMDDH%NDHFTLS, NDHFTSS=>YDMDDH%NDHFTSS, NDHFTTS=>YDMDDH%NDHFTTS, &
 & NDHFWLS=>YDMDDH%NDHFWLS, NDHVIIS=>YDMDDH%NDHVIIS, NDHVSSS=>YDMDDH%NDHVSSS, &
 & NDHVTIS=>YDMDDH%NDHVTIS, NDHVTLS=>YDMDDH%NDHVTLS, NDHVTSS=>YDMDDH%NDHVTSS, &
 & NDHVTTS=>YDMDDH%NDHVTTS, NDHVWLS=>YDMDDH%NDHVWLS, &
 & MSLB2VVEL=>YDPTRSLB2%MSLB2VVEL, NFLDSLB2=>YDPTRSLB2%NFLDSLB2, &
 & DERIVATIVELW=>YDRADF%DERIVATIVELW, EDRO=>YDRADF%EDRO, EMTC=>YDRADF%EMTC, &
 & EMTD=>YDRADF%EMTD, SRCDIR=>YDRADF%SRCDIR, SRFDIR=>YDRADF%SRFDIR, &
 & SRLWD=>YDRADF%SRLWD, SRLWDC=>YDRADF%SRLWDC, SRSWD=>YDRADF%SRSWD, &
 & SRSWDC=>YDRADF%SRSWDC, SRSWDCS=>YDRADF%SRSWDCS, SRSWPAR=>YDRADF%SRSWPAR, &
 & SRSWPARC=>YDRADF%SRSWPARC, SRSWTINC=>YDRADF%SRSWTINC, &
 & SRSWUVB=>YDRADF%SRSWUVB, TAUAER=>YDRADF%TAUAER, TRSC=>YDRADF%TRSC, &
 & TRSW=>YDRADF%TRSW, &
 & SAVTEND=>YDSLPHY%SAVTEND, &
 & GPSTREAM=>YDSTOPH%GPSTREAM, GPTEMP=>YDSTOPH%GPTEMP, LSTOPH_SPBS_T=>YDSTOPH%LSTOPH_SPBS_T, &
 & GPTOTDISS=>YDSTOPH%GPTOTDISS, GPTOTDISS_SMOOTH=>YDSTOPH%GPTOTDISS_SMOOTH, &
 & GPVORTGRAD=>YDSTOPH%GPVORTGRAD, LFORCENL=>YDSTOPH%LFORCENL, &
 & RSTOPHCA=>YDSTOPH%RSTOPHCA, &
 & YSD_PFD=>YDSURF%YSD_PFD, YSD_V2D=>YDSURF%YSD_V2D, YSD_V3D=>YDSURF%YSD_V3D, &
 & YSD_VDD=>YDSURF%YSD_VDD, YSD_VFD=>YDSURF%YSD_VFD, YSD_VND=>YDSURF%YSD_VND, &
 & YSD_WSD=>YDSURF%YSD_WSD, YSD_WWD=>YDSURF%YSD_WWD, YSD_X2D=>YDSURF%YSD_X2D, &
 & YSD_SMD=>YDSURF%YSD_SMD, YSD_XAD=>YDSURF%YSD_XAD, YSP_EPD=>YDSURF%YSP_EPD, &
 & YSP_OMD=>YDSURF%YSP_OMD, YSP_RRD=>YDSURF%YSP_RRD, YSP_SBD=>YDSURF%YSP_SBD, &
 & YSP_SGD=>YDSURF%YSP_SGD, YSP_SLD=>YDSURF%YSP_SLD, YSP_X2D=>YDSURF%YSP_X2D, &
 & YSD_VF=>YDSURF%YSD_VF, PHYS_MWAVE=>YDPHYSMWAVE%PHYS_MWAVE, &
 & RAHFSTI=>YDTILEPROP%RAHFSTI, REVAPTI=>YDTILEPROP%REVAPTI, &
 & RTSKTI=>YDTILEPROP%RTSKTI, RUSTRTI=>YDTILEPROP%RUSTRTI, &
 & RVSTRTI=>YDTILEPROP%RVSTRTI, TSPHY=>YDPHY2%TSPHY, &
 & LNODRYFLX=>YDDYN%LNODRYFLX, &
 & LACTIVEQ=>YDSPPT_CONFIG%LACTIVEQ_SDT, LACTIVEO=>YDSPPT_CONFIG%LACTIVEO_SDT)
!     ------------------------------------------------------------------


LLRADFR = MOD(NSTEP,NRADFR)==0
CALL GSTATS(1063,0)

!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JKGLO,ICEND,IBL)
DO JKGLO=1,NGPTOT,NPROMA

  IBL=(JKGLO-1)/NPROMA+1
  ICEND=MIN(NPROMA,NGPTOT-JKGLO+1)


  ! Convert T1 variables to tendencies
  CALL GPMKTEND(YDGEOMETRY,YGFL,1,ICEND,TSPHY,&
   & PGMVT1(1,1,YT1%MU,IBL),PGMVT1(1,1,YT1%MV,IBL),PGMVT1(1,1,YT1%MT,IBL),&
   & PGFLT1(1,1,1,IBL),&
   & PGMV(1,1,YPH9%MU,IBL),PGMV(1,1,YPH9%MV,IBL) ,PGMV(1,1,YPH9%MT,IBL),&
   & PGFL(1,1,1,IBL),ZGFL_DYN(1,1,1,IBL))

ENDDO
!$OMP END PARALLEL DO

CALL GSTATS(1063,1)


! Allocate fields to store tendencies for lspptgfix
IF (YDSPPT_CONFIG%LSPSDT.AND.YDSPPT_CONFIG%LSPPTGFIX) THEN
  ALLOCATE(ZSPPTGFIX(NPROMA,NFLEVG,4,2,NGPBLKS))
ENDIF




IF(.NOT.LLRADFR)THEN
  CALL GSTATS(1001,0)
ELSE
  CALL GSTATS(1002,0)
ENDIF


IF( LHELDSUAREZ ) THEN
  !$OMP PARALLEL PRIVATE(JKGLO,ICST,ICEND,IBL,IOFF)
  !$OMP DO SCHEDULE(DYNAMIC,1)
  DO JKGLO=1,NGPTOT,NPROMA
    ICST=1
    ICEND=MIN(NPROMA,NGPTOT-JKGLO+1)
    IBL=(JKGLO-1)/NPROMA+1
    IOFF=JKGLO

    CALL HELDSUAREZ(YDVAB,YDGEOMETRY%YRCVER,YDGEOMETRY%YRDIMV,YDSURF,YDMODEL%YRML_GCONF%YRRIP,ICST,ICEND,NPROMA,NFLEVG,&
     & PGMV(1,1,YPH9%MU,IBL),PGMV(1,1,YPH9%MV,IBL),&
     & PGMV(1,1,YPH9%MT,IBL),PGMVS(1,YPH9%MSP,IBL),&
     & YDGSGEOM(IBL)%GEMU,&
     & PGMVT1(1,1,YT1%MU,IBL) ,PGMVT1(1,1,YT1%MV,IBL) ,PGMVT1(1,1,YT1%MT,IBL),&
     & PSD_XA(1,1,1,IBL),PSD_X2(1,1,IBL))

  ENDDO
  !$OMP END DO
  !$OMP END PARALLEL

ELSE

  ! Global setup of state and tendency objects for the parallel physics loop

  ! Create keymask to signal which variables are active within a single state/tendency
  CALL KEYMASK%INIT(Q=YDVARS%Q%LACTIVE, O3=YDVARS%O3%LACTIVE, A=YDVARS%A%LACTIVE, &
   &                QL=YDVARS%L%LACTIVE, QI=YDVARS%I%LACTIVE, &
   &                QR=YDVARS%R%LACTIVE, QS=YDVARS%S%LACTIVE, TKE=YDVARS%TKE%LACTIVE)

  ! Similar structure as above used for stochastic physics tendencies
  IF (YDSPPT_CONFIG%LSPSDT) THEN
    ! Need to guard this, because LACTIVEQ_SDT/LACTIVEO_SDT are pointers?!
    CALL KMASK_SDT%INIT(Q=LACTIVEQ, O3=LACTIVEO, A=LACTIVEO, QL=LACTIVEO, QI=LACTIVEO, QR=LACTIVEO, QS=LACTIVEO, TKE=LACTIVEO)
  END IF

  ! Initialize STATE_T0 from PH9 field pointers and TENDENCY_DYN from T1 pointers
  CALL STATE_T0%INIT(YDGEOMETRY, KEYMASK=KEYMASK, &
   &                 U=YDVARS%U%FPH9, V=YDVARS%V%FPH9, T=YDVARS%T%FPH9, O3=YDVARS%O3%FPH9, &
   &                 Q=YDVARS%Q%FPH9, A=YDVARS%A%FPH9, QL=YDVARS%L%FPH9, QI=YDVARS%I%FPH9, &
   &                 QR=YDVARS%R%FPH9, QS=YDVARS%S%FPH9, TKE=YDVARS%TKE%FPH9)
  CALL TENDENCY_DYN%INIT(YDGEOMETRY, KEYMASK=KEYMASK, &
   &                     U=YDVARS%U%FT1, V=YDVARS%V%FT1, T=YDVARS%T%FT1, O3=YDVARS%O3%FT1, &
   &                     Q=YDVARS%Q%FT1, A=YDVARS%A%FT1, QL=YDVARS%L%FT1, QI=YDVARS%I%FT1, &
   &                     QR=YDVARS%R%FT1, QS=YDVARS%S%FT1, TKE=YDVARS%TKE%FT1)

  ! Initialize temporaries for all other state copies and tendencies
  CALL TENDENCY_CML%INIT(YDGEOMETRY, KEYMASK=KEYMASK)
  CALL STATE_TMP%INIT(YDGEOMETRY, KEYMASK=KEYMASK)
  CALL TENDENCY_TMP%INIT(YDGEOMETRY, KEYMASK=KEYMASK)
  CALL TENDENCY_VDF%INIT(YDGEOMETRY, KEYMASK=KEYMASK)
  CALL TENDENCY_SATADJ%INIT(YDGEOMETRY, KEYMASK=KEYMASK)
  CALL TENDENCY_LOC%INIT(YDGEOMETRY, KEYMASK=KEYMASK)
  IF (YDSPPT_CONFIG%LSPSDT) THEN
    ALLOCATE(TENDENCY_PHY(YDSPPT%N2D))
    DO J2D = 1,YDSPPT%N2D
      CALL TENDENCY_PHY(J2D)%INIT(YDGEOMETRY, KEYMASK=KMASK_SDT)
    ENDDO
  ELSE
    ALLOCATE(TENDENCY_PHY(0))
  ENDIF

  ! Initialize dimension object with global information
  CALL IDIMS%INIT(YDGEOMETRY, YDMODEL, YDSURF)

  ! Initialize local views for surface state fields
  CALL ZSURF%INIT(YDFIELDS%REGISTRY, YDVARS, YDFIELDS%SURFVARS, &
   &              NLEVS=YSP_SBD%NLEVS, NLEVSN=NCSNEC, NLEVO=YSP_OMD%NLEVS)
  CALL ZAUX%INIT(YDFIELDS%REGISTRY, YDVARS, NLEV=NFLEVG)
  CALL ZRAD%INIT(YDFIELDS%REGISTRY, YDVARS, NLEV=NFLEVG)
  CALL ZFLUX%INIT(YDFIELDS%REGISTRY, NLEV=YDDIMV%NFLEVG, NLEVS=YDSURF%YSP_SBD%NLEVS, &
   &              NACTAERO=YGFL%NACTAERO, NPAERODIAG=NPAERODIAG)
  CALL ZDIAG%INIT(YDFIELDS%REGISTRY, NLEV=YDDIMV%NFLEVG)
  CALL ZDDHS%INIT(YDFIELDS%REGISTRY, DIMS=IDIMS)
  CALL ZAUXL%INIT(YDFIELDS%REGISTRY, NLEV=YDDIMV%NFLEVG)
  CALL ZSURFL%INIT(YDFIELDS%REGISTRY, YDDPHY%NCSNEC, NTILES=YDDPHY%NTILES, &
   &               NTSW=YDMODEL%YRML_PHY_RAD%YRERAD%NTSW, NLWEMISS=YDERAD%NLWEMISS)
  CALL ZLLKEYS%INIT(YDFIELDS%REGISTRY)
  CALL ZPERTL%INIT(YDFIELDS%REGISTRY, NLEV=YDDIMV%NFLEVG)

  !$OMP PARALLEL PRIVATE(JKGLO,ICST,ICEND,IBL,IOFF,ZSLPHY9,ZPERT,TRAJECTORY_PHYSICS) &
  !$OMP FIRSTPRIVATE(STATE_T0,TENDENCY_DYN,TENDENCY_CML,STATE_TMP,TENDENCY_TMP,TENDENCY_VDF,TENDENCY_SATADJ,TENDENCY_LOC,TENDENCY_PHY, &
  !$OMP &            YDVARS,IDIMS,ZSURF,ZAUX,ZRAD,ZFLUX,ZDIAG,ZDDHS,ZAUXL,ZSURFL,ZLLKEYS,ZPERTL)

  !$OMP DO SCHEDULE(DYNAMIC,1)
  DO JKGLO=1,NGPTOT,NPROMA
    ICST=1
    ICEND=MIN(NPROMA,NGPTOT-JKGLO+1)
    IBL=(JKGLO-1)/NPROMA+1
    IOFF=JKGLO

    ! Set view pointers in the thread-local variable hierarchy.
    ! Variable arrays need to be explicitly replicated per thread
    ! here, and associations to storage fields set up.
    CALL YDVARS%CLONE_ARRAYS()
    CALL YDVARS%UPDATE_VIEW(BLOCK_INDEX=IBL)

    ! Set up thread-local data views
    CALL STATE_T0%UPDATE_VIEW(IBL)
    CALL TENDENCY_DYN%UPDATE_VIEW(IBL)
    CALL TENDENCY_CML%UPDATE_VIEW(IBL)
    CALL STATE_TMP%UPDATE_VIEW(IBL)
    CALL TENDENCY_TMP%UPDATE_VIEW(IBL)
    CALL TENDENCY_VDF%UPDATE_VIEW(IBL)
    CALL TENDENCY_SATADJ%UPDATE_VIEW(IBL)
    CALL TENDENCY_LOC%UPDATE_VIEW(IBL)
    IF (YDSPPT_CONFIG%LSPSDT) THEN
      DO J2D = 1,YDSPPT%N2D
        CALL TENDENCY_PHY(J2D)%UPDATE_VIEW(IBL)
      ENDDO
    ENDIF

    CALL IDIMS%UPDATE(IBL, ICEND, JKGLO, KGPLAT=YDGSGEOM(IBL)%NGPLAT)
    CALL ZSURF%UPDATE_VIEW(BLOCK_INDEX=IBL)
    CALL ZAUX%UPDATE_VIEW(BLOCK_INDEX=IBL)
    CALL ZRAD%UPDATE_VIEW(BLOCK_INDEX=IBL)
    CALL ZPERT%UPDATE_VIEW(YDMODEL, YDSTOPH, IBL, IOFF, ICEND, NPROMA, NFLEVG, ZSPPTGFIX)
    CALL ZFLUX%UPDATE_VIEW(BLOCK_INDEX=IBL)
    CALL ZDIAG%UPDATE_VIEW(BLOCK_INDEX=IBL)
    CALL ZDDHS%UPDATE_VIEW(BLOCK_INDEX=IBL)
    CALL ZAUXL%UPDATE_VIEW(BLOCK_INDEX=IBL)
    CALL ZSURFL%UPDATE_VIEW(BLOCK_INDEX=IBL)
    CALL ZLLKEYS%UPDATE_VIEW(BLOCK_INDEX=IBL)
    CALL ZPERTL%UPDATE_VIEW(BLOCK_INDEX=IBL)

    ! Interface to global arrays (through derived type variables)
    ! Note: It is better not to trust any model dimension and secure it here (to avoid bound checking pb).
    !       Still it would be much easier to expect, that dimensions are at least 1.
    IF (YSP_SBD%NDIM > 0) THEN
      ZSURF%PSP_SB => PSP_SB(:,:,:,IBL)
    ELSE
      ALLOCATE (ZSURF%PSP_SB(NPROMA,MAX(1,YSP_SBD%NLEVS),1))
    ENDIF
    IF (YSP_SGD%NDIM > 0) THEN
      ZSURF%PSP_SG => PSP_SG(:,:,:,IBL)
    ELSE
      ALLOCATE (ZSURF%PSP_SG(NPROMA,MAX(1,YSP_SGD%NLEVS),1))
    ENDIF
    IF (YSP_SLD%NDIM > 0) THEN
      ZSURF%PSP_SL => PSP_SL(:,:,IBL)
    ELSE
      ALLOCATE (ZSURF%PSP_SL(NPROMA,1))
    ENDIF
    IF (YSP_RRD%NDIM > 0) THEN
      ZSURF%PSP_RR => PSP_RR(:,:,IBL)
    ELSE
      ALLOCATE (ZSURF%PSP_RR(NPROMA,1))
    ENDIF
    IF (YSP_EPD%NDIM > 0) THEN
      ZSURF%PSP_EP => PSP_EP(:,:,:,IBL)
    ELSE
      ALLOCATE (ZSURF%PSP_EP(NPROMA,MAX(1,YSP_EPD%NLEVS),1))
    ENDIF
    IF (YSP_X2D%NDIM > 0 ) THEN
      ZSURF%PSP_X2 => PSP_X2(:,:,IBL)
    ELSE
      ALLOCATE(ZSURF%PSP_X2(NPROMA,1))
    ENDIF
    IF (YSP_OMD%NDIM > 0 ) THEN
      ZSURF%PSP_OM => PSP_OM(:,:,:,IBL)
    ELSE
      ALLOCATE(ZSURF%PSP_OM(NPROMA,MAX(1,YSP_OMD%NLEVS),1))
    ENDIF
    IF (YSD_VFD%NDIM > 0 ) THEN
      ZSURF%PSD_VF => PSD_VF(:,:,IBL)
    ELSE
      ALLOCATE(ZSURF%PSD_VF(NPROMA,1))
    ENDIF
    IF (YSD_VND%NDIM > 0 ) THEN
      ZSURF%PSD_VN => PSD_VN(:,:,IBL)
    ELSE
      ALLOCATE(ZSURF%PSD_VN(NPROMA,1))
    ENDIF
    IF (YSD_VDD%NDIM > 0 ) THEN
      ZSURF%PSD_VD => PSD_VD(:,:,IBL)
    ELSE
      ALLOCATE(ZSURF%PSD_VD(NPROMA,1))
    ENDIF
    IF (YSD_WSD%NDIM > 0 ) THEN
      ZSURF%PSD_WS => PSD_WS(:,:,IBL)
    ELSE
      ALLOCATE(ZSURF%PSD_WS(NPROMA,1))
    ENDIF
    IF (YSD_WWD%NDIM > 0 ) THEN
      ZSURF%PSD_WW => PSD_WW(:,:,IBL)
    ELSE
      ALLOCATE(ZSURF%PSD_WW(NPROMA,1))
    ENDIF
    IF (YSD_XAD%NDIM > 0 ) THEN
      ZSURF%PSD_XA => PSD_XA(:,:,:,IBL)
    ELSE
      ALLOCATE (ZSURF%PSD_XA(NPROMA,MAX(1,YSD_XAD%NLEVS),1))
    ENDIF
    IF (YSD_X2D%NDIM > 0 ) THEN
      ZSURF%PSD_X2 => PSD_X2(:,:,IBL)
    ELSE
      ALLOCATE (ZSURF%PSD_X2(NPROMA,1))
    ENDIF
    IF (YSD_SMD%NDIM > 0 ) THEN
      ZSURF%PSD_SM => PSD_SM(:,:,:,IBL)
    ELSE
      ALLOCATE (ZSURF%PSD_SM(NPROMA,MAX(1,YSD_SMD%NLEVS),1))
    ENDIF
    IF (YSD_V2D%NDIM > 0 ) THEN
      ZSURF%PSD_V2 => PSD_V2(:,:,IBL)
    ELSE
      ALLOCATE (ZSURF%PSD_V2(NPROMA,1))
    ENDIF
    IF (YSD_V3D%NDIM > 0 ) THEN
      ZSURF%PSD_V3 => PSD_V3(:,:,:,IBL)
    ELSE
      ALLOCATE (ZSURF%PSD_V3(NPROMA,MAX(1,YSD_V3D%NLEVS),1))
    ENDIF

    ZSURF%PEXTRD => PEXTRADYN(:,:,:,IBL)
    ZSURF%PCOVPTOT => PSD_PF(:,:,1,IBL)

    ZSLPHY9%U    => PPBUP9(:,:,IBL)
    ZSLPHY9%V    => PPBVP9(:,:,IBL)
    ZSLPHY9%T    => PPBTP9(:,:,IBL)
    ZSLPHY9%GFL  => PPBGFLP9(:,:,:,IBL)

    ZAUX%PVERVEL => PB2(:,MSLB2VVEL:MSLB2VVEL+NFLEVG-1,IBL)

    IF (PRESENT(PTRAJEC)) THEN
      TRAJECTORY_PHYSICS => PTRAJEC%PHYS(IBL)
    ELSE
      TRAJECTORY_PHYSICS => PTRAJEC_OOPS%PHYS(IBL)
    ENDIF

    IF (LECV .AND. LSIGFLTORO) THEN
      ZSURF%PSD_VF(:,YSD_VF%YSDFOR%MP) = ZHSDFOR(:,IBL)
    ENDIF

    CALL EC_PHYS(YDGEOMETRY,YDVARS,YDGMV,YDSURF,YDMODEL,CDCONF,IDIMS,&
       & YDVARS%U, YDVARS%V, YDVARS%T, YDVARS%SP, YDVARS%Q, YDVARS%I, YDVARS%L, YDVARS%A,&
       & PGFLT1(:,:,:,IBL),&
       & PGFL(:,:,:,IBL),PGFLSLP(:,:,:,IBL),ZCONVCTY(:,:,IBL),PHYS_MWAVE(:,:,:,IBL),&
       & ZAUX, ZSURF, ZCGPP(1,IBL),ZCREC(1,IBL),ZRAD, &
       & ZPERT, ZFLUX, ZDIAG, ZDDHS, ZAUXL, ZSURFL, ZLLKEYS, ZPERTL, ZSLPHY9,&
       & SAVTEND(1,1,1,IBL), TRAJECTORY_PHYSICS,&
       & PSMOS_OBS_BUF,PSMOS_TB_BUF,PSMOS_ANGLE,PSMOS_FARAD,PSMOS_GEOMET,&
       & KSMOS_BUF,PSMAP_OBS_BUF,PSMAP_TB_BUF,PSMAP_ANGLE,KSMAP_BUF,&
       & STATE_T0, TENDENCY_DYN, TENDENCY_CML, STATE_TMP, TENDENCY_TMP,&
       & TENDENCY_VDF, TENDENCY_SATADJ, TENDENCY_LOC, TENDENCY_PHY&
       & )

    CALL ZPERT%FINAL(YDMODEL, YDSTOPH)

    IF (YSP_SBD%NDIM < 1) DEALLOCATE (ZSURF%PSP_SB)
    IF (YSP_SGD%NDIM < 1) DEALLOCATE (ZSURF%PSP_SG)
    IF (YSP_SLD%NDIM < 1) DEALLOCATE (ZSURF%PSP_SL)
    IF (YSP_RRD%NDIM < 1) DEALLOCATE (ZSURF%PSP_RR)
    IF (YSP_EPD%NDIM < 1) DEALLOCATE (ZSURF%PSP_EP)
    IF (YSP_X2D%NDIM < 1) DEALLOCATE (ZSURF%PSP_X2)
    IF (YSP_OMD%NDIM < 1) DEALLOCATE (ZSURF%PSP_OM)
    IF (YSD_VFD%NDIM < 1) DEALLOCATE (ZSURF%PSD_VF)
    IF (YSD_VND%NDIM < 1) DEALLOCATE (ZSURF%PSD_VN)
    IF (YSD_VDD%NDIM < 1) DEALLOCATE (ZSURF%PSD_VD)
    IF (YSD_WSD%NDIM < 1) DEALLOCATE (ZSURF%PSD_WS)
    IF (YSD_WWD%NDIM < 1) DEALLOCATE (ZSURF%PSD_WW)
    IF (YSD_XAD%NDIM < 1) DEALLOCATE (ZSURF%PSD_XA)
    IF (YSD_X2D%NDIM < 1) DEALLOCATE (ZSURF%PSD_X2)
    IF (YSD_SMD%NDIM < 1) DEALLOCATE (ZSURF%PSD_SM)
    IF (YSD_V2D%NDIM < 1) DEALLOCATE (ZSURF%PSD_V2)
    IF (YSD_V3D%NDIM < 1) DEALLOCATE (ZSURF%PSD_V3)

    ! Reset thread-local variable arrays
    CALL YDVARS%RESET_ARRAYS()

  ENDDO
  !$OMP END DO
  !$OMP END PARALLEL
  CALL STATE_T0%FINAL()
  CALL TENDENCY_DYN%FINAL()
  CALL TENDENCY_CML%FINAL()
  CALL STATE_TMP%FINAL()
  CALL TENDENCY_TMP%FINAL()
  CALL TENDENCY_VDF%FINAL()
  CALL TENDENCY_SATADJ%FINAL()
  CALL TENDENCY_LOC%FINAL()
  IF (YDSPPT_CONFIG%LSPSDT) THEN
    DO J2D = 1,YDSPPT%N2D
      CALL TENDENCY_PHY(J2D)%FINAL()
    ENDDO
  ENDIF
  DEALLOCATE(TENDENCY_PHY)

  CALL ZSURF%FINAL()
  CALL ZAUX%FINAL()
  CALL ZRAD%FINAL()
  CALL ZFLUX%FINAL()
  CALL ZDIAG%FINAL()
  CALL ZDDHS%FINAL()
  CALL ZAUXL%FINAL()
  CALL ZSURFL%FINAL()
  CALL ZLLKEYS%FINAL()
  CALL ZPERTL%FINAL()

ENDIF  ! LHELDSUAREZ

IF(.NOT.LLRADFR)THEN
  CALL GSTATS(1001,1)
ELSE
  CALL GSTATS(1002,1)
ENDIF

IF(YDSPPT_CONFIG%LSPSDT.AND.YDSPPT_CONFIG%LSPPTGFIX) THEN
  CALL SPPTGFIX(YDMODEL,YDGEOMETRY,YDGMV,YGFL,YDPHY2%TSPHY,PGMVS,ZSPPTGFIX,PGFL,PGFLT1,PGMVT1,YDSPPT_CONFIG%XSPPTGFIXRLX)
  DEALLOCATE(ZSPPTGFIX)
ENDIF


IF (LHOOK) CALL DR_HOOK('EC_PHYS_DRV_BAR',0,ZHOOK_HANDLE_BAR)
CALL GSTATS_BARRIER(730)
IF (LHOOK) CALL DR_HOOK('EC_PHYS_DRV_BAR',1,ZHOOK_HANDLE_BAR)

CALL GSTATS(1064,0)

!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JKGLO,ICEND,IBL,ICST,IOFF)
DO JKGLO=1,YDGEM%NGPTOT,YDDIM%NPROMA

  ICST=1
  IBL=(JKGLO-1)/YDDIM%NPROMA+1
  IOFF=JKGLO-1
  ICEND=MIN(YDDIM%NPROMA,YDGEM%NGPTOT-JKGLO+1)

  CALL CPQTUV(YDMODEL%YRML_PHY_EC%YRECLDP,YGFL,YDDIM%NPROMA,1,ICEND,YDDIMV%NFLEVG,YDPHY2%TSPHY,LNODRYFLX, &
   & PGMV(1,1,YDGMV%YPH9%MU,IBL),PGMV(1,1,YDGMV%YPH9%MV,IBL),PGMV(1,1,YDGMV%YPH9%MT,IBL),&
   & PGFL(1,1,1,IBL),ZGFL_DYN(1,1,1,IBL),ZCONVCTY(1,1,IBL), &
   & PGMVT1(1,1,YDGMV%YT1%MU,IBL),PGMVT1(1,1,YDGMV%YT1%MV,IBL),PGMVT1(1,1,YDGMV%YT1%MT,IBL),&
   & PGFLT1(1,1,1,IBL))

ENDDO
!$OMP END PARALLEL DO
CALL GSTATS(1064,1)

!     ------------------------------------------------------------------
END ASSOCIATE
END ASSOCIATE

IF (LHOOK) CALL DR_HOOK('EC_PHYS_DRV',1,ZHOOK_HANDLE)

END SUBROUTINE EC_PHYS_DRV
