! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE LOCAL_ARRAYS_FIN(LLKEYS,AUXL,SURFL,PERTL,GEMSL)

!**** *deallocations of derived variables local to CALLPAR* - creator

!     PURPOSE.
!     --------

!**   INTERFACE.
!     ----------

!        EXPLICIT ARGUMENTS :
!        --------------------

! Derived arrays
! --------------
! LLKEYS
! AUXL
! SURFL
! PERTL
! GEMSL

!     METHOD.
!     -------
!        SEE DOCUMENTATION

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF RESEARCH DEPARTMENT DOCUMENTATION OF THE IFS

!     AUTHOR.
!     -------
!      Original : 2013-06-03  S. MARTINEZ (c) METEO-FRANCE

!     MODIFICATIONS.
!     --------------
!     JJMorcrette 20131001 DMS-related variables
!-----------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK

USE YOMPHYDER ,ONLY : KEYS_LOCAL_TYPE, AUX_DIAG_LOCAL_TYPE, &
  & SURF_AND_MORE_LOCAL_TYPE, PERTURB_LOCAL_TYPE, GEMS_LOCAL_TYPE
!-----------------------------------------------------------------------

IMPLICIT NONE

TYPE(KEYS_LOCAL_TYPE)          , INTENT(INOUT) :: LLKEYS
TYPE(AUX_DIAG_LOCAL_TYPE)      , INTENT(INOUT) :: AUXL
TYPE(SURF_AND_MORE_LOCAL_TYPE) , INTENT(INOUT) :: SURFL
TYPE(PERTURB_LOCAL_TYPE)       , INTENT(INOUT) :: PERTL
TYPE(GEMS_LOCAL_TYPE)          , INTENT(INOUT) :: GEMSL
!-----------------------------------------------------------------------

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!-----------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('LOCAL_ARRAYS_FIN',0,ZHOOK_HANDLE)

!-----------------------------------------------------------------------

! --- ZEMIR and ZEMIW point to parts of ZSPECTRALEMISS
IF (ASSOCIATED(SURFL%ZEMIR)) NULLIFY(SURFL%ZEMIR)
IF (ASSOCIATED(SURFL%ZEMIW)) NULLIFY(SURFL%ZEMIW)
! ---

IF (ASSOCIATED(GEMSL%ITRAC)) DEALLOCATE(GEMSL%ITRAC)
IF (ASSOCIATED(GEMSL%ZCEN)) DEALLOCATE(GEMSL%ZCEN)
IF (ASSOCIATED(GEMSL%ZTENC)) DEALLOCATE(GEMSL%ZTENC)
IF (ASSOCIATED(GEMSL%ZTENC_SKF)) DEALLOCATE(GEMSL%ZTENC_SKF)
IF (ASSOCIATED(GEMSL%ZCFLX)) DEALLOCATE(GEMSL%ZCFLX)
IF (ASSOCIATED(GEMSL%ZSCAV)) DEALLOCATE(GEMSL%ZSCAV)
!DEALLOCATE(GEMSL%ZCEN,GEMSL%ZTENC,GEMSL%ZTENC_SKF,GEMSL%ZCFLX,GEMSL%ZSCAV)
IF (ASSOCIATED(GEMSL%IAERO)) DEALLOCATE(GEMSL%IAERO)
IF (ASSOCIATED(GEMSL%ICHEM)) DEALLOCATE(GEMSL%ICHEM)
IF (ASSOCIATED(GEMSL%ZAZ0M)) DEALLOCATE(GEMSL%ZAZ0M)
IF (ASSOCIATED(GEMSL%ZAZ0H)) DEALLOCATE(GEMSL%ZAZ0H)
IF (ASSOCIATED(GEMSL%ZAERWS)) DEALLOCATE(GEMSL%ZAERWS)
IF (ASSOCIATED(GEMSL%ZAERGUST)) DEALLOCATE(GEMSL%ZAERGUST)
IF (ASSOCIATED(GEMSL%ZAERUST)) DEALLOCATE(GEMSL%ZAERUST)
IF (ASSOCIATED(GEMSL%ZDIST)) DEALLOCATE(GEMSL%ZDIST)
IF (ASSOCIATED(GEMSL%ZCLAERS)) DEALLOCATE(GEMSL%ZCLAERS)
IF (ASSOCIATED(GEMSL%ZPRAERS)) DEALLOCATE(GEMSL%ZPRAERS)
IF (ASSOCIATED(GEMSL%ZVISICL)) DEALLOCATE(GEMSL%ZVISICL)
IF (ASSOCIATED(GEMSL%ZAERMAP)) DEALLOCATE(GEMSL%ZAERMAP)
IF (ASSOCIATED(GEMSL%ZLRCH4)) DEALLOCATE(GEMSL%ZLRCH4)
IF (ASSOCIATED(GEMSL%ZKOZO)) DEALLOCATE(GEMSL%ZKOZO)

! additional ones due to DMSO
IF (ASSOCIATED(GEMSL%ZDMSO)) DEALLOCATE(GEMSL%ZDMSO)
IF (ASSOCIATED(GEMSL%ZLDAY)) DEALLOCATE(GEMSL%ZLDAY)
IF (ASSOCIATED(GEMSL%ZLISS)) DEALLOCATE(GEMSL%ZLISS)
IF (ASSOCIATED(GEMSL%ZSO2))  DEALLOCATE(GEMSL%ZSO2)
IF (ASSOCIATED(GEMSL%ZTDMS)) DEALLOCATE(GEMSL%ZTDMS)
IF (ASSOCIATED(GEMSL%ZDMSI)) DEALLOCATE(GEMSL%ZDMSI)
IF (ASSOCIATED(GEMSL%ZODMS)) DEALLOCATE(GEMSL%ZODMS)

IF (ASSOCIATED(GEMSL%ZCAERO)) DEALLOCATE(GEMSL%ZCAERO)
IF (ASSOCIATED(GEMSL%ZAEROP)) DEALLOCATE(GEMSL%ZAEROP)
IF (ASSOCIATED(GEMSL%ZAERDDP)) DEALLOCATE(GEMSL%ZAERDDP)
IF (ASSOCIATED(GEMSL%ZAERSDM)) DEALLOCATE(GEMSL%ZAERSDM)
IF (ASSOCIATED(GEMSL%ZAERSRC)) DEALLOCATE(GEMSL%ZAERSRC)
!IF (ASSOCIATED(GEMSL%ZAERDDP)) GEMSL%ZAERDDP =>NULL()
!IF (ASSOCIATED(GEMSL%ZAERSDM)) GEMSL%ZAERSDM =>NULL()
!IF (ASSOCIATED(GEMSL%ZAERSRC)) GEMSL%ZAERSRC =>NULL()

IF (ASSOCIATED(GEMSL%ZAERFLX_M7)) DEALLOCATE(GEMSL%ZAERFLX_M7)
IF (ASSOCIATED(GEMSL%ZAERFLX)) DEALLOCATE(GEMSL%ZAERFLX)
IF (ASSOCIATED(GEMSL%ZAERLIF)) DEALLOCATE(GEMSL%ZAERLIF)
IF (ASSOCIATED(GEMSL%ZTAUAER)) DEALLOCATE(GEMSL%ZTAUAER)
IF (ASSOCIATED(GEMSL%ZAERAOT)) DEALLOCATE(GEMSL%ZAERAOT)
IF (ASSOCIATED(GEMSL%ZAERAOTLEV)) DEALLOCATE(GEMSL%ZAERAOTLEV)
IF (ASSOCIATED(GEMSL%ZAERAAOTLEV)) DEALLOCATE(GEMSL%ZAERAAOTLEV)
IF (ASSOCIATED(GEMSL%ZAERASYLEV)) DEALLOCATE(GEMSL%ZAERASYLEV)
IF (ASSOCIATED(GEMSL%ZAERLISI)) DEALLOCATE(GEMSL%ZAERLISI)

! GLOMAP fields
IF (ASSOCIATED(GEMSL%ZDRYDIAM)) DEALLOCATE(GEMSL%ZDRYDIAM)
IF (ASSOCIATED(GEMSL%ZWETDIAM)) DEALLOCATE(GEMSL%ZWETDIAM)
IF (ASSOCIATED(GEMSL%ZDRYVOL)) DEALLOCATE(GEMSL%ZDRYVOL)
IF (ASSOCIATED(GEMSL%ZWETVOL)) DEALLOCATE(GEMSL%ZWETVOL)
IF (ASSOCIATED(GEMSL%ZVOL_WAT)) DEALLOCATE(GEMSL%ZVOL_WAT)
IF (ASSOCIATED(GEMSL%ZRHOPAR)) DEALLOCATE(GEMSL%ZRHOPAR)
IF (ASSOCIATED(GEMSL%ZMD)) DEALLOCATE(GEMSL%ZMD)
IF (ASSOCIATED(GEMSL%ZMDT)) DEALLOCATE(GEMSL%ZMDT)
IF (ASSOCIATED(GEMSL%ZND)) DEALLOCATE(GEMSL%ZND)


! M7 fields
IF (ASSOCIATED(GEMSL%ZAEROTAU))   DEALLOCATE(GEMSL%ZAEROTAU)
IF (ASSOCIATED(GEMSL%ZAEROSSA))   DEALLOCATE(GEMSL%ZAEROSSA)
IF (ASSOCIATED(GEMSL%ZAEROASY))   DEALLOCATE(GEMSL%ZAEROASY)
IF (ASSOCIATED(GEMSL%ZAEROTAULW)) DEALLOCATE(GEMSL%ZAEROTAULW)

! dry depostion and effective flux fields 
IF (ASSOCIATED(GEMSL%ZDDVLC)) DEALLOCATE(GEMSL%ZDDVLC)
IF (ASSOCIATED(GEMSL%ZCFLXO)) DEALLOCATE(GEMSL%ZCFLXO)
IF (ASSOCIATED(GEMSL%ZCHEMDV)) DEALLOCATE(GEMSL%ZCHEMDV)
!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('LOCAL_ARRAYS_FIN',1,ZHOOK_HANDLE)
END SUBROUTINE LOCAL_ARRAYS_FIN
