! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE PHYS_ARRAYS_INI(YDSURF,YDEPHY,YGFL,DIMS,PAUX,ZDDHS,ZDIAG,PSURF,PRAD,FLUX)

!----compiled for Cray with -h contiguous----

!**** *Initialization of derived variables local to physics sub-space

!     PURPOSE.
!     --------

!**   INTERFACE.
!     ----------

!        EXPLICIT ARGUMENTS :
!        --------------------

! Derived arrays           Reserved space
! -----------------------------------------------
! PAUX                     PAUX_ARR
! ZDDHS                    PDDHS_ARR
! ZDIAG                    PDIAG_ARR
! PSURF                    PSURF_ARR
!                          KSURF_ARR
! PRAD                     PRAD_ARR
! FLUX                     PFLUX_ARR

!        --------------------

!     METHOD.
!     -------
!        SEE DOCUMENTATION

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF RESEARCH DEPARTMENT DOCUMENTATION OF THE IFS

!     AUTHOR.
!     -------
!      Original : 31-Jan-2013  F. VANA (c) ECMWF

!     MODIFICATIONS.
!     --------------
!     JJMorcrette 20131001 additional volcanic aerosol diagnostics 
!     P. Lopez, ECMWF, July 2015 Added lightning fields in ZDIAG.
!     F. Vana 19-Nov-2016  Negative q pseudo-flux must be initialized to 0 here.
!     E. Dutra/G.Arduini, Jan 2018: snow multi-layer and new snow liquid water content 
!     B. Ingleby,      2019-01-17 Remove PQCFL
!-----------------------------------------------------------------------

USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1           , ONLY : JPRB
USE YOMHOOK            , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMPHYDER          , ONLY : AUX_RAD_TYPE, SURF_AND_MORE_TYPE, AUX_TYPE, &
   &                            AUX_DIAG_TYPE, FLUX_TYPE, DDH_SURF_TYPE, DIMENSION_TYPE
USE YOM_YGFL           , ONLY : TYPE_GFLD
USE YOEPHY             , ONLY : TEPHY
USE YOE_AERODIAG       , ONLY : NPAERODIAG

!     -----------------------------------------------------------------------------

IMPLICIT NONE

TYPE(TSURF)    ,INTENT(INOUT) :: YDSURF
TYPE(TEPHY)    ,INTENT(INOUT) :: YDEPHY
TYPE(TYPE_GFLD),INTENT(INOUT) :: YGFL
TYPE (DIMENSION_TYPE)    ,INTENT(IN)    :: DIMS
TYPE (AUX_TYPE)          ,INTENT(INOUT) :: PAUX
TYPE (DDH_SURF_TYPE)     ,INTENT(INOUT) :: ZDDHS
TYPE (AUX_DIAG_TYPE)     ,INTENT(INOUT) :: ZDIAG
TYPE (SURF_AND_MORE_TYPE),INTENT(INOUT) :: PSURF
TYPE (AUX_RAD_TYPE)      ,INTENT(INOUT) :: PRAD
TYPE (FLUX_TYPE)         ,INTENT(INOUT) :: FLUX
!-----------------------------------------------------------------------
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!-----------------------------------------------------------------------


IF (LHOOK) CALL DR_HOOK('PHYS_ARRAYS_INI',0,ZHOOK_HANDLE)
ASSOCIATE(NACTAERO=>YGFL%NACTAERO, &
 & LECURR=>YDEPHY%LECURR, &
 & YSD_VD=>YDSURF%YSD_VD, YSD_VF=>YDSURF%YSD_VF, YSP_OMD=>YDSURF%YSP_OMD)
!-----------------------------------------------------------------------

!   initialize surface DDH fields
ZDDHS%PDHTLS(:,:,:) = 0.0_JPRB
ZDDHS%PDHTSS(:,:,:) = 0.0_JPRB
ZDDHS%PDHTTS(:,:,:) = 0.0_JPRB
ZDDHS%PDHTIS(:,:,:) = 0.0_JPRB
ZDDHS%PDHSSS(:,:,:) = 0.0_JPRB
ZDDHS%PDHIIS(:,:)   = 0.0_JPRB
ZDDHS%PDHWLS(:,:,:) = 0.0_JPRB


!   initialize the diag fields
ZDIAG%PMFUDE_RATE(:,:) = 0.0_JPRB
ZDIAG%PMFDDE_RATE(:,:) = 0.0_JPRB
ZDIAG%PMFU(:,:)        = 0.0_JPRB
ZDIAG%PMFD(:,:)        = 0.0_JPRB
ZDIAG%ZLUDE(:,:)       = 0.0_JPRB
ZDIAG%ZLUDELI(:,:,:)   = 0.0_JPRB
ZDIAG%ZSNDE(:,:,:)     = 0.0_JPRB
ZDIAG%PRSUD(:,:,:)     = 0.0_JPRB
ZDIAG%ZLU(:,:)         = 0.0_JPRB
ZDIAG%ZLRAIN(:,:)      = 0.0_JPRB
ZDIAG%PCOVPTOT(:,:)    = 0.0_JPRB
ZDIAG%ZCAPE(:,:)       = 0.0_JPRB
ZDIAG%PVISIH(:)        = 0.0_JPRB
ZDIAG%PLIGH_TOT(:)     = 0.0_JPRB
ZDIAG%PLIGH_CTG(:)     = 0.0_JPRB
ZDIAG%PCHARGE_LIG(:)   = 0.0_JPRB

ZDIAG%ITYPE(:)         =0
ZDIAG%IPBLTYPE(:)      =0
ZDIAG%ICBOT(:)         =0
ZDIAG%ICTOP(:)         =0
ZDIAG%ICBOT_LIG(:)     =0
ZDIAG%ICTOP_LIG(:)     =0

#if defined init_alloc_zero
PSURF%PQCFL = 0.0_JPRB
PSURF%PEMIS = 0.0_JPRB
PSURF%PSNSE1 = 0.0_JPRB
PSURF%PASNE1 = 0.0_JPRB
PSURF%PRSNE1 = 0.0_JPRB
PSURF%PTSNE1 = 0.0_JPRB
PSURF%PWLE1 = 0.0_JPRB
PSURF%PTLE1 = 0.0_JPRB
PSURF%PHSTD = 0.0_JPRB
PSURF%PCVL = 0.0_JPRB
PSURF%PCVH = 0.0_JPRB
PSURF%PLAIL = 0.0_JPRB
PSURF%PLAIH = 0.0_JPRB
PSURF%PEVAPMU = 0.0_JPRB
PSURF%PTLICEE1 = 0.0_JPRB
PSURF%PTLMNWE1 = 0.0_JPRB
PSURF%PTLWMLE1 = 0.0_JPRB
PSURF%PTLBOTE1 = 0.0_JPRB
PSURF%PTLSFE1 = 0.0_JPRB
PSURF%PHLICEE1 = 0.0_JPRB
PSURF%PHLMLE1 = 0.0_JPRB
PSURF%PTSAE1 = 0.0_JPRB
PSURF%PWSAE1 = 0.0_JPRB
PSURF%PTIAE1 = 0.0_JPRB
PSURF%PUOE1 = 0.0_JPRB
PSURF%PVOE1 = 0.0_JPRB
PSURF%PTOE1 = 0.0_JPRB
PSURF%PSOE1 = 0.0_JPRB
PSURF%ITVH = 0.0_JPRB
PSURF%ITVL = 0.0_JPRB
PSURF%ISOTY = 0.0_JPRB
#elif defined init_alloc_huge
PSURF%PQCFL = HUGE(PSURF%PQCFL)
PSURF%PEMIS = HUGE(PSURF%PEMIS)
PSURF%PSNSE1 = HUGE(PSURF%PSNSE1)
PSURF%PASNE1 = HUGE(PSURF%PASNE1)
PSURF%PRSNE1 = HUGE(PSURF%PRSNE1)
PSURF%PTSNE1 = HUGE(PSURF%PTSNE1)
PSURF%PWLE1 = HUGE(PSURF%PWLE1)
PSURF%PTLE1 = HUGE(PSURF%PTLE1)
PSURF%PHSTD = HUGE(PSURF%PHSTD)
PSURF%PCVL = HUGE(PSURF%PCVL)
PSURF%PCVH = HUGE(PSURF%PCVH)
PSURF%PLAIL = HUGE(PSURF%PLAIL)
PSURF%PLAIH = HUGE(PSURF%PLAIH)
PSURF%PEVAPMU = HUGE(PSURF%PEVAPMU)
PSURF%PTLICEE1 = HUGE(PSURF%PTLICEE1)
PSURF%PTLMNWE1 = HUGE(PSURF%PTLMNWE1)
PSURF%PTLWMLE1 = HUGE(PSURF%PTLWMLE1)
PSURF%PTLBOTE1 = HUGE(PSURF%PTLBOTE1)
PSURF%PTLSFE1 = HUGE(PSURF%PTLSFE1)
PSURF%PHLICEE1 = HUGE(PSURF%PHLICEE1)
PSURF%PHLMLE1 = HUGE(PSURF%PHLMLE1)
PSURF%PTSAE1 = HUGE(PSURF%PTSAE1)
PSURF%PWSAE1 = HUGE(PSURF%PWSAE1)
PSURF%PTIAE1 = HUGE(PSURF%PTIAE1)
PSURF%PUOE1 = HUGE(PSURF%PUOE1)
PSURF%PVOE1 = HUGE(PSURF%PVOE1)
PSURF%PTOE1 = HUGE(PSURF%PTOE1)
PSURF%PSOE1 = HUGE(PSURF%PSOE1)
PSURF%ITVH = HUGE(PSURF%ITVH)
PSURF%ITVL = HUGE(PSURF%ITVL)
PSURF%ISOTY = HUGE(PSURF%ISOTY)
#endif

!*        SET SURFACE TENDENCIES TO ZERO
PSURF%PTSAE1(:,:)=0.0_JPRB
PSURF%PWSAE1(:,:)=0.0_JPRB
PSURF%PTIAE1(:,:)=0.0_JPRB
PSURF%PTLE1(:)=0.0_JPRB
PSURF%PWLE1(:)=0.0_JPRB
PSURF%PSNSE1(:,:)=0.0_JPRB       ! Tendency of snow mass
PSURF%PASNE1(:,:)=0.0_JPRB       ! Tendency of snow albedo (only 1st layer used)
PSURF%PRSNE1(:,:)=0.0_JPRB       ! Tendency of snow density
PSURF%PTSNE1(:,:)=0.0_JPRB       ! Tendency of snow temperature
PSURF%PWSNE1(:,:)=0.0_JPRB       ! Tendency of snow liquid water content
PSURF%PTLICEE1(:)=0.0_JPRB       ! tendency of lake ice temperature
PSURF%PTLMNWE1(:)=0.0_JPRB       ! tendency of lake totat layer temperature
PSURF%PTLWMLE1(:)=0.0_JPRB       ! tendency of lake mixed layer temperature
PSURF%PTLBOTE1(:)=0.0_JPRB       ! tendency of lake bottom layer temperature
PSURF%PTLSFE1(:)=0.0_JPRB        ! tendency of lake shape factor - 
PSURF%PHLICEE1(:)=0.0_JPRB       ! tendency of lake ice depth m
PSURF%PHLMLE1(:)=0.0_JPRB        ! tendency of lake mixed layer depth m/s

IF (.NOT. LECURR) THEN
  PSURF%PSD_VF(:,YSD_VF%YUCUR%MP)=0.0_JPRB
  PSURF%PSD_VF(:,YSD_VF%YVCUR%MP)=0.0_JPRB
ENDIF

!- set all aerosol optical depths to zero (except accumulated)
PSURF%PSD_VD(:,YSD_VD%YODSS%MP)  =0._JPRB
PSURF%PSD_VD(:,YSD_VD%YODDU%MP)  =0._JPRB
PSURF%PSD_VD(:,YSD_VD%YODOM%MP)  =0._JPRB
PSURF%PSD_VD(:,YSD_VD%YODBC%MP)  =0._JPRB
PSURF%PSD_VD(:,YSD_VD%YODSU%MP)  =0._JPRB
PSURF%PSD_VD(:,YSD_VD%YODNI%MP)  =0._JPRB
PSURF%PSD_VD(:,YSD_VD%YODAM%MP)  =0._JPRB
PSURF%PSD_VD(:,YSD_VD%YODVFA%MP) =0._JPRB
PSURF%PSD_VD(:,YSD_VD%YODVSU%MP) =0._JPRB
!- set all PMs to zero
PSURF%PSD_VD(:,YSD_VD%YAEPM1%MP) =0._JPRB
PSURF%PSD_VD(:,YSD_VD%YAEPM25%MP)=0._JPRB
PSURF%PSD_VD(:,YSD_VD%YAEPM10%MP)=0._JPRB
!- set all UVs to zero
PSURF%PSD_VD(:,YSD_VD%YUVBED%MP)  =0._JPRB
PSURF%PSD_VD(:,YSD_VD%YUVBEDCS%MP)=0._JPRB



#if defined init_alloc_zero
PRAD%PTINCF = 0.0_JPRB
PRAD%PDSRP = 0.0_JPRB
PRAD%PFDIR = 0.0_JPRB
PRAD%PCDIR = 0.0_JPRB
PRAD%PISUND = 0.0_JPRB
PRAD%PINCSR = 0.0_JPRB
PRAD%PINCSR0 = 0.0_JPRB
PRAD%PNEB = 0.0_JPRB
PRAD%PQICE = 0.0_JPRB
PRAD%PQLI = 0.0_JPRB
PRAD%PHRSW = 0.0_JPRB
PRAD%PHRLW = 0.0_JPRB
PRAD%PHRSC = 0.0_JPRB
PRAD%PHRLC = 0.0_JPRB
#elif defined init_alloc_huge
PRAD%PTINCF = HUGE(PRAD%PTINCF)
PRAD%PDSRP = HUGE(PRAD%PDSRP)
PRAD%PFDIR = HUGE(PRAD%PFDIR)
PRAD%PCDIR = HUGE(PRAD%PCDIR)
PRAD%PISUND = HUGE(PRAD%PISUND)
PRAD%PINCSR = HUGE(PRAD%PINCSR)
PRAD%PINCSR0 = HUGE(PRAD%PINCSR0)
PRAD%PNEB = HUGE(PRAD%PNEB)
PRAD%PQICE = HUGE(PRAD%PQICE)
PRAD%PQLI = HUGE(PRAD%PQLI)
PRAD%PHRSW = HUGE(PRAD%PHRSW)
PRAD%PHRLW = HUGE(PRAD%PHRLW)
PRAD%PHRSC = HUGE(PRAD%PHRSC)
PRAD%PHRLC = HUGE(PRAD%PHRLC)
#endif

!PFLUX_ARR

#if defined init_alloc_zero
FLUX%PFRSOD = 0.0_JPRB
FLUX%PFRSODC = 0.0_JPRB
FLUX%PUVDF = 0.0_JPRB
FLUX%PPARF = 0.0_JPRB
FLUX%PPARCF = 0.0_JPRB
FLUX%PFRTHD = 0.0_JPRB
FLUX%PFRTHDC = 0.0_JPRB
FLUX%PTOFDU = 0.0_JPRB
FLUX%PTOFDV = 0.0_JPRB
FLUX%PFTG12 = 0.0_JPRB
FLUX%PFWEV = 0.0_JPRB
FLUX%PFWSB = 0.0_JPRB
FLUX%PFWG12 = 0.0_JPRB
FLUX%PFWMLT = 0.0_JPRB
FLUX%PFWROD = 0.0_JPRB
FLUX%PFWRO1 = 0.0_JPRB
FLUX%PFTLHEV = 0.0_JPRB
FLUX%PFTLHSB = 0.0_JPRB
FLUX%PFRSOC = 0.0_JPRB
FLUX%PFRTHC = 0.0_JPRB
FLUX%PDIFCQ = 0.0_JPRB
FLUX%PDIFCS = 0.0_JPRB
FLUX%PDIFTQ = 0.0_JPRB
FLUX%PDIFTS = 0.0_JPRB
FLUX%PFCQNG = 0.0_JPRB
FLUX%PFPLCL = 0.0_JPRB
FLUX%PFPLCN = 0.0_JPRB
FLUX%PFPLSL = 0.0_JPRB
FLUX%PFPLSN = 0.0_JPRB
FLUX%PFHPCL = 0.0_JPRB
FLUX%PFHPCN = 0.0_JPRB
FLUX%PFHPSL = 0.0_JPRB
FLUX%PFHPSN = 0.0_JPRB
FLUX%PFRSO = 0.0_JPRB
FLUX%PFRTH = 0.0_JPRB
FLUX%PSTRCU = 0.0_JPRB
FLUX%PSTRCV = 0.0_JPRB
FLUX%PSTRDU = 0.0_JPRB
FLUX%PSTRDV = 0.0_JPRB
FLUX%PSTRTU = 0.0_JPRB
FLUX%PSTRTV = 0.0_JPRB
FLUX%PDIFTL = 0.0_JPRB
FLUX%PDIFTI = 0.0_JPRB
FLUX%PFCCQL = 0.0_JPRB
FLUX%PFCCQN = 0.0_JPRB
FLUX%PFCSQL = 0.0_JPRB
FLUX%PFCSQN = 0.0_JPRB
FLUX%PFCQLNG = 0.0_JPRB
FLUX%PFCQNNG = 0.0_JPRB
FLUX%PFSQRF = 0.0_JPRB
FLUX%PFSQSF = 0.0_JPRB
FLUX%PFCQRNG = 0.0_JPRB
FLUX%PFCQSNG = 0.0_JPRB
FLUX%PFSQLTUR = 0.0_JPRB
FLUX%PFSQITUR = 0.0_JPRB
FLUX%PAERODDF = 0.0_JPRB
FLUX%PENES = 0.0_JPRB
#elif defined init_alloc_huge
FLUX%PFRSOD = HUGE(FLUX%PFRSOD)
FLUX%PFRSODC = HUGE(FLUX%PFRSODC)
FLUX%PUVDF = HUGE(FLUX%PUVDF)
FLUX%PPARF = HUGE(FLUX%PPARF)
FLUX%PPARCF = HUGE(FLUX%PPARCF)
FLUX%PFRTHD = HUGE(FLUX%PFRTHD)
FLUX%PFRTHDC = HUGE(FLUX%PFRTHDC)
FLUX%PTOFDU = HUGE(FLUX%PTOFDU)
FLUX%PTOFDV = HUGE(FLUX%PTOFDV)
FLUX%PFTG12 = HUGE(FLUX%PFTG12)
FLUX%PFWEV = HUGE(FLUX%PFWEV)
FLUX%PFWSB = HUGE(FLUX%PFWSB)
FLUX%PFWG12 = HUGE(FLUX%PFWG12)
FLUX%PFWMLT = HUGE(FLUX%PFWMLT)
FLUX%PFWROD = HUGE(FLUX%PFWROD)
FLUX%PFWRO1 = HUGE(FLUX%PFWRO1)
FLUX%PFTLHEV = HUGE(FLUX%PFTLHEV)
FLUX%PFTLHSB = HUGE(FLUX%PFTLHSB)
FLUX%PFRSOC = HUGE(FLUX%PFRSOC)
FLUX%PFRTHC = HUGE(FLUX%PFRTHC)
FLUX%PDIFCQ = HUGE(FLUX%PDIFCQ)
FLUX%PDIFCS = HUGE(FLUX%PDIFCS)
FLUX%PDIFTQ = HUGE(FLUX%PDIFTQ)
FLUX%PDIFTS = HUGE(FLUX%PDIFTS)
FLUX%PFCQNG = HUGE(FLUX%PFCQNG)
FLUX%PFPLCL = HUGE(FLUX%PFPLCL)
FLUX%PFPLCN = HUGE(FLUX%PFPLCN)
FLUX%PFPLSL = HUGE(FLUX%PFPLSL)
FLUX%PFPLSN = HUGE(FLUX%PFPLSN)
FLUX%PFHPCL = HUGE(FLUX%PFHPCL)
FLUX%PFHPCN = HUGE(FLUX%PFHPCN)
FLUX%PFHPSL = HUGE(FLUX%PFHPSL)
FLUX%PFHPSN = HUGE(FLUX%PFHPSN)
FLUX%PFRSO = HUGE(FLUX%PFRSO)
FLUX%PFRTH = HUGE(FLUX%PFRTH)
FLUX%PSTRCU = HUGE(FLUX%PSTRCU)
FLUX%PSTRCV = HUGE(FLUX%PSTRCV)
FLUX%PSTRDU = HUGE(FLUX%PSTRDU)
FLUX%PSTRDV = HUGE(FLUX%PSTRDV)
FLUX%PSTRTU = HUGE(FLUX%PSTRTU)
FLUX%PSTRTV = HUGE(FLUX%PSTRTV)
FLUX%PDIFTL = HUGE(FLUX%PDIFTL)
FLUX%PDIFTI = HUGE(FLUX%PDIFTI)
FLUX%PFCCQL = HUGE(FLUX%PFCCQL)
FLUX%PFCCQN = HUGE(FLUX%PFCCQN)
FLUX%PFCSQL = HUGE(FLUX%PFCSQL)
FLUX%PFCSQN = HUGE(FLUX%PFCSQN)
FLUX%PFCQLNG = HUGE(FLUX%PFCQLNG)
FLUX%PFCQNNG = HUGE(FLUX%PFCQNNG)
FLUX%PFSQRF = HUGE(FLUX%PFSQRF)
FLUX%PFSQSF = HUGE(FLUX%PFSQSF)
FLUX%PFCQRNG = HUGE(FLUX%PFCQRNG)
FLUX%PFCQSNG = HUGE(FLUX%PFCQSNG)
FLUX%PFSQLTUR = HUGE(FLUX%PFSQLTUR)
FLUX%PFSQITUR = HUGE(FLUX%PFSQITUR)
FLUX%PAERODDF = HUGE(FLUX%PAERODDF)
FLUX%PENES = HUGE(FLUX%PENES)
#endif

!*      SET FLUXES TO ZERO
FLUX%PDIFTI(:,:) = 0.0_JPRB
FLUX%PDIFTL(:,:) = 0.0_JPRB
FLUX%PFCQNNG(:,:) = 0.0_JPRB
FLUX%PFCQLNG(:,:) = 0.0_JPRB
FLUX%PFCSQN(:,:) = 0.0_JPRB
FLUX%PFCSQL(:,:) = 0.0_JPRB
FLUX%PFSQRF(:,:) = 0.0_JPRB
FLUX%PFSQSF(:,:) = 0.0_JPRB
FLUX%PFCQRNG(:,:) = 0.0_JPRB
FLUX%PFCQSNG(:,:) = 0.0_JPRB
FLUX%PFSQLTUR(:,:) = 0.0_JPRB
FLUX%PFSQITUR(:,:) = 0.0_JPRB
FLUX%PFCCQL(:,:) = 0.0_JPRB
FLUX%PFCCQN(:,:) = 0.0_JPRB
FLUX%PFPLCL(:,:) = 0.0_JPRB
FLUX%PFPLCN(:,:) = 0.0_JPRB
FLUX%PFPLSL(:,:) = 0.0_JPRB
FLUX%PFPLSN(:,:) = 0.0_JPRB
FLUX%PFCQNG(:,:) = 0.0_JPRB
!     ------------------------------------------------------------------
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('PHYS_ARRAYS_INI',1,ZHOOK_HANDLE)
END SUBROUTINE PHYS_ARRAYS_INI



