! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

#ifdef RS6K
@PROCESS NOOPTIMIZE
#endif
!pgi$r opt=0 
SUBROUTINE UPDECAEC(YDGEOMETRY,YDERAD,YDRIP,KINDAT,KMINUT)
!DEC$ NOOPTIMIZE

!**** *UPDECAEC* - DEFINES NEW CLIMATOLOGICAL DISTRIBUTION OF AEROSOLS

!     PURPOSE.
!     --------

!**   INTERFACE.
!     ----------
!        CALL *UPDECAEC* FROM *UPDTIM*

!        EXPLICIT ARGUMENTS :
!        --------------------
!     ==== INPUTS ===
!     ==== OUTPUTS ===
!     AEROSOL TOTAL OPTICAL THICKNESS (0.55 MICRON)

!-- TEGEN ET AL. MONTHLY CLIMATOLOGY OF TROPOSPHERIC AEROSOLS

! RTAEBC : BLACK CARBON AEROSOL
! RTAEOR : ORGANIC AEROSOL
! RTAESD : SAND DUST AEROSOL
! RTAESS : SEA SALT AEROSOL
! RTAESU : SULFATE AEROSOL

!-- HISTORICAL STRATOSPHERIC VOLCANIC AEROSOLS

! RTAEVO : VOLCANIC AEROSOL

!        IMPLICIT ARGUMENTS :   NONE
!        --------------------

!     METHOD.
!     -------

!     EXTERNALS.
!     ----------

!          NONE

!     REFERENCE.
!     ----------

!        SEE RADIATION'S PART OF THE MODEL'S DOCUMENTATION AND
!        ECMWF RESEARCH DEPARTMENT DOCUMENTATION OF THE "I.F.S"

!     AUTHOR.
!     -------
!      O. Marsden 2018-01-30  From SUECAEC

!     MODIFICATIONS.
!     --------------
!      
!-----------------------------------------------------------------------

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1     , ONLY : JPRD, JPIM, JPRB, JPIB
USE YOMLUN       , ONLY : NULOUT, FOPEN
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOEAERC      , ONLY : CVOLCDATA, LVOLCDATA
USE YOERAD       , ONLY : TERAD
USE YOMVERT      , ONLY : VP00
USE YOMRIP       , ONLY : TRIP
IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(TERAD)       ,INTENT(INOUT) :: YDERAD
TYPE(TRIP)        ,INTENT(INOUT) :: YDRIP
INTEGER(KIND=JPIM),INTENT(IN)    :: KINDAT 
INTEGER(KIND=JPIB),INTENT(IN)    :: KMINUT 

!     -----------------------------------------------------------------

REAL(KIND=JPRB),PARAMETER :: ZYTIME(12)= (/&
   & 22320._JPRB,  64980._JPRB, 107640._JPRB, 151560._JPRB, 195480._JPRB, 239400._JPRB&
   & , 283320._JPRB, 327960._JPRB, 371880._JPRB, 415800._JPRB, 459720._JPRB, 503640._JPRB&
   & /) 
REAL(KIND=JPRB),PARAMETER :: ZMDAY(12)=(/ &
   & 31._JPRB,    59.25_JPRB,  90.25_JPRB, 120.25_JPRB, 151.25_JPRB, 181.25_JPRB&
   & ,  212.25_JPRB, 243.25_JPRB, 273.25_JPRB, 304.25_JPRB, 334.25_JPRB, 365.25_JPRB&
   & /)  

REAL(KIND=JPRB),PARAMETER :: ZRAESHDUM(12) = (/&
 & 1000, 1000, 2000, 2000, 2000, 3000, 3000, 2000, 2000, 2000, 1000, 1000/)

INTEGER(KIND=JPIM) :: IDY, IM, IM1, IM2, IMN, IYR, IYR1, IYR2, JI, JL, JK
INTEGER(KIND=JPIM) :: IDYADD, IDAYMIN, IT1, IT2, INYR, INMN, INDY, IMV1, IMV2
INTEGER(KIND=JPIM) :: ILMO(12)

INTEGER(KIND=JPIM) :: IU,INLEV,ILAT,IDUM
REAL(KIND=JPRB)    :: Z_GRID, ZINT, ZLAT, ZRES, ZRESM, ZRESP, ZTIMI, ZXTIME
REAL(KIND=JPRB)    :: ZW1, ZW2
CHARACTER(LEN=1000):: CLINE

LOGICAL            :: LL_USE_OPENMP = .TRUE.

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE


REAL(KIND=JPRB) :: ZPRES(0:YDGEOMETRY%YRDIMV%NFLEVG),ZETAH(0:YDGEOMETRY%YRDIMV%NFLEVG),ZPRESF(YDGEOMETRY%YRDIMV%NFLEVG)

#include "abor1.intfb.h"
#include "updcal.intfb.h"
#include "fcttim.func.h"      
#include "su_aerv.intfb.h"
#include "gphpre.intfb.h"

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('UPDECAEC',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIMV=>YDGEOMETRY%YRDIMV,YDVAB=>YDGEOMETRY%YRVAB,YDCVER=>YDGEOMETRY%YRCVER)
ASSOCIATE(NAERMACC=>YDERAD%NAERMACC, NMCLAT=>YDERAD%NMCLAT, NMCLON=>YDERAD%NMCLON,NMCLEV=>YDERAD%NMCLEV, &
 & RAESHDU=>YDERAD%RAESHDU, CVDAEBC=>YDERAD%CVDAEBC, CVDAEDU=>YDERAD%CVDAEDU, & 
 & CVDAEOM=>YDERAD%CVDAEOM, CVDAESS=>YDERAD%CVDAESS, CVDAESU=>YDERAD%CVDAESU, &
 & NFLEVG=>YDDIMV%NFLEVG, LDUSEASON=>YDERAD%LDUSEASON, &
 & YDECMIP=>YDRIP%YRECMIP, YDEAERC_TEGEN=>YDRIP%YREAERC_TEGEN, YDEAERC_MACC=>YDRIP%YREAERC_MACC)


!     ------------------------------------------------------------------

!*         1.     TIME INDEX WITHIN AEROSOL CLIMATOLOGY
!                 -------------------------------------

!*         1.1    SEASONAL TIME INDEX WITHIN TEGEN'S AEROSOL CLIMATOLOGY
!                 ------------------------------------------------------

IDY=NDD(KINDAT)-1
IMN=NMM(KINDAT)
IF (IMN == 1) THEN
  ZXTIME=REAL(IDY)*1440._JPRB + KMINUT
ELSEIF (IMN == 2) THEN
  IF(IDY == 28) IDY=IDY-1
! A DAY IN FEB. IS 28.25*24*60/28=1452.8571min LONG.
  ZXTIME=44640._JPRB+REAL(IDY)*1452.8571_JPRB+KMINUT
ELSE
  ZXTIME=(ZMDAY(IMN-1)+REAL(IDY))*1440._JPRB+KMINUT
ENDIF
! 525960=MINUTES IN A SIDERAL YEAR (365.25d)
ZXTIME=MOD(ZXTIME,525960._JPRB)

IM1=0
IM2=0
IF (ZXTIME <= ZYTIME(1)) THEN
  IM1=12
  IM2=1
  ZTIMI=(ZYTIME(1)-ZXTIME)/44640._JPRB
ELSEIF(ZXTIME > ZYTIME(12)) THEN
  IM1=12
  IM2=1
  ZTIMI=(548280._JPRB-ZXTIME)/44640._JPRB
! 548280.=(365.25d + 15.5d)*24*60
ELSE
  DO IM=1,11
    IF (ZXTIME > ZYTIME(IM) .AND. ZXTIME <= ZYTIME(IM+1)) THEN
      IM1=IM
      IM2=IM+1
      ZTIMI=(ZXTIME-ZYTIME(IM2))/(ZYTIME(IM1)-ZYTIME(IM2))
    ENDIF
  ENDDO
  IF (IM1 == 0.OR. IM2 == 0 ) THEN
    CALL ABOR1('Problem with time interpolation in UPDECAEC!')
  ENDIF
ENDIF

!*         1.2    TIME INDEX WITHIN GISS VOLCANIC AEROSOL CLIMATOLOGY
!                 ---------------------------------------------------

IYR=NCCAA(KINDAT)
IDY=NDD(KINDAT)

IDYADD=KMINUT/1440
IDAYMIN=KMINUT-1440*IDYADD

CALL UPDCAL(IDY,IMN,IYR,IDYADD,INDY,INMN,INYR,ILMO,-1)

! Assume monthly means valid at 0Z on the 16th of each month and interpolate linearly

IF(INDY >= 16) THEN
  IMV1=INMN
  IMV2=1+MOD(INMN,12)
  IYR1=INYR
  IF(IMV1 /= 12) THEN
    IYR2=INYR
  ELSE
    IYR2=INYR+1
  ENDIF
  IT1=16
  IT2=16+ILMO(IMV1)
ELSE
  IMV1=1+MOD(INMN+10,12)
  IMV2=INMN
  IF(IMV1 /= 12) THEN
    IYR1=INYR
  ELSE
    IYR1=INYR-1
  ENDIF
  IYR2=INYR
  IT1=16-ILMO(IMV1)
  IT2=16
ENDIF
! Ensure date within range as provided in data set
IYR1=MAX(IYR1,YDEAERC_TEGEN%ISYEAR)
IYR2=MAX(IYR2,YDEAERC_TEGEN%ISYEAR)
IYR1=MIN(IYR1,YDEAERC_TEGEN%IEYEAR)
IYR2=MIN(IYR2,YDEAERC_TEGEN%IEYEAR)

ZW1=REAL(IT2*1440-(INDY*1440+IDAYMIN),JPRB)/REAL((IT2-IT1)*1440,JPRB)
ZW2=1.0_JPRB-ZW1


!*         2.0    TOTAL OPTICAL THICKNESS
!                 -----------------------

!*         2.1    TROPOSPHERIC AEROSOL MONTHLY CLIMATOLOGY
!                 ----------------------------------------

!-- VECTOR OF LATITUDES FOR TEGEN ET AL. AEROSOL CLIMATOLOGY:

IF (.NOT. LL_USE_OPENMP) THEN
DO JI=1,46
  DO JL=1,72
    YDEAERC_TEGEN%RTAEBC(JL,JI)=YDEAERC_TEGEN%RAERBC(JL,JI,IM2)&
     & +ZTIMI*(YDEAERC_TEGEN%RAERBC(JL,JI,IM1)-YDEAERC_TEGEN%RAERBC(JL,JI,IM2))       
    YDEAERC_TEGEN%RTAEOR(JL,JI)=YDEAERC_TEGEN%RAEROR(JL,JI,IM2)&
     & +ZTIMI*(YDEAERC_TEGEN%RAEROR(JL,JI,IM1)-YDEAERC_TEGEN%RAEROR(JL,JI,IM2))       
    YDEAERC_TEGEN%RTAESD(JL,JI)=YDEAERC_TEGEN%RAERSD(JL,JI,IM2)&
     & +ZTIMI*(YDEAERC_TEGEN%RAERSD(JL,JI,IM1)-YDEAERC_TEGEN%RAERSD(JL,JI,IM2))       
    YDEAERC_TEGEN%RTAESS(JL,JI)=YDEAERC_TEGEN%RAERSS(JL,JI,IM2)&
     & +ZTIMI*(YDEAERC_TEGEN%RAERSS(JL,JI,IM1)-YDEAERC_TEGEN%RAERSS(JL,JI,IM2))       
    YDEAERC_TEGEN%RTAESU(JL,JI)=YDEAERC_TEGEN%RAERSU(JL,JI,IM2)&
     & +ZTIMI*(YDEAERC_TEGEN%RAERSU(JL,JI,IM1)-YDEAERC_TEGEN%RAERSU(JL,JI,IM2))  
  ENDDO
ENDDO

ELSE
  !$OMP PARALLEL FIRSTPRIVATE(IM1,IM2,ZTIMI)
  CALL UPDATE_ARR_2D(72, 46, YDEAERC_TEGEN%RAERBC, YDEAERC_TEGEN%RTAEBC, IM1, IM2, ZTIMI)
  CALL UPDATE_ARR_2D(72, 46, YDEAERC_TEGEN%RAEROR, YDEAERC_TEGEN%RTAEOR, IM1, IM2, ZTIMI)
  CALL UPDATE_ARR_2D(72, 46, YDEAERC_TEGEN%RAERSD, YDEAERC_TEGEN%RTAESD, IM1, IM2, ZTIMI)
  CALL UPDATE_ARR_2D(72, 46, YDEAERC_TEGEN%RAERSS, YDEAERC_TEGEN%RTAESS, IM1, IM2, ZTIMI)
  CALL UPDATE_ARR_2D(72, 46, YDEAERC_TEGEN%RAERSU, YDEAERC_TEGEN%RTAESU, IM1, IM2, ZTIMI)
  !$OMP END PARALLEL
ENDIF

IF(NAERMACC == 1) THEN
  WRITE(NULOUT,FMT='(" UPDECAEC NAERMACC = ",I2)') NAERMACC
  
  IF (LDUSEASON) THEN
    !time interpolation of the monthly-mean scale height for dust
    RAESHDU=ZRAESHDUM(IM2)&
     & +ZTIMI*(ZRAESHDUM(IM1)-ZRAESHDUM(IM2))       
  !     ------------------------------------------------------------------
  !*          DEFINE STANDARD ATMOSPHERE VERTICAL CONFIGURATION
  !                 -------------------------------------------------
    ZPRES(NFLEVG)=VP00

    CALL GPHPRE(1,NFLEVG,1,1,YDVAB,YDCVER,ZPRES,PRESF=ZPRESF)

    DO JK=0,NFLEVG
      ZETAH(JK)= ZPRES(JK)/ZPRES(NFLEVG)
    ENDDO
  !update the function to distribute vertically the aerosols 
  !(it is actually only dust that is updated, the others 
  !remain the same as their default in suecrad)
    WRITE(UNIT=NULOUT,FMT='('' UPDT RAESHDU = '',F7.1 )') RAESHDU

    CALL SU_AERV(YDERAD,NFLEVG,ZETAH)
  ENDIF

    IF (YDERAD%LAER3D) THEN
      IF (.NOT. LL_USE_OPENMP) THEN
           DO JK=1,NMCLEV
              DO JI=1,NMCLAT
                 DO JL=1,NMCLON
                    YDEAERC_MACC%RMAEBC13D(JL,JI,JK)=YDEAERC_MACC%RMACBC13D(JL,JI,JK,IM2)&
                         & +ZTIMI*(YDEAERC_MACC%RMACBC13D(JL,JI,JK,IM1)-YDEAERC_MACC%RMACBC13D(JL,JI,JK,IM2))       
                    YDEAERC_MACC%RMAEBC23D(JL,JI,JK)=YDEAERC_MACC%RMACBC23D(JL,JI,JK,IM2)&
                         & +ZTIMI*(YDEAERC_MACC%RMACBC23D(JL,JI,JK,IM1)-YDEAERC_MACC%RMACBC23D(JL,JI,JK,IM2))       
                    YDEAERC_MACC%RMAEOR13D(JL,JI,JK)=YDEAERC_MACC%RMACOR13D(JL,JI,JK,IM2)&
                         & +ZTIMI*(YDEAERC_MACC%RMACOR13D(JL,JI,JK,IM1)-YDEAERC_MACC%RMACOR13D(JL,JI,JK,IM2))       
                    YDEAERC_MACC%RMAEOR23D(JL,JI,JK)=YDEAERC_MACC%RMACOR23D(JL,JI,JK,IM2)&
                         & +ZTIMI*(YDEAERC_MACC%RMACOR23D(JL,JI,JK,IM1)-YDEAERC_MACC%RMACOR23D(JL,JI,JK,IM2))       
                    YDEAERC_MACC%RMAESD13D(JL,JI,JK)=YDEAERC_MACC%RMACSD13D(JL,JI,JK,IM2)&
                         & +ZTIMI*(YDEAERC_MACC%RMACSD13D(JL,JI,JK,IM1)-YDEAERC_MACC%RMACSD13D(JL,JI,JK,IM2))       
                    YDEAERC_MACC%RMAESD23D(JL,JI,JK)=YDEAERC_MACC%RMACSD23D(JL,JI,JK,IM2)&
                         & +ZTIMI*(YDEAERC_MACC%RMACSD23D(JL,JI,JK,IM1)-YDEAERC_MACC%RMACSD23D(JL,JI,JK,IM2))       
                    YDEAERC_MACC%RMAESD33D(JL,JI,JK)=YDEAERC_MACC%RMACSD33D(JL,JI,JK,IM2)&
                         & +ZTIMI*(YDEAERC_MACC%RMACSD33D(JL,JI,JK,IM1)-YDEAERC_MACC%RMACSD33D(JL,JI,JK,IM2))       
                    YDEAERC_MACC%RMAESS13D(JL,JI,JK)=YDEAERC_MACC%RMACSS13D(JL,JI,JK,IM2)&
                         & +ZTIMI*(YDEAERC_MACC%RMACSS13D(JL,JI,JK,IM1)-YDEAERC_MACC%RMACSS13D(JL,JI,JK,IM2))       
                    YDEAERC_MACC%RMAESS23D(JL,JI,JK)=YDEAERC_MACC%RMACSS23D(JL,JI,JK,IM2)&
                         & +ZTIMI*(YDEAERC_MACC%RMACSS23D(JL,JI,JK,IM1)-YDEAERC_MACC%RMACSS23D(JL,JI,JK,IM2))       
                    YDEAERC_MACC%RMAESS33D(JL,JI,JK)=YDEAERC_MACC%RMACSS33D(JL,JI,JK,IM2)&
                         & +ZTIMI*(YDEAERC_MACC%RMACSS33D(JL,JI,JK,IM1)-YDEAERC_MACC%RMACSS33D(JL,JI,JK,IM2))       
                    YDEAERC_MACC%RMAESU13D(JL,JI,JK)=YDEAERC_MACC%RMACSU13D(JL,JI,JK,IM2)&
                         & +ZTIMI*(YDEAERC_MACC%RMACSU13D(JL,JI,JK,IM1)-YDEAERC_MACC%RMACSU13D(JL,JI,JK,IM2)) 
                    !reference pressure
                    YDEAERC_MACC%REF_AER_PRS(JL,JI,JK)=YDEAERC_MACC%REF_MON_AER_PRS(JL,JI,JK,IM2)&
                         & +ZTIMI*(YDEAERC_MACC%REF_MON_AER_PRS(JL,JI,JK,IM1)-YDEAERC_MACC%REF_MON_AER_PRS(JL,JI,JK,IM2)) 
                    YDEAERC_MACC%REF_AER_DPRS(JL,JI,JK)=YDEAERC_MACC%REF_MON_AER_DPRS(JL,JI,JK,IM2)&
                         & +ZTIMI*(YDEAERC_MACC%REF_MON_AER_DPRS(JL,JI,JK,IM1)-YDEAERC_MACC%REF_MON_AER_DPRS(JL,JI,JK,IM2)) 
                 ENDDO
              ENDDO
           ENDDO
      ELSE
        !$OMP PARALLEL FIRSTPRIVATE(IM1,IM2,ZTIMI)
        CALL UPDATE_ARR_3D(NMCLON,NMCLAT,NMCLEV,YDEAERC_MACC%RMACBC13D, YDEAERC_MACC%RMAEBC13D, IM1, IM2, ZTIMI)
        CALL UPDATE_ARR_3D(NMCLON,NMCLAT,NMCLEV,YDEAERC_MACC%RMACBC23D, YDEAERC_MACC%RMAEBC23D, IM1, IM2, ZTIMI)
        CALL UPDATE_ARR_3D(NMCLON,NMCLAT,NMCLEV,YDEAERC_MACC%RMACOR13D, YDEAERC_MACC%RMAEOR13D, IM1, IM2, ZTIMI)
        CALL UPDATE_ARR_3D(NMCLON,NMCLAT,NMCLEV,YDEAERC_MACC%RMACOR23D, YDEAERC_MACC%RMAEOR23D, IM1, IM2, ZTIMI)
        CALL UPDATE_ARR_3D(NMCLON,NMCLAT,NMCLEV,YDEAERC_MACC%RMACSD13D, YDEAERC_MACC%RMAESD13D, IM1, IM2, ZTIMI)
        CALL UPDATE_ARR_3D(NMCLON,NMCLAT,NMCLEV,YDEAERC_MACC%RMACSD23D, YDEAERC_MACC%RMAESD23D, IM1, IM2, ZTIMI)
        CALL UPDATE_ARR_3D(NMCLON,NMCLAT,NMCLEV,YDEAERC_MACC%RMACSD33D, YDEAERC_MACC%RMAESD33D, IM1, IM2, ZTIMI)
        CALL UPDATE_ARR_3D(NMCLON,NMCLAT,NMCLEV,YDEAERC_MACC%RMACSS13D, YDEAERC_MACC%RMAESS13D, IM1, IM2, ZTIMI)
        CALL UPDATE_ARR_3D(NMCLON,NMCLAT,NMCLEV,YDEAERC_MACC%RMACSS23D, YDEAERC_MACC%RMAESS23D, IM1, IM2, ZTIMI)
        CALL UPDATE_ARR_3D(NMCLON,NMCLAT,NMCLEV,YDEAERC_MACC%RMACSS33D, YDEAERC_MACC%RMAESS33D, IM1, IM2, ZTIMI)
        CALL UPDATE_ARR_3D(NMCLON,NMCLAT,NMCLEV,YDEAERC_MACC%RMACSU13D, YDEAERC_MACC%RMAESU13D, IM1, IM2, ZTIMI)
        CALL UPDATE_ARR_3D(NMCLON,NMCLAT,NMCLEV,YDEAERC_MACC%REF_MON_AER_PRS, YDEAERC_MACC%REF_AER_PRS, IM1, IM2, ZTIMI)
        CALL UPDATE_ARR_3D(NMCLON,NMCLAT,NMCLEV,YDEAERC_MACC%REF_MON_AER_DPRS, YDEAERC_MACC%REF_AER_DPRS, IM1, IM2, ZTIMI)
        !$OMP END PARALLEL
      ENDIF
  ENDIF

IF (.NOT. LL_USE_OPENMP) THEN
  DO JI=1,NMCLAT
    DO JL=1,NMCLON
      YDEAERC_MACC%RMAEBC1(JL,JI)=YDEAERC_MACC%RMACBC1(JL,JI,IM2)&
       & +ZTIMI*(YDEAERC_MACC%RMACBC1(JL,JI,IM1)-YDEAERC_MACC%RMACBC1(JL,JI,IM2))       
      YDEAERC_MACC%RMAEBC2(JL,JI)=YDEAERC_MACC%RMACBC2(JL,JI,IM2)&
       & +ZTIMI*(YDEAERC_MACC%RMACBC2(JL,JI,IM1)-YDEAERC_MACC%RMACBC2(JL,JI,IM2))       
      YDEAERC_MACC%RMAEOR1(JL,JI)=YDEAERC_MACC%RMACOR1(JL,JI,IM2)&
       & +ZTIMI*(YDEAERC_MACC%RMACOR1(JL,JI,IM1)-YDEAERC_MACC%RMACOR1(JL,JI,IM2))       
      YDEAERC_MACC%RMAEOR2(JL,JI)=YDEAERC_MACC%RMACOR2(JL,JI,IM2)&
       & +ZTIMI*(YDEAERC_MACC%RMACOR2(JL,JI,IM1)-YDEAERC_MACC%RMACOR2(JL,JI,IM2))       
      YDEAERC_MACC%RMAESD1(JL,JI)=YDEAERC_MACC%RMACSD1(JL,JI,IM2)&
       & +ZTIMI*(YDEAERC_MACC%RMACSD1(JL,JI,IM1)-YDEAERC_MACC%RMACSD1(JL,JI,IM2))       
      YDEAERC_MACC%RMAESD2(JL,JI)=YDEAERC_MACC%RMACSD2(JL,JI,IM2)&
       & +ZTIMI*(YDEAERC_MACC%RMACSD2(JL,JI,IM1)-YDEAERC_MACC%RMACSD2(JL,JI,IM2))       
      YDEAERC_MACC%RMAESD3(JL,JI)=YDEAERC_MACC%RMACSD3(JL,JI,IM2)&
       & +ZTIMI*(YDEAERC_MACC%RMACSD3(JL,JI,IM1)-YDEAERC_MACC%RMACSD3(JL,JI,IM2))       
      YDEAERC_MACC%RMAESS1(JL,JI)=YDEAERC_MACC%RMACSS1(JL,JI,IM2)&
       & +ZTIMI*(YDEAERC_MACC%RMACSS1(JL,JI,IM1)-YDEAERC_MACC%RMACSS1(JL,JI,IM2))       
      YDEAERC_MACC%RMAESS2(JL,JI)=YDEAERC_MACC%RMACSS2(JL,JI,IM2)&
       & +ZTIMI*(YDEAERC_MACC%RMACSS2(JL,JI,IM1)-YDEAERC_MACC%RMACSS2(JL,JI,IM2))       
      YDEAERC_MACC%RMAESS3(JL,JI)=YDEAERC_MACC%RMACSS3(JL,JI,IM2)&
       & +ZTIMI*(YDEAERC_MACC%RMACSS3(JL,JI,IM1)-YDEAERC_MACC%RMACSS3(JL,JI,IM2))       
      YDEAERC_MACC%RMAESU1(JL,JI)=YDEAERC_MACC%RMACSU1(JL,JI,IM2)&
       & +ZTIMI*(YDEAERC_MACC%RMACSU1(JL,JI,IM1)-YDEAERC_MACC%RMACSU1(JL,JI,IM2))  
    ENDDO
  ENDDO
ELSE
!$OMP PARALLEL FIRSTPRIVATE(IM1,IM2,ZTIMI) 
  CALL UPDATE_ARR_2D(NMCLON, NMCLAT, YDEAERC_MACC%RMACBC1, YDEAERC_MACC%RMAEBC1, IM1, IM2, ZTIMI)
  CALL UPDATE_ARR_2D(NMCLON, NMCLAT, YDEAERC_MACC%RMACBC2, YDEAERC_MACC%RMAEBC2, IM1, IM2, ZTIMI)
  CALL UPDATE_ARR_2D(NMCLON, NMCLAT, YDEAERC_MACC%RMACOR1, YDEAERC_MACC%RMAEOR1, IM1, IM2, ZTIMI)
  CALL UPDATE_ARR_2D(NMCLON, NMCLAT, YDEAERC_MACC%RMACOR2, YDEAERC_MACC%RMAEOR2, IM1, IM2, ZTIMI)
  CALL UPDATE_ARR_2D(NMCLON, NMCLAT, YDEAERC_MACC%RMACSD1, YDEAERC_MACC%RMAESD1, IM1, IM2, ZTIMI)
  CALL UPDATE_ARR_2D(NMCLON, NMCLAT, YDEAERC_MACC%RMACSD2, YDEAERC_MACC%RMAESD2, IM1, IM2, ZTIMI)
  CALL UPDATE_ARR_2D(NMCLON, NMCLAT, YDEAERC_MACC%RMACSD3, YDEAERC_MACC%RMAESD3, IM1, IM2, ZTIMI)
  CALL UPDATE_ARR_2D(NMCLON, NMCLAT, YDEAERC_MACC%RMACSS1, YDEAERC_MACC%RMAESS1, IM1, IM2, ZTIMI)
  CALL UPDATE_ARR_2D(NMCLON, NMCLAT, YDEAERC_MACC%RMACSS2, YDEAERC_MACC%RMAESS2, IM1, IM2, ZTIMI)
  CALL UPDATE_ARR_2D(NMCLON, NMCLAT, YDEAERC_MACC%RMACSS3, YDEAERC_MACC%RMAESS3, IM1, IM2, ZTIMI)
  CALL UPDATE_ARR_2D(NMCLON, NMCLAT, YDEAERC_MACC%RMACSU1, YDEAERC_MACC%RMAESU1, IM1, IM2, ZTIMI)
!$OMP END PARALLEL
ENDIF

ENDIF

!*         2.2    VOLCANIC AEROSOL CLIMATOLOGY
!                 ----------------------------


IF (YDECMIP%NCMIPFIXYR>0) THEN
   IYR1=YDECMIP%NCMIPFIXYR
   IYR2=YDECMIP%NCMIPFIXYR
ENDIF

Z_GRID=4._JPRB
DO JI=1,46
  ZLAT=90._JPRB-(JI-1)*Z_GRID
  DO JL=1,23
    IF (ZLAT == YDEAERC_TEGEN%RLATV(JL)) THEN
      ZRES=ZW1*YDEAERC_TEGEN%RAERV(JL,IYR1,IMV1)+ZW2*YDEAERC_TEGEN%RAERV(JL,IYR2,IMV2)
    ELSEIF (ZLAT < YDEAERC_TEGEN%RLATV(JL).AND.ZLAT >= YDEAERC_TEGEN%RLATV(JL+1))THEN
      ZINT=(ZLAT-YDEAERC_TEGEN%RLATV(JL+1))/(YDEAERC_TEGEN%RLATV(JL)-YDEAERC_TEGEN%RLATV(JL+1))
      ZRESM=ZW1*YDEAERC_TEGEN%RAERV(JL  ,IYR1,IMV1)+ZW2*YDEAERC_TEGEN%RAERV(JL  ,IYR2,IMV2)
      ZRESP=ZW1*YDEAERC_TEGEN%RAERV(JL+1,IYR1,IMV1)+ZW2*YDEAERC_TEGEN%RAERV(JL+1,IYR2,IMV2)
      ZRES=ZRESP-ZINT*(ZRESP-ZRESM)
    ENDIF
  ENDDO
  YDEAERC_TEGEN%RTAEVO(JI)=ZRES
ENDDO

WRITE(NULOUT,*)"UPDECAEC: GLOBAL AVERAGE VOLCANIC SULPHATE FOR (KINDAT,KMINUT,IYR1,IYR2) ", &
    & KINDAT, KMINUT, IYR1, IYR2,SUM(YDEAERC_TEGEN%RTAEVO)/46._JPRB 

!-- security for aerosol optical thickness
YDEAERC_TEGEN%REPAER=1.E-12_JPRB

!     ------------------------------------------------------------------

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('UPDECAEC',1,ZHOOK_HANDLE)

!-----------------------------------------------------------------------------
CONTAINS

  SUBROUTINE UPDATE_ARR_2D(KDIM1,KDIM2,ARR_IN, ARR_OUT, KM1, KM2,PTIMI)
  IMPLICIT NONE
  REAL(KIND=JPRB), DIMENSION(KDIM1,KDIM2,12), INTENT(IN)  :: ARR_IN
  REAL(KIND=JPRB), DIMENSION(KDIM1,KDIM2),    INTENT(OUT) :: ARR_OUT
  INTEGER(KIND=JPIM), INTENT(IN) :: KDIM1, KDIM2, KM1, KM2
  REAL(KIND=JPRB),    INTENT(IN) :: PTIMI

  INTEGER :: JI, JL

  !$OMP DO
  DO JI=1,KDIM2
    DO JL=1,KDIM1
      ARR_OUT(JL,JI)=ARR_IN(JL,JI,KM2)&
       & +PTIMI*(ARR_IN(JL,JI,KM1)-ARR_IN(JL,JI,KM2))       
    END DO
  END DO
  !$OMP ENDDO

  END SUBROUTINE UPDATE_ARR_2D 

  SUBROUTINE UPDATE_ARR_3D(KDIM1,KDIM2,KDIM3,ARR_IN, ARR_OUT, KM1, KM2,PTIMI)
  IMPLICIT NONE
  REAL(KIND=JPRB), DIMENSION(KDIM1,KDIM2,KDIM3, 12), INTENT(IN)  :: ARR_IN
  REAL(KIND=JPRB), DIMENSION(KDIM1,KDIM2,KDIM3),    INTENT(OUT) :: ARR_OUT
  INTEGER(KIND=JPIM), INTENT(IN) :: KDIM1,KDIM2,KDIM3,KM1, KM2
  REAL(KIND=JPRB),    INTENT(IN) :: PTIMI

  INTEGER :: JI, JL, JK

!DIR$ ASSUME_ALIGNED ARR_IN: 64
!DIR$ ASSUME_ALIGNED ARR_OUT: 64

   !$OMP DO COLLAPSE(2) SCHEDULE(STATIC)
   DO JK=1,KDIM3
      DO JI=1,KDIM2
        !$omp simd 
        DO JL=1,KDIM1
          ARR_OUT(JL,JI,JK)=ARR_IN(JL,JI,JK,KM2)&
           & +PTIMI*(ARR_IN(JL,JI,JK,KM1)-ARR_IN(JL,JI,JK,KM2))
        END DO
      END DO
   END DO
   !$OMP ENDDO

   END SUBROUTINE UPDATE_ARR_3D 

END SUBROUTINE UPDECAEC
