! (C) Copyright 1989- Meteo-France.

SUBROUTINE SUCDDH(YDMODEL)
!     ------------------------------------------------------------------

!**   *SUCDDH* IS THE SET-UP ROUTINE FOR MODULE *YOMCDDH*

!     Original    C.Jakob         E.C.M.W.F.      15/05/00

!     PURPOSE
!     -------

!          This routine fills the character arrays that 
!          contain the names of variables and fluxes for
!          the writeout of the surface variables/fluxes to
!          the DDH file. The arrays are kept in module YOMCDDH.
!          The writeout is performed in routine PPFIDH.  

!     INTERFACE.
!     ----------

!     CALL *SUCDDH* FROM *SU0YOMA*

!          JJMorcrette 020930  UV, PAR, CAPE 
!        M.Hamrud      01-Oct-2003 CY28 Cleaning
!        M.Hamrud      01-Dec-2003 CY28R1 Cleaning
!        JJMorcrette 20060721 PP of clear-sky PAR and TOA incident soalr radiation
!        S.Serrar      26-09-2005 add DDH names for GHG 
!        S.Serrar      07-09-2006 DDH names for new tracers
!        S.Serrar      17-07-2007 update DDH for GEMS adding methane
!        JJMorcrette 20061002 DDH for aerosol physics
!        JJMorcrette 20100512 bug-fix for FDIR, CDIR
!        M.Ahlgrimm  20111031 Clear-sky downward radiation at surface
!        L.Jones       26-10-2011 MACC: bug fixes and removal of duplicated logic.
!        R Engelen   20111024 Clean-up SF6
!        M. Ahlgrimm Apr 2014: Add lake variables and precip fraction to DDH output
!        P.Bechtold 10-Nov-2015: Add Ceiling,CTOPC,ZWETB0,1 
!        A. Bozzo:   Jan 2016 Add solar direct beam at surface
!     ------------------------------------------------------------------

USE TYPE_MODEL         , ONLY : MODEL
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 , ONLY : JPRB, JPIM
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK


IMPLICIT NONE

TYPE(MODEL) ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM) :: JFLX

CHARACTER(LEN=3) :: CLTXT(7)

INTEGER(KIND=JPIM) :: JVAR , IFSVAR_ECMWF , IFSFLX_ECMWF
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
!     ------------------------------------------------------------------

!     1) Allocate the arrays

! Tiles
IF (LHOOK) CALL DR_HOOK('SUCDDH',0,ZHOOK_HANDLE)
ALLOCATE (YDMODEL%YRML_DIAG%YRCDDH%CADHTLS(YDMODEL%YRML_DIAG%YRMDDH%NDHVTLS+YDMODEL%YRML_DIAG%YRMDDH%NDHFTLS))

! Snow energy budget
ALLOCATE (YDMODEL%YRML_DIAG%YRCDDH%CADHTSS(YDMODEL%YRML_DIAG%YRMDDH%NDHVTSS+YDMODEL%YRML_DIAG%YRMDDH%NDHFTSS))

! Soil energy budget
ALLOCATE (YDMODEL%YRML_DIAG%YRCDDH%CADHTTS(YDMODEL%YRML_DIAG%YRMDDH%NDHVTTS+YDMODEL%YRML_DIAG%YRMDDH%NDHFTTS))

! Sea-ice energy budget
ALLOCATE (YDMODEL%YRML_DIAG%YRCDDH%CADHTIS(YDMODEL%YRML_DIAG%YRMDDH%NDHVTIS+YDMODEL%YRML_DIAG%YRMDDH%NDHFTIS))

! Snow water budget
ALLOCATE (YDMODEL%YRML_DIAG%YRCDDH%CADHSSS(YDMODEL%YRML_DIAG%YRMDDH%NDHVSSS+YDMODEL%YRML_DIAG%YRMDDH%NDHFSSS))

! Interception layer water budget
ALLOCATE (YDMODEL%YRML_DIAG%YRCDDH%CADHIIS(YDMODEL%YRML_DIAG%YRMDDH%NDHVIIS+YDMODEL%YRML_DIAG%YRMDDH%NDHFIIS))

! Soil water budget
ALLOCATE (YDMODEL%YRML_DIAG%YRCDDH%CADHWLS(YDMODEL%YRML_DIAG%YRMDDH%NDHVWLS+YDMODEL%YRML_DIAG%YRMDDH%NDHFWLS))

! Free-style variables and fluxes
ALLOCATE (YDMODEL%YRML_DIAG%YRCDDH%CADHFSS(YDMODEL%YRML_DIAG%YRMDDH%NDHVFS+YDMODEL%YRML_DIAG%YRMDDH%NDHFFS))

ASSOCIATE(YDCDDH=>YDMODEL%YRML_DIAG%YRCDDH,YDCOMPO=>YDMODEL%YRML_CHEM%YRCOMPO,YDMDDH=>YDMODEL%YRML_DIAG%YRMDDH, &
 & YGFL=>YDMODEL%YRML_GCONF%YGFL,YDEPHY=>YDMODEL%YRML_PHY_EC%YREPHY)
ASSOCIATE(LAEROSFC=>YDCOMPO%LAEROSFC, NACTAERO=>YGFL%NACTAERO, NGHG=>YGFL%NGHG, &
 & YAERO=>YGFL%YAERO, YGHG=>YGFL%YGHG, &
 & LEFLAKE=>YDEPHY%LEFLAKE, &
 & NDHFFS=>YDMDDH%NDHFFS, NDHFIIS=>YDMDDH%NDHFIIS, NDHFSSS=>YDMDDH%NDHFSSS, &
 & NDHFTIS=>YDMDDH%NDHFTIS, NDHFTLS=>YDMDDH%NDHFTLS, NDHFTSS=>YDMDDH%NDHFTSS, &
 & NDHFTTS=>YDMDDH%NDHFTTS, NDHFWLS=>YDMDDH%NDHFWLS, NDHVFS=>YDMDDH%NDHVFS, &
 & NDHVIIS=>YDMDDH%NDHVIIS, NDHVSSS=>YDMDDH%NDHVSSS, NDHVTIS=>YDMDDH%NDHVTIS, &
 & NDHVTLS=>YDMDDH%NDHVTLS, NDHVTSS=>YDMDDH%NDHVTSS, NDHVTTS=>YDMDDH%NDHVTTS, &
 & NDHVWLS=>YDMDDH%NDHVWLS)
!     2) Fill the arrays with variable and flux names
!        Note: The order of names has to agree with the order
!              of filling the PDH**S arrays in CALLPAR
!              Generally variables should be before the fluxes.

! Tiles

YDCDDH%CADHTLS(1)='SVGTLF'
YDCDDH%CADHTLS(2)='SVGTLT'
YDCDDH%CADHTLS(3)='SVGTLALB'
YDCDDH%CADHTLS(4)='SFGTLSWDO'
YDCDDH%CADHTLS(5)='SFGTLSWUP'
YDCDDH%CADHTLS(6)='SFGTLLWDO'
YDCDDH%CADHTLS(7)='SFGTLLWUP'
YDCDDH%CADHTLS(8)='SFGTLSH'
YDCDDH%CADHTLS(9)='SFGTLLH'
YDCDDH%CADHTLS(10)='SFGTLG'
YDCDDH%CADHTLS(11)='SFGTLE'
YDCDDH%CADHTLS(12)='SFGTLC'

! Snow energy budget

YDCDDH%CADHTSS(1)='SVLTSC'
YDCDDH%CADHTSS(2)='SVLTST'
YDCDDH%CADHTSS(3)='SVLTSCT'
YDCDDH%CADHTSS(4)='SVLTSDEP'
YDCDDH%CADHTSS(5)='SVLTSRHO'
YDCDDH%CADHTSS(6)='SVLTSALB'
YDCDDH%CADHTSS(7)='SFLTSSWDO'
YDCDDH%CADHTSS(8)='SFLTSSWUP'
YDCDDH%CADHTSS(9)='SFLTSLWDO'
YDCDDH%CADHTSS(10)='SFLTSLWUP'
YDCDDH%CADHTSS(11)='SFLTSSH'
YDCDDH%CADHTSS(12)='SFLTSLH'
YDCDDH%CADHTSS(13)='SFLTSG'
YDCDDH%CADHTSS(14)='SFLTSMLT'
YDCDDH%CADHTSS(15)='SFLTSESC' 

! Soil energy budget

YDCDDH%CADHTTS(1)='SVLTTC'
YDCDDH%CADHTTS(2)='SVLTTT'
YDCDDH%CADHTTS(3)='SVLTTCT'
YDCDDH%CADHTTS(4)='SVLTTDEP'
YDCDDH%CADHTTS(5)='SFLTTSWDO'
YDCDDH%CADHTTS(6)='SFLTTSWUP'
YDCDDH%CADHTTS(7)='SFLTTLWDO'
YDCDDH%CADHTTS(8)='SFLTTLWUP'
YDCDDH%CADHTTS(9)='SFLTTSH'
YDCDDH%CADHTTS(10)='SFLTTLH'
YDCDDH%CADHTTS(11)='SFLTTG'
YDCDDH%CADHTTS(12)='SFLTTMLT'
YDCDDH%CADHTTS(13)='SFLTTGSN'
YDCDDH%CADHTTS(14)='SFLTTGT'
YDCDDH%CADHTTS(15)='SFLTTGESC'

! Sea-ice energy budget

YDCDDH%CADHTIS(1)='SVITIC'
YDCDDH%CADHTIS(2)='SVITIT'
YDCDDH%CADHTIS(3)='SVITICT'
YDCDDH%CADHTIS(4)='SVITIDEP'
YDCDDH%CADHTIS(5)='SFITISWDO'
YDCDDH%CADHTIS(6)='SFITISWUP'
YDCDDH%CADHTIS(7)='SFITILWDO'
YDCDDH%CADHTIS(8)='SFITILWUP'
YDCDDH%CADHTIS(9)='SFITISH'
YDCDDH%CADHTIS(10)='SFITILH'
YDCDDH%CADHTIS(11)='SFITIG'
YDCDDH%CADHTIS(12)='SFITIMLT'
YDCDDH%CADHTIS(13)='SFITIGSN'

! Snow water budget

YDCDDH%CADHSSS(1)='SVLSS'
YDCDDH%CADHSSS(2)='SFLSSLSSF'
YDCDDH%CADHSSS(3)='SFLSSCVSF'
YDCDDH%CADHSSS(4)='SFLSSE'
YDCDDH%CADHSSS(5)='SFLSSMLT'

! Interception layer water budget

YDCDDH%CADHIIS(1)='SVLII'
YDCDDH%CADHIIS(2)='SFLIILSINT'
YDCDDH%CADHIIS(3)='SFLIICVINT'
YDCDDH%CADHIIS(4)='SFLIIE'

! Soil water budget

YDCDDH%CADHWLS(1)='SVLWL'
YDCDDH%CADHWLS(2)='SVLWLI'
YDCDDH%CADHWLS(3)='SFLWLLSTHR'
YDCDDH%CADHWLS(4)='SFLWLCVTHR'
YDCDDH%CADHWLS(5)='SFLWLMLTHR'
YDCDDH%CADHWLS(6)='SFLWLRO'
YDCDDH%CADHWLS(7)='SFLWLE'
YDCDDH%CADHWLS(8)='SFLWLG'
YDCDDH%CADHWLS(9)='SFLWLBGE'
YDCDDH%CADHWLS(10)='SFLWLCOND'

! Free-style variables and fluxes

YDCDDH%CADHFSS(1)='SVGFST2M'
YDCDDH%CADHFSS(2)='SVGFSQ2M'
YDCDDH%CADHFSS(3)='SVGFS10U'
YDCDDH%CADHFSS(4)='SVGFS10V'
YDCDDH%CADHFSS(5)='SVGFSTSK'
YDCDDH%CADHFSS(6)='SVGFSZ0M'
YDCDDH%CADHFSS(7)='SVGFSZ0H'
YDCDDH%CADHFSS(8)='SVGFSAL'
YDCDDH%CADHFSS(9)='SVGFSBLH'
YDCDDH%CADHFSS(10)='SVGFSLF'
YDCDDH%CADHFSS(11)='SVGFSIF'
YDCDDH%CADHFSS(12)='SVGFSFG'
YDCDDH%CADHFSS(13)='SVGFSZ'
YDCDDH%CADHFSS(14)='SVGFSTCC'
YDCDDH%CADHFSS(15)='SVGFSLCC'
YDCDDH%CADHFSS(16)='SVGFSMCC'
YDCDDH%CADHFSS(17)='SVGFSHCC'
YDCDDH%CADHFSS(18)='SVGFSCAPE'
YDCDDH%CADHFSS(19)='SVGFSCBAS'
YDCDDH%CADHFSS(20)='SVGFS0DEG'
YDCDDH%CADHFSS(21)='SVGFSVISI'

YDCDDH%CADHFSS(22)='SVGFSPCIN'
YDCDDH%CADHFSS(23)='SVGFSPCI1'
YDCDDH%CADHFSS(24)='SVGFSPCI2'
YDCDDH%CADHFSS(25)='SVGFSFGCV'
YDCDDH%CADHFSS(26)='SVGFSCEIL'
YDCDDH%CADHFSS(27)='SVGFSCTOP'
YDCDDH%CADHFSS(28)='SVGFSTWB0'
YDCDDH%CADHFSS(29)='SVGFSTWB1'

YDCDDH%CADHFSS(30)='SVGFSM10L'
YDCDDH%CADHFSS(31)='SVGFSCAPMU'
YDCDDH%CADHFSS(32)='SVGFSCAP50'
YDCDDH%CADHFSS(33)='SVGFSCAP100'
YDCDDH%CADHFSS(34)='SVGFSCIN50'
YDCDDH%CADHFSS(35)='SVGFSCIN100'
YDCDDH%CADHFSS(36)='SVGFSDEPL'
YDCDDH%CADHFSS(37)='SVGFSTRPL'

IFSVAR_ECMWF=37

DO JVAR=1,NACTAERO
  YDCDDH%CADHFSS(IFSVAR_ECMWF+JVAR)='SVGFS'//TRIM(YAERO(JVAR)%CNAME)
ENDDO
IFSVAR_ECMWF=IFSVAR_ECMWF+NACTAERO

DO JVAR=1,NGHG
  YDCDDH%CADHFSS(IFSVAR_ECMWF+JVAR)='SVGFS'//TRIM(YGHG(JVAR)%CNAME)
ENDDO
IFSVAR_ECMWF=IFSVAR_ECMWF+NGHG

YDCDDH%CADHFSS(NDHFFS)='SVGFSINCS'
YDCDDH%CADHFSS(NDHVFS+1)='SFGFSSWDO'
YDCDDH%CADHFSS(NDHVFS+2)='SFGFSLWDO'
YDCDDH%CADHFSS(NDHVFS+3)='SFGFSSUND'
YDCDDH%CADHFSS(NDHVFS+4)='SFGFSES'
YDCDDH%CADHFSS(NDHVFS+5)='SFGFSSMLT'
YDCDDH%CADHFSS(NDHVFS+6)='SFGFSLSR'
YDCDDH%CADHFSS(NDHVFS+7)='SFGFSCR'
YDCDDH%CADHFSS(NDHVFS+8)='SFGFSLSF'
YDCDDH%CADHFSS(NDHVFS+9)='SFGFSCF'
YDCDDH%CADHFSS(NDHVFS+10)='SFGFSSSHF'
YDCDDH%CADHFSS(NDHVFS+11)='SFGFSSLHF'
YDCDDH%CADHFSS(NDHVFS+12)='SFGFSSW'
YDCDDH%CADHFSS(NDHVFS+13)='SFGFSLW'
YDCDDH%CADHFSS(NDHVFS+14)='SFGFSE'
YDCDDH%CADHFSS(NDHVFS+15)='SFGFSRO'
YDCDDH%CADHFSS(NDHVFS+16)='SFGFSSWC'
YDCDDH%CADHFSS(NDHVFS+17)='SFGFSLWC'
YDCDDH%CADHFSS(NDHVFS+18)='SFGFSLSPF'
YDCDDH%CADHFSS(NDHVFS+19)='SFGFSPAR'
YDCDDH%CADHFSS(NDHVFS+20)='SFGFSUV'
YDCDDH%CADHFSS(NDHVFS+21)='SFGFSPARC'
YDCDDH%CADHFSS(NDHVFS+22)='SFGFSTISR'
YDCDDH%CADHFSS(NDHVFS+23)='SFGFSVIMD'
YDCDDH%CADHFSS(NDHVFS+24)='SFGFSTSRC'
YDCDDH%CADHFSS(NDHVFS+25)='SFGFSTTRC'
YDCDDH%CADHFSS(NDHVFS+26)='SFGFSFDIR'
YDCDDH%CADHFSS(NDHVFS+27)='SFGFSCDIR'
YDCDDH%CADHFSS(NDHVFS+28)='SFGFSSWDC'
YDCDDH%CADHFSS(NDHVFS+29)='SFGFSLWDC'
YDCDDH%CADHFSS(NDHVFS+30)='SFGFSTSR'
YDCDDH%CADHFSS(NDHVFS+31)='SFGFSTTR'
YDCDDH%CADHFSS(NDHVFS+32)='SFGFLAIL'
YDCDDH%CADHFSS(NDHVFS+33)='SFGFLAIH'
YDCDDH%CADHFSS(NDHVFS+34)='SFGFSOTY'
YDCDDH%CADHFSS(NDHVFS+35)='SFGFSDSRP'

IFSFLX_ECMWF=35

CLTXT(1)='SRC'
CLTXT(2)='DDP'
CLTXT(3)='SDM'
CLTXT(4)='WDL'
CLTXT(5)='WDC'
CLTXT(6)='NGT'
CLTXT(7)='TAU'

! looks like LAEROSFC equals to NACTAERO>0
DO JVAR=1,NACTAERO
  DO JFLX=1,7
    YDCDDH%CADHFSS(NDHVFS+IFSFLX_ECMWF+(JVAR-1)*7+JFLX)='SFGF'//TRIM(YAERO(JVAR)%CNAME)//CLTXT(JFLX)
  ENDDO
ENDDO
IFSFLX_ECMWF=IFSFLX_ECMWF+NACTAERO*7

IF (LEFLAKE) THEN
  YDCDDH%CADHFSS(NDHVFS+IFSFLX_ECMWF+1)='SFGFLMLT'
  IFSFLX_ECMWF=IFSFLX_ECMWF+1
  YDCDDH%CADHFSS(NDHVFS+IFSFLX_ECMWF+1)='SFGFLMLD'
  IFSFLX_ECMWF=IFSFLX_ECMWF+1
  YDCDDH%CADHFSS(NDHVFS+IFSFLX_ECMWF+1)='SFGFLBLT'
  IFSFLX_ECMWF=IFSFLX_ECMWF+1
  YDCDDH%CADHFSS(NDHVFS+IFSFLX_ECMWF+1)='SFGFLTLT'
  IFSFLX_ECMWF=IFSFLX_ECMWF+1
  YDCDDH%CADHFSS(NDHVFS+IFSFLX_ECMWF+1)='SFGFLSHF'
  IFSFLX_ECMWF=IFSFLX_ECMWF+1
  YDCDDH%CADHFSS(NDHVFS+IFSFLX_ECMWF+1)='SFGFLICT'
  IFSFLX_ECMWF=IFSFLX_ECMWF+1
  YDCDDH%CADHFSS(NDHVFS+IFSFLX_ECMWF+1)='SFGFLICD'
  IFSFLX_ECMWF=IFSFLX_ECMWF+1
  YDCDDH%CADHFSS(NDHVFS+IFSFLX_ECMWF+1)='SFGFCLK'
  IFSFLX_ECMWF=IFSFLX_ECMWF+1
  YDCDDH%CADHFSS(NDHVFS+IFSFLX_ECMWF+1)='SFGFDL'
  IFSFLX_ECMWF=IFSFLX_ECMWF+1
ENDIF 

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUCDDH',1,ZHOOK_HANDLE)

END SUBROUTINE SUCDDH     
