! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE WRMLPPG(YDGEOMETRY,YDGFL,YDGFL5,YDSURF,YDMODEL,YDSPEC,PTRAJEC,YDECV,LDOOPS)

!**** *WRMLPPG*  - writes out the model level fields in GRIB

!     Purpose.
!     --------
!     Write out the model level fields in GRIB

!**   Interface.
!     ----------
!        *CALL* *WRMLPPG

!        Implicit arguments :      The state variables of the model
!        --------------------

!     Method.
!     -------
!        See documentation

!     Externals.   MODNSEC - modify GRIB headers
!     ----------

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     Author.
!     -------
!      Mats Hamrud *ECMWF*
!      Original : 93-10-20 (From WRMLPP, exclude ARPEGE files)

!     Modifications.
!     --------------
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      M.Hamrud      10-Jan-2004 CY28R1 Cleaning
!      P. Viterbo  : 24-05-2004   Change surface units
!      T. Wilhelmsson (Sept 2013) Geometry and setup refactoring.
!      F. Vana  28-Nov-2013 : Redesigned trajectory handling
!      M. Janiskova 07-Apr-2016 : writing increments in GRIB using full precision
!      S. Massart    20-Mar-2020 ECV move outside the main loop
!     ------------------------------------------------------------------

USE TYPE_MODEL   , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF, GPOPER, TYPE_SFL_COMM
USE YOMGFL   , ONLY : TGFL
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMMP0   , ONLY : MYSETV
USE YOMLUN   , ONLY : NULOUT, NULERR
USE YOMCT0   , ONLY : LOBSC1, LR2D
USE YOM_GRIB_CODES  , ONLY :&
 & NGRBZ    ,NGRBT    ,NGRBQ    ,NGRBVO   ,&
 & NGRBSD   ,NGRBSDSL ,NGRBLSP  ,NGRBCP   ,NGRBSF   ,NGRBFZRA ,NGRBLNSP ,&
 & NGRBD    ,NGRBSDOR ,NGRBSR   ,NGRBE    ,&
 & NGRBSRC  ,NGRBO3   ,NGRBRO   ,NGRBSSRO ,NGRBSRO  ,&
 & NGRBCSF  ,NGRBLSF  ,NGRBFSR  ,NGRBCLWC ,NGRBCIWC ,&
 & NGRBCC     
USE YOMCST   , ONLY : RG
USE YOMPPC   , ONLY : M2DGGP, M3DSPM, M3DGGM, M2DSPE, M3DSPE, M3DGGE, &
  & NO2DGG, NO3DSPM, NO3DGGM, NO2DSPE, NO3DSPE, NO3DGGE, LRSUP  
USE YOETHF   , ONLY : RHOH2O
USE YOMTRAJ  , ONLY : TRAJ_TYPE
USE YOMJBECV , ONLY : YRECVGRIB, YRECVCONFIG, NDIAECV, SPNORM_ECV
!USE SPECTRAL_FIELDS_MOD, ONLY : SPECTRAL_FIELD, ASSIGNMENT(=)
USE SPECTRAL_FIELDS_MOD
USE GRIB_API, ONLY : GRIB_SET
USE IOSTREAM_MIX, ONLY : YGBH
USE YOMVAR   , ONLY : NSIM4DL, LTWBGV, LTWCGL, LTWINC, LECV
USE ALGORITHM_STATE_MOD  , ONLY : GET_NSIM4D
USE YOETLDIAG, ONLY : LINCRPR, LINCTV, NSIM4DWR
USE YOMCT3   , ONLY : NSTEP
USE YOMOPH0  , ONLY : LINC
USE TYPE_ECV , ONLY : ECV_CONTAINER
USE YOMJBECPHYSECV, ONLY : ECPHYS_WRMLPPG
USE TYPE_FPFIELDS, ONLY : TFPFIELDS

IMPLICIT NONE

TYPE(GEOMETRY)      ,INTENT(IN)    :: YDGEOMETRY
TYPE(TGFL)          ,INTENT(INOUT) :: YDGFL
TYPE(TGFL)          ,INTENT(INOUT) :: YDGFL5
TYPE(TSURF)         ,INTENT(INOUT) :: YDSURF
TYPE(MODEL)         ,INTENT(INOUT) :: YDMODEL
TYPE(SPECTRAL_FIELD),INTENT(INOUT) :: YDSPEC
TYPE(TRAJ_TYPE),    OPTIONAL, INTENT(IN)    :: PTRAJEC
TYPE(ECV_CONTAINER), OPTIONAL, INTENT(IN)    :: YDECV
LOGICAL,         OPTIONAL, INTENT(IN)    :: LDOOPS

INTEGER(KIND=JPIM), EXTERNAL :: ISRCHEQ
#include "abor1.intfb.h"
#include "specrt.intfb.h"
#include "suecfname.intfb.h"
#include "wroutgpgb.intfb.h"
#include "wroutspgb.intfb.h"
#include "gpnorm1.intfb.h"


CHARACTER (LEN = 1)  ::  CLMODE
CHARACTER (LEN = 30)  :: CLFNGG
CHARACTER (LEN = 210) :: CLFNSH
CHARACTER (LEN=16)    :: CLLABEL

REAL(KIND=JPRB),ALLOCATABLE :: ZFPDAT(:,:)
REAL(KIND=JPRB),ALLOCATABLE :: ZREAL(:,:)
REAL(KIND=JPRB) :: ZFIELD(YDGEOMETRY%YRDIM%NPROMA,1)
REAL(KIND=JPRB) :: ZSPT(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2)
INTEGER(KIND=JPIM), ALLOCATABLE :: IGRIBIOSH(:,:), IGRIBIOGG(:,:)

INTEGER(KIND=JPIM) :: IBSETV, IEND, IFIELDST, IFOUND, IGGMAX,&
 & IGRIBCD, IJUMP, ILEVEL, ILOCLV, IPT, ISHMAX,&
 & IST, IZZ, J, JCODE, JF, JGFL, JLEV, JSTGLO, IBL, IFLD, IFF, IECV, JECV

LOGICAL :: LLWRSURF, LLOOPS

TYPE(TFPFIELDS)     :: YDFPFIELDS
TYPE(TYPE_SFL_COMM) :: YLCOM
REAL(KIND=JPRB) :: ZSCALE, ZZSCALE
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "fcttim.func.h"

!     ------------------------------------------------------------------

!*       1.    PREPARATIONS.
!              --------------

IF (LHOOK) CALL DR_HOOK('WRMLPPG',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV,YDGEM=>YDGEOMETRY%YRGEM, YDMP=>YDGEOMETRY%YRMP, &
 & YDOROG=>YDGEOMETRY%YROROG, YDDIMECV=>YDMODEL%YRML_GCONF%YRDIMECV, YDEPHLI=>YDMODEL%YRML_PHY_SLIN%YREPHLI, &
 & YDDIMF=>YDMODEL%YRML_GCONF%YRDIMF,YDEPHY=>YDMODEL%YRML_PHY_EC%YREPHY,YDECLDP=>YDMODEL%YRML_PHY_EC%YRECLDP, &
 & YDRIP=>YDMODEL%YRML_GCONF%YRRIP,YDDYNA=>YDMODEL%YRML_DYN%YRDYNA,&
 & YDPHY=>YDMODEL%YRML_PHY_MF%YRPHY,YGFL=>YDMODEL%YRML_GCONF%YGFL)
ASSOCIATE(NUMFLDS=>YGFL%NUMFLDS, YCOMP=>YGFL%YCOMP, &
 & NPROMA=>YDDIM%NPROMA, NRESOL=>YDDIM%NRESOL, NSPEC2=>YDDIM%NSPEC2, &
 & NS2D=>YDDIMF%NS2D, NS3D=>YDDIMF%NS3D, &
 & NFLEVG=>YDDIMV%NFLEVG, NFLEVL=>YDDIMV%NFLEVL, &
 & RAMIN=>YDECLDP%RAMIN, RLMIN=>YDECLDP%RLMIN, &
 & LEPHYS=>YDEPHY%LEPHYS, &
 & NGPTOT=>YDGEM%NGPTOT, &
 & GFL=>YDGFL%GFL, &
 & NBSETLEV=>YDMP%NBSETLEV, NBSETSP=>YDMP%NBSETSP, &
 & NPTRLL=>YDMP%NPTRLL, LMPHYS=>YDPHY%LMPHYS, &
 & LTLEVOL=>YDEPHLI%LTLEVOL, &
 & TSTEP=>YDRIP%TSTEP, NSTOP=>YDRIP%NSTOP,&
 & LPHYLIN=>YDEPHLI%LPHYLIN, &
 & LECV_2D=>YDDIMECV%LECV_2D, LECV_3D=>YDDIMECV%LECV_3D, &
 & NECVSP_2D=>YDDIMECV%NECVSP_2D, NECVSP_3D=>YDDIMECV%NECVSP_3D, &
 & NECVGP_2D=>YDDIMECV%NECVGP_2D, NECVGP_3D=>YDDIMECV%NECVGP_3D, &
 & MECVGRB_2D=>YRECVGRIB%MECVGRB_2D, MECVGRB_3D=>YRECVGRIB%MECVGRB_3D)



LLOOPS = .FALSE.
IF (PRESENT(LDOOPS)) LLOOPS = LDOOPS

WRITE(NULOUT,*) 'WRITING HISTORY FILE - WRMLPPG'

CLMODE='w'

!      -----------------------------------------------------------

!*       2.    WRITE SPECTRAL DATA ON MODEL LEVELS.
!              ------------------------------------

!*       2.1 Build list of spectral fields to be output

! Initialise igribiosh data structure
!   1 - grib code
!   2 - level (used in file name)
!   3 - bset to send this field
!   4 - local level for sending bset

ISHMAX = 0
IF(NO3DSPM > 0) THEN

  ALLOCATE(IGRIBIOSH(4,NS3D*NFLEVG+NS2D))

!     VORTICITY.

  IGRIBCD = NGRBVO
  IF(ISRCHEQ(NO3DSPM,M3DSPM,1,IGRIBCD) <= NO3DSPM) THEN
    DO JLEV=1,NFLEVG
      ISHMAX = ISHMAX+1
      IGRIBIOSH(1,ISHMAX) = IGRIBCD
      IGRIBIOSH(2,ISHMAX) = JLEV
      IGRIBIOSH(3,ISHMAX) = NBSETLEV(JLEV)
      IGRIBIOSH(4,ISHMAX) = JLEV-NPTRLL(NBSETLEV(JLEV))+1
    ENDDO
  ENDIF

!     DIVERGENCE.

  IGRIBCD = NGRBD
  IF(ISRCHEQ(NO3DSPM,M3DSPM,1,IGRIBCD) <= NO3DSPM) THEN
    DO JLEV=1,NFLEVG
      ISHMAX = ISHMAX+1
      IGRIBIOSH(1,ISHMAX) = IGRIBCD
      IGRIBIOSH(2,ISHMAX) = JLEV
      IGRIBIOSH(3,ISHMAX) = NBSETLEV(JLEV)
      IGRIBIOSH(4,ISHMAX) = JLEV-NPTRLL(NBSETLEV(JLEV))+1
    ENDDO
  ENDIF

!     THERMODYNAMIC VARIABLES.

  IF (YDDYNA%LSPRT .AND. .NOT. LLOOPS) THEN
    ZSPT(:,:) = YDSPEC%T(:,:)
    IF (.NOT.LINCTV) THEN
      CALL SPECRT(YDGEOMETRY,YDGFL,YGFL,1,YDSPEC,LDINCR=LTWINC,YDGFL5=YDGFL5,PTRAJEC=PTRAJEC)
    ELSE
      IF (GET_NSIM4D()==NSIM4DL .OR. GET_NSIM4D()==NSIM4DWR) THEN
        WRITE(NULOUT,*) 'Tv increments written at NSIM4D=', GET_NSIM4D()
      ELSE
        CALL SPECRT(YDGEOMETRY,YDGFL,YGFL,1,YDSPEC,LDINCR=LTWINC,YDGFL5=YDGFL5,PTRAJEC=PTRAJEC)
      ENDIF
    ENDIF
  ENDIF
! SW config do not output T
  IF ( .NOT.LR2D ) THEN
  IGRIBCD = NGRBT
  IF(ISRCHEQ(NO3DSPM,M3DSPM,1,IGRIBCD) <= NO3DSPM) THEN
    DO JLEV=1,NFLEVG
      ISHMAX = ISHMAX+1
      IGRIBIOSH(1,ISHMAX) = IGRIBCD
      IGRIBIOSH(2,ISHMAX) = JLEV
      IGRIBIOSH(3,ISHMAX) = NBSETLEV(JLEV)
      IGRIBIOSH(4,ISHMAX) = JLEV-NPTRLL(NBSETLEV(JLEV))+1
    ENDDO
  ENDIF
  ENDIF

!     GFL

  DO JGFL=1,NUMFLDS
    IF(YCOMP(JGFL)%LSP) THEN
      IGRIBCD=YCOMP(JGFL)%IGRBCODE
      IF(ISRCHEQ(NO3DSPM,M3DSPM,1,IGRIBCD) <= NO3DSPM) THEN
        DO JLEV=1,NFLEVG
          ISHMAX = ISHMAX+1
          IGRIBIOSH(1,ISHMAX) = IGRIBCD
          IGRIBIOSH(2,ISHMAX) = JLEV
          IGRIBIOSH(3,ISHMAX) = NBSETLEV(JLEV)
          IGRIBIOSH(4,ISHMAX) = JLEV-NPTRLL(NBSETLEV(JLEV))+1
        ENDDO
      ENDIF
    ENDIF
  ENDDO

!     SURFACE PRESSURE.

  IGRIBCD = NGRBLNSP
  IF(ISRCHEQ(NO3DSPM,M3DSPM,1,IGRIBCD) <= NO3DSPM) THEN
    ISHMAX = ISHMAX+1
    IGRIBIOSH(1,ISHMAX) = IGRIBCD
    IGRIBIOSH(2,ISHMAX) = 1
    IGRIBIOSH(3,ISHMAX) = NBSETSP
    IGRIBIOSH(4,ISHMAX) = 1
  ENDIF

!     SPECTRAL OROGRAPHY.

  IGRIBCD = NGRBZ
  IF(ISRCHEQ(NO3DSPM,M3DSPM,1,IGRIBCD) <= NO3DSPM) THEN
    ISHMAX = ISHMAX+1
    IGRIBIOSH(1,ISHMAX) = IGRIBCD
    IGRIBIOSH(2,ISHMAX) = 1
    IGRIBIOSH(3,ISHMAX) = NBSETSP
    IGRIBIOSH(4,ISHMAX) = 1
  ENDIF

  IF (ISHMAX > SIZE(IGRIBIOSH,2)) THEN
     WRITE(NULERR,*) 'ISHMAX            = ',ISHMAX
     WRITE(NULERR,*) 'SIZE(IGRIBIOSH,2) = ',SIZE(IGRIBIOSH,2)
     CALL ABOR1('WRMLPPG: ISHMAX > THAN SIZE OF IGRIBIOSH')
  ENDIF

  IFF=0
  DO JF=1,ISHMAX
    IBSETV  = IGRIBIOSH(3,JF)
    IF( IBSETV == MYSETV )THEN
      IFF=IFF+1
    ENDIF
  ENDDO

  ALLOCATE(ZFPDAT(NSPEC2,IFF))

  IF (LINCRPR .AND. LPHYLIN .AND. (GET_NSIM4D()==NSIM4DL .OR. GET_NSIM4D()==NSIM4DWR)) THEN
    WRITE(NULOUT,*) 'calling grib_set for TL/AD diag, YGBH%NGRIB_HANDLE_SH_ML =',&
     & YGBH%NGRIB_HANDLE_SH_ML
    CALL GRIB_SET(YGBH%NGRIB_HANDLE_SH_ML, 'packingType' , 'spectral_ieee')
    CALL GRIB_SET(YGBH%NGRIB_HANDLE_SH_ML, 'unpackedSubsetPrecision',2) 
    CALL GRIB_SET(YGBH%NGRIB_HANDLE_SH_ML, 'bitsPerValue',64) 
  ENDIF

  IFF=0
  DO JF=1,ISHMAX
    IGRIBCD = IGRIBIOSH(1,JF)
    ILEVEL = IGRIBIOSH(2,JF)
    IBSETV  = IGRIBIOSH(3,JF)
    ILOCLV = IGRIBIOSH(4,JF)
    IF( IBSETV == MYSETV )THEN
      IFF=IFF+1
      IF    ( IGRIBCD == NGRBZ )THEN
        DO J=1,NSPEC2
          ZFPDAT(J,IFF) = YDSPEC%OROG(J)
        ENDDO
      ELSEIF( IGRIBCD == NGRBT )THEN
        DO J=1,NSPEC2
          ZFPDAT(J,IFF) = YDSPEC%T(ILOCLV,J)
        ENDDO
      ELSEIF( IGRIBCD == NGRBQ )THEN
        DO J=1,NSPEC2
          ZFPDAT(J,IFF) = YDSPEC%Q(ILOCLV,J)
        ENDDO
      ELSEIF( IGRIBCD == NGRBO3 )THEN
        DO J=1,NSPEC2
          ZFPDAT(J,IFF) = YDSPEC%O3(ILOCLV,J)
        ENDDO
      ELSEIF( IGRIBCD == NGRBVO )THEN
        DO J=1,NSPEC2
          ZFPDAT(J,IFF) = YDSPEC%VOR(ILOCLV,J)
        ENDDO
      ELSEIF( IGRIBCD == NGRBLNSP )THEN
        DO J=1,NSPEC2
          ZFPDAT(J,IFF) = YDSPEC%SP(J)
        ENDDO
      ELSEIF( IGRIBCD == NGRBD )THEN
        DO J=1,NSPEC2
          ZFPDAT(J,IFF) = YDSPEC%DIV(ILOCLV,J)
        ENDDO
      ELSE
        WRITE(NULERR,'(A,I6)')' WRMLPPG: SH INVALID IGRIBCD ',IGRIBCD
        CALL ABOR1(' WRMLPPG: SH INVALID IGRIBCD ')
      ENDIF
    ENDIF
  ENDDO
  CALL SUECFNAME(LINC,'m',NSTEP,TSTEP,NSTOP,CLFNGG,CLFNSH)
  CALL WROUTSPGB(YDMODEL,YDGEOMETRY,YDDIM,ZFPDAT,ISHMAX,IGRIBIOSH,'m',NRESOL,CLFNSH,YDFPFIELDS,PTSTEP=TSTEP)
  DEALLOCATE(ZFPDAT)
  IF (YDDYNA%LSPRT .AND. .NOT. LLOOPS) THEN
    YDSPEC%T(:,:) = ZSPT(:,:)
  ENDIF
  DEALLOCATE(IGRIBIOSH)
ENDIF


!      -----------------------------------------------------------

!*       3.    WRITE ALPHA VARIABLES ON MODEL LEVELS. (only spectral currently)
!              ------------------------------------

!*       3.1 Build list of spectral fields to be output


IF(NSTEP==0 .AND. LECV .AND. PRESENT(YDECV)) THEN

  ALLOCATE(IGRIBIOSH(4,NFLEVG))
  ALLOCATE(IGRIBIOGG(2,NFLEVG))
  IECV = 0
  CALL SUECFNAME(LINC,'m',NSTEP,TSTEP,NSTOP,CLFNGG,CLFNSH)
  WRITE(CLFNSH(1:1),'(A1)') 'A'
  WRITE(CLFNGG(1:1),'(A1)') 'A'

  IF ((LECV_2D .AND. NO2DSPE > 0).OR.(LECV_3D .AND. NO3DSPE > 0)) THEN 
    IF (NDIAECV > 0) THEN 
      WRITE(CLLABEL,'(A7)')'ECV 4I '
      CALL SPNORM_ECV(YDGEOMETRY,YDDIMECV,YDECV,CLLABEL)  
    ENDIF 
  ENDIF

  IF (LECV_2D .AND. NO2DSPE > 0) THEN 
    DO JCODE=1,NO2DSPE
      IGRIBCD = M2DSPE(JCODE)
      JECV = 1
      DO WHILE (MECVGRB_2D(JECV) /=  IGRIBCD) 
        JECV = JECV + 1
        IF (JECV > NECVSP_2D) THEN
          WRITE(NULERR,'('' WRMLPPG - ISSUE WITH 2D ECV GRIB CODE '')')
          WRITE(NULERR,'('' GRIB CODE = '',I3.3)') IGRIBCD
          CALL ABOR1('WRMLPPG: ABOR1 CALLED')
        ENDIF
      ENDDO
      !
      IFF=0
      IF( NBSETSP == MYSETV )THEN
        IFF=IFF+1
      ENDIF
      !
      ALLOCATE(ZFPDAT(NSPEC2,1))
      IF (TRIM(YRECVCONFIG%YRCONFIG(JECV)%CSETDESC) ==  'EC_PHYS') THEN
        CALL ECPHYS_WRMLPPG(YDGEOMETRY,YDECV%RSPECV2D(JECV,:),JECV,IGRIBCD,ZFPDAT,IGRIBIOSH)
      ELSE
        IGRIBIOSH(:,:) = 0_JPIM
        IGRIBIOSH(1,1) = IGRIBCD
        IGRIBIOSH(2,1) = 1
        IGRIBIOSH(3,1) = NBSETSP
        IGRIBIOSH(4,1) = 1
        IFF=0
        IF( NBSETSP == MYSETV )THEN
          IFF=IFF+1
          DO J=1,NSPEC2
            ZFPDAT(J,IFF) = YDECV%RSPECV2D(JECV,J)
          ENDDO
        ENDIF
      ENDIF
      IECV = IECV + 1 
      WRITE(CLFNSH(19:23),'(A1,I3.3)') '+', IECV
      CALL WROUTSPGB(YDMODEL,YDGEOMETRY,YDDIM,ZFPDAT(:,1:IFF),1,IGRIBIOSH,'m',NRESOL,CLFNSH,YDFPFIELDS,PTSTEP=TSTEP)
      DEALLOCATE(ZFPDAT)
      !
    ENDDO
  ENDIF

  IF (LECV_3D .AND. NO3DSPE > 0) THEN 
    DO JCODE=1,NO3DSPE
      IGRIBCD = M3DSPE(JCODE)
      JECV = 1
      DO WHILE (MECVGRB_3D(JECV) /=  IGRIBCD) 
        JECV = JECV + 1
        IF (JECV > NECVSP_3D) THEN
          WRITE(NULERR,'('' WRMLPPG - ISSUE WITH 3D SP ECV GRIB CODE '')')
          WRITE(NULERR,'('' GRIB CODE = '',I3.3)') IGRIBCD
          CALL ABOR1('WRMLPPG: ABOR1 CALLED')
        ENDIF
      ENDDO
      !
      IFF=0
      DO JLEV=1,NFLEVG
        IF( NBSETLEV(JLEV) == MYSETV )THEN
          IFF=IFF+1
        ENDIF
      ENDDO
      !
      ALLOCATE(ZFPDAT(NSPEC2,IFF))
      IF (TRIM(YRECVCONFIG%YRCONFIG(JECV)%CSETDESC) ==  'EC_PHYS') THEN
        CALL ECPHYS_WRMLPPG(YDGEOMETRY,YDECV%RSPECV3D(JECV,:,:),JECV,IGRIBCD,ZFPDAT,IGRIBIOSH)
      ELSE
        IFF=0
        IGRIBIOSH(:,:) = 0_JPIM
        DO JLEV=1,NFLEVG
          IGRIBIOSH(1,JLEV) = IGRIBCD 
          IGRIBIOSH(2,JLEV) = JLEV
          IGRIBIOSH(3,JLEV) = NBSETLEV(JLEV)
          IGRIBIOSH(4,JLEV) = JLEV-NPTRLL(NBSETLEV(JLEV))+1
          IF( NBSETLEV(JLEV) == MYSETV )THEN
            IFF=IFF+1
            DO J=1,NSPEC2
              ZFPDAT(J,IFF) = YDECV%RSPECV3D(JECV,IGRIBIOSH(4,JLEV),J)
            ENDDO
          ENDIF
        ENDDO
      ENDIF
      IECV = IECV + 1 
      WRITE(CLFNSH(19:23),'(A1,I3.3)') '+', IECV
      CALL WROUTSPGB(YDMODEL,YDGEOMETRY,YDDIM,ZFPDAT,NFLEVG,IGRIBIOSH,'m',NRESOL,CLFNSH,YDFPFIELDS,PTSTEP=TSTEP)
      DEALLOCATE(ZFPDAT)
    ENDDO
  ENDIF 

  IF (LECV_3D .AND. NO3DGGE > 0) THEN 

    DO JCODE=1,NO3DGGE
      IGRIBCD = M3DGGE(JCODE)
      JECV = 1
      DO WHILE (MECVGRB_3D(NECVSP_3D+JECV) /=  IGRIBCD) 
        JECV = JECV + 1
        IF (JECV > NECVGP_3D) THEN
          WRITE(NULERR,'('' WRMLPPG - ISSUE WITH 3D GG ECV GRIB CODE '')')
          WRITE(NULERR,'('' GRIB CODE = '',I3.3)') IGRIBCD
          CALL ABOR1('WRMLPPG: ABOR1 CALLED')
        ENDIF
      ENDDO
      !
      ALLOCATE(ZREAL(NGPTOT,NFLEVG))
      IF (TRIM(YRECVCONFIG%YRCONFIG(JECV)%CSETDESC) ==  'EC_PHYS') THEN
        CALL ECPHYS_WRMLPPG(YDGEOMETRY,YDECV%RGPECV3D(JECV,:,:,:),JECV,IGRIBCD,ZREAL,IGRIBIOGG)
      ELSE
        IGRIBIOGG(:,:) = 0_JPIM
        DO JLEV=1,NFLEVG
          IGRIBIOGG(1,JLEV) = IGRIBCD
          IGRIBIOGG(2,JLEV) = JLEV
          DO JSTGLO=1,NGPTOT,NPROMA
            IST=1
            IEND=MIN(NPROMA,NGPTOT-JSTGLO+1)
            IBL=(JSTGLO-1)/NPROMA+1
            DO J=IST,IEND
                ZREAL(JSTGLO-1+J,JLEV)=YDECV%RGPECV3D(JECV,J,JLEV,IBL)
            ENDDO
          ENDDO
        ENDDO
      ENDIF
      !
      IECV = IECV + 1 
      WRITE(CLFNGG(19:23),'(A1,I3.3)') '+', IECV
      CALL WROUTGPGB(YDMODEL,YDGEOMETRY,ZREAL,NGPTOT,NFLEVG,IGRIBIOGG,'m',CLMODE,NRESOL,CLFNGG,YDFPFIELDS,TSTEP)
      DEALLOCATE(ZREAL)
      IF (NDIAECV > 0) THEN 
        WRITE(CLLABEL,'(A10,I6.6)')'ECV 4I 3D ', IGRIBCD 
        CALL GPNORM1(YDGEOMETRY,YDECV%RGPECV3D(JECV,:,:,:),NFLEVG,.TRUE.,CDLABEL=CLLABEL)  
      ENDIF 
      

    ENDDO ! JCODE=1,NO3DGGE
  ENDIF ! LECV_3D .AND. NO3DGGE

  DEALLOCATE(IGRIBIOSH)
  DEALLOCATE(IGRIBIOGG)

ENDIF




!      -----------------------------------------------------------

IF (LINCRPR .AND. LPHYLIN .AND. (GET_NSIM4D()==NSIM4DL .OR. GET_NSIM4D()==NSIM4DWR)) THEN
  WRITE(NULOUT,*) 'calling grib_set for TL/AD diag, YGBH%NGRIB_HANDLE_GG_ML =',&
   & YGBH%NGRIB_HANDLE_GG_ML
  CALL GRIB_SET(YGBH%NGRIB_HANDLE_GG_ML, 'packingType' , 'grid_ieee')
  CALL GRIB_SET(YGBH%NGRIB_HANDLE_GG_ML, 'precision',2) 
ENDIF

LLWRSURF = (.NOT.LTWBGV) .AND. (.NOT.LTWCGL)&
         & .AND.(LRSUP.AND.(LMPHYS.OR.LEPHYS).OR.LOBSC1)


IF (LLOOPS) LLWRSURF = .FALSE.

!*       4.0   WRITE OUT SURFACE GRID POINT FIELDS
!              -----------------------------------

IF ( LLWRSURF ) THEN

!*       4.1   COPY FROM NPROMA FORMAT TO FIELD FORMAT


  ALLOCATE(ZREAL(NGPTOT,NO2DGG))
  ALLOCATE(IGRIBIOGG(2,NO2DGG+1))

  IGGMAX=0
  DO JCODE=1,NO2DGG
    IGRIBCD = M2DGGP(JCODE)
    YLCOM%IGRBCODE = IGRIBCD
    CALL GPOPER(YDDIM,YDMODEL%YRML_DYN%YRDYN,'GETGRIBPOS',YDSURF,KBL=1,YDCOM=YLCOM)
    IF(YLCOM%L_OK) THEN
      IGGMAX = IGGMAX+1
      IGRIBIOGG(1,IGGMAX) = IGRIBCD
      DO JSTGLO=1,NGPTOT,NPROMA
        IST=1
        IEND=MIN(NPROMA,NGPTOT-JSTGLO+1)
        IBL=(JSTGLO-1)/NPROMA+1
        CALL GPOPER(YDDIM,YDMODEL%YRML_DYN%YRDYN,'GETFIELD',YDSURF,KBL=IBL,YDCOM=YLCOM,PFIELD=ZFIELD)
        DO J=JSTGLO,JSTGLO+IEND-IST
          ZREAL(J,IGGMAX)=ZFIELD(J-JSTGLO+1,1)
        ENDDO
      ENDDO
    ELSE  
      IF(IGRIBCD /= NGRBZ) THEN
        WRITE(NULOUT,'(A,I4,A)') ' WRMLPP - GRIB CODE ',IGRIBCD,' NOT FOUND '
      ENDIF
    ENDIF
  ENDDO

  IGRIBCD = NGRBZ
  IFOUND  = ISRCHEQ(NO2DGG,M2DGGP,1,IGRIBCD)
  IF(IFOUND <= NO2DGG) THEN
    IGGMAX = IGGMAX+1
    IGRIBIOGG(1,IGGMAX) = IGRIBCD
    DO JSTGLO=1,NGPTOT,NPROMA
      IST=1
      IEND=MIN(NPROMA,NGPTOT-JSTGLO+1)
      IBL=(JSTGLO-1)/NPROMA+1
      DO J=JSTGLO,JSTGLO+IEND-IST
        ZREAL(J,IGGMAX) = YDOROG(IBL)%OROG(J-JSTGLO+1)
      ENDDO
    ENDDO
  ENDIF
  IGRIBIOGG(2,:) = 0

  DO JF=1,IGGMAX
    IGRIBCD = IGRIBIOGG(1,JF)

!*       4.2   SCALINGS FOR ECMWF MARS ARCHIVING

    IF    (IGRIBCD == NGRBSD  ) THEN 
      ZSCALE = 1.0_JPRB        ! sd multi-layer in kg m-2
    ELSEIF(IGRIBCD == NGRBSDSL) THEN
      ZSCALE = 1.0_JPRB/RHOH2O ! sd tot in m water eq.
    ELSEIF(IGRIBCD == NGRBLSP ) THEN
      ZSCALE = 1.0_JPRB/RHOH2O
    ELSEIF(IGRIBCD == NGRBCP  ) THEN
      ZSCALE = 1.0_JPRB/RHOH2O
    ELSEIF(IGRIBCD == NGRBSF  ) THEN
      ZSCALE = 1.0_JPRB/RHOH2O
    ELSEIF(IGRIBCD == NGRBFZRA) THEN
      ZSCALE = 1.0_JPRB/RHOH2O
    ELSEIF(IGRIBCD == NGRBSR  ) THEN
      ZSCALE = 1.0_JPRB/RG
    ELSEIF(IGRIBCD == NGRBE   ) THEN
      ZSCALE = 1.0_JPRB/RHOH2O
    ELSEIF(IGRIBCD == NGRBSRC ) THEN
      ZSCALE = 1.0_JPRB/RHOH2O
    ELSEIF(IGRIBCD == NGRBRO  ) THEN
      ZSCALE = 1.0_JPRB/RHOH2O
    ELSEIF(IGRIBCD == NGRBSSRO  ) THEN
      ZSCALE = 1.0_JPRB/RHOH2O
    ELSEIF(IGRIBCD == NGRBSRO  ) THEN
      ZSCALE = 1.0_JPRB/RHOH2O
    ELSEIF(IGRIBCD == NGRBCSF ) THEN
      ZSCALE = 1.0_JPRB/RHOH2O
    ELSEIF(IGRIBCD == NGRBLSF ) THEN
      ZSCALE = 1.0_JPRB/RHOH2O
    ELSEIF(IGRIBCD == NGRBFSR ) THEN
      ZSCALE = 1.0_JPRB/RG
    ELSEIF(IGRIBCD == NGRBSDOR) THEN
      ZSCALE = 1.0_JPRB/RG
    ELSE
      ZSCALE = 1.0_JPRB
    ENDIF

    IF (ZSCALE /= 1.0_JPRB) THEN
      DO J=1,NGPTOT
        ZREAL(J,JF) = ZREAL(J,JF)*ZSCALE
      ENDDO
    ENDIF
  ENDDO

  CALL SUECFNAME(LINC,'s',NSTEP,TSTEP,NSTOP,CLFNGG,CLFNSH)
  CALL WROUTGPGB(YDMODEL,YDGEOMETRY,ZREAL,NGPTOT,IGGMAX,IGRIBIOGG,'s',CLMODE,NRESOL,CLFNGG,YDFPFIELDS,TSTEP)
  DEALLOCATE(ZREAL)
  DEALLOCATE(IGRIBIOGG)

ENDIF

!      -----------------------------------------------------------

!*       5.0   WRITE OUT UPPER AIR GRID POINT FIELDS
!              --------------------------------------

!*       5.1   COPY FROM NPROMA FORMAT TO FIELD FORMAT

IGGMAX = 0
ALLOCATE(IGRIBIOGG(2,NO3DGGM*YDGEOMETRY%YRDIMV%NFLEVG))
DO JCODE=1,NO3DGGM
  IGRIBCD = M3DGGM(JCODE)
  IPT=0
  DO JGFL=1,NUMFLDS
    IF(YCOMP(JGFL)%LGP .AND. YCOMP(JGFL)%IGRBCODE ==IGRIBCD) THEN
      IPT=JGFL
    ENDIF
  ENDDO
  IF(IPT == 0) THEN
    WRITE(NULERR,'('' WRMLPPG - GRIB CODE UNKNOWN '')')
    WRITE(NULERR,'('' GRIB CODE = '',I3.3)') IGRIBCD
    CALL ABOR1('WRMLPPG: ABOR1 CALLED')
  ENDIF
  DO JLEV=1,NFLEVG
    IGGMAX = IGGMAX+1
    IPT    = IPT+1
    IGRIBIOGG(1,IGGMAX) = IGRIBCD
    IGRIBIOGG(2,IGGMAX) = JLEV
  ENDDO
ENDDO

IFIELDST = IGGMAX
IJUMP    = MIN(NGPTOT,NPROMA)
ALLOCATE(ZREAL(NGPTOT,IGGMAX))
IFLD=0
DO JF=1,IFIELDST/NFLEVG
  DO JLEV=1,NFLEVG
    IFLD=IFLD+1
    IGRIBCD = IGRIBIOGG(1,IFLD)
    ILEVEL  = IGRIBIOGG(2,IFLD)
    IPT=0
    DO JGFL=1,NUMFLDS
      IF(YCOMP(JGFL)%LGP .AND. YCOMP(JGFL)%IGRBCODE == IGRIBCD) THEN
        IPT=JGFL
      ENDIF
    ENDDO
    IF(IPT /= 0) THEN
      DO JSTGLO=1,NGPTOT,NPROMA
        IST=1
        IEND=MIN(NPROMA,NGPTOT-JSTGLO+1)
        IBL=(JSTGLO-1)/NPROMA+1
        DO J=IST,IEND
          ZREAL(JSTGLO-1+J,IFLD)=GFL(J,JLEV,IPT,IBL)
        ENDDO
      ENDDO
    ENDIF
    
    IF(IGRIBCD == NGRBCC.OR.&
       & IGRIBCD == NGRBCLWC.OR.&
       & IGRIBCD == NGRBCIWC) THEN  
      IF(IGRIBCD == NGRBCLWC) THEN
        ZSCALE=RLMIN
      ELSEIF(IGRIBCD == NGRBCIWC) THEN
        ZSCALE=RLMIN
      ELSEIF(IGRIBCD == NGRBCC  ) THEN
        ZSCALE=RAMIN
      ENDIF
      !                 prevent small values falling outside physical range
      ZZSCALE=1.0_JPRB/ZSCALE
      DO J=1,NGPTOT
        IZZ=ZREAL(J,IFLD)*ZZSCALE
        ZREAL(J,IFLD)=IZZ*ZSCALE
      ENDDO
    ENDIF
  ENDDO
ENDDO

!*       5.3   WRITE FIELDS

IF(IGGMAX > 0) THEN
  CALL SUECFNAME(LINC,'m',NSTEP,TSTEP,NSTOP,CLFNGG,CLFNSH)
  CALL WROUTGPGB(YDMODEL,YDGEOMETRY,ZREAL,NGPTOT,IGGMAX,IGRIBIOGG,'m',CLMODE,NRESOL,CLFNGG,YDFPFIELDS,TSTEP)
ENDIF
DEALLOCATE(ZREAL)
DEALLOCATE(IGRIBIOGG)

!     ---------------------------------------------------------------

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('WRMLPPG',1,ZHOOK_HANDLE)
END SUBROUTINE WRMLPPG
