MODULE ECE_CMIP

! =============================================================================
! *** ECE_CMIP contains everything related to CMIP6 or CMIP7:
!   - paths
!   - filenames
!   - switches
!   - namelist NAMECECMIP
! =============================================================================

    USE PARKIND1,ONLY : JPIM, JPRB

    IMPLICIT NONE

    PRIVATE

    PUBLIC SETUP_ECE_CMIP

    PUBLIC LCMIP6
    PUBLIC CMIP6DATADIR
    PUBLIC LCMIP7
    PUBLIC CMIP7DATADIR
    PUBLIC SCENARIONAME
    PUBLIC NCMIPFIXYR
    PUBLIC NCMIPFIXYR_CH4
    PUBLIC LANxCO2
    PUBLIC RNxCO2
    PUBLIC L1PCTCO2
    PUBLIC LGHGMONTHLY

    LOGICAL :: LCMIP6 = .FALSE.
    LOGICAL :: LCMIP7 = .FALSE.
    CHARACTER(LEN=255) :: CMIP6DATADIR = 'CMIP6DATADIR NOT SET'
    CHARACTER(LEN=255) :: CMIP7DATADIR = 'CMIP7DATADIR NOT SET'
    CHARACTER(LEN=24)  :: SCENARIONAME = 'SCENARIONAME NOT SET'
    INTEGER(KIND=JPIM) :: NCMIPFIXYR = -1
    INTEGER(KIND=JPIM) :: NCMIPFIXYR_CH4 = -1
    LOGICAL :: LANxCO2 = .FALSE.
    LOGICAL :: L1PCTCO2 = .FALSE.
    LOGICAL :: LGHGMONTHLY = .FALSE.
    REAL(KIND=JPRB)    :: RNxCO2 = 4.0_JPRB

    NAMELIST /NAMECECMIP/ LCMIP6
    NAMELIST /NAMECECMIP/ CMIP6DATADIR
    NAMELIST /NAMECECMIP/ LCMIP7
    NAMELIST /NAMECECMIP/ CMIP7DATADIR
    NAMELIST /NAMECECMIP/ SCENARIONAME
    NAMELIST /NAMECECMIP/ NCMIPFIXYR
    NAMELIST /NAMECECMIP/ NCMIPFIXYR_CH4
    NAMELIST /NAMECECMIP/ LANxCO2
    NAMELIST /NAMECECMIP/ RNxCO2
    NAMELIST /NAMECECMIP/ L1PCTCO2
    NAMELIST /NAMECECMIP/ LGHGMONTHLY

CONTAINS

SUBROUTINE SETUP_ECE_CMIP

    USE YOMLUN, ONLY: NULOUT, NULNAM

    ! Read EC-Earth CMIP namelist
    CALL POSNAM(NULNAM,'NAMECECMIP')
    READ(NULNAM,NAMECECMIP)

    ! Sanity checks
    IF (LCMIP6.AND.LCMIP7) &
         &   CALL ABOR1('ECE_CMIP: LCMIP6 and LCMIP7 cannot both be true.')

    ! set NCMIPFIXYR_CH4 if not already set in namelist
    IF (NCMIPFIXYR_CH4<=0) NCMIPFIXYR_CH4=NCMIPFIXYR

    IF (LANxCO2.AND.L1PCTCO2) &
        &   CALL ABOR1('ECE_CMIP: LANxCO2 and L1PCTCO2 cannot both be true.')

    IF ((LANxCO2.OR.L1PCTCO2).AND.NCMIPFIXYR<=0) &
        &   CALL ABOR1('ECE_CMIP: set NCMIPFIXYR if LANxCO2 or L1PCTCO2')

    IF (RNxCO2<=0) &
        &   CALL ABOR1('ECE_CMIP: RNxCO2 must be positive.')

    ! print actual setting in logfile
    WRITE(NULOUT, nml=NAMECECMIP)
END SUBROUTINE SETUP_ECE_CMIP

END MODULE ECE_CMIP
