! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE POSTPHY(YDGEOMETRY,YDSURF,YDMODEL,KPROMA ,KST    ,KEND   ,KFLEVG ,&
 & LDFSTEP,LDMLPP, LDRS6, LDACCRS,&
 & KLEVS  ,KLEVXP ,KFLDXP ,KSATSIM,KSTGLO,KLEVSN,&
 & KFLDXP2,KLEVO  ,PDTPHY,&!KPP, KLEVO
 & PUT9,PVT9,PTT9,PGFL,PAERODDF,PTENQ,&
 & PDELP9 ,PDIFTQ ,PDIFCQ ,PDIFTS ,PDIFCS,&
 & PFRSO  ,PFRSOD ,PFRSODC,PFRTH  ,PFRTHD ,PFRTHDC,PUVDF  ,PPARF  ,&
 & PCAPE  ,PPARCF ,PTINCF ,PFDIR  ,PDSRP  ,PCDIR,&
 & PCBASE ,PPDEPL, P0DEGL ,PM10DEGL,PVISIH,PCIN   ,PCONVIND,&
 & PLIGH_TOT ,PLIGH_CTG,&
 & PCBASEA,PCTOPC ,PTROPOTP,PZTWETB,&
 & PFHPCL ,PFHPCN ,PFHPSL ,PFHPSN ,PFPLCL,&
 & PFPLCN ,PFPLSL ,PFPLSN ,PSTRCU ,PSTRCV ,PSTRDU ,PSTRDV,&
 & PFCCQN ,PFCCQL ,PFCSQN ,PFCSQL ,PFCQLNG,&
 & PFCQNNG,PFSQRF,   PFSQSF ,  PFCQRNG,  PFCQSNG,PFSQLTUR, PFSQITUR ,&
 & PSTRTU ,PSTRTV ,&
 & POROG  ,PENES  ,PFEVN,&
 & PGESLO ,PGECLO ,PVFLSM ,PVFCI,&
 & PINEE  ,PIGPP  ,PIREC,&
 & PVDZ0F,&
 & PTSAE1 ,PTLE1  ,PWSAE1,&
 & PISAE1,&
 & PWLE1  ,PSNSE1,PWSNE1,&
 & PASNE1 ,PRSNE1 ,PTSNE1,&
 & PTLICEE1, PTLMNWE1,&!LAKE
 & PTLWMLE1, PTLBOTE1,&!LAKE
 & PTLSFE1 ,&!LAKE
 & PHLICEE1, PHLMLE1,&!LAKE
 & PEXTRE1,PXTR2E1,PEVAPMU,&
 & PUOE1  ,PVOE1  ,PTOE1  ,PSOE1,&!KPP
 & PFSNNU1,PWSNU1,&
 & PASNU1 ,PRSNU1 ,PTSNU1,&
 & PTSLNU1,PWRENU1,PTRENU1,PQLINU1,&
 & PTILINU1,&
 & PTLICNU1, PTLMNNU1,&!LAKE
 & PTLMLNU1, PTLBTNU1,&!LAKE
 & PTLSFNU1,&!LAKE
 & PHLICNU1, PHLMNU1,&!LAKE
 & PEXTRP1,PXTRP21,&
 & PUO1  ,PVO1  ,PTO1  ,PSO1,&!KPP or ocean TKE
 & PRE9   ,PRE9F  ,&
 & PWRENU0,PFCLL  ,PFCLN,&
 & PTRENU0,PQLINU0,&
 & PTCLS,&
 & PQCLS  ,PISUND ,PVDBLH   ,PVDSUND,&
 & PITTRC ,PITSRC ,PISTRC   ,PISSRC ,PI10FG, PI10FGCV, PILSPF, PPRECTYPE, PFZRA,&
 & PVTTRC ,PVTSRC ,PVSTRC   ,PVSSRC ,PVES, PVSMLT, PV10FG, PV10FG6, PVI10FG,&
 & PVLSPF ,PVVIMD ,&
 & PUCLS  ,PVCLS  ,PVDLZ0H,PVDALB,&
 & PVLCC  ,PVMCC  ,PVHCC  ,PVTCC,&
 & PVDIS  ,PVDISG ,PUSTRG,&
 & PVSTRG ,PRUISS,&
 & PVDLSP ,PVDCP  ,PVDSF  ,PVDFZRA,PVDBLD ,PVDSSHF,PVDSLHF,PVDSP,PVDMSL,&
 & PVDSSR ,PVDSTR ,PVDSSRD,PVDSTRD,PVDSSRDC,PVDSTRDC,&
 & PVDTSR ,PVDTTR ,PVDUVDF,PVDPARF,PVDCAPE ,PVDCAPES,PVDMXCAP6,PVDMXCAPS6,&
 & PVDPARCF, PVDTINCF, PVDFDIR, PVDDSRP, PVDCDIR,&
 & PVCBASE,PV0DEGL,PVM10DEGL,PVVISIH,PVCIN  ,PVKINDEX,PVTTINDEX,&
 & PVPDEPL,PVMUCAPE,PVMLCAPE50,PVMLCAPE100,PVMLCIN50,PVMLCIN100,&
 & PVCBASEA,PVCTOPC,PVTROPOTP,PVZTWETB0, PVZTWETB1,&
 & PVDIEWSS,PVDINSSS,&
 & PVDEWSS,PVDNSSS,PVDE   ,PVDPEV ,PVDLGWS,PVDISSHF,PVDIE,PVDVIWVE,PVDVIWVN,&
 & PVDTCW ,PVDTCWV,PVDTCLW,PVDTCIW,PVDTCRW,PVDTCSW,PVDTCSLW,&
 & PVDMGWS,PVDGWD ,PVDMX2T,PVDMN2T,PVDMX2T6,PVDMN2T6,&
 & PVDRO,PVDSSRO,PVDSRO,PVDCSF,PVDLSSF,&
 & PVDMXTPR,PVDMNTPR,PVDMXTPR6,PVDMNTPR6,&
 & PVDTPR ,PVDLSRR,PVDCRR ,PVDLSSFR,PVDCSFR,PVDPTYPE,PVILSPF,&
 & PVDTCO3,PVDNEE ,PVDGPP ,PVDREC,&
 & PVDLITOTI,PVDLITOTA6,PVDLICGI,PVDLICGA6,&
 & PSMCLBT,PSMCSBT,&
 & PVDPTYPEOCC6,PVDTCAERO,PVDAEROF,PVDTCGHG,PVDTCCHEM,PSD_VF,&
 & PGNORDL,PGNORDM,PGEMU  ,PGSQM2 ,PGELAM ,PGELAT ,PGAW   ,PFCQNG ,&
 & PFONTE ,PRUISP ,PDHTLS ,PDHTSS ,PDHTTS ,PDHTIS ,PDHSSS ,PDHIIS,&
 & PDHWLS ,PDHFSS)


!**** *POSTPHY - Post physics computations

!     Purpose.
!     --------
!           To perform the computations related to the physics
!       done after the call to APLPAR including the computation
!       of tendencies, the accumalation of diabatic tendencies for
!       diagnostics. The main reason for creating the routine
!       is memory savings.  

!**   Interface.
!     ----------
!        *CALL* *POSTPHY*

!        Explicit arguments : see in EC_PHYS
!        --------------------

!        Implicit arguments :
!        --------------------

!     Method.
!     -------
!        See documentation

!     Externals.
!     ----------

!     Reference.
!     ----------
!        ARPEGE documentation vol 2 ch 1 and vol 3 ch 6

!     Author.
!     -------
!      Mats Hamrud  *ECMWF*
!      Original : 93-02-15

!     Modifications.
!     --------------
!      N. Wedi and K. Yessad (Jan 2008): different dev for NH model and PC scheme
!      Y. Takaya    : 01-Feb-2009 ocean mixed layer model fields
!      JJMorcrette    20100212 PP of CBASE, 0DEGL, VISIH
!      JJMorcrette  : 20091201 Total and clear-sky direct SW radiation flux at surface
!      R.Forbes     : 01-Mar-10 Adding TCRW,TCSW
!      K. Yessad (Jan 2011): remove useless overdimension.
!      P.Bechtold   : 09-Aug-11 Adding CIN,ConvIndices, reordering old fields
!        so that 0DEGL, CAPE etc are now in free style and not wrongly in fluxes
!      M. Ahlgrimm    31-Oct-2011 Add rain, snow and PEXTRA to DDH output
!      M. Ahlgrimm    31 Oct 2011 Clear-sky downward radiation at surface
!      L. Jones     : 26-Oct-11 Tidied parameter list r.e. MACC species
!      R.Engelen    : 24-Oct-11 Removing SF6
!      A. Inness    : 28-Mar-2012 Add total column CHEM fields
!      G. Balsamo   : 13-Jun-2013 Add lake prognostic fields
!      R. Forbes    : 01-Mar-2014 Add precip rates/type,I10FG,TCSLW,PEV
!      M. Ahlgrimm Apr 2014: Add lake variables and precip fraction to DDH output
!      R. Forbes    : 10-Jan-2015 Add freezing rain FZRA
!      P. Lopez     : Nov 2015 Added lightning fields
!      P. Bechtold: :  10-Nov-2015 Add CBASEA, CTOPC, ZTWETB0,1
!      E. Dutra & G.Arduini : Jan 2018 Snow multi-layer 
!      K. Yessad (Feb 2018): remove deep-layer formulations.
!      P. Bechtold  : 11-Feb-2020 Add PM10DEGL plus more CAPE,CIN variables and conv departure level
!      P. Bechtold: : 26-Mar-2021 Add TROPOTP
!      R. Forbes    : May-2022 Added precip-type occurrence frequency PTYPEOCC6
!     ----------------------------------------------------------------------------------------------

USE TYPE_MODEL         , ONLY : MODEL
USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1           , ONLY : JPIM, JPRB
USE YOMHOOK            , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMCST             , ONLY : RG, RMD, RMCO2, RMCH4, RMN2O
USE YOMINI             , ONLY : LINITER
USE YOMPPC             , ONLY : LRSACC
USE YOM_GRIB_CODES     , ONLY : NGRBGHG
USE YOE_AERODIAG       , ONLY : NPAERODIAG
USE YOECLDP            , ONLY : NPRECTYPES
USE ECEARTH            , ONLY : LECEARTH

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)         :: YDGEOMETRY
TYPE(TSURF)       ,INTENT(INOUT)      :: YDSURF
TYPE(MODEL)       ,INTENT(INOUT)      :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN)         :: KLEVS 
INTEGER(KIND=JPIM),INTENT(IN)         :: KLEVSN 
INTEGER(KIND=JPIM),INTENT(IN)         :: KLEVXP
INTEGER(KIND=JPIM),INTENT(IN)         :: KLEVO  !KPP
INTEGER(KIND=JPIM),INTENT(IN)         :: KFLDXP
INTEGER(KIND=JPIM),INTENT(IN)         :: KFLDXP2
INTEGER(KIND=JPIM),INTENT(IN)         :: KSATSIM
INTEGER(KIND=JPIM),INTENT(IN)         :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN)         :: KST
INTEGER(KIND=JPIM),INTENT(IN)         :: KEND
INTEGER(KIND=JPIM),INTENT(IN)         :: KFLEVG
LOGICAL           ,INTENT(IN)         :: LDFSTEP
LOGICAL           ,INTENT(IN)         :: LDMLPP
LOGICAL           ,INTENT(IN)         :: LDRS6
LOGICAL           ,INTENT(IN)         :: LDACCRS
INTEGER(KIND=JPIM),INTENT(IN)         :: KSTGLO
REAL(KIND=JPRB)   ,INTENT(IN)         :: PDTPHY
REAL(KIND=JPRB)   ,INTENT(IN)         :: PUT9(KPROMA,KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PVT9(KPROMA,KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PTT9(KPROMA,KFLEVG)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PGFL(KPROMA,KFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PAERODDF(KPROMA,YDMODEL%YRML_GCONF%YGFL%NACTAERO,NPAERODIAG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PTENQ(KPROMA,KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PDELP9(KPROMA,KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PDIFTQ(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PDIFCQ(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PDIFTS(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PDIFCS(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFRSO(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFRSOD(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFRSODC(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFRTH(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFRTHD(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFRTHDC(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PUVDF(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PPARF(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PCAPE(KPROMA,4)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PPARCF(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PTINCF(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFDIR(KPROMA), PDSRP(KPROMA), PCDIR(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PCBASE(KPROMA), PPDEPL(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: P0DEGL(KPROMA), PM10DEGL(KPROMA), PVISIH(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PCIN(KPROMA,3), PCONVIND(KPROMA,2)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PLIGH_TOT(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PLIGH_CTG(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PCBASEA(KPROMA), PCTOPC(KPROMA), PZTWETB(KPROMA,2)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PTROPOTP(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PPRECTYPE(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFZRA(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFHPCL(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFHPCN(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFHPSL(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFHPSN(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFPLCL(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFPLCN(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFPLSL(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFPLSN(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PSTRCU(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PSTRCV(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PSTRDU(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PSTRDV(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFCCQN(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFCCQL(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFCSQN(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFCSQL(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFCQLNG(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFCQNNG(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFSQRF(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFSQSF(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFCQRNG(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFCQSNG(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFSQLTUR(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFSQITUR(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PSTRTU(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PSTRTV(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: POROG(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PENES(KPROMA,KLEVS)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFEVN(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PGESLO(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PGECLO(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PVFLSM(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PVFCI(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PINEE(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PIGPP(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PIREC(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PVDZ0F(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PTSAE1(KPROMA,KLEVS)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PTLE1(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PWSAE1(KPROMA,KLEVS)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PISAE1(KPROMA,KLEVS)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PWLE1(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PSNSE1(KPROMA,KLEVSN) 
REAL(KIND=JPRB)   ,INTENT(IN)         :: PASNE1(KPROMA,KLEVSN) 
REAL(KIND=JPRB)   ,INTENT(IN)         :: PRSNE1(KPROMA,KLEVSN) 
REAL(KIND=JPRB)   ,INTENT(IN)         :: PTSNE1(KPROMA,KLEVSN) 
REAL(KIND=JPRB)   ,INTENT(IN)         :: PWSNE1(KPROMA,KLEVSN)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PTLICEE1(KPROMA)         !LAKE
REAL(KIND=JPRB)   ,INTENT(IN)         :: PTLMNWE1(KPROMA)         !LAKE
REAL(KIND=JPRB)   ,INTENT(IN)         :: PTLWMLE1(KPROMA)         !LAKE
REAL(KIND=JPRB)   ,INTENT(IN)         :: PTLBOTE1(KPROMA)         !LAKE
REAL(KIND=JPRB)   ,INTENT(IN)         :: PTLSFE1(KPROMA)          !LAKE
REAL(KIND=JPRB)   ,INTENT(IN)         :: PHLICEE1(KPROMA)         !LAKE
REAL(KIND=JPRB)   ,INTENT(IN)         :: PHLMLE1(KPROMA)          !LAKE
REAL(KIND=JPRB)   ,INTENT(IN)         :: PEXTRE1(KPROMA,KLEVXP,KFLDXP)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PXTR2E1(KPROMA,KFLDXP2)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PEVAPMU(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PUOE1(KPROMA,KLEVO)      !KPP or Ocean TKE
REAL(KIND=JPRB)   ,INTENT(IN)         :: PVOE1(KPROMA,KLEVO)      !KPP or Ocean TKE
REAL(KIND=JPRB)   ,INTENT(IN)         :: PTOE1(KPROMA,KLEVO)      !KPP or Ocean TKE
REAL(KIND=JPRB)   ,INTENT(IN)         :: PSOE1(KPROMA,KLEVO)      !KPP or Ocean TKE
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PFSNNU1(KPROMA,KLEVSN) 
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PASNU1(KPROMA,KLEVSN) 
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PRSNU1(KPROMA,KLEVSN) 
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PTSNU1(KPROMA,KLEVSN)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PWSNU1(KPROMA,KLEVSN)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PTSLNU1(KPROMA,KLEVS)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PWRENU1(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PTRENU1(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PQLINU1(KPROMA,KLEVS)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PTILINU1(KPROMA,KLEVS)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PTLICNU1(KPROMA)         !LAKE
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PTLMNNU1(KPROMA)         !LAKE
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PTLMLNU1(KPROMA)         !LAKE
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PTLBTNU1(KPROMA)         !LAKE
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PTLSFNU1(KPROMA)         !LAKE
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PHLICNU1(KPROMA)         !LAKE
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PHLMNU1(KPROMA)          !LAKE
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PEXTRP1(KPROMA,KLEVXP,KFLDXP)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PXTRP21(KPROMA,KFLDXP2)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PUO1(KPROMA,KLEVO)       !KPP or Ocean TKE
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVO1(KPROMA,KLEVO)       !KPP or Ocean TKE
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PTO1(KPROMA,KLEVO)       !KPP or Ocean TKE
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PSO1(KPROMA,KLEVO)       !KPP
REAL(KIND=JPRB)   ,INTENT(IN)         :: PRE9(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PRE9F(KPROMA,KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PWRENU0(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFCLL(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFCLN(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PTRENU0(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PQLINU0(KPROMA,KLEVS)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PTCLS(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PQCLS(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PISUND(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PVDBLH(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDSUND(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PITTRC(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PITSRC(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PISTRC(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PISSRC(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PI10FG(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PI10FGCV(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PILSPF(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVTTRC(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVTSRC(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVSTRC(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVSSRC(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVES(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVSMLT(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PV10FG(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PV10FG6(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVI10FG(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVLSPF(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVVIMD(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PUCLS(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PVCLS(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PVDLZ0H(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PVDALB(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PVLCC(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PVMCC(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PVHCC(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PVTCC(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PVDIS(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PVDISG(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PUSTRG(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PVSTRG(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PRUISS(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDLSP(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDCP(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDSF(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDFZRA(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDBLD(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDSSHF(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDSLHF(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDSP(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDMSL(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDSSR(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDSTR(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDSSRD(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDSSRDC(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDSTRD(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDSTRDC(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDTSR(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDTTR(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDUVDF(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDPARF(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDCAPE(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVMUCAPE(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVMLCAPE50(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVMLCAPE100(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDCAPES(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDMXCAP6(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDMXCAPS6(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDPARCF(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDTINCF(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVCBASE(KPROMA), PVPDEPL(KPROMA), PVVISIH(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PV0DEGL(KPROMA), PVM10DEGL(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVCIN(KPROMA), PVMLCIN50(KPROMA), PVMLCIN100(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVKINDEX(KPROMA), PVTTINDEX(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVCBASEA(KPROMA), PVCTOPC(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVTROPOTP(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVZTWETB0(KPROMA), PVZTWETB1(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDFDIR(KPROMA), PVDDSRP(KPROMA), PVDCDIR(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDIEWSS(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDINSSS(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDEWSS(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDNSSS(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDE(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDPEV(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDLGWS(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDISSHF(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDIE(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDVIWVE(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDVIWVN(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDTCW(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDTCWV(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDTCLW(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDTCIW(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDTCRW(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDTCSW(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDTCSLW(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDMGWS(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDGWD(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDMX2T(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDMN2T(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDMX2T6(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDMN2T6(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDRO(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDSRO(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDSSRO(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDCSF(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDLSSF(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDMXTPR(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDMNTPR(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDMXTPR6(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDMNTPR6(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDTPR(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDLSRR(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDCRR(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDLSSFR(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDCSFR(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDPTYPE(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVILSPF(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDTCO3(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDNEE(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDGPP(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDREC(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDLITOTI(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDLITOTA6(KPROMA)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDLICGI(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDLICGA6(KPROMA)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PVDPTYPEOCC6(KPROMA,NPRECTYPES)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PSMCLBT(KPROMA,KSATSIM)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PSMCSBT(KPROMA,KSATSIM)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDTCAERO(KPROMA,YDMODEL%YRML_GCONF%YGFL%NACTAERO)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDAEROF(KPROMA,YDMODEL%YRML_GCONF%YGFL%NACTAERO,8)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDTCGHG(KPROMA,YDMODEL%YRML_GCONF%YGFL%NGHG)
REAL(KIND=JPRB)   ,INTENT(OUT)        :: PVDTCCHEM(KPROMA,YDMODEL%YRML_GCONF%YGFL%NCHEM_TC)
REAL(KIND=JPRB)   ,INTENT(IN),TARGET  :: PSD_VF(KPROMA,YDSURF%YSD_VFD%NDIM)
! naj the interface has to be extented for NCHEM_SFX
REAL(KIND=JPRB)   ,INTENT(IN)         :: PGNORDL(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PGNORDM(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PGEMU(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PGSQM2(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PGELAM(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PGELAT(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PGAW(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFCQNG(KPROMA,0:KFLEVG)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PFONTE(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PRUISP(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PDHTLS(KPROMA,YDMODEL%YRML_PHY_G%YRDPHY%NTILES, &
 & YDMODEL%YRML_DIAG%YRMDDH%NDHVTLS+YDMODEL%YRML_DIAG%YRMDDH%NDHFTLS)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PDHTSS(KPROMA,YDMODEL%YRML_PHY_G%YRDPHY%NCSNEC, &
 & YDMODEL%YRML_DIAG%YRMDDH%NDHVTSS+YDMODEL%YRML_DIAG%YRMDDH%NDHFTSS)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PDHTTS(KPROMA,YDSURF%YSP_SBD%NLEVS, &
 & YDMODEL%YRML_DIAG%YRMDDH%NDHVTTS+YDMODEL%YRML_DIAG%YRMDDH%NDHFTTS)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PDHTIS(KPROMA,YDMODEL%YRML_PHY_G%YRDPHY%NCSI, &
 & YDMODEL%YRML_DIAG%YRMDDH%NDHVTIS+YDMODEL%YRML_DIAG%YRMDDH%NDHFTIS)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PDHSSS(KPROMA,YDMODEL%YRML_PHY_G%YRDPHY%NCSNEC, &
 & YDMODEL%YRML_DIAG%YRMDDH%NDHVSSS+YDMODEL%YRML_DIAG%YRMDDH%NDHFSSS)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PDHIIS(KPROMA,YDMODEL%YRML_DIAG%YRMDDH%NDHVIIS+YDMODEL%YRML_DIAG%YRMDDH%NDHFIIS)
REAL(KIND=JPRB)   ,INTENT(IN)         :: PDHWLS(KPROMA,YDSURF%YSP_SBD%NLEVS, &
 & YDMODEL%YRML_DIAG%YRMDDH%NDHVWLS+YDMODEL%YRML_DIAG%YRMDDH%NDHFWLS)
REAL(KIND=JPRB)   ,INTENT(INOUT)      :: PDHFSS(KPROMA,YDMODEL%YRML_DIAG%YRMDDH%NDHVFS+YDMODEL%YRML_DIAG%YRMDDH%NDHFFS)
!     ------------------------------------------------------------------
! Pointers to various sections of PSD_VF
REAL(KIND=JPRB), POINTER :: ZVDLAIL(:), ZVDLAIH(:), ZVDSOTY(:), ZVDCLK(:), ZVDDL(:)

!     ------------------------------------------------------------------

REAL(KIND=JPRB) :: ZVDZ0H (KPROMA),ZVDZ0F (KPROMA)
REAL(KIND=JPRB) :: ZIES  (KPROMA),ZISMLT(KPROMA)

REAL(KIND=JPRB) ::  ZLSM(KPROMA)
!     --- DIAGNOSTICS DDH ---
!     IDDHI(KPROMA) : DISTRIBUTION OF INTERNAL AREAS INDEXES
!     ZDHSF(KPROMA) : DISTRIBUTION OF HORIZONTAL MEANS WEIGHTS
!                        --------------------------
!     ZUZGEO, ZVMGEO : GEOGRAPHICAL ZONAL AND MERIDIAN WIND
!                    (INITIALISED IF LHDHKS OR LHDMCI TRUE)

INTEGER(KIND=JPIM) :: IDDHI(KPROMA)
REAL(KIND=JPRB) :: ZCPT1  (KPROMA),ZCPT234(KPROMA)
REAL(KIND=JPRB) :: ZWL1   (KPROMA),ZW234  (KPROMA)
REAL(KIND=JPRB) :: ZDHSF(KPROMA)
REAL(KIND=JPRB) :: ZDHCV(KPROMA,0:KFLEVG,YDMODEL%YRML_DIAG%YRMDDH%NDHCVSUL)
REAL(KIND=JPRB) :: ZDHCS(KPROMA,YDMODEL%YRML_DIAG%YRMDDH%NDHCSSU)
REAL(KIND=JPRB) :: ZUZGEO(KPROMA,KFLEVG), ZVMGEO(KPROMA,KFLEVG)
REAL(KIND=JPRB) :: ZGHG(KPROMA,KFLEVG,YDMODEL%YRML_GCONF%YGFL%NGHG)
REAL(KIND=JPRB) :: ZCHEM(KPROMA,KFLEVG,YDMODEL%YRML_GCONF%YGFL%NCHEM_TC)
REAL(KIND=JPRB) :: ZAERO(KPROMA,KFLEVG,YDMODEL%YRML_GCONF%YGFL%NACTAERO)
REAL(KIND=JPRB) :: ZSUMDELP, ZRMGHG, ZRGI
REAL(KIND=JPRB) :: ZIVIMD(KPROMA)

INTEGER(KIND=JPIM) ::   JL, JLEV, JROF, JSU, JGHG, JCHEM, JCHEM_TC, JAERO, JFLX,ICO2,ICH4
INTEGER(KIND=JPIM) ::   IFSVAR_ECMWF , IFSFLX_ECMWF

LOGICAL :: LLDYN, LLPHY
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

#include "cpcuddh.intfb.h"
#include "cpedia.intfb.h"
#include "cpphddhe.intfb.h"
!#include "cpqtuv.intfb.h"
#include "cpspe.intfb.h"

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('POSTPHY',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDVAB=>YDGEOMETRY%YRVAB, YDMDDH=>YDMODEL%YRML_DIAG%YRMDDH, &
 & YDDPHY=>YDMODEL%YRML_PHY_G%YRDPHY,YDLDDH=>YDMODEL%YRML_DIAG%YRLDDH, &
  & YGFL=>YDMODEL%YRML_GCONF%YGFL,YDEPHY=>YDMODEL%YRML_PHY_EC%YREPHY)
ASSOCIATE(NACTAERO=>YGFL%NACTAERO, NCHEM_TC=>YGFL%NCHEM_TC, NDIM=>YGFL%NDIM, &
 & NGHG=>YGFL%NGHG, YAERO=>YGFL%YAERO, YCHEM=>YGFL%YCHEM, &
 & YGHG=>YGFL%YGHG, YA=>YGFL%YA, YI=>YGFL%YI, YL=>YGFL%YL, YO3=>YGFL%YO3, &
 & YQ=>YGFL%YQ, YR=>YGFL%YR, YS=>YGFL%YS, &
 & NCSI=>YDDPHY%NCSI, NCSNEC=>YDDPHY%NCSNEC, NTILES=>YDDPHY%NTILES, &
 & LEFLAKE=>YDEPHY%LEFLAKE, LEPHYS=>YDEPHY%LEPHYS, &
 & LHDENT=>YDLDDH%LHDENT, LHDHKS=>YDLDDH%LHDHKS, LHDMCI=>YDLDDH%LHDMCI, &
 & LSDDH=>YDLDDH%LSDDH, &
 & HDSF=>YDMDDH%HDSF, NDDHI=>YDMDDH%NDDHI, NDHCSSU=>YDMDDH%NDHCSSU, &
 & NDHCVSUL=>YDMDDH%NDHCVSUL, NDHFFS=>YDMDDH%NDHFFS, NDHFIIS=>YDMDDH%NDHFIIS, &
 & NDHFSSS=>YDMDDH%NDHFSSS, NDHFTIS=>YDMDDH%NDHFTIS, NDHFTLS=>YDMDDH%NDHFTLS, &
 & NDHFTSS=>YDMDDH%NDHFTSS, NDHFTTS=>YDMDDH%NDHFTTS, NDHFWLS=>YDMDDH%NDHFWLS, &
 & NDHVFS=>YDMDDH%NDHVFS, NDHVIIS=>YDMDDH%NDHVIIS, NDHVSSS=>YDMDDH%NDHVSSS, &
 & NDHVTIS=>YDMDDH%NDHVTIS, NDHVTLS=>YDMDDH%NDHVTLS, NDHVTSS=>YDMDDH%NDHVTSS, &
 & NDHVTTS=>YDMDDH%NDHVTTS, NDHVWLS=>YDMDDH%NDHVWLS, &
 & NFSFLX_AERO=>YDMDDH%NFSFLX_AERO, NFSVAR_AERO=>YDMDDH%NFSVAR_AERO, &
 & YSD_VF=>YDSURF%YSD_VF, YSD_VFD=>YDSURF%YSD_VFD, YSP_SBD=>YDSURF%YSP_SBD)
!     ------------------------------------------------------------------

!*       1.    UPDATE T+1 VARIABLES.
!              ---------------------

!*        1.1   UPDATE SURFACE VARIABLES

CALL CPSPE (&
 & KPROMA,KST,KEND,KLEVS,KLEVXP,KLEVO,KLEVSN,&!KPP KLEVO
 & KFLDXP,KFLDXP2,PDTPHY,&
 & PTSAE1 , PTLE1  ,PWSAE1 ,&
 & PISAE1,&
 & PWLE1  ,PSNSE1 ,PWSNE1,&
 & PASNE1 ,PRSNE1 ,PTSNE1 ,&
 & PTLICEE1, PTLMNWE1,&!LAKE
 & PTLWMLE1, PTLBOTE1,&!LAKE
 & PTLSFE1 ,&!LAKE
 & PHLICEE1, PHLMLE1,&!LAKE
 & PEXTRE1,PXTR2E1,&
 & PUOE1  ,PVOE1  ,PTOE1  ,PSOE1,&!KPP
 & PTSLNU1, PTRENU1,PQLINU1,&
 & PTILINU1,&
 & PWRENU1,PFSNNU1,PWSNU1,&
 & PASNU1 ,PRSNU1 ,PTSNU1,&
 & PTLICNU1, PTLMNNU1,&!LAKE
 & PTLMLNU1, PTLBTNU1,&!LAKE
 & PTLSFNU1,&!LAKE
 & PHLICNU1, PHLMNU1,&!LAKE
 & PEXTRP1,PXTRP21,&
 & PUO1  ,PVO1  ,PTO1  ,PSO1&!KPP or ocean TKE
 & )
!     ------------------------------------------------------------------

!*        3.  DIAGNOSTICS.
!             ------------

!*    3.1   ECMWF SPECIFIC  DIAGNOSTICS

PVDTCGHG(:,:)=0._JPRB
PVDTCAERO(:,:)=0._JPRB
PVDTCCHEM(:,:)=0._JPRB

IF(LEPHYS) THEN

  ! * For a SL2TL (resp. leap-frog scheme) scheme,
  !   the following pointers must ALWAYS match with
  !   quantities at time t (resp t-dt).

! change units from kg/m2/s to m/s
  ZIES(KST:KEND)=PFEVN(KST:KEND)/1.E+03_JPRB
  ZISMLT(KST:KEND)=PFONTE(KST:KEND)/1.E+03_JPRB

  DO JGHG=1,NGHG
    DO JLEV=1,KFLEVG
      DO JROF=1,KPROMA
        ZGHG(JROF,JLEV,JGHG)=PGFL(JROF,JLEV,YGHG(JGHG)%MP9)
      ENDDO
    ENDDO
  ENDDO

  JCHEM_TC=0 
  DO JCHEM=1,NCHEM_TC
    IF(YCHEM(JCHEM)%IGRIBTC > 0) THEN
      JCHEM_TC=JCHEM_TC+1
      DO JLEV=1,KFLEVG
        DO JROF=1,KPROMA
          ZCHEM(JROF,JLEV,JCHEM_TC)=PGFL(JROF,JLEV,YCHEM(JCHEM)%MP9)
        ENDDO
      ENDDO
    ENDIF
  ENDDO

  DO JAERO=1,NACTAERO
    DO JLEV=1,KFLEVG
      DO JROF=1,KPROMA
        ZAERO(JROF,JLEV,JAERO)=PGFL(JROF,JLEV,YAERO(JAERO)%MP9)
      ENDDO
    ENDDO
  ENDDO

  CALL CPEDIA(YDVAB,YDMODEL%YRML_PHY_EC%YRECUMF,YDMODEL%YRML_GCONF,KPROMA,KST,KEND,KFLEVG,KSATSIM,&
   & LDFSTEP,LDMLPP,LDRS6,LRSACC,LDACCRS,&
   & PGELAM ,PGELAT ,PFPLCL ,PFPLCN ,PFPLSL ,PFPLSN ,&
   & PFRSO  ,PFRSOD ,PFRSODC,PFRTH  ,PFRTHD ,PFRTHDC,PUVDF  ,PPARF  ,&
   & PCAPE  ,PPARCF ,PTINCF ,PFDIR  ,PDSRP  ,PCDIR  ,&
   & PCBASE ,PPDEPL ,P0DEGL, PM10DEGL,PVISIH,PCIN   ,PCONVIND,&
   & PLIGH_TOT ,PLIGH_CTG,&
   & PCBASEA,PCTOPC ,PTROPOTP,PZTWETB,&
   & PDIFTS ,PDIFTQ ,PSTRTU ,PSTRTV,&
   & PFCLL  ,PFCLN  ,PTCLS  ,PQCLS  ,PUCLS  ,PVCLS  ,PTRENU0,PQLINU0,PVFLSM ,&
   & PVFCI  ,PISUND,&
   & PVDIS  ,PVDISG ,PUSTRG,&
   & PVSTRG ,PRUISS ,PRUISP,&
   & PINEE  ,PIGPP  ,PIREC,&
   & PRE9   ,PRE9F  ,PDELP9,&
   & PUT9,PVT9,PTT9,PGFL(1,1,YQ%MP9_PH),PGFL(1,1,YO3%MP9_PH),ZGHG,ZCHEM,ZAERO,&
   & PGFL(1,1,YA%MP9_PH),PGFL(1,1,YL%MP9_PH),PGFL(1,1,YR%MP9_PH),&
   & PGFL(1,1,YI%MP9_PH),PGFL(1,1,YS%MP9_PH),PTENQ,&
   & POROG,&  
   & PVDLSP ,PVDCP  ,PVDSF  ,PVDFZRA,PVDBLD  ,PVDSUND,&
   & PITTRC ,PITSRC ,PISTRC ,PISSRC ,ZIES, ZISMLT, PI10FG, PILSPF,&
   & PPRECTYPE,PFZRA,ZIVIMD, PEVAPMU,&
   & PVTTRC ,PVTSRC ,PVSTRC ,PVSSRC ,PVES, PVSMLT, PV10FG, PV10FG6, PVI10FG,&
   & PVLSPF ,PVVIMD,&
   & PVDSSHF,PVDSLHF,PVDSP  ,PVDMSL,&
   & PVDSSR ,PVDSTR ,PVDSSRD,PVDSTRD,PVDSSRDC,PVDSTRDC,PVDTSR ,PVDTTR,&
   & PVDUVDF,PVDPARF,PVDCAPE,PVDCAPES,PVDMXCAP6,PVDMXCAPS6,&
   & PVDPARCF,PVDTINCF,PVDFDIR,PVDDSRP,PVDCDIR,&
   & PVCBASE,PV0DEGL,PVM10DEGL,PVVISIH,PVCIN  ,PVKINDEX,PVTTINDEX,&
   & PVPDEPL,PVMUCAPE,PVMLCAPE50,PVMLCAPE100,PVMLCIN50,PVMLCIN100,&
   & PVCBASEA,PVCTOPC,PVTROPOTP,PVZTWETB0, PVZTWETB1,&
   & PVDEWSS,PVDNSSS,PVDE   ,PVDPEV   ,PVDLGWS,&
   & PVDMGWS,PVDGWD ,PVDMX2T,PVDMN2T,PVDMX2T6,PVDMN2T6,PVDRO,PVDSSRO,PVDSRO,&
   & PVDNEE ,PVDGPP ,PVDREC ,&
   & PVDCSF ,PVDLSSF,PVDMXTPR,PVDMNTPR,PVDMXTPR6,PVDMNTPR6,&
   & PVDTPR ,PVDLSRR,PVDCRR ,PVDLSSFR,PVDCSFR,PVDPTYPE,PVILSPF,&
   & PVDIEWSS,PVDINSSS,PVDISSHF,PVDIE,PVDVIWVE,PVDVIWVN,&
   & PVDTCW ,PVDTCWV,PVDTCLW,PVDTCIW,PVDTCRW,PVDTCSW,PVDTCSLW,PVDTCO3,&
   & PVDTCGHG,PVDTCCHEM,PVDTCAERO,&
   & PVDLITOTI,PVDLITOTA6,PVDLICGI,PVDLICGA6,&
   & PVDPTYPEOCC6, PSMCLBT, PSMCSBT)  
ENDIF

!     ------------------------------------------------------------------

!*        4.  DDH.
!             ----

!*    4.1 INITIALIZATION

IF ( LSDDH ) THEN
  DO JROF=KST,KEND
    IDDHI(JROF)=NDDHI(JROF+KSTGLO-1)
    ZDHSF(JROF)=HDSF(JROF+KSTGLO-1)
  ENDDO

!        INITIALISATION OF INTERMEDIATE COMPUTATION ARRAYS
!        IN ORDER TO MAKE THE ACCUMULATION EASIER

  DO JSU=1,NDHCVSUL
    DO JROF=KST,KEND
      ZDHCV(JROF,0   ,JSU)=0.0_JPRB
    ENDDO
  ENDDO

!        INITIALISATION IN CASE OF CONTROL OPTION

ENDIF

!*       4.2  COMP. OF PHYS. FIELDS AND SURFACE FLUXES

IF (LSDDH.AND..NOT.LINITER) THEN

!     CALCUL DES VENTS ZONAL ET MERIDIEN VRAIS, GEOGRAPHIQUES
  IF ( LHDHKS .OR. LHDMCI .OR. LHDENT ) THEN
    DO JLEV = 1, KFLEVG
      DO JROF=KST,KEND
        ZUZGEO(JROF,JLEV) = PGNORDM(JROF)*PUT9(JROF,JLEV)-&
         & PGNORDL(JROF)*PVT9(JROF,JLEV)
        ZVMGEO(JROF,JLEV) = PGNORDL(JROF)*PUT9(JROF,JLEV)+&
         & PGNORDM(JROF)*PVT9(JROF,JLEV)
      ENDDO
    ENDDO
  ENDIF

  DO JL=KST,KEND
    ZVDZ0F(JL) = PVDZ0F(JL) /RG
    ZVDZ0H(JL) = EXP(PVDLZ0H(JL))
  ENDDO
  DO JL=KST,KEND
    ZCPT1(JL)  =PENES(JL,1)
    ZCPT234(JL)=PENES(JL,2)+PENES(JL,3)+PENES(JL,4)
    ZWL1(JL)   =PQLINU0(JL,1)+PWRENU0(JL)
    ZW234(JL)  =PQLINU0(JL,2)+PQLINU0(JL,3)+PQLINU0(JL,4)
  ENDDO
  LLDYN=.FALSE.
  LLPHY=.TRUE.

  !LAI, soil type
  ZVDLAIL  => PSD_VF(1:KPROMA,YSD_VF%YLAIL%MP)
  ZVDLAIH  => PSD_VF(1:KPROMA,YSD_VF%YLAIH%MP)
  ZVDSOTY  => PSD_VF(1:KPROMA,YSD_VF%YSOTY%MP)

  !lake variables
  IF (LEFLAKE) THEN
     ZVDCLK  => PSD_VF(1:KPROMA,YSD_VF%YCLK%MP)
     ZVDDL   => PSD_VF(1:KPROMA,YSD_VF%YDL%MP)
  ENDIF

!cj begin change for new sfc DDH

  DO JROF=KST,KEND

! determine land-sea mask and

    IF(PVFLSM(JROF) > 0.5_JPRB) THEN
      ZLSM(JROF)=1.0_JPRB
    ELSE
      ZLSM(JROF)=0.0_JPRB
    ENDIF

! fill free-style array with appropriate variables

! 2m temperature
    PDHFSS(JROF,1)=PTCLS(JROF)
! 2m specific humidity
    PDHFSS(JROF,2)=PQCLS(JROF)
! 10m wind components
    PDHFSS(JROF,3)=PUCLS(JROF)
    PDHFSS(JROF,4)=PVCLS(JROF)
! skin temperature
    PDHFSS(JROF,5)=PTRENU0(JROF)
! forecast surface roughness length for momentum and heat
    PDHFSS(JROF,6)=ZVDZ0F(JROF)
    PDHFSS(JROF,7)=ZVDZ0H(JROF)
! forecast albedo
    PDHFSS(JROF,8)=PVDALB(JROF)
! boundary layer height
    PDHFSS(JROF,9)=PVDBLH(JROF)
! land-sea mask and sea-ice fraction
    PDHFSS(JROF,10)=ZLSM(JROF)
    PDHFSS(JROF,11)=PVFCI(JROF)
! wind gusts
    PDHFSS(JROF,12)=PV10FG(JROF)
    PDHFSS(JROF,25)=PI10FGCV(JROF)
! Orography
    PDHFSS(JROF,13)=POROG(JROF)
! Total cloud cover
    PDHFSS(JROF,14)=PVTCC(JROF)
! Low cloud cover
    PDHFSS(JROF,15)=PVLCC(JROF)
! Medium cloud cover
    PDHFSS(JROF,16)=PVMCC(JROF)
! High cloud cover
    PDHFSS(JROF,17)=PVHCC(JROF)
! convective available potential energy
    PDHFSS(JROF,18)=PCAPE(JROF,1)
! Cloud base level
    PDHFSS(JROF,19)=PCBASE(JROF)
! zero deg level
    PDHFSS(JROF,20)=P0DEGL(JROF)
! Horizontal visibility
    PDHFSS(JROF,21)=PVISIH(JROF)
! CIN
    PDHFSS(JROF,22)=PCIN(JROF,1)
! COnvective Indices
    PDHFSS(JROF,23)=PCONVIND(JROF,1)
    PDHFSS(JROF,24)=PCONVIND(JROF,2)
! Ceiling cloud base level aviation
    PDHFSS(JROF,26)=PCBASEA(JROF)
! Cloud top level convective
    PDHFSS(JROF,27)=PCTOPC(JROF)
! Height of 0,1deg wet bulb T
    PDHFSS(JROF,28)=PZTWETB(JROF,1)
    PDHFSS(JROF,29)=PZTWETB(JROF,2)
! -10 deg level
    PDHFSS(JROF,30)=PM10DEGL(JROF)
! most unstable and mixed-layer CAPE
    PDHFSS(JROF,31)=PCAPE(JROF,2)
    PDHFSS(JROF,32)=PCAPE(JROF,3)
    PDHFSS(JROF,33)=PCAPE(JROF,4)
! mixed-layer CIN
    PDHFSS(JROF,34)=PCIN(JROF,2)
    PDHFSS(JROF,35)=PCIN(JROF,3)
! departure level(pressure) of most unstable convective parcel
    PDHFSS(JROF,36)=PPDEPL(JROF)
! pressure at thermal tropopause
    PDHFSS(JROF,37)=PTROPOTP(JROF)

! the number of ECMWF permanent free style variables
    IFSVAR_ECMWF=37

! Total column AERO
    NFSVAR_AERO=IFSVAR_ECMWF + 1
    DO JAERO=1,NACTAERO
      PDHFSS(JROF,IFSVAR_ECMWF +  JAERO)=PVDTCAERO(JROF,JAERO)
    ENDDO
    IFSVAR_ECMWF=IFSVAR_ECMWF + NACTAERO

! Please if you introduce new variables always let the following
! GEMS diagnostics at the end of the free style variables
! and change the incrementation accordingly

! Total column GHG - Not permanent (conditional variables)
! IF CO2 is run together with CH4 the order in DDH will be
! CO2 first then CH4

    DO JGHG = 1, NGHG
      ICO2=MIN(NGHG,1)
      ICH4=MAX(NGHG,1)
      IF(YGHG(JGHG)%IGRBCODE == 210061) THEN
        PDHFSS(JROF,IFSVAR_ECMWF+ICO2)=PVDTCGHG(JROF,ICO2)
      ELSEIF(YGHG(JGHG)%IGRBCODE == 210062) THEN
        PDHFSS(JROF,IFSVAR_ECMWF+ICH4)=PVDTCGHG(JROF,ICH4)
      ENDIF
    ENDDO
    IFSVAR_ECMWF=IFSVAR_ECMWF + NGHG 

! surface downward shortwave and longwave radiation
    PDHFSS(JROF,NDHVFS+1)=PFRSOD(JROF)
    PDHFSS(JROF,NDHVFS+2)=PFRTHD(JROF)
! sunshine duration
    PDHFSS(JROF,NDHVFS+3)=PISUND(JROF)
! snow evaporation
    PDHFSS(JROF,NDHVFS+4)=PFEVN(JROF)
! snowmelt
    PDHFSS(JROF,NDHVFS+5)=PFONTE(JROF)
! large-scale rainfall
    PDHFSS(JROF,NDHVFS+6)=PFPLSL(JROF,KFLEVG)
! convective rainfall
    PDHFSS(JROF,NDHVFS+7)=PFPLCL(JROF,KFLEVG)
! large-scale snowfall
    PDHFSS(JROF,NDHVFS+8)=PFPLSN(JROF,KFLEVG)
! convective snowfall
    PDHFSS(JROF,NDHVFS+9)=PFPLCN(JROF,KFLEVG)
! surface sensible heat flux
    PDHFSS(JROF,NDHVFS+10)=PDIFTS(JROF,KFLEVG)
! surface latent heat flux
    PDHFSS(JROF,NDHVFS+11)=PFCLL(JROF)+PFCLN(JROF)
! surface solar radiation
    PDHFSS(JROF,NDHVFS+12)=PFRSO (JROF,KFLEVG)
! surface thermal radiation
    PDHFSS(JROF,NDHVFS+13)=PFRTH (JROF,KFLEVG)
! surface evaporation
    PDHFSS(JROF,NDHVFS+14)=PDIFTQ(JROF,KFLEVG)
! total runoff
    PDHFSS(JROF,NDHVFS+15)=PRUISS(JROF) + PRUISP(JROF)
! surface solar radiation, clear-sky
    PDHFSS(JROF,NDHVFS+16)=PISSRC(JROF)
! surface thermal radiation, clear-sky
    PDHFSS(JROF,NDHVFS+17)=PISTRC(JROF)
! Large-scale precipitation fraction
    PDHFSS(JROF,NDHVFS+18)=PILSPF(JROF)
! surface UV flux
    PDHFSS(JROF,NDHVFS+19)=PUVDF(JROF)
! surface Photosynth.Active Radiation
    PDHFSS(JROF,NDHVFS+20)=PPARF(JROF)
! surface Photosynth.Active Radiation - Clear Sky
    PDHFSS(JROF,NDHVFS+21)=PPARCF(JROF)
! TOA incident solar radiation
    PDHFSS(JROF,NDHVFS+22)=PTINCF(JROF)
! vertically integr. mass divergence
    PDHFSS(JROF,NDHVFS+23)=ZIVIMD(JROF)
! TOA SW radiation clearsky
    PDHFSS(JROF,NDHVFS+24)=PITSRC(JROF)
! TOA LW radiation clearsky
    PDHFSS(JROF,NDHVFS+25)=PITTRC(JROF)
! Surface direct SW radiation - total sky
    PDHFSS(JROF,NDHVFS+26)=PFDIR(JROF)
! Surface direct SW radiation - clear-sky
    PDHFSS(JROF,NDHVFS+27)=PCDIR(JROF)
! Surface clear-sky downward shortwave flux
    PDHFSS(JROF,NDHVFS+28)=PFRSODC(JROF)
! Surface clear-sky downward longwave flux
    PDHFSS(JROF,NDHVFS+29)=PFRTHDC(JROF)
! TOA SW radiation net
    PDHFSS(JROF,NDHVFS+30)=PFRSO(JROF,0)
! TOA LW radiation net
    PDHFSS(JROF,NDHVFS+31)=PFRTH (JROF,0)
! Leaf area index low
    PDHFSS(JROF,NDHVFS+32)=ZVDLAIL(JROF)
! Leaf area index high
    PDHFSS(JROF,NDHVFS+33)=ZVDLAIH(JROF)
! Dominant soil texture type
    PDHFSS(JROF,NDHVFS+34)=ZVDSOTY(JROF)
! Surface direct beam SW radiation - total sky
    PDHFSS(JROF,NDHVFS+35)=PDSRP(JROF)

! the number of ECMWF permanent free style fluxes
    IFSFLX_ECMWF=35

! Aerosols: fluxes from physical processes
    IF (NACTAERO > 0) THEN
      NFSFLX_AERO=IFSFLX_ECMWF + 1
      DO JAERO=1,NACTAERO
        DO JFLX=1,7
          PDHFSS(JROF,NDHVFS+IFSFLX_ECMWF + (JAERO-1)*7 + JFLX)=&
           & PAERODDF(JROF,JAERO,JFLX)
        ENDDO
      ENDDO
      IFSFLX_ECMWF=IFSFLX_ECMWF+NACTAERO*7
    ENDIF

    IF (LEFLAKE) THEN
       IFSFLX_ECMWF=IFSFLX_ECMWF+1
       PDHFSS(JROF,NDHVFS+IFSFLX_ECMWF)=PTLMLNU1(JROF)
       IFSFLX_ECMWF=IFSFLX_ECMWF+1
       PDHFSS(JROF,NDHVFS+IFSFLX_ECMWF)=PHLMNU1(JROF)
       IFSFLX_ECMWF=IFSFLX_ECMWF+1
       PDHFSS(JROF,NDHVFS+IFSFLX_ECMWF)=PTLBTNU1(JROF)
       IFSFLX_ECMWF=IFSFLX_ECMWF+1
       PDHFSS(JROF,NDHVFS+IFSFLX_ECMWF)=PTLMNNU1(JROF)
       IFSFLX_ECMWF=IFSFLX_ECMWF+1
       PDHFSS(JROF,NDHVFS+IFSFLX_ECMWF)=PTLSFNU1(JROF)
       IFSFLX_ECMWF=IFSFLX_ECMWF+1
       PDHFSS(JROF,NDHVFS+IFSFLX_ECMWF)=PTLICNU1(JROF)
       IFSFLX_ECMWF=IFSFLX_ECMWF+1
       PDHFSS(JROF,NDHVFS+IFSFLX_ECMWF)=PHLICNU1(JROF)
       IFSFLX_ECMWF=IFSFLX_ECMWF+1
       PDHFSS(JROF,NDHVFS+IFSFLX_ECMWF)=ZVDCLK(JROF)
       IFSFLX_ECMWF=IFSFLX_ECMWF+1
       PDHFSS(JROF,NDHVFS+IFSFLX_ECMWF)=ZVDDL(JROF)
    ENDIF

  ENDDO
!print 9421,(PDHFSS(JROF,NDHVFS+19),JROF=KST,KEND)
!  9421 FORMAT(1X,'PostphyD UVBF ',15E10.3)
!print 9422,(PDHFSS(JROF,NDHVFS+20),JROF=KST,KEND)
!  9422 FORMAT(1X,'PostphyD PARF ',15E10.3)
!print 9423,(PDHFSS(JROF,NDHVFS+21),JROF=KST,KEND)
!  9423 FORMAT(1X,'PostphyD CAPE ',15E10.3)
!print 9424,(PDHFSS(JROF,NDHVFS+22),JROF=KST,KEND)
!  9424 FORMAT(1X,'PostphyD PARCF ',15E10.3)
!print 9425,(PDHFSS(JROF,NDHVFS+23),JROF=KST,KEND)
!  9425 format(1x,'PostphyD TINCF ',15E10.3)
!print 9426,(PDHFSS(JROF,NDHVFS+24),JROF=KST,KEND)
!  9426 format(1x,'PostphyD VIMDF ',15E10.3)
!print 9427,(PDHFSS(JROF,NDHVFS+25),JROF=KST,KEND)
!  9427 format(1x,'PostphyD TSRC ',15E10.3)
!print 9428,(PDHFSS(JROF,NDHVFS+26),JROF=KST,KEND)
!  9428 format(1x,'PostphyD TTRC ',15E10.3)
!print 9426,(PDHFSS(JROF,NDHVFS+27),JROF=KST,KEND)
!  9426 format(1x,'PostphyD FDIR ',15E10.3)
!print 9426,(PDHFSS(JROF,NDHVFS+28),JROF=KST,KEND)
!  9426 format(1x,'PostphyD CDIR ',15E10.3)
!print 9429,(PDHFSS(JROF,NDHVFS+29),JROF=KST,KEND)
!  9429 format(1x,'PostphyD CBASE ',15E10.3)
!print 9430,(PDHFSS(JROF,NDHVFS+30),JROF=KST,KEND)
!  9430 format(1x,'PostphyD 0DEGL ',15E10.3)
!print 9431,(PDHFSS(JROF,NDHVFS+31),JROF=KST,KEND)
!  9431 format(1x,'PostphyD VISIH ',15E10.3)


  CALL CPPHDDHE(YDDIM,YDSURF,YDMODEL%YRML_DIAG,YDDPHY,YDMODEL%YRML_GCONF%YRRIP,YDMODEL%YRML_PHY_MF%YRPHY,KPROMA,KST,KEND,KFLEVG,&
   & PGNORDL,PGNORDM,ZUZGEO ,ZVMGEO ,&
   & PGELAM ,ZLSM   ,PVFCI  ,&
   & PDIFCQ ,PDIFCS ,PDIFTQ ,PDIFTS ,PFCQNG ,&
   & PFPLCL ,PFPLCN ,PFPLSL ,PFPLSN ,&
   & PFRSO  ,PFRTH  ,&
   & PFHPCL ,PFHPCN ,PFHPSL ,PFHPSN ,&
   & PSTRCU ,PSTRCV ,PSTRDU ,PSTRDV ,PSTRTU ,PSTRTV ,&
   & PFCQLNG, PFSQRF,   PFSQSF ,  PFCQRNG,  PFCQSNG,PFSQLTUR, PFSQITUR ,&
   & PFCQNNG,&
   & PFCCQL ,PFCCQN ,PFCSQL ,PFCSQN ,&
   & PDHTLS ,PDHTSS ,PDHTTS ,PDHTIS ,&
   & PDHSSS ,PDHIIS ,PDHWLS ,PDHFSS ,&
   & ZDHCV  ,ZDHCS)

!*    4.3   STORE/ACCUM. IN HORIZONTAL MEAN ARRAYS

  CALL CPCUDDH(YDMODEL%YRML_DIAG,YDMODEL%YRML_GCONF%YRRIP,KPROMA,KST,KEND,KFLEVG,IDDHI,ZDHSF,ZDHCV,ZDHCS,LLDYN,LLPHY,NDHCVSUL)
ENDIF

!* CHANGE GHG TOTAL COLUMN UNIT (kg/m2-->ppm for CO2 and ppb for CH4) (integral --> average)
! EC-Earth4 : disable this for output of co2mass (used as a diagnostic), shoud we make this optional?

IF(NGHG > 0) THEN
  ZRGI=1.0_JPRB/RG
  DO JL=KST,KEND
    ZSUMDELP=0.0_JPRB
    DO JLEV=1,KFLEVG
      ZSUMDELP=ZSUMDELP+PDELP9(JL,JLEV)*ZRGI
    ENDDO
    DO JGHG=1,NGHG
      IF(YGHG(JGHG)%IGRBCODE == NGRBGHG(1)) THEN
        IF(.NOT. LECEARTH) THEN
          PVDTCGHG(JL,JGHG)=PVDTCGHG(JL,JGHG)/ZSUMDELP*1.E6_JPRB*RMD/RMCO2
        ENDIF
      ELSE
        IF(YGHG(JGHG)%IGRBCODE == NGRBGHG(2)) ZRMGHG=RMCH4/1.E3_JPRB
        IF(YGHG(JGHG)%IGRBCODE == NGRBGHG(3)) ZRMGHG=RMN2O
        PVDTCGHG(JL,JGHG)=PVDTCGHG(JL,JGHG)/ZSUMDELP*1.E6_JPRB*RMD/ZRMGHG
      ENDIF
    ENDDO
  ENDDO
ENDIF

!     ------------------------------------------------------------------

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('POSTPHY',1,ZHOOK_HANDLE)
END SUBROUTINE POSTPHY
