MODULE CPLNG2_FINALIZE_MOD

    IMPLICIT NONE

    PRIVATE

    PUBLIC CPLNG2_FINALIZE

CONTAINS

    SUBROUTINE CPLNG2_FINALIZE
        USE PARKIND1, ONLY: JPIM
        USE CPLNG2_DATA_MOD
        ! locals
        INTEGER(KIND=JPIM) :: error
        CHARACTER(LEN=3) :: error_str

    END SUBROUTINE CPLNG2_FINALIZE

END MODULE CPLNG2_FINALIZE_MOD
