MODULE CPLNG2_INIT_MOD

    IMPLICIT NONE

    PRIVATE

    PUBLIC CPLNG2_INIT

CONTAINS

    SUBROUTINE CPLNG2_INIT
        USE PARKIND1, ONLY: JPIM
        USE MPL_MODULE, ONLY: LMPLUSERCOMM, MPLUSERCOMM
        USE CPLNG2_DATA_MOD
        ! parameters
        CHARACTER(LEN=*), PARAMETER :: CMODEL_NAME = "OpenIFS"
        ! locals
        INTEGER(KIND=JPIM) :: comp_id
        INTEGER(KIND=JPIM) :: error
        CHARACTER(LEN=3) :: error_str

    END SUBROUTINE CPLNG2_INIT

END MODULE CPLNG2_INIT_MOD
