NAMELIST /NAMORB/ &
& LCORBMD, &
& ORBMODE, ORBIY, ORBECCEN, ORBOBLIQ, &
& ORBMVELP, ORBORLIQR, ORBLAMBM0, ORBMVELPP, &
& ORBCALDAY, ORBCALDAYM, ORBCYEAR
!  -----------------------------------------------------------
