! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

!     -----------------------------------------------------------------
NAMELIST/NAERAD/&
&  LERAD1H, LEPO3RA, LONEWSW &
&, LCCNL  , LCCNO  , LRAYL  , LRRTM  , LSRTM  &
&, LHVOLCA, LNEWAER, LDIFFC , LNOTROAER &
&, LETRACGMS,LAERCLIM,LAERVISI,LAERADJDU,LAERADCLI &
&, LPERPET, LAER3D  &
&, NICEOPT, NLIQOPT, NSWICEOPT, NLWICEOPT, NSWLIQOPT, NLWLIQOPT & 
&, NMCICA , NRADIP , NRADLP  & 
&, NREDGLW, NREDGSW &
&, NAERMACC,NMCLAT , NMCLON &
&, NAER   , NMODE  , NOZOCL , NINHOM , NLAYINH &
&, NOVLP  , NSW    , NRADFR , NLNGR1H, NRADELG &
&, NRADPFR, NRADPLA, NRPROMA &
&, NRADINT, NRADRES, NGHGRAD, NDECOLAT, NMINICE, NVOLCVERT &
&, LVOLCSPEC, LVOLCDAMP, LVOLCDATA, CVOLCDATA, RVOLCSPEC &
&, CRTABLEDIR, CRTABLEFIL &
&, RCCNSEA, RCCNLND, NPERTAER, NPERTOZ &
&, RPERTOZ, RLWINHF, RSWINHF, RRe2De , RMINICE &
&, RCCO2  , RCCH4  , RCN2O  , RCCFC11, RCCFC12 &
&, RAESHSS, RAESHDU, RAESHOM, RAESHBC, RAESHSU &
&, NHINCSOL,LECO2VAR,LHGHG  , NSCEN   &
&, LUVPROC, LUVTDEP, LUVDBG , NUV     &
&, LEDBUG , LESO4HIS,CLISTSO4 &
&, NUVTIM , NRADUV , RUVLAM , RMUZUV  &
&, NO3CMIP, CO3DATADIR &
&, NGHGCMIP,GHGDATADIR,NRCP,LDIAGFORCING,KMODTS,LUVAERP,LECOMPGRID,LECSRAD &
&, LAPPROXLWUPDATE, LAPPROXSWUPDATE, LCENTREDTIMESZA, LMANNERSSWUPDATE &
&, LAVERAGESZA, TRBKG, STBKG, LO3_CHEM_UV &
&, LUSEPRE2017RAD, NLWSCATTERING, NSWSOLVER, NLWSOLVER &
&, RCLOUD_FRAC_STD, LFU_LW_ICE_OPTICS_BUG, CSOLARDATA, NCMIPFIXYR &
&, NSOLARSPECTRUM, NSWWVCONTINUUM, NDUMPBADINPUTS, LINTERPINCLOUDMEAN &
&, NCLOUDOVERLAP, NDUMPINPUTS &
&, RCLOUD_SEPARATION_SCALE_TOA, RCLOUD_SEPARATION_SCALE_SURF &
&, CGHGCLIMFILE, CGHGTIMESERIESFILE, CSOLARIRRADIANCEFILE &
&, LCMIP_STRATAER_CMIP6,LCMIP_STRATAER_CMIP7 &
&, LCMIP_STRATAER_BCKGD,  CCMIP_STRAT_FULL &
&, CCMIP_STRAT_FULL_CLIM, NCLOUDACT, NAEROOPT
!     -----------------------------------------------------------------

