! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBMODULE (MODEL_MOD) MODEL_MOD_MODEL_STEP
IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE MODEL_STEP(SELF, YDFIELDS, YDTIME, KSECS, YDERRMOD_FIELDS, LDCLUPD)

USE PARKIND1         , ONLY : JPRB, JPIM, JPIB
USE YOMHOOK          , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMCT0           , ONLY : NCONF, NFRCO
USE YOMCT3           , ONLY : NSTEP
USE FIELDS_MOD       , ONLY : FIELDS
USE ERRMOD_FIELDS_MOD, ONLY : ERRMOD_FIELDS
USE MTRAJ_MOD        , ONLY : MTRAJ
USE GMV_SUBS_MOD     , ONLY : SETUP_GMV5
USE YOMTRAJ_OOPS     , ONLY : TRAJ_TYPE_OOPS,LTRAJSAVE_OOPS,LTRAJSLAG_OOPS
USE YOMTRAJ          , ONLY : LTRAJSAVE,LTRAJSLAG
USE YOMLUN           , ONLY : NULOUT, NULERR
USE GEOMETRY_MOD     , ONLY : GEOMETRY_SAME
USE DATETIME_TMP_MOD , ONLY : DATETIME_TMP, SETRIP0, GETRIPSTEP, SETRIPSTEP
USE YOMFPC           , ONLY : LOCEDELAY


IMPLICIT NONE

#include "updtim.intfb.h"
#include "spmcuf.intfb.h"



#include "wvcouple.intfb.h"
#include "couplnemo.intfb.h"
#include "updnemoocean.intfb.h"
#include "getnemodiag.intfb.h"
#include "getnemodiag3d.intfb.h"
#include "abor1.intfb.h"

TYPE(MODEL)        ,           INTENT(INOUT) :: SELF
TYPE(FIELDS)       ,           INTENT(INOUT) :: YDFIELDS
TYPE(DATETIME_TMP) ,           INTENT(INOUT) :: YDTIME
INTEGER(KIND=JPIM) ,           INTENT(INOUT) :: KSECS
TYPE(ERRMOD_FIELDS), OPTIONAL, INTENT(IN)    :: YDERRMOD_FIELDS
LOGICAL            , OPTIONAL, INTENT(IN)    :: LDCLUPD

TYPE(MTRAJ)          :: YLMTRAJ
TYPE(TRAJ_TYPE_oops) :: YLOOPSTRAJ

LOGICAL              :: LLCLUPD,LLNEMOUPD,LLMLPP
LOGICAL              :: LLSTOP,LLWRRW
CHARACTER(LEN=9)     :: CL="AAAA00AAA"
CHARACTER (LEN = 10) :: CLTIMEOD,CLDAT(3)
INTEGER(KIND=JPIM)   :: IVALUES(8)
INTEGER(KIND=JPIM)   :: IMINUT, ISTPW
REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_STEP',0,ZHOOK_HANDLE)

ASSOCIATE(YDRIP=>SELF%YRML_GCONF%YRRIP, YDDIM=>YDFIELDS%GEOM%YRDIM, &
 &        YDGEM=>YDFIELDS%GEOM%YRGEM, YDML_AOC=>SELF%YRML_AOC, &
 &        YDML_PHY_EC=>SELF%YRML_PHY_EC, YDEWCOU=>SELF%YREWCOU )
ASSOCIATE(NSTART=>YDRIP%NSTART, NSTOP=>YDRIP%NSTOP, TSTEP=>YDRIP%TSTEP, &
 &        NPROMA=>YDDIM%NPROMA, NGPTOT=>YDGEM%NGPTOT, &
 &        YDMCC=>YDML_AOC%YRMCC, YDEPHY=>YDML_PHY_EC%YREPHY, &
 &        LWCOU=>YDEWCOU%LWCOU)

CALL MODEL_SET(SELF)
IF(.NOT.GEOMETRY_SAME(SELF%YRML_GCONF%GEOM,YDFIELDS%GEOM)) &
 & CALL ABOR1('MODEL_MOD:MODEL_STEP - GEOMETRIES DIFFERENT')

!! 3D-Var case
IF ( SELF%YRML_GCONF%YRRIP%NSTOP == 0 ) RETURN

!! this should not be necessary here!
CALL SETUP_GMV5(YDFIELDS%GEOM, YLMTRAJ%YRGMV5, SELF%YRML_GCONF%YRDIMF,&
 & SELF%YRML_DYN%YRDYNA)

LTRAJSLAG_oops=.FALSE.
LTRAJSAVE_oops=.FALSE.
LTRAJSLAG=.FALSE.
LTRAJSAVE=.FALSE.

IF(PRESENT(LDCLUPD)) THEN
   LLCLUPD=LDCLUPD
ELSE
   LLCLUPD=.TRUE.
ENDIF

! Set time-step and update time of the model
CALL SETRIPSTEP(SELF%YRML_GCONF%YRRIP%TSTEP, YDTIME, KSECS)
CALL UPDTIM(YDFIELDS%GEOM,YDFIELDS%YRSURF,SELF,INT(NSTEP, KIND=JPIB), &
 &          SELF%YRML_GCONF%YRRIP%TDT,SELF%YRML_GCONF%YRRIP%TSTEP,LLCLUPD)
CALL DATE_AND_TIME(CLDAT(1),CLTIMEOD,CLDAT(3),IVALUES)

! Update ocean fields if previus time step was a coupled time step
! or we are at the beginning of the run.
#ifdef WITH_NEMO
  IF(YDMCC%LMCC04.AND.YDMCC%LNEMOCOUP) THEN
    IF(NSTART/=0) THEN
      LLNEMOUPD=((MOD(NSTEP-1,NFRCO)==0).AND.(NSTEP>NSTART).AND.&
       &         .NOT.LOCEDELAY).OR.(LOCEDELAY.AND.(NSTEP==NSTART+1))
    ELSE
      LLNEMOUPD=((MOD(NSTEP-1,NFRCO)==0).AND.(NSTEP-1>0).AND.&
       &         .NOT.LOCEDELAY).OR.(NSTEP==0)
    ENDIF

    IF(LLNEMOUPD) THEN
      CALL GSTATS(33,0)
      IF (LOCEDELAY.AND.(NSTEP==NSTART+1)) THEN
        CALL UPDNEMOOCEAN(YDMCC,YDEPHY,YDRIP,NPROMA,NGPTOT,&
         &                NSTART,TSTEP,YDFIELDS%YRSURF,YDFIELDS%GEOM)
      ELSE
        CALL UPDNEMOOCEAN(YDMCC,YDEPHY,YDRIP,NPROMA,NGPTOT,&
         &                NSTEP,TSTEP,YDFIELDS%YRSURF,YDFIELDS%GEOM)
      ENDIF
      CALL GSTATS(33,1)
      IF(YDMCC%LNEMOGRIBFLDS) THEN
        CALL GSTATS(32,0)
        CALL GETNEMODIAG(NGPTOT,NPROMA,NSTEP,YDFIELDS%YRSURF,YDMCC)
        CALL GSTATS(32,1)
      ENDIF
      IF(YDMCC%LNEMOGRIB3D) THEN
        CALL GSTATS(32,0)
        CALL GETNEMODIAG3D(NGPTOT,NPROMA,NSTEP,YDFIELDS%YRSURF,&
         &                 YDMCC,YDFIELDS%GEOM)
        CALL GSTATS(32,1)
      ENDIF
    ENDIF
  ENDIF
#endif

! Perform time-step
! Coupling to NEMO
#ifdef WITH_NEMO
  IF(NFRCO /= 0 .AND. YDMCC%LNEMOCOUP &
   &            .AND. YDMCC%LMCC04) THEN
    ! Coupling to NEMO except at timestep NSTAR2
    ! where we reset the fluxes to zero to avoid
    ! double counting
    IF(NSTEP == NSTART) THEN
      CALL GSTATS(33,0)
      CALL SUGCO0(YDMCC)
      IF (LWCOU) THEN
        CALL UPDNEMOSTRESS
      ENDIF
      CALL GSTATS(33,1)
    ELSEIF(MOD(NSTEP+1,NFRCO) == 0) THEN
      CALL GSTATS(32,0)
      IF (LWCOU) THEN
        CALL UPDNEMOFIELDS
        CALL UPDNEMOSTRESS
      ENDIF
      CALL COUPLNEMO(YDGEM,YDMCC,YDRIP,NSTEP)
      CALL GSTATS(32,1)
      CALL GSTATS(33,0)
      IF (LOCEDELAY) THEN
        CALL UPDNEMOOCEAN(YDMCC,YDEPHY,YDRIP,NPROMA,NGPTOT,&
         &                NSTEP,TSTEP,YDFIELDS%YRSURF,YDFIELDS%GEOM)
      ENDIF
      CALL GSTATS(33,1)
    ENDIF
  ENDIF

  ! Optionally get fields from NEMO.
  LLMLPP = YDEPHY%LFPOS_EC_PHYS

  IF(YDMCC%LMCC04.AND.YDMCC%LNEMOCOUP.AND.&
   & YDMCC%LNEMOGRIBFLDS.AND.LOCEDELAY.AND.LLMLPP) THEN
     CALL GSTATS(32,0)
     CALL GETNEMODIAG(NGPTOT,NPROMA,NSTEP,YDFIELDS%YRSURF,YDMCC)
     CALL GSTATS(32,1)
  ENDIF
  IF(YDMCC%LMCC04.AND.YDMCC%LNEMOCOUP.AND.&
   & YDMCC%LNEMOGRIB3D.AND.LOCEDELAY.AND.LLMLPP) THEN
     CALL GSTATS(32,0)
     CALL GETNEMODIAG3D(NGPTOT,NPROMA,NSTEP,YDFIELDS%YRSURF,&
      &                 YDMCC,YDFIELDS%GEOM)
     CALL GSTATS(32,1)
  ENDIF
#endif

! Update time-step
NSTEP=NSTEP+1
CALL GETRIPSTEP(SELF%YRML_GCONF%YRRIP%TSTEP, YDTIME, KSECS)

! Couple with the wave model
IF(SELF%YREWCOU%LWCOU) THEN
  ISTPW=1
  LLSTOP=.FALSE.
  LLWRRW=.FALSE.
  CALL WVCOUPLE(YDFIELDS%GEOM,YDFIELDS%YRSURF,SELF%YRML_PHY_EC%YREPHY,&
   &            SELF%YREWCOU,SELF%YRML_GCONF%YRRIP%TSTEP,&
   &            SELF%YRML_GCONF%YRRIP%NSTOP,ISTPW,LLSTOP,LLWRRW)
ENDIF

IF (YDFIELDS%YMCUF%LMCUF) &
 & CALL SPMCUF(YDFIELDS%GEOM,YDFIELDS%YRSPEC,YDFIELDS%YMCUF)

CALL MODEL_UNSET(SELF)

END ASSOCIATE
END ASSOCIATE

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_STEP',1,ZHOOK_HANDLE)

END SUBROUTINE MODEL_STEP

END SUBMODULE
