MODULE YOEDUST

USE PARKIND1, ONLY: JPIM, JPRB
USE YOMHOOK,  ONLY: LHOOK, DR_HOOK, JPHOOK
USE YOMLUN,   ONLY: NULOUT

IMPLICIT NONE

SAVE 
! ------------------------------------------------------------------
!*** *YOEDUST* - ECE4 CLIMATOLOGIAL FIELD FOR DUST EMISSION SCHEME ! 
!                       Called in tm5m7_src_dust.F90
!     info:  
!                This module reads and interpolates climatological !
!                surface fields that used in Dust emission Scheme
!                Tegen et al., 2002. 
!     
!         :      Marios Chatziparaschos 
!                Barcelona Supercomputing Center 
!         :      26/06/2025        
! -----------------------------------------------------------------!-

INTEGER(KIND=JPIM), PARAMETER :: IMONTH = 12
INTEGER(KIND=JPIM), PARAMETER :: ILAT   = 180 
INTEGER(KIND=JPIM), PARAMETER :: ILON   = 360 

TYPE :: TEAERC_DUST
!- based on SURFACE 2D (lat,lon) 1x1
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:)   :: CULT,POTSRC !,SOILTYPE
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:)   :: CULT1, SOILTYPE1,POTSRC1
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:)     :: SOILTYPE12
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:)     :: SOILTYPE123
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:)   :: AREA,SOILPH
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:)   :: SOILPH1,SOILPH2,SOILPH3,SOILPH4,SOILPH5
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:)   :: LAI_MAX, LAI_AVG
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:)   :: Z0AM
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:)   :: SOILTYPE

!latitude and logitude in Degrees 
REAL(KIND=JPRB),ALLOCATABLE, DIMENSION(:)     :: LATD,LOND

! in radians
REAL(KIND=JPRB) :: LAT1 = 0.0_JPRB, LON1 = 0.0_JPRB
REAL(KIND=JPRB) :: DLAT = 0.0_JPRB, DLON = 0.0_JPRB
INTEGER(KIND=JPIM) :: NLAT = 0, NLON = 0, NLEV = 0, NMON = 0, NAER = 0

REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:) :: Z0M
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:) :: FPAR
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:,:) :: FPAR1
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:)   :: FPAR2
!lon,lat,month

! Number of the Grouped fields for 2d-3d, numb-month
INTEGER(KIND=JPIM) :: N3D = 0, N2D = 0, N4D = 0, NMONTH=0
!Grouped of 2D species (lon, lat, species) 
REAL(KIND=JPRB),ALLOCATABLE, DIMENSION(:,:,:)   :: SPECIES3D
REAL(KIND=JPRB),ALLOCATABLE, DIMENSION(:,:,:,:)   :: SPECIES4D

! INTERPOLATED ARRAYS MAYBE DO NOT NEED IT but saved into the main  pointer
REAL(KIND=JPRB),ALLOCATABLE, DIMENSION(:)   :: TCULT, TSOILTYPE, TPOTSRC
REAL(KIND=JPRB),ALLOCATABLE, DIMENSION(:)   :: TAREA, TSOILPH, TZ0AM
REAL(KIND=JPRB),ALLOCATABLE, DIMENSION(:)   :: TSOILPH1, TSOILPH2, TSOILPH3, TSOILPH4, TSOILPH5
REAL(KIND=JPRB),ALLOCATABLE, DIMENSION(:)   :: TZ0M , TFPAR
REAL(KIND=JPRB),ALLOCATABLE, DIMENSION(:)   :: TLAI_MAX, TLAI_AVG
LOGICAL :: IS_INITIALISED = .FALSE.
LOGICAL :: IS_INTERPOLATED = .FALSE.
LOGICAL :: IS_GROUPED = .FALSE. 
CONTAINS
PROCEDURE :: READ => SETUP_DUST_CLIM
PROCEDURE :: INTERPOLATION =>SU_DUST_FIELDS_INTERP

END TYPE TEAERC_DUST

TYPE(TEAERC_DUST), POINTER :: YDUSTCLIM => NULL()

!==========================================================================================

CONTAINS 

SUBROUTINE SETUP_DUST_CLIM(SELF)
  USE YOMLUN, ONLY : NULOUT
  !------------
  CLASS(TEAERC_DUST), INTENT(INOUT) :: SELF
  
  CALL SU_DUST_FIELDS(SELF)
  WRITE(NULOUT,*) '2D FIELDS FOR DUST CLIMATOLOGY IS LOADED'
  SELF%IS_INITIALISED = .TRUE.
  
END SUBROUTINE SETUP_DUST_CLIM

SUBROUTINE GET_2DSPECIES(SELF)
IMPLICIT NONE
! ARGUMENTS
! ------------
TYPE(TEAERC_DUST), INTENT(INOUT) :: SELF

! Expected dimension lengths for month, latitude and longitude
INTEGER(KIND=JPIM), PARAMETER :: IMONTH = 12
INTEGER(KIND=JPIM), PARAMETER :: ILAT   = 180 !61
INTEGER(KIND=JPIM), PARAMETER :: ILON   = 360 !120
INTEGER, PARAMETER :: idx_SOILPH1 = 1
INTEGER, PARAMETER :: idx_SOILPH2 = 2
INTEGER, PARAMETER :: idx_SOILPH3 = 3
INTEGER, PARAMETER :: idx_SOILPH4 = 4
INTEGER, PARAMETER :: idx_SOILPH5 = 5
INTEGER, PARAMETER :: idx_Z0AM = 6
INTEGER, PARAMETER :: idx_POTSRC = 7
INTEGER, PARAMETER :: idx_SOILTYPE = 8
INTEGER, PARAMETER :: idx_AREA = 9
INTEGER, PARAMETER :: idx_CULT = 10
!3D SPECIES 
INTEGER, PARAMETER :: idx_FPAR = 1
INTEGER, PARAMETER :: idx_Z0M = 2
! Assuming dimensions have been set for lat and lon
IF (.NOT. ALLOCATED(SELF%SPECIES3D)) THEN
    ALLOCATE(SELF%SPECIES3D(SELF%NLON, SELF%NLAT, 10))
END IF
! Assuming dimensions have been set for lat and lon
IF (.NOT. ALLOCATED(SELF%SPECIES4D)) THEN
    ALLOCATE(SELF%SPECIES4D(SELF%NLON, SELF%NLAT, SELF%NMONTH, 2))
END IF
! Populate the 3D array with existing 2D data
SELF%SPECIES3D(:,:, idx_SOILPH1) = SELF%SOILPH1(:,:) !1
SELF%SPECIES3D(:,:, idx_SOILPH2) = SELF%SOILPH2(:,:) !2
SELF%SPECIES3D(:,:, idx_SOILPH3) = SELF%SOILPH3(:,:) !3
SELF%SPECIES3D(:,:, idx_SOILPH4) = SELF%SOILPH4(:,:) !4
SELF%SPECIES3D(:,:, idx_SOILPH5) = SELF%SOILPH5(:,:) !5
SELF%SPECIES3D(:,:, idx_Z0AM)    = SELF%Z0AM(:,:)    !6
SELF%SPECIES3D(:,:, idx_POTSRC)  = SELF%POTSRC(:,:)  !7
SELF%SPECIES3D(:,:, idx_SOILTYPE)= SELF%SOILTYPE(:,:)!8 
SELF%SPECIES3D(:,:, idx_AREA)= SELF%AREA(:,:)        !9
SELF%SPECIES3D(:,:, idx_CULT)= SELF%CULT(:,:)        !10 
SELF%IS_GROUPED = .TRUE.
SELF%N2D=SIZE(SELF%SPECIES3D,3)
SELF%SPECIES4D(:,:,:,idx_FPAR) = SELF%FPAR(:,:,:)
SELF%SPECIES4D(:,:,:,idx_Z0M)  = SELF%Z0M(:,:,:)
SELF%N4D=SIZE(SELF%SPECIES4D,4)
END SUBROUTINE GET_2DSPECIES

SUBROUTINE SU_DUST_FIELDS(SELF_DUST)
!-----------------------------------------------------------------------
USE PARKIND1  , ONLY : JPIM, JPRB
USE EASY_NETCDF_READ_MPI,ONLY : NETCDF_FILE
USE YOMHOOK   , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMLUN    , ONLY : NULERR
USE YOMLUN    , ONLY : NULOUT
USE YOMCST    , ONLY : RPI

IMPLICIT NONE

! ARGUMENTS
TYPE(TEAERC_DUST), INTENT(INOUT) :: SELF_DUST
! Expected dimension lengths for month, latitude and longitude
INTEGER(KIND=JPIM), PARAMETER :: IMONTH = 12
INTEGER(KIND=JPIM), PARAMETER :: ILAT   = 180 !61
INTEGER(KIND=JPIM), PARAMETER :: ILON   = 360 !120
! Full and base names of the aerosol climatology file
CHARACTER(len=:),ALLOCATABLE :: CL_FILE_NAME, CL_AER_CLIM_FILE 
!Temporary file containing the input of fields
! "DATA" directory
CHARACTER(LEN=512)  :: CLDIRECTORY
! The NetCDF file containing the input climatology
TYPE(NETCDF_FILE)  :: FILE
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
!LOCAL TEMPORAL ARRAY 
REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:) ::  RSOILTYPE 
!REAL(KIND=JPRB), ALLOCATABLE, DIMENSION(:,:) :: RZ0AM, RSOILPH3, RSOILPH4, RSOILPH5

#include "abor1.intfb.h"
!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('YOEDUST:SU_DUST_CLIMATOLOGY',0,ZHOOK_HANDLE)

  CL_AER_CLIM_FILE = "onlinedust_v4_rmp.nc"
  CALL GET_ENVIRONMENT_VARIABLE("DATA",CLDIRECTORY)
  IF(CLDIRECTORY /= " ") THEN
    CL_FILE_NAME = TRIM(CLDIRECTORY) // "/composition/" // CL_AER_CLIM_FILE
  ELSE
    CL_FILE_NAME = CL_AER_CLIM_FILE
  ENDIF
  CALL FILE%OPEN(TRIM(CL_FILE_NAME), IVERBOSE=4)
  CALL FILE%GET('lat', SELF_DUST%LATD)
  CALL FILE%GET('lon', SELF_DUST%LOND)
  CALL FILE%GET('cult', SELF_DUST%CULT)  
  CALL FILE%GET('lai_max', SELF_DUST%LAI_MAX)
  CALL FILE%GET('lai_avg', SELF_DUST%LAI_AVG)

  CALL FILE%GET('fpar', SELF_DUST%FPAR)
  IF (    SIZE(SELF_DUST%FPAR,1) /= ILON .OR. &
       &  SIZE(SELF_DUST%FPAR,2) /= ILAT .OR. &
       &  SIZE(SELF_DUST%FPAR,3) /= IMONTH) THEN
    WRITE(NULERR,*) 'Aerosols in', CL_FILE_NAME, 'must be dimensioned (', &
         &  ILON, ",", ILAT, ",", IMONTH, ")"
    CALL ABOR1("Error reading aerosol climatology NetCDF file")
  ENDIF
  CALL FILE%GET('potsrc', SELF_DUST%POTSRC)
  !CALL FILE%GET('soiltype', RSOILTYPE) 
  !SELF_DUST%SOILTYPE =  RSOILTYPE
  CALL FILE%GET('soiltype',SELF_DUST%SOILTYPE)
  CALL FILE%GET('soilph1', SELF_DUST%SOILPH1)
  CALL FILE%GET('soilph2', SELF_DUST%SOILPH2)
  CALL FILE%GET('soilph3', SELF_DUST%SOILPH3)
  CALL FILE%GET('soilph4', SELF_DUST%SOILPH4)
  CALL FILE%GET('soilph5', SELF_DUST%SOILPH5)
  CALL FILE%GET('z0am', SELF_DUST%Z0AM)
  CALL FILE%GET('area', SELF_DUST%AREA)
  CALL FILE%GET('z0m', SELF_DUST%Z0M)

  SELF_DUST%NLAT = SIZE(SELF_DUST%LATD)
  SELF_DUST%LAT1 = SELF_DUST%LATD(1) * RPI / 180.0_JPRB                        !rads
  SELF_DUST%DLAT = (SELF_DUST%LATD(2)-SELF_DUST%LATD(1)) * RPI / 180.0_JPRB    ! delta in rads

  IF (SELF_DUST%LOND(1) < 0) THEN
     WRITE(NULERR,*) "THE LON SHOULD BE 0- 360 THE CURRENT FILE LON ARE -180 to 180"
    ! SELF_DUST%LOND = MOD(SELF_DUST%LOND(:) +180.0,360.0)
  ELSE
     SELF_DUST%LOND = SELF_DUST%LOND
  ENDIF
  SELF_DUST%NLON = SIZE(SELF_DUST%LOND)
  SELF_DUST%LON1 = SELF_DUST%LOND(1) * RPI / 180.0_JPRB                        !rad
  SELF_DUST%DLON = (SELF_DUST%LOND(2)-SELF_DUST%LOND(1)) * RPI / 180.0_JPRB    !delta in rads
  
  ! Check dimensions
  IF (    SIZE(SELF_DUST%Z0M,1) /= SELF_DUST%NLON .OR. &
       &  SIZE(SELF_DUST%Z0M,2) /= SELF_DUST%NLAT .OR. &
       &  SIZE(SELF_DUST%Z0M,3) /= IMONTH) THEN
    WRITE(NULERR,*) 'Aerosols in', CL_FILE_NAME, 'must be dimensioned LON,LAT,MONTH (', &
         &  ILON, ",", ILAT, ",", IMONTH, ")"
    CALL ABOR1("Error reading aerosol climatology NetCDF file")
  ENDIF
  SELF_DUST%NMONTH= SIZE(SELF_DUST%Z0M,3)

  CALL FILE%CLOSE()

IF (LHOOK) CALL DR_HOOK('YOEDUST:SU_AER_CLIMATOLOGY',1,ZHOOK_HANDLE)

END SUBROUTINE SU_DUST_FIELDS

SUBROUTINE SU_DUST_FIELDS_INTERP(SELF, KSTART, KEND, KCOL, PLAT, PLON, &
                                  ISOILPH1, ISOILPH2, ISOILPH3, ISOILPH4, ISOILPH5, &
                                  IZ0AM, IPOTSRC, ISOILTYPE, IAREA, ICULT, IZ0M, IFPAR, IM0,ILAI_MAX,ILAI_AVG )

  USE YOMHOOK   , ONLY : LHOOK, DR_HOOK, JPHOOK
  IMPLICIT NONE
  CLASS(TEAERC_DUST), INTENT(INOUT) :: SELF
  INTEGER(KIND=JPIM), INTENT(IN) :: KCOL
  INTEGER(KIND=JPIM), INTENT(IN) :: KSTART, KEND
  INTEGER(KIND=JPIM), INTENT(IN) :: IM0 
  ! Sine of latitude of input columns
  !REAL(KIND=JPRB) :: PSINLAT(KSTART:KEND)
  REAL(KIND=JPRB), INTENT(IN) :: PLAT(KCOL)  !rads = PGELAT
  REAL(KIND=JPRB), INTENT(IN) :: PLON(KCOL)  !rads = PGELAM
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  REAL(KIND=JPRB), INTENT(OUT) :: &
  ISOILPH1(KCOL), ISOILPH2(KCOL), ISOILPH3(KCOL), ISOILPH4(KCOL), ISOILPH5(KCOL), &
  IZ0AM(KCOL), IPOTSRC(KCOL), IAREA(KCOL), ICULT(KCOL)!, ISOILTYPE(KCOL)
  REAL(KIND=JPRB),  INTENT(OUT) :: ILAI_MAX(KCOL), ILAI_AVG(KCOL)
  REAL(KIND=JPRB),  INTENT(OUT) :: IZ0M(KCOL), IFPAR(KCOL)
  !INTEGER(KIND=JPIM), INTENT(OUT) :: ISOILTYPE(KSTART:KEND)  
  REAL(KIND=JPRB),  INTENT(OUT) :: ISOILTYPE(KSTART:KEND)

  #include "abor1.intfb.h"
  
  IF (LHOOK) CALL DR_HOOK('YOEDUST:INTERPOLATION main call',0,ZHOOK_HANDLE)
  
  CALL INTP_SOILT(SELF,SELF%SOILTYPE, KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), ISOILTYPE)
  SELF%TSOILTYPE(:) = ISOILTYPE(:)


  CALL INTP_SOILT(SELF, SELF%AREA, KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), IAREA)
  SELF%TAREA(:) = IAREA(:)

  CALL INTP_SOILT(SELF, SELF%SOILPH1, KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), ISOILPH1)
  SELF%TSOILPH1(:) = ISOILPH1(:)

  CALL INTP_SOILT(SELF, SELF%SOILPH2, KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), ISOILPH2)
  SELF%TSOILPH2(:) = ISOILPH2(:)

  CALL INTP_SOILT(SELF, SELF%SOILPH3, KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), ISOILPH3)
  SELF%TSOILPH3(:) = ISOILPH3(:)

  CALL INTP_SOILT(SELF, SELF%SOILPH4, KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), ISOILPH4)
  SELF%TSOILPH4(:) = ISOILPH4(:)

  CALL INTP_SOILT(SELF, SELF%SOILPH5, KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), ISOILPH5)
  SELF%TSOILPH5(:) = ISOILPH5(:)

  CALL INTP_SOILT(SELF, SELF%Z0AM, KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), IZ0AM)
  SELF%TZ0AM(:) = IZ0AM(:)

  CALL INTP_SOILT(SELF, SELF%POTSRC, KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), IPOTSRC)
  SELF%TPOTSRC(:) = IPOTSRC(:)

  CALL INTP_SOILT(SELF, SELF%CULT, KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), ICULT)
  SELF%TCULT(:) = ICULT(:)

  CALL INTP_SOILT(SELF, SELF%LAI_MAX, KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), ILAI_MAX)
  SELF%TLAI_MAX(:) = ILAI_MAX(:)

  CALL INTP_SOILT(SELF, SELF%LAI_AVG, KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), ILAI_AVG)
  SELF%TLAI_AVG(:) = ILAI_AVG(:)

  CALL INTP_SOILT(SELF, SELF%FPAR(:,:,IM0), KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), IFPAR)
  SELF%TFPAR(:) = IFPAR(:)

  CALL INTP_SOILT(SELF, SELF%Z0M(:,:,IM0), KSTART, KEND, KCOL, PLAT(KSTART:KEND), PLON(KSTART:KEND), IZ0M)
  SELF%TZ0M(:) = IZ0M(:)


  IF (LHOOK) CALL DR_HOOK('YOEDUST:INTERPOLATION FIELDS main call',1,ZHOOK_HANDLE)


CONTAINS 

SUBROUTINE CALC_INTERP_DUST(SELF, FIELD2D, KSTART, KEND, KCOL, PLAT, PLON, INTEROUT)

  USE YOMLUN    , ONLY : NULERR
  USE YOMLUN    , ONLY : NULOUT
  USE YOMHOOK   , ONLY : LHOOK, DR_HOOK, JPHOOK
  !USE, INTRINSIC :: IEEE_ARITHMETIC
  LOGICAL :: LPROBLEM
  REAL(KIND=JPRB) :: BIG_VAL = HUGE(1.0_JPRB), SMALL_VAL = TINY(1.0_JPRB)
  CLASS(TEAERC_DUST), INTENT(INOUT):: SELF
  
  REAL(KIND=JPRB),    INTENT(IN) :: FIELD2D(:,:)
  INTEGER(KIND=JPIM), INTENT(IN) :: KCOL
  INTEGER(KIND=JPIM), INTENT(IN) :: KSTART, KEND
  REAL(KIND=JPRB),  INTENT(OUT) :: INTEROUT(KSTART:KEND)
  ! Sine of latitude of input columns
  REAL(KIND=JPRB) :: PSINLAT(KSTART:KEND)
  REAL(KIND=JPRB), INTENT(IN) :: PLAT(KSTART:KEND)
  REAL(KIND=JPRB), INTENT(IN) :: PLON(KSTART:KEND)
  INTEGER(KIND=JPIM), DIMENSION(KSTART:KEND) :: KLAT1, KLAT2, KLON1, KLON2
  REAL(KIND=JPRB)   , DIMENSION(KSTART:KEND) :: PLATWEIGHT, PLONWEIGHT
  INTEGER(KIND=JPIM) :: JL, JS, N2, N4, NM, JM, JA
  REAL(KIND=JPRB) :: ZLAT(KSTART:KEND)
  REAL(KIND=JPRB) :: ZAERA, ZAERB
  REAL(KIND=JPRB), DIMENSION(KSTART:KEND) :: ZAER2D
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  REAL(KIND=JPHOOK) :: DENOM
  
  #include "abor1.intfb.h"
  
  IF (LHOOK) CALL DR_HOOK('YOEDUST:INTERPOLATION FIELDS 2D',0,ZHOOK_HANDLE)
  
  PLONWEIGHT = 0.0
  ! Longitude interpolation points and weights
  PLONWEIGHT = 1.0_JPRB + (PLON - SELF%LON1) / SELF%DLON
  KLON1 = MAX(1, MIN(INT(PLONWEIGHT), SELF%NLON))
  KLON2 = MOD(KLON1,SELF%NLON)+1 ! Correct treatment of dateline
  PLONWEIGHT = PLONWEIGHT - KLON1
  !ZLAT = ASIN(PSINLAT)
  PSINLAT=SIN(PLAT) ! SIN of rads
  ZLAT = PLAT !RADS

  PLATWEIGHT = 0.0
  PLATWEIGHT = 1.0_JPRB + (ZLAT - SELF%LAT1) / SELF%DLAT
  KLAT1 = MAX(0, MIN(INT(PLATWEIGHT), SELF%NLAT-1))
  KLAT2 = KLAT1+1
  ! Interpolation in sin(latitude)
  DO JL = KSTART, KEND
  DENOM = SIN(SELF%LAT1+(KLAT2(JL)-1)*SELF%DLAT) - SIN(SELF%LAT1+(KLAT1(JL)-1)*SELF%DLAT)
  PLATWEIGHT(JL) = (PSINLAT(JL) - SIN(SELF%LAT1 + (KLAT1(JL)-1)*SELF%DLAT)) / DENOM
  END DO
  !PLATWEIGHT = (PSINLAT - SIN(SELF%LAT1+(KLAT1-1)*SELF%DLAT)) &
  !     &     / (SIN(SELF%LAT1+(KLAT2-1)*SELF%DLAT) - SIN(SELF%LAT1+(KLAT1-1)*SELF%DLAT))
  ZAERA =0.0_JPRB
  ZAERB = 0.0_JPRB
  INTEROUT(KSTART:KEND) = 0.0_JPRB
  ! Interpolation loop
    DO JL = KSTART, KEND
    ZAERA = FIELD2D(KLON1(JL), KLAT1(JL)) + &
            PLATWEIGHT(JL) * (FIELD2D(KLON1(JL), KLAT2(JL)) - FIELD2D(KLON1(JL), KLAT1(JL)))
    ZAERB = FIELD2D(KLON2(JL), KLAT1(JL)) + &
            PLATWEIGHT(JL) * (FIELD2D(KLON2(JL), KLAT2(JL)) - FIELD2D(KLON2(JL), KLAT1(JL)))
    INTEROUT(JL) = ZAERA + PLONWEIGHT(JL) * (ZAERB - ZAERA)
    END DO

   IF (LHOOK) CALL DR_HOOK('YOEDUST:INTERPOLATION FIELDS 2D',1,ZHOOK_HANDLE)
END SUBROUTINE CALC_INTERP_DUST

!for simplicity this routine do NOT  be USED. 
!
SUBROUTINE CALC_3DINTERP_DUST(SELF, FIELD3D, KSTART, KEND, KCOL, PLAT, PLON, INTEROUT)
  USE YOMLUN, ONLY : NULOUT
  USE YOMHOOK   , ONLY : LHOOK, DR_HOOK, JPHOOK  
  IMPLICIT NONE
  
  CLASS(TEAERC_DUST), INTENT(INOUT) :: SELF
  REAL(KIND=JPRB), INTENT(IN) :: FIELD3D(:,:,:)
  INTEGER(KIND=JPIM), INTENT(IN) :: KSTART, KEND, KCOL
  REAL(KIND=JPRB), INTENT(IN) :: PLAT(KSTART:KEND), PLON(KSTART:KEND)
  REAL(KIND=JPRB), INTENT(OUT) :: INTEROUT(KSTART:KEND,SELF%NMONTH)
  INTEGER(KIND=JPIM), PARAMETER :: ILAT = 180, ILON = 360, IMONTH = 12
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  INTEGER(KIND=JPIM) :: JL, JM
  INTEGER(KIND=JPIM), DIMENSION(KSTART:KEND) :: KLAT1, KLAT2, KLON1, KLON2
  REAL(KIND=JPRB), DIMENSION(KSTART:KEND) ::  PLATWEIGHT, PLONWEIGHT
  REAL(KIND=JPRB), DIMENSION(KSTART:KEND):: PSINLAT, ZLAT
  REAL(KIND=JPRB)    :: ZAERA, ZAERB
  #include "abor1.intfb.h"

  IF (LHOOK) CALL DR_HOOK('YOEDUST:INTERPOLATION FIELDS 3D',0,ZHOOK_HANDLE)
  ! Precompute sine of latitude and indices
  PSINLAT = SIN(PLAT)
  ZLAT = PLAT

  PLONWEIGHT = 1.0_JPRB + (PLON - SELF%LON1) / SELF%DLON
  KLON1 = MAX(1, MIN(INT(PLONWEIGHT), SELF%NLON))
  KLON2 = MOD(KLON1, SELF%NLON) + 1
  PLONWEIGHT = PLONWEIGHT - KLON1

  PLATWEIGHT = 1.0_JPRB + (ZLAT - SELF%LAT1) / SELF%DLAT
  KLAT1 = MAX(1, MIN(INT(PLATWEIGHT), SELF%NLAT - 1))
  KLAT2 = KLAT1 + 1
  PLATWEIGHT = (PSINLAT - SIN(SELF%LAT1 + (KLAT1 - 1)*SELF%DLAT)) / &
               (SIN(SELF%LAT1 + (KLAT2 - 1)*SELF%DLAT) - SIN(SELF%LAT1 + (KLAT1 - 1)*SELF%DLAT))

  ! --- Interpolate for each column across all months and average ---
    IF (    SIZE(FIELD3D,1) == ILON .OR. &
       &  SIZE(FIELD3D,2) == ILAT .OR. &
       &  SIZE(FIELD3D,3) == IMONTH) THEN
    WRITE(NULOUT,*) '3D FIELDS INTERPOLATION ...'
    ELSE 
     WRITE(NULOUT,*) '3D FIELDS INTERPOLATION was not 3d ...', FIELD3D(195,116,6)
     WRITE(NULOUT,*) '3D FIELDS LON:',SIZE(FIELD3D,1),'LAT:', SIZE(FIELD3D,2), 'MONTH:', SIZE(FIELD3D,3)
    END IF
    DO JM =1,SELF%NMONTH                           !loop months
      DO JL = KSTART,KEND                        !loop model colum
    ! Bilinear interpolation in lon/lat month  for each species3d
      ZAERA =  FIELD3D(KLON1(JL), KLAT1(JL), JM) &
                 & + PLATWEIGHT(JL) * (FIELD3D(KLON1(JL), KLAT2(JL), JM) &
            &                    - FIELD3D(KLON1(JL), KLAT1(JL), JM))
      ZAERB = FIELD3D(KLON2(JL), KLAT1(JL),  JM) &
                  & + PLATWEIGHT(JL) * (FIELD3D(KLON2(JL), KLAT2(JL), JM) &
              &                    -  FIELD3D(KLON2(JL), KLAT1(JL),  JM))
      INTEROUT(JL,JM) = ZAERA + PLONWEIGHT(JL) * (ZAERB - ZAERA)
      END DO
     END DO

     IF (LHOOK) CALL DR_HOOK('YOEDUST:INTERPOLATION FIELDS 3D',1,ZHOOK_HANDLE)
END SUBROUTINE CALC_3DINTERP_DUST

SUBROUTINE INTP_SOILT(SELF,FIELD2D, KSTART, KEND,KCOL, PLAT, PLON, INTERSOILT)

  USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK
  USE YOMLUN    , ONLY : NULOUT
  REAL(KIND=JPRB),    INTENT(IN) :: FIELD2D(:,:)
  INTEGER(KIND=JPIM), INTENT(IN) :: KCOL
  CLASS(TEAERC_DUST), INTENT(IN) :: SELF
  INTEGER(KIND=JPIM), INTENT(IN) :: KSTART, KEND
  REAL(KIND=JPRB) :: PSINLAT(KSTART:KEND)
  REAL(KIND=JPRB), INTENT(IN) :: PLAT(KSTART:KEND)
  REAL(KIND=JPRB), INTENT(IN) :: PLON(KSTART:KEND)
  !REAL(KIND=JPRM), INTENT(OUT), DIMENSION(KCOL) :: INTERSOILT
  !INTEGER(KIND=JPIM), INTENT(OUT) :: INTERSOILT (KSTART:KEND)
  REAL(KIND=JPRB), INTENT(OUT) :: INTERSOILT (KSTART:KEND)
  
  INTEGER(KIND=JPIM), DIMENSION(KSTART:KEND) :: KLAT1, KLAT2, KLON1, KLON2
  REAL(KIND=JPRB), DIMENSION(KSTART:KEND) :: PLATWEIGHT, PLONWEIGHT
  INTEGER(KIND=JPIM) :: JL, JS, N2, N4, NM, JM, JA
  REAL(KIND=JPRB) :: ZLAT(KSTART:KEND)
  REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  REAL(KIND=JPRB) :: ZAERA, ZAERB
  REAL(KIND=JPRB), DIMENSION(KSTART:KEND) :: ZAER2D
  !C. Perez
  INTEGER(KIND=JPIM) :: I_INX, J_INX
  IF (LHOOK) CALL DR_HOOK('YOEDUST:INTERPOLATION FIELDS SOILTYPE',0,ZHOOK_HANDLE)

  PLATWEIGHT = 0.0
  PLONWEIGHT = 0.0
  ! Longitude interpolation points and weights
  PLONWEIGHT = 1.0_JPRB + (PLON - SELF%LON1) / SELF%DLON
  KLON1 = MAX(1, MIN(INT(PLONWEIGHT), SELF%NLON))
  KLON2 = MOD(KLON1,SELF%NLON)+1 ! Correct treatment of dateline
  PLONWEIGHT = PLONWEIGHT - KLON1

  !ZLAT = ASIN(PSINLAT)
  PSINLAT=SIN(PLAT) ! SIN of rads
  ZLAT = PLAT !RADS
  PLATWEIGHT = 1.0_JPRB + (ZLAT - SELF%LAT1) / SELF%DLAT
!  KLAT1 = MAX(0, MIN(INT(PLATWEIGHT), SELF%NLAT-1))  !C. Perez: Why 0? Does the latitude indexing start in 0? 
  KLAT1 = MAX(1, MIN(INT(PLATWEIGHT), SELF%NLAT-1))
  KLAT2 = KLAT1+1

  ! Interpolation in sin(latitude)
  PLATWEIGHT = (PSINLAT - SIN(SELF%LAT1+(KLAT1-1)*SELF%DLAT)) &
       &     / (SIN(SELF%LAT1+(KLAT2-1)*SELF%DLAT) - SIN(SELF%LAT1+(KLAT1-1)*SELF%DLAT))

  DO JL = KSTART,KEND
  !C.Perez
  !choose the closer longitude corner
  IF (PLONWEIGHT(JL) > 0.5_JPRB) THEN
      I_INX = KLON2(JL)
    ELSE
      I_INX = KLON1(JL)
    END IF
   !choose the closer latitude  corner
  IF (PLATWEIGHT(JL) > 0.5_JPRB) THEN
      J_INX = KLAT2(JL)
    ELSE
      J_INX = KLAT1(JL)
    END IF
  
   INTERSOILT(JL) = FIELD2D(I_INX, J_INX)
   !C. Perez
  END DO
  IF (LHOOK) CALL DR_HOOK('YOEDUST:INTERPOLATION FIELDS SOILTYPE',1,ZHOOK_HANDLE)
END SUBROUTINE INTP_SOILT

END SUBROUTINE SU_DUST_FIELDS_INTERP

END MODULE YOEDUST
