! (C) Copyright 1988- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
!
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

MODULE YOMPHYDER

USE PARKIND1  ,ONLY : JPIM     ,JPRB

USE ECPHYS_DIMENSION_TYPE_MOD, ONLY: DIMENSION_TYPE
USE ECPHYS_STATE_TYPE_MOD, ONLY: STATE_TYPE, MASK_GFL_TYPE
USE ECPHYS_SURFACE_TYPE_MOD, ONLY: SURF_AND_MORE_TYPE, SURF_AND_MORE_LOCAL_TYPE, DDH_SURF_TYPE
USE ECPHYS_AUX_TYPE_MOD, ONLY: AUX_TYPE, KEYS_LOCAL_TYPE
USE ECPHYS_AUX_RAD_TYPE_MOD, ONLY: AUX_RAD_TYPE
USE ECPHYS_AUX_DIAG_TYPE_MOD, ONLY: AUX_DIAG_TYPE, AUX_DIAG_LOCAL_TYPE
USE ECPHYS_PERTURB_TYPE_MOD, ONLY: PERTURB_TYPE, PERTURB_LOCAL_TYPE
USE ECPHYS_FLUX_TYPE_MOD, ONLY: FLUX_TYPE

!     ------------------------------------------------------------------

IMPLICIT NONE
SAVE

TYPE MODEL_STATE_TYPE
  REAL(KIND=JPRB), DIMENSION(:,:), POINTER, CONTIGUOUS ::  U, V, T ! GMV
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS ::  GFL   ! GFL
END TYPE MODEL_STATE_TYPE

TYPE GEMS_LOCAL_TYPE
  INTEGER(KIND=JPIM), POINTER                            :: ITRAC
  INTEGER(KIND=JPIM), DIMENSION(:),  POINTER, CONTIGUOUS :: IAERO      ! Index array for aerosol tracers
  INTEGER(KIND=JPIM), DIMENSION(:),  POINTER, CONTIGUOUS :: ICHEM      ! Index array for chemical species
  REAL(KIND=JPRB), DIMENSION(:,:) ,  POINTER, CONTIGUOUS :: ZLRCH4     ! temporal storage for AD code
!-- basic GEMS fields
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: ZCEN,ZTENC,ZTENC_SKF
  REAL(KIND=JPRB), DIMENSION(:,:)  , POINTER, CONTIGUOUS :: ZCFLX,ZDDVLC,ZCHEMDV,ZCFLXO
  REAL(KIND=JPRB), DIMENSION(:)    , POINTER, CONTIGUOUS :: ZSCAV
! - aerosols transport arrays
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER, CONTIGUOUS :: ZAERLISI
  REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER, CONTIGUOUS :: ZAERAOT, ZTAUAER, ZCAERO, ZAEROP
  REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER, CONTIGUOUS :: ZAERAOTLEV,ZAERAAOTLEV, ZAERASYLEV
  REAL(KIND=JPRB), DIMENSION(:,:,:),   POINTER, CONTIGUOUS :: ZAERFLX_M7
  REAL(KIND=JPRB), DIMENSION(:,:)  ,   POINTER, CONTIGUOUS :: ZAERSRC, ZAERDDP, ZAERSDM, ZAERFLX, ZAERLIF
  REAL(KIND=JPRB), DIMENSION(:)    ,   POINTER, CONTIGUOUS :: ZAZ0M, ZAZ0H
!--aerosol optical properties at 14 SW wavelengths (TM5M7)
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS ::  ZAEROTAU, ZAEROSSA,ZAEROASY,ZAEROTAULW

! - DMS-related aerosol local arrays
  REAL(KIND=JPRB), DIMENSION(:)    , POINTER, CONTIGUOUS :: ZDMSO, ZLDAY, ZLISS, ZSO2, ZTDMS, ZDMSI, ZODMS
!-- other prognostic aerosol-related quantities
  REAL(KIND=JPRB), DIMENSION(:)    , POINTER, CONTIGUOUS ::  ZAERWS, ZAERGUST, ZAERUST, ZDIST
  REAL(KIND=JPRB), DIMENSION(:,:)  , POINTER, CONTIGUOUS ::  ZAERMAP ! (KDIM%KLON,5)
! - aerosol-chemistry coupling local arrays
  REAL(KIND=JPRB), DIMENSION(:,:)  , POINTER, CONTIGUOUS :: ZSO2TOSO4 ! (KDIM%KLON,KDIM%KLEV) SO2->SO4 oxidation flux from CHEM for use in AER
!-- GLOMAP fields: modal dry and wet diameter/volume and effective radius
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS ::  ZDRYDIAM, ZWETDIAM !(KDIM%KLON,KDIM%KLEV,7)
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS ::  ZDRYVOL, ZWETVOL   !(KDIM%KLON,KDIM%KLEV,7)
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS ::  ZVOL_WAT, ZRHOPAR   !(KDIM%KLON,KDIM%KLEV,7)
  REAL(KIND=JPRB), DIMENSION(:,:,:,:), POINTER, CONTIGUOUS ::  ZMD
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS ::  ZND, ZMDT

! Visibility
  REAL(KIND=JPRB), DIMENSION(:)    , POINTER, CONTIGUOUS :: ZCLAERS,  ZPRAERS ! zpraers not used for the moment
  REAL(KIND=JPRB), DIMENSION(:)    , POINTER, CONTIGUOUS :: ZVISICL
! Preparation for chemistry
  REAL(KIND=JPRB), DIMENSION(:,:,:), POINTER, CONTIGUOUS :: ZKOZO ! PHOTOCHEMICAL COEFFICIENTS COMPUTED FROM A 2D PHOTOCHEMICAL MODEL
END TYPE GEMS_LOCAL_TYPE

END MODULE YOMPHYDER

